'use strict';

/**@type {{[k: string]: {learnset: {[k: string]: MoveSource[]}}}} */
let BattleLearnsets = {
	sandshrewalola: {learnset: {
		aerialace: ["7M"],
		amnesia: ["7E"],
		aquatail: ["7T"],
		attract: ["7M"],
		auroraveil: ["7M"],
		bide: ["7L3", "7S0"],
		blizzard: ["7M", "7L46"],
		brickbreak: ["7M"],
		bulldoze: ["7M"],
		chipaway: ["7E"],
		confide: ["7M"],
		counter: ["7E"],
		covet: ["7T"],
		crushclaw: ["7E"],
		curse: ["7E"],
		defensecurl: ["7L1"],
		doubleteam: ["7M"],
		earthquake: ["7M"],
		endure: ["7E"],
		facade: ["7M"],
		flail: ["7E"],
		fling: ["7M"],
		focuspunch: ["7T"],
		frostbreath: ["7M"],
		frustration: ["7M"],
		furycutter: ["7L11"],
		furyswipes: ["7L20"],
		gyroball: ["7M", "7L34"],
		hail: ["7M", "7L42"],
		hiddenpower: ["7M"],
		honeclaws: ["7E"],
		iceball: ["7L7", "7S0"],
		icepunch: ["7T"],
		iciclecrash: ["7E"],
		iciclespear: ["7E"],
		icywind: ["7T"],
		irondefense: ["7T", "7L23"],
		ironhead: ["7T", "7L30"],
		irontail: ["7T"],
		knockoff: ["7T"],
		leechlife: ["7M"],
		metalclaw: ["7L14", "7E"],
		mirrorcoat: ["7L16"],
		nightslash: ["7E"],
		poisonjab: ["7M"],
		powdersnow: ["7L5", "7S0"],
		protect: ["7M"],
		rapidspin: ["7L9", "7S0"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		scratch: ["7L1"],
		shadowclaw: ["7M"],
		slash: ["7L26"],
		sleeptalk: ["7M"],
		snore: ["7T"],
		stealthrock: ["7T"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		superfang: ["7T"],
		swagger: ["7M"],
		swift: ["7L17"],
		swordsdance: ["7M", "7L38"],
		thief: ["7M"],
		throatchop: ["7T"],
		toxic: ["7M"],
		workup: ["7M"],
		xscissor: ["7M"],
	}},
	sandslashalola: {learnset: {
		aerialace: ["7M"],
		aquatail: ["7T"],
		attract: ["7M"],
		auroraveil: ["7M"],
		blizzard: ["7M"],
		brickbreak: ["7M"],
		bulldoze: ["7M"],
		confide: ["7M"],
		covet: ["7T"],
		defensecurl: ["7L1"],
		doubleteam: ["7M"],
		drillrun: ["7T"],
		earthquake: ["7M"],
		facade: ["7M"],
		fling: ["7M"],
		focusblast: ["7M"],
		focuspunch: ["7T"],
		frostbreath: ["7M"],
		frustration: ["7M"],
		gigaimpact: ["7M"],
		gyroball: ["7M"],
		hail: ["7M"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		iceball: ["7L1"],
		icepunch: ["7T"],
		iciclecrash: ["7L1"],
		iciclespear: ["7L1"],
		icywind: ["7T"],
		irondefense: ["7T"],
		ironhead: ["7T"],
		irontail: ["7T"],
		knockoff: ["7T"],
		leechlife: ["7M"],
		metalburst: ["7L1"],
		metalclaw: ["7L1"],
		mirrorcoat: ["7L1"],
		poisonjab: ["7M"],
		protect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		shadowclaw: ["7M"],
		slash: ["7L1"],
		sleeptalk: ["7M"],
		snore: ["7T"],
		stealthrock: ["7T"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		superfang: ["7T"],
		swagger: ["7M"],
		swordsdance: ["7M"],
		thief: ["7M"],
		throatchop: ["7T"],
		toxic: ["7M"],
		workup: ["7M"],
		xscissor: ["7M"],
	}},
};

exports.BattleLearnsets = BattleLearnsets;
