exports.BattleFormats = {

	// formats

	RandomBattle: {
		effectType: 'Format',
		name: "Random Battle",
		team: 'random',
		searchDefault: true,
		ranked: true,
		challengeShow: true,
		searchShow: true,
		ruleset: ['Pokemon','PotD', 'SleepClause']
	},
	UnrankedRandomBattle: {
		effectType: 'Format',
		name: "Unranked Random Battle",
		team: 'random',
		searchShow: true,
		ruleset: ['Pokemon','PotD', 'SleepClause']
	},
	OU: {
		effectType: 'Format',
		name: "OU",
		challengeDefault: true,
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: ['Uber', 'Drizzle ++ SwiftSwim']
	},
	CAP: {
		effectType: 'Format',
		name: "CAP",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['CAPPokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: ['Uber', 'Drizzle ++ SwiftSwim']
	},
	CAPNecturnaPlaytest: {
		effectType: 'Format',
		name: "CAP Necturna Playtest",
		ranked: true,
		ruleset: ['CAPPokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: ['Uber','G4CAP','Tomohawk','ShadowStrike','PaleoWave']
	},
	Ubers: {
		effectType: 'Format',
		name: "Ubers",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: []
	},
	UU: {
		effectType: 'Format',
		name: "UU",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: ['Uber','OU','BL', 'SnowWarning','Drought']
	},
	RU: {
		effectType: 'Format',
		name: "RU",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: ['Uber','OU','BL','UU','BL2', 'SnowWarning','Drought', 'ShellSmash + BatonPass']
	},
	NU: {
		effectType: 'Format',
		name: "NU",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview'],
		banlist: ['Uber','OU','BL','UU','BL2','RU','BL3', 'SnowWarning','Drought', 'ShellSmash + BatonPass']
	},
	LCUbers: {
		effectType: 'Format',
		name: "LC Ubers",
		ranked: true,
		challengeShow: true,
		searchShow: true,
//		isTeambuilderFormat: true, // I don't know, so left out for now
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview', 'LCUbersBans'],
		banlist: []
	},
	LC: {
		effectType: 'Format',
		name: "LC",
		ranked: true,
		challengeShow: true,
		searchShow: true,
//		isTeambuilderFormat: true, // I don't know, so left out for now
		ruleset: ['Pokemon', 'SleepClause', 'SpeciesClause', 'Standard', 'TeamPreview', 'LCUbersBans', 'LCBans'],
		banlist: []
	},
	Hackmons: {
		effectType: 'Format',
		name: "Hackmons",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		isTeambuilderFormat: true,
		ruleset: ['Pokemon'],
		banlist: []
	},
	BalancedHackmons: {
		effectType: 'Format',
		name: "Balanced Hackmons",
		ranked: true,
		challengeShow: true,
		searchShow: true,
		teambuilderFormat: 'Hackmons',
		ruleset: ['Pokemon'],
		banlist: ['OHKO', 'WonderGuard']
	},
	Haxmons: {
		effectType: 'Format',
		name: "Haxmons",
		ruleset: ['HaxClause', 'TeamPreview']
	},
	DebugMode: {
		effectType: 'Format',
		name: "Debug Mode",
		challengeShow: true,
		canUseRandomTeam: true,
		// no restrictions, for serious
		ruleset: []
	},

	// rules

	Standard: {
		effectType: 'Banlist',
		banlist: ['Unreleased', 'Illegal', 'OHKO', 'Moody', 'BrightPowder', 'LaxIncense', 'Minimize', 'DoubleTeam', 'Legal'],
		validateSet: function(set) {
			// limit one of each move in Standard
			var moves = [];
			if (set.moves)
			{
				var hasMove = {};
				for (var i=0; i<set.moves.length; i++)
				{
					var move = this.getMove(set.moves[i]);
					var moveid = move.id;
					if (hasMove[moveid]) continue;
					hasMove[moveid] = true;
					moves.push(set.moves[i]);
				}
			}
			set.moves = moves;
		}
	},
	Pokemon: {
		effectType: 'Banlist',
		validateSet: function(set, format) {
			var item = this.getItem(set.item);
			var template = this.getTemplate(set.species);
			var problems = [];

			if (set.species === set.name) delete set.name;
			if (template.num == 493) // Arceus
			{
				if (set.ability === 'Multitype' && item.onPlate)
				{
					set.species = 'Arceus-'+item.onPlate;
				}
				else
				{
					set.species = 'Arceus';
				}
			}
			if (template.num == 487) // Giratina
			{
				if (item.id === 'GriseousOrb')
				{
					set.species = 'Giratina-O';
				}
				else
				{
					set.species = 'Giratina';
				}
			}
			if (template.num == 555) // Darmanitan
			{
				set.species = 'Darmanitan';
			}
			if (template.num == 648) // Meloetta
			{
				set.species = 'Meloetta';
			}
			if (template.num == 351) // Castform
			{
				set.species = 'Castform';
			}
			if (template.num == 421) // Cherrim
			{
				set.species = 'Cherrim';
			}
			if (template.isNonstandard)
			{
				problems.push(set.species+' is not a real pokemon.');
			}
			if (set.moves) for (var i=0; i<set.moves.length; i++)
			{
				var move = this.getMove(set.moves[i]);
				if (move.isNonstandard)
				{
					problems.push(move.name+' is not a real move.');
				}
			}
			return problems;
		}
	},
	CAPPokemon: {
		effectType: 'Rule',
		validateSet: function(set, format) {
			// don't return
			this.getEffect('Pokemon').validateSet.call(this, set, format);
		}
	},
	Legal: {
		effectType: 'Banlist',
		banlist: ['Crobat+BraveBird+Hypnosis']
	},
	PotD: {
		effectType: 'Rule',
		onPotD: '',
		onStart: function() {
			if (this.effect.onPotD)
			{
				this.add('rule Pokemon of the Day: '+this.effect.onPotD);
			}
		}
	},
	TeamPreview: {
		onStartPriority: -10,
		onStart: function() {
			for (var i=0; i<this.sides[0].pokemon.length; i++)
			{
				this.add('pokemon '+this.sides[0].pokemon[i].tpid);
			}
			for (var i=0; i<this.sides[1].pokemon.length; i++)
			{
				this.add('pokemon '+this.sides[1].pokemon[i].tpid);
			}
		},
		onTeamPreview: function() {
			this.callback('team-preview');
		}
	},
	HaxClause: {
		effectType: 'Rule',
		onStart: function() {
			this.add('rule Hax Clause');
		},
		onModifyMovePriority: -100,
		onModifyMove: function(move) {
			if (move.secondary)
			{
				move.secondary.chance = 100;
			}
			if (move.accuracy !== true && move.accuracy <= 99)
			{
				move.accuracy = 0;
			}
			move.willCrit = true;
		}
	},
	SpeciesClause: {
		effectType: 'Rule',
		onStart: function() {
			this.add('rule Species Clause');
		},
		validateTeam: function(team, format) {
			var speciesTable = {};
			for (var i=0; i<team.length; i++) {
				var template = this.getTemplate(team[i].species);
				if (speciesTable[template.num]) {
					return [template.name+" is banned by Species Clause."];
				}
				speciesTable[template.num] = true;
			}
		}
	},
	SleepClause: {
		effectType: 'Rule',
		onStart: function() {
			this.add('rule Sleep Clause');
		},
		onSetStatus: function(status, target, source) {
			if (source && source.side === target.side)
			{
				return;
			}
			if (status.id === 'slp')
			{
				for (var i=0; i<target.side.pokemon.length; i++)
				{
					var pokemon = target.side.pokemon[i];
					if (pokemon.status === 'slp')
					{
						if (!pokemon.statusData.source ||
						    pokemon.statusData.source.side !== pokemon.side)
						{
							this.add('message Sleep Clause activated.');
							return false;
						}
					}
				}
			}
		}
	},
	FreezeClause: {
		effectType: 'Rule',
		onStart: function() {
			this.add('rule Freeze Clause');
		}
	},
    LCUbersBans: {
        effectType: 'Banlist',
        banlist: [
            // Items
            'BerryJuice',

            // Moves (Generated from http://209.85.62.24/114/106/0/p69834/LC_illegal_movesets.txt)
            'Aipom+DoubleHit+MegaPunch',
            'Aipom+DoubleHit+MegaKick',
            'Aipom+DoubleHit+BodySlam',
            'Aipom+DoubleHit+Double-Edge',
            'Aipom+DoubleHit+SeismicToss',
            'Aipom+DoubleHit+Mimic',
            'Aipom+DoubleHit+Metronome',
            'Aipom+DoubleHit+DynamicPunch',
            'Aipom+DoubleHit+DefenseCurl',
            'Aipom+DoubleHit+Nightmare',
            'Aipom+NastyPlot+MegaPunch',
            'Aipom+NastyPlot+MegaKick',
            'Aipom+NastyPlot+BodySlam',
            'Aipom+NastyPlot+Double-Edge',
            'Aipom+NastyPlot+SeismicToss',
            'Aipom+NastyPlot+Mimic',
            'Aipom+NastyPlot+Metronome',
            'Aipom+NastyPlot+DynamicPunch',
            'Aipom+NastyPlot+DefenseCurl',
            'Aipom+NastyPlot+Nightmare',
            'Anorith+CrushClaw+BodySlam',
            'Anorith+CrushClaw+Double-Edge',
            'Anorith+CrushClaw+Mimic',
            'Aron+MetalBurst+Mimic',
            'Aron+MetalBurst+DefenseCurl',
            'Bagon+Wish+Leer',
            'Bagon+Wish+Headbutt',
            'Bagon+Wish+FocusEnergy',
            'Bagon+Wish+DragonBreath',
            'Bagon+Wish+ScaryFace',
            'Bagon+Wish+Crunch',
            'Bagon+IronDefense+Leer',
            'Bagon+IronDefense+Headbutt',
            'Bagon+IronDefense+FocusEnergy',
            'Bagon+IronDefense+DragonBreath',
            'Bagon+IronDefense+ScaryFace',
            'Bagon+IronDefense+Crunch',
            'Baltoy+Refresh',
            'Baltoy+Psybeam',
            'Baltoy+PowerTrick',
            'Baltoy+CosmicPower',
            'Baltoy+HealBlock',
            'Barboach+MudBomb+Double-Edge',
            'Barboach+MudBomb+Mimic',
            'Bellsprout+WringOut+Double-Edge',
            'Bellsprout+WringOut+Mimic',
            'Bellsprout+WringOut+TeeterDance',
            'Bellsprout+TeeterDance+Growth',
            'Bellsprout+TeeterDance+Wrap',
            'Bellsprout+TeeterDance+SleepPowder',
            'Bellsprout+TeeterDance+PoisonPowder',
            'Bellsprout+TeeterDance+StunSpore',
            'Bellsprout+TeeterDance+Acid',
            'Bellsprout+TeeterDance+SweetScent',
            'Bellsprout+TeeterDance+RazorLeaf',
            'Bellsprout+TeeterDance+Slam',
            'Bronzor+Hypnosis',
            'Bronzor+Imprison',
            'Bronzor+ConfuseRay',
            'Bronzor+Extrasensory',
            'Bronzor+IronDefense',
            'Bronzor+FutureSight',
            'Bronzor+FaintAttack',
            'Bronzor+HealBlock',
            'Bulbasaur+TakeDown+BodySlam',
            'Bulbasaur+TakeDown+Mimic',
            'Bulbasaur+TakeDown+DefenseCurl',
            'Bulbasaur+WorrySeed+BodySlam',
            'Bulbasaur+WorrySeed+Mimic',
            'Bulbasaur+WorrySeed+DefenseCurl',
            'Cacnea+Encore+Growth',
            'Cacnea+Encore+LeechSeed',
            'Cacnea+Encore+Sand-Attack',
            'Cacnea+Encore+PinMissile',
            'Cacnea+Encore+Ingrain',
            'Cacnea+Encore+FaintAttack',
            'Cacnea+Encore+Spikes',
            'Cacnea+Encore+NeedleArm',
            'Cacnea+Encore+CottonSpore',
            'Cacnea+Encore+DestinyBond',
            'Carvanha+Refresh',
            'Carvanha+IceFang+Mimic',
            'Carvanha+Assurance+Mimic',
            'Carvanha+AquaJet+Mimic',
            'Charmander+Howl',
            'Charmander+QuickAttack',
            'Charmander+FireFang+MegaPunch',
            'Charmander+FireFang+MegaKick',
            'Charmander+FireFang+BodySlam',
            'Charmander+FireFang+Double-Edge',
            'Charmander+FireFang+Counter',
            'Charmander+FireFang+SeismicToss',
            'Charmander+FireFang+Mimic',
            'Charmander+FireFang+DefenseCurl',
            'Charmander+FireFang+DynamicPunch',
            'Chikorita+MagicalLeaf+Double-Edge',
            'Chikorita+MagicalLeaf+Mimic',
            'Chikorita+MagicalLeaf+FrenzyPlant',
            'Chikorita+SweetScent+Double-Edge',
            'Chikorita+SweetScent+Mimic',
            'Chikorita+SweetScent+FrenzyPlant',
            'Chikorita+Aromatherapy+Double-Edge',
            'Chikorita+Aromatherapy+Mimic',
            'Chikorita+Aromatherapy+FrenzyPlant',
            'Chikorita+FrenzyPlant+RazorLeaf',
            'Chikorita+FrenzyPlant+PoisonPowder',
            'Chinchou+BubbleBeam+Double-Edge',
            'Chinchou+BubbleBeam+Mimic',
            'Chinchou+Discharge+Double-Edge',
            'Chinchou+Discharge+Mimic',
            'Chinchou+AquaRing+Double-Edge',
            'Chinchou+AquaRing+Mimic',
            'Cleffa+Copycat+MegaPunch',
            'Cleffa+Copycat+MegaKick',
            'Cleffa+Copycat+BodySlam',
            'Cleffa+Copycat+Double-Edge',
            'Cleffa+Copycat+Counter',
            'Cleffa+Copycat+SeismicToss',
            'Cleffa+Copycat+Softboiled',
            'Cleffa+Copycat+DefenseCurl',
            'Cleffa+Copycat+Nightmare',
            'Corphish+WaterSport+Harden',
            'Corphish+WaterSport+ViceGrip',
            'Corphish+WaterSport+Leer',
            'Corphish+WaterSport+BubbleBeam',
            'Corphish+WaterSport+Crabhammer',
            'Corphish+WaterSport+Crunch',
            'Corphish+WaterSport+Guillotine',
            'Corphish+WaterSport+NightSlash',
            'Corphish+NightSlash+Double-Edge',
            'Corphish+NightSlash+Counter',
            'Corphish+NightSlash+Mimic',
            'Cyndaquil+LavaPlume+BodySlam',
            'Cyndaquil+LavaPlume+Mimic',
            'Cyndaquil+LavaPlume+BlastBurn',
            'Cyndaquil+Eruption+BodySlam',
            'Cyndaquil+Eruption+Mimic',
            'Cyndaquil+Eruption+BlastBurn',
            'Cyndaquil+BlastBurn+Ember',
            'Cyndaquil+BlastBurn+QuickAttack',
            'Cyndaquil+BlastBurn+FlameWheel',
            'Diglett+Astonish+BodySlam',
            'Diglett+Astonish+Double-Edge',
            'Diglett+Astonish+Mimic',
            'Diglett+Astonish+FurySwipes',
            'Diglett+MudBomb+BodySlam',
            'Diglett+MudBomb+Double-Edge',
            'Diglett+MudBomb+Mimic',
            'Diglett+MudBomb+FurySwipes',
            'Doduo+Acupressure+BodySlam',
            'Doduo+Acupressure+Double-Edge',
            'Doduo+Acupressure+Mimic',
            'Doduo+Acupressure+SkyAttack',
            'Doduo+Acupressure+TriAttack',
            'Doduo+DoubleHit+BodySlam',
            'Doduo+DoubleHit+Double-Edge',
            'Doduo+DoubleHit+Mimic',
            'Doduo+DoubleHit+SkyAttack',
            'Doduo+DoubleHit+TriAttack',
            'Dratini+DragonRush+BodySlam',
            'Dratini+DragonRush+Double-Edge',
            'Dratini+DragonRush+Mimic',
            'Dratini+DragonDance+Haze+BodySlam',
            'Dratini+DragonDance+Haze+Double-Edge',
            'Dratini+DragonDance+Haze+Mimic',
            'Dratini+DragonDance+LightScreen+BodySlam',
            'Dratini+DragonDance+LightScreen+Double-Edge',
            'Dratini+DragonDance+LightScreen+Mimic',
            'Dratini+DragonDance+Supersonic+BodySlam',
            'Dratini+DragonDance+Supersonic+Double-Edge',
            'Dratini+DragonDance+Supersonic+Mimic',
            'Drowzee+Psybeam+MegaPunch',
            'Drowzee+Psybeam+MegaKick',
            'Drowzee+Psybeam+Double-Edge',
            'Drowzee+Psybeam+Counter',
            'Drowzee+Psybeam+SeismicToss',
            'Drowzee+Psybeam+Mimic',
            'Drowzee+Psybeam+Metronome',
            'Drowzee+Psybeam+DynamicPunch',
            'Drowzee+Psybeam+Nightmare',
            'Drowzee+Psybeam+BellyDrum',
            'Drowzee+Psybeam+Wish',
            'Drowzee+NastyPlot+MegaPunch',
            'Drowzee+NastyPlot+MegaKick',
            'Drowzee+NastyPlot+Double-Edge',
            'Drowzee+NastyPlot+Counter',
            'Drowzee+NastyPlot+SeismicToss',
            'Drowzee+NastyPlot+Mimic',
            'Drowzee+NastyPlot+Metronome',
            'Drowzee+NastyPlot+DynamicPunch',
            'Drowzee+NastyPlot+Nightmare',
            'Drowzee+NastyPlot+BellyDrum',
            'Drowzee+NastyPlot+Wish',
            'Drowzee+BellyDrum+Disable',
            'Drowzee+BellyDrum+Confusion',
            'Drowzee+BellyDrum+Headbutt',
            'Drowzee+BellyDrum+PoisonGas',
            'Drowzee+BellyDrum+Meditate',
            'Drowzee+BellyDrum+FutureSight',
            'Drowzee+Wish+Disable',
            'Drowzee+Wish+Confusion',
            'Drowzee+Wish+Headbutt',
            'Drowzee+Wish+PoisonGas',
            'Drowzee+Wish+Meditate',
            'Drowzee+Wish+FutureSight',
            'Duskull+HelpingHand',
            'Duskull+ShadowSneak+BodySlam',
            'Duskull+ShadowSneak+Double-Edge',
            'Duskull+ShadowSneak+Mimic',
            'Duskull+ShadowSneak+Nightmare',
            'Eevee+TrumpCard+BodySlam',
            'Eevee+TrumpCard+Double-Edge',
            'Eevee+TrumpCard+Mimic',
            'Ekans+MudBomb+BodySlam',
            'Ekans+MudBomb+Double-Edge',
            'Ekans+MudBomb+Mimic',
            'Electrike+ThunderFang+BodySlam',
            'Electrike+ThunderFang+Double-Edge',
            'Electrike+ThunderFang+Mimic',
            'Electrike+Discharge+BodySlam',
            'Electrike+Discharge+Double-Edge',
            'Electrike+Discharge+Mimic',
            'Elekid+ThunderShock+MegaPunch',
            'Elekid+ThunderShock+MegaKick',
            'Elekid+ThunderShock+BodySlam',
            'Elekid+ThunderShock+Double-Edge',
            'Elekid+ThunderShock+Counter',
            'Elekid+ThunderShock+SeismicToss',
            'Elekid+ThunderShock+Mimic',
            'Elekid+LowKick+MegaPunch',
            'Elekid+LowKick+MegaKick',
            'Elekid+LowKick+BodySlam',
            'Elekid+LowKick+Double-Edge',
            'Elekid+LowKick+Counter',
            'Elekid+LowKick+SeismicToss',
            'Elekid+LowKick+Mimic',
            'Elekid+Discharge+MegaPunch',
            'Elekid+Discharge+MegaKick',
            'Elekid+Discharge+BodySlam',
            'Elekid+Discharge+Double-Edge',
            'Elekid+Discharge+Counter',
            'Elekid+Discharge+SeismicToss',
            'Elekid+Discharge+Mimic',
            'Exeggcute+WorrySeed+Double-Edge',
            'Exeggcute+WorrySeed+Mimic',
            'Exeggcute+WorrySeed+Nightmare',
            'Exeggcute+WorrySeed+Selfdestruct',
            'Exeggcute+WorrySeed+SweetScent',
            'Exeggcute+WorrySeed+Wish',
            'Exeggcute+SweetScent+LeechSeed',
            'Exeggcute+SweetScent+StunSpore',
            'Exeggcute+SweetScent+PoisonPowder',
            'Exeggcute+SweetScent+SleepPowder',
            'Exeggcute+SweetScent+Confusion',
            'Exeggcute+Wish+LeechSeed',
            'Exeggcute+Wish+StunSpore',
            'Exeggcute+Wish+PoisonPowder',
            'Exeggcute+Wish+SleepPowder',
            'Exeggcute+Wish+Confusion',
            'Gligar+KnockOff+Mimic',
            'Gligar+KnockOff+DreamEater',
            'Goldeen+AquaRing+Double-Edge',
            'Goldeen+AquaRing+Mimic',
            'Grimer+HelpingHand',
            'Grimer+MudBomb+BodySlam',
            'Grimer+MudBomb+Mimic',
            'Grimer+MudBomb+DynamicPunch',
            'Grimer+MudBomb+Selfdestruct',
            'Growlithe+Charm',
            'Growlithe+Reversal+BodySlam',
            'Growlithe+Reversal+Mimic',
            'Growlithe+FireFang+BodySlam',
            'Growlithe+FireFang+Mimic',
            'Gulpin+Sing',
            'Gulpin+WringOut+BodySlam',
            'Gulpin+WringOut+Double-Edge',
            'Gulpin+WringOut+Counter',
            'Gulpin+WringOut+Mimic',
            'Gulpin+WringOut+DynamicPunch',
            'Gulpin+WringOut+DefenseCurl',
            'Gulpin+WringOut+Nightmare',
            'Gulpin+WringOut+Selfdestruct',
            'Happiny+Refresh+SweetKiss',
            'Happiny+Refresh+Present',
            'Happiny+Refresh+Metronome',
            'Happiny+Refresh+HealBell',
            'Happiny+Refresh+Aromatherapy',
            'Happiny+Refresh+Gravity',
            'Happiny+SweetKiss+HealBell',
            'Hoothoot+Uproar+Double-Edge',
            'Hoothoot+Uproar+Mimic',
            'Hoothoot+Uproar+Snore',
            'Hoothoot+Uproar+Nightmare',
            'Hoothoot+AirSlash+Double-Edge',
            'Hoothoot+AirSlash+Mimic',
            'Hoothoot+AirSlash+Snore',
            'Hoothoot+AirSlash+Nightmare',
            'Hoothoot+Extrasensory+Double-Edge',
            'Hoothoot+Extrasensory+Mimic',
            'Hoothoot+Extrasensory+Snore',
            'Hoothoot+Extrasensory+Nightmare',
            'Hoothoot+PsychoShift+Double-Edge',
            'Hoothoot+PsychoShift+Mimic',
            'Hoothoot+PsychoShift+Snore',
            'Hoothoot+PsychoShift+Nightmare',
            'Hoppip+WorrySeed+Mimic',
            'Hoppip+WorrySeed+DefenseCurl',
            'Hoppip+Memento+Mimic',
            'Hoppip+Memento+DefenseCurl',
            'Horsea+FocusEnergy+Double-Edge',
            'Horsea+FocusEnergy+Mimic',
            'Horsea+BubbleBeam+Double-Edge',
            'Horsea+BubbleBeam+Mimic',
            'Houndour+Charm',
            'Houndour+FireFang+BodySlam',
            'Houndour+FireFang+Double-Edge',
            'Houndour+FireFang+Mimic',
            'Houndour+FireFang+Nightmare',
            'Houndour+NastyPlot+BodySlam',
            'Houndour+NastyPlot+Double-Edge',
            'Houndour+NastyPlot+Mimic',
            'Houndour+NastyPlot+Nightmare',
            'Igglybuff+Tickle+Pound',
            'Igglybuff+Tickle+SweetKiss',
            'Igglybuff+Tickle+Copycat',
            'Igglybuff+Copycat+MegaPunch',
            'Igglybuff+Copycat+MegaKick',
            'Igglybuff+Copycat+BodySlam',
            'Igglybuff+Copycat+Double-Edge',
            'Igglybuff+Copycat+Counter',
            'Igglybuff+Copycat+SeismicToss',
            'Igglybuff+Copycat+Mimic',
            'Igglybuff+Copycat+Nightmare',
            'Kabuto+AquaJet+BodySlam',
            'Kabuto+AquaJet+Double-Edge',
            'Kabuto+AquaJet+Mimic',
            'Kabuto+WringOut+BodySlam',
            'Kabuto+WringOut+Double-Edge',
            'Kabuto+WringOut+Mimic',
            'Koffing+Assurance+Mimic',
            'Krabby+MetalClaw+BodySlam',
            'Krabby+MetalClaw+Double-Edge',
            'Krabby+MetalClaw+Mimic',
            'Krabby+Slam+Amnesia+BodySlam',
            'Krabby+Slam+Amnesia+Double-Edge',
            'Krabby+Slam+Amnesia+Mimic',
            'Krabby+Slam+Flail+BodySlam',
            'Krabby+Slam+Flail+Double-Edge',
            'Krabby+Slam+Flail+Mimic',
            'Ledyba+Refresh',
            'Ledyba+MachPunch+MegaPunch',
            'Ledyba+MachPunch+Mimic',
            'Ledyba+MachPunch+DynamicPunch',
            'Ledyba+BugBuzz+MegaPunch',
            'Ledyba+BugBuzz+Mimic',
            'Ledyba+BugBuzz+DynamicPunch',
            'Lickitung+HelpingHand',
            'Lickitung+MeFirst+MegaPunch',
            'Lickitung+MeFirst+MegaKick',
            'Lickitung+MeFirst+Double-Edge',
            'Lickitung+MeFirst+Counter',
            'Lickitung+MeFirst+SeismicToss',
            'Lickitung+MeFirst+Mimic',
            'Lickitung+MeFirst+DynamicPunch',
            'Lickitung+MeFirst+Nightmare',
            'Lickitung+MeFirst+HealBell',
            'Lickitung+MeFirst+Wish',
            'Lickitung+PowerWhip+MegaPunch',
            'Lickitung+PowerWhip+MegaKick',
            'Lickitung+PowerWhip+Double-Edge',
            'Lickitung+PowerWhip+Counter',
            'Lickitung+PowerWhip+SeismicToss',
            'Lickitung+PowerWhip+Mimic',
            'Lickitung+PowerWhip+DynamicPunch',
            'Lickitung+PowerWhip+Nightmare',
            'Lickitung+PowerWhip+HealBell',
            'Lickitung+PowerWhip+Wish',
            'Lickitung+WringOut+MegaPunch',
            'Lickitung+WringOut+MegaKick',
            'Lickitung+WringOut+Double-Edge',
            'Lickitung+WringOut+Counter',
            'Lickitung+WringOut+SeismicToss',
            'Lickitung+WringOut+Mimic',
            'Lickitung+WringOut+DynamicPunch',
            'Lickitung+WringOut+Nightmare',
            'Lickitung+WringOut+HealBell',
            'Lickitung+WringOut+Wish',
            'Lickitung+HealBell+KnockOff',
            'Lickitung+HealBell+Wrap',
            'Lickitung+HealBell+Stomp',
            'Lickitung+HealBell+Disable',
            'Lickitung+HealBell+Slam',
            'Lickitung+HealBell+Refresh',
            'Lickitung+HealBell+Screech',
            'Lickitung+Wish+KnockOff',
            'Lickitung+Wish+Wrap',
            'Lickitung+Wish+Stomp',
            'Lickitung+Wish+Disable',
            'Lickitung+Wish+Slam',
            'Lickitung+Wish+Refresh',
            'Lickitung+Wish+Screech',
            'Lileep+WringOut+BodySlam',
            'Lileep+WringOut+Double-Edge',
            'Lileep+WringOut+Mimic',
            'Lileep+WringOut+PsychUp',
            'Lotad+BubbleBeam+BodySlam',
            'Lotad+BubbleBeam+Double-Edge',
            'Lotad+BubbleBeam+Mimic',
            'Machop+Wake-UpSlap+MegaPunch',
            'Machop+Wake-UpSlap+MegaKick',
            'Machop+Wake-UpSlap+BodySlam',
            'Machop+Wake-UpSlap+Double-Edge',
            'Machop+Wake-UpSlap+Mimic',
            'Machop+Wake-UpSlap+Metronome',
            'Magby+FaintAttack+MegaKick',
            'Magby+FaintAttack+BodySlam',
            'Magby+FaintAttack+Double-Edge',
            'Magby+FaintAttack+Counter',
            'Magby+FaintAttack+SeismicToss',
            'Magby+FaintAttack+Mimic',
            'Magby+FireSpin+MegaKick',
            'Magby+FireSpin+BodySlam',
            'Magby+FireSpin+Double-Edge',
            'Magby+FireSpin+Counter',
            'Magby+FireSpin+SeismicToss',
            'Magby+FireSpin+Mimic',
            'Magby+LavaPlume+MegaKick',
            'Magby+LavaPlume+BodySlam',
            'Magby+LavaPlume+Double-Edge',
            'Magby+LavaPlume+Counter',
            'Magby+LavaPlume+SeismicToss',
            'Magby+LavaPlume+Mimic',
            'Magnemite+ThunderShock',
            'Magnemite+Supersonic',
            'Magnemite+SonicBoom',
            'Magnemite+Spark',
            'Magnemite+Lock-On',
            'Magnemite+MagnetBomb',
            'Magnemite+Screech',
            'Magnemite+ZapCannon',
            'Makuhita+Refresh',
            'Makuhita+ForcePalm+MegaPunch',
            'Makuhita+ForcePalm+MegaKick',
            'Makuhita+ForcePalm+BodySlam',
            'Makuhita+ForcePalm+Double-Edge',
            'Makuhita+ForcePalm+Mimic',
            'Makuhita+ForcePalm+Metronome',
            'Makuhita+Wake-UpSlap+MegaPunch',
            'Makuhita+Wake-UpSlap+MegaKick',
            'Makuhita+Wake-UpSlap+BodySlam',
            'Makuhita+Wake-UpSlap+Double-Edge',
            'Makuhita+Wake-UpSlap+Mimic',
            'Makuhita+Wake-UpSlap+Metronome',
            'Makuhita+CloseCombat+MegaPunch',
            'Makuhita+CloseCombat+MegaKick',
            'Makuhita+CloseCombat+BodySlam',
            'Makuhita+CloseCombat+Double-Edge',
            'Makuhita+CloseCombat+Mimic',
            'Makuhita+CloseCombat+Metronome',
            'Mankey+Assurance+MegaPunch',
            'Mankey+Assurance+MegaKick',
            'Mankey+Assurance+BodySlam',
            'Mankey+Assurance+Double-Edge',
            'Mankey+Assurance+Mimic',
            'Mankey+Assurance+Metronome',
            'Mankey+Assurance+DynamicPunch',
            'Mankey+Assurance+PsychUp',
            'Mankey+Assurance+Snore',
            'Mankey+Assurance+DefenseCurl',
            'Mankey+Punishment+MegaPunch',
            'Mankey+Punishment+MegaKick',
            'Mankey+Punishment+BodySlam',
            'Mankey+Punishment+Double-Edge',
            'Mankey+Punishment+Mimic',
            'Mankey+Punishment+Metronome',
            'Mankey+Punishment+DynamicPunch',
            'Mankey+Punishment+PsychUp',
            'Mankey+Punishment+Snore',
            'Mankey+Punishment+DefenseCurl',
            'Mankey+CloseCombat+MegaPunch',
            'Mankey+CloseCombat+MegaKick',
            'Mankey+CloseCombat+BodySlam',
            'Mankey+CloseCombat+Double-Edge',
            'Mankey+CloseCombat+Mimic',
            'Mankey+CloseCombat+Metronome',
            'Mankey+CloseCombat+DynamicPunch',
            'Mankey+CloseCombat+PsychUp',
            'Mankey+CloseCombat+Snore',
            'Mankey+CloseCombat+DefenseCurl',
            'Mareep+Discharge+Double-Edge',
            'Mareep+Discharge+Mimic',
            'Mareep+Discharge+DefenseCurl',
            'Mareep+PowerGem+Double-Edge',
            'Mareep+PowerGem+Mimic',
            'Mareep+PowerGem+DefenseCurl',
            'Meditite+Feint+MegaPunch',
            'Meditite+Feint+MegaKick',
            'Meditite+Feint+BodySlam',
            'Meditite+Feint+Double-Edge',
            'Meditite+Feint+Counter',
            'Meditite+Feint+SeismicToss',
            'Meditite+Feint+Mimic',
            'Meditite+Feint+Metronome',
            'Meditite+ForcePalm+MegaPunch',
            'Meditite+ForcePalm+MegaKick',
            'Meditite+ForcePalm+BodySlam',
            'Meditite+ForcePalm+Double-Edge',
            'Meditite+ForcePalm+Counter',
            'Meditite+ForcePalm+SeismicToss',
            'Meditite+ForcePalm+Mimic',
            'Meditite+ForcePalm+Metronome',
            'Meditite+PowerTrick+MegaPunch',
            'Meditite+PowerTrick+MegaKick',
            'Meditite+PowerTrick+BodySlam',
            'Meditite+PowerTrick+Double-Edge',
            'Meditite+PowerTrick+Counter',
            'Meditite+PowerTrick+SeismicToss',
            'Meditite+PowerTrick+Mimic',
            'Meditite+PowerTrick+Metronome',
            'Meowth+Sing',
            'Meowth+NastyPlot+BodySlam',
            'Meowth+NastyPlot+Double-Edge',
            'Meowth+NastyPlot+Mimic',
            'Meowth+NastyPlot+DefenseCurl',
            'Meowth+NastyPlot+Nightmare',
            'Meowth+NastyPlot+PetalDance',
            'Meowth+Assurance+BodySlam',
            'Meowth+Assurance+Double-Edge',
            'Meowth+Assurance+Mimic',
            'Meowth+Assurance+DefenseCurl',
            'Meowth+Assurance+Nightmare',
            'Meowth+Assurance+PetalDance',
            'Meowth+NightSlash+BodySlam',
            'Meowth+NightSlash+Double-Edge',
            'Meowth+NightSlash+Mimic',
            'Meowth+NightSlash+DefenseCurl',
            'Meowth+NightSlash+Nightmare',
            'Meowth+Feint+BodySlam',
            'Meowth+Feint+Double-Edge',
            'Meowth+Feint+Mimic',
            'Meowth+Feint+DefenseCurl',
            'Meowth+Feint+Nightmare',
            'Meowth+PetalDance+Bite',
            'Meowth+PetalDance+FakeOut',
            'Meowth+PetalDance+FurySwipes',
            'Meowth+PetalDance+Screech',
            'Meowth+PetalDance+FaintAttack',
            'Meowth+PetalDance+PayDay',
            'Meowth+PetalDance+Slash',
            'Misdreavus+PowerGem+Double-Edge',
            'Misdreavus+PowerGem+Mimic',
            'Misdreavus+PowerGem+DefenseCurl',
            'Misdreavus+PowerGem+Nightmare',
            'Murkrow+Assurance+Double-Edge',
            'Murkrow+Assurance+Mimic',
            'Murkrow+Assurance+Nightmare',
            'Murkrow+WingAttack+DrillPeck+Double-Edge',
            'Murkrow+WingAttack+DrillPeck+Mimic',
            'Murkrow+WingAttack+DrillPeck+Nightmare',
            'Murkrow+WingAttack+PerishSong+Double-Edge',
            'Murkrow+WingAttack+PerishSong+Mimic',
            'Murkrow+WingAttack+PerishSong+Nightmare',
            'Murkrow+WingAttack+ConfuseRay+FeatherDance+Double-Edge',
            'Murkrow+WingAttack+ConfuseRay+FeatherDance+Mimic',
            'Murkrow+WingAttack+ConfuseRay+FeatherDance+Nightmare',
            'Natu+BatonPass',
            'Natu+LuckyChant+Double-Edge',
            'Natu+LuckyChant+Mimic',
            'Natu+LuckyChant+Nightmare',
            'Natu+LuckyChant+SkyAttack',
            'Natu+MiracleEye+Double-Edge',
            'Natu+MiracleEye+Mimic',
            'Natu+MiracleEye+Nightmare',
            'Natu+MiracleEye+SkyAttack',
            'Natu+MeFirst+Double-Edge',
            'Natu+MeFirst+Mimic',
            'Natu+MeFirst+Nightmare',
            'Natu+MeFirst+SkyAttack',
            'Natu+PsychoShift+Double-Edge',
            'Natu+PsychoShift+Mimic',
            'Natu+PsychoShift+Nightmare',
            'Natu+PsychoShift+SkyAttack',
            'Natu+PowerSwap+Double-Edge',
            'Natu+PowerSwap+Mimic',
            'Natu+PowerSwap+Nightmare',
            'Natu+PowerSwap+SkyAttack',
            'Natu+GuardSwap+Double-Edge',
            'Natu+GuardSwap+Mimic',
            'Natu+GuardSwap+Nightmare',
            'Natu+GuardSwap+SkyAttack',
            'NidoranF+ToxicSpikes+BodySlam',
            'NidoranF+ToxicSpikes+Double-Edge',
            'NidoranF+ToxicSpikes+Mimic',
            'NidoranF+ToxicSpikes+DefenseCurl',
            'NidoranF+PoisonFang+BodySlam',
            'NidoranF+PoisonFang+Double-Edge',
            'NidoranF+PoisonFang+Mimic',
            'NidoranF+PoisonFang+DefenseCurl',
            'NidoranM+FuryAttack',
            'NidoranM+HornAttack',
            'NidoranM+HornDrill',
            'NidoranM+ToxicSpikes+BodySlam',
            'NidoranM+ToxicSpikes+Double-Edge',
            'NidoranM+ToxicSpikes+Mimic',
            'NidoranM+ToxicSpikes+DefenseCurl',
            'Nosepass+HelpingHand',
            'Nosepass+PowerGem+BodySlam',
            'Nosepass+PowerGem+Mimic',
            'Nosepass+PowerGem+DynamicPunch',
            'Nosepass+PowerGem+DefenseCurl',
            'Nosepass+PowerGem+Selfdestruct',
            'Nosepass+Discharge+BodySlam',
            'Nosepass+Discharge+Mimic',
            'Nosepass+Discharge+DynamicPunch',
            'Nosepass+Discharge+DefenseCurl',
            'Nosepass+Discharge+Selfdestruct',
            'Numel+Charm',
            'Numel+LavaPlume+Mimic',
            'Oddish+MegaDrain+Double-Edge',
            'Oddish+MegaDrain+Mimic',
            'Oddish+MegaDrain+LeechSeed',
            'Oddish+LuckyChant+Double-Edge',
            'Oddish+LuckyChant+Mimic',
            'Oddish+LuckyChant+LeechSeed',
            'Oddish+LeechSeed+SweetScent',
            'Oddish+LeechSeed+PoisonPowder',
            'Oddish+LeechSeed+StunSpore',
            'Oddish+LeechSeed+SleepPowder',
            'Oddish+LeechSeed+Acid',
            'Oddish+LeechSeed+Moonlight',
            'Oddish+LeechSeed+PetalDance',
            'Omanyte+RockBlast+BodySlam',
            'Omanyte+RockBlast+Double-Edge',
            'Omanyte+RockBlast+Mimic',
            'Onix+Curse+BodySlam',
            'Onix+Curse+Mimic',
            'Onix+Curse+Selfdestruct',
            'Paras+Refresh',
            'Phanpy+Slam+Mimic',
            'Phanpy+Charm+Mimic',
            'Pichu+TeeterDance+SweetKiss',
            'Pichu+TeeterDance+NastyPlot',
            'Pichu+FollowMe+SweetKiss',
            'Pichu+FollowMe+NastyPlot',
            'Pichu+NastyPlot+MegaPunch',
            'Pichu+NastyPlot+MegaKick',
            'Pichu+NastyPlot+BodySlam',
            'Pichu+NastyPlot+Double-Edge',
            'Pichu+NastyPlot+Counter',
            'Pichu+NastyPlot+SeismicToss',
            'Pichu+NastyPlot+Mimic',
            'Pichu+NastyPlot+DefenseCurl',
            'Pidgey+Tailwind+Double-Edge',
            'Pidgey+Tailwind+Mimic',
            'Pidgey+Tailwind+SkyAttack',
            'Pidgey+AirSlash+Double-Edge',
            'Pidgey+AirSlash+Mimic',
            'Pidgey+AirSlash+SkyAttack',
            'Pineco+Refresh',
            'Pineco+BugBite+BodySlam',
            'Pineco+BugBite+Mimic',
            'Pineco+BugBite+DefenseCurl',
            'Poliwag+MudShot+Double-Edge',
            'Poliwag+MudShot+Mimic',
            'Poliwag+MudShot+DefenseCurl',
            'Poliwag+MudShot+SweetScent',
            'Poliwag+Wake-UpSlap+Double-Edge',
            'Poliwag+Wake-UpSlap+Mimic',
            'Poliwag+Wake-UpSlap+DefenseCurl',
            'Poliwag+Wake-UpSlap+SweetScent',
            'Poliwag+MudBomb+Double-Edge',
            'Poliwag+MudBomb+Mimic',
            'Poliwag+MudBomb+DefenseCurl',
            'Poliwag+MudBomb+SweetScent',
            'Poliwag+SweetScent+Hypnosis',
            'Poliwag+SweetScent+WaterGun',
            'Poliwag+SweetScent+DoubleSlap',
            'Poliwag+SweetScent+BubbleBeam',
            'Poliwag+SweetScent+BellyDrum',
            'Poliwag+SweetScent+HydroPump',
            'Poliwag+BubbleBeam+IceBall+Double-Edge',
            'Poliwag+BubbleBeam+IceBall+Mimic',
            'Poliwag+BubbleBeam+IceBall+DefenseCurl',
            'Ponyta+FlareBlitz+BodySlam',
            'Ponyta+FlareBlitz+Mimic',
            'Ponyta+FlareBlitz+QuickAttack',
            'Poochyena+HealBell',
            'Poochyena+Assurance+BodySlam',
            'Poochyena+Assurance+Double-Edge',
            'Poochyena+Assurance+Counter',
            'Poochyena+Assurance+Mimic',
            'Poochyena+Assurance+PsychUp',
            'Porygon+Psybeam',
            'Porygon+Agility',
            'Porygon+Recover',
            'Porygon+MagnetRise',
            'Porygon+Discharge',
            'Porygon+Lock-On',
            'Porygon+TriAttack',
            'Porygon+MagicCoat',
            'Porygon+ZapCannon',
            'Psyduck+Amnesia+MegaPunch',
            'Psyduck+Amnesia+MegaKick',
            'Psyduck+Amnesia+BodySlam',
            'Psyduck+Amnesia+Double-Edge',
            'Psyduck+Amnesia+Counter',
            'Psyduck+Amnesia+SeismicToss',
            'Psyduck+Amnesia+Mimic',
            'Psyduck+Amnesia+DynamicPunch',
            'Psyduck+Amnesia+MudSport',
            'Psyduck+MudSport+WaterGun',
            'Psyduck+MudSport+Disable',
            'Psyduck+MudSport+Confusion',
            'Psyduck+MudSport+FurySwipes',
            'Psyduck+MudSport+Screech',
            'Psyduck+MudSport+HydroPump',
            'Ralts+Sing',
            'Ralts+Wish+Confusion',
            'Ralts+Wish+Teleport',
            'Ralts+Wish+Imprison',
            'Ralts+Wish+FutureSight',
            'Ralts+Wish+Hypnosis',
            'Ralts+Wish+LuckyChant',
            'Ralts+Wish+MagicalLeaf',
            'Ralts+Wish+Charm',
            'Ralts+LuckyChant+BodySlam',
            'Ralts+LuckyChant+Double-Edge',
            'Ralts+LuckyChant+Mimic',
            'Ralts+LuckyChant+DefenseCurl',
            'Ralts+LuckyChant+Nightmare',
            'Ralts+MagicalLeaf+BodySlam',
            'Ralts+MagicalLeaf+Double-Edge',
            'Ralts+MagicalLeaf+Mimic',
            'Ralts+MagicalLeaf+DefenseCurl',
            'Ralts+MagicalLeaf+Nightmare',
            'Ralts+Charm+Confusion+BodySlam',
            'Ralts+Charm+Confusion+Double-Edge',
            'Ralts+Charm+Confusion+Mimic',
            'Ralts+Charm+Confusion+DefenseCurl',
            'Ralts+Charm+Confusion+Nightmare',
            'Ralts+Charm+Teleport+BodySlam',
            'Ralts+Charm+Teleport+Double-Edge',
            'Ralts+Charm+Teleport+Mimic',
            'Ralts+Charm+Teleport+DefenseCurl',
            'Ralts+Charm+Teleport+Nightmare',
            'Ralts+Charm+Imprison+BodySlam',
            'Ralts+Charm+Imprison+Double-Edge',
            'Ralts+Charm+Imprison+Mimic',
            'Ralts+Charm+Imprison+DefenseCurl',
            'Ralts+Charm+Imprison+Nightmare',
            'Ralts+Charm+FutureSight+BodySlam',
            'Ralts+Charm+FutureSight+Double-Edge',
            'Ralts+Charm+FutureSight+Mimic',
            'Ralts+Charm+FutureSight+DefenseCurl',
            'Ralts+Charm+FutureSight+Nightmare',
            'Ralts+Charm+Hypnosis+BodySlam',
            'Ralts+Charm+Hypnosis+Double-Edge',
            'Ralts+Charm+Hypnosis+Mimic',
            'Ralts+Charm+Hypnosis+DefenseCurl',
            'Ralts+Charm+Hypnosis+Nightmare',
            'Ralts+Charm+Disable+BodySlam',
            'Ralts+Charm+Disable+Double-Edge',
            'Ralts+Charm+Disable+Mimic',
            'Ralts+Charm+Disable+DefenseCurl',
            'Ralts+Charm+Disable+Nightmare',
            'Ralts+Charm+Will-O-Wisp+BodySlam',
            'Ralts+Charm+Will-O-Wisp+Double-Edge',
            'Ralts+Charm+Will-O-Wisp+Mimic',
            'Ralts+Charm+Will-O-Wisp+DefenseCurl',
            'Ralts+Charm+Will-O-Wisp+Nightmare',
            'Ralts+Charm+MeanLook+BodySlam',
            'Ralts+Charm+MeanLook+Double-Edge',
            'Ralts+Charm+MeanLook+Mimic',
            'Ralts+Charm+MeanLook+DefenseCurl',
            'Ralts+Charm+MeanLook+Nightmare',
            'Ralts+Charm+Memento+BodySlam',
            'Ralts+Charm+Memento+Double-Edge',
            'Ralts+Charm+Memento+Mimic',
            'Ralts+Charm+Memento+DefenseCurl',
            'Ralts+Charm+Memento+Nightmare',
            'Ralts+Charm+DestinyBond+BodySlam',
            'Ralts+Charm+DestinyBond+Double-Edge',
            'Ralts+Charm+DestinyBond+Mimic',
            'Ralts+Charm+DestinyBond+DefenseCurl',
            'Ralts+Charm+DestinyBond+Nightmare',
            'Rattata+Crunch+BodySlam',
            'Rattata+Crunch+Mimic',
            'Rattata+Assurance+BodySlam',
            'Rattata+Assurance+Mimic',
            'Riolu+AuraSphere',
            'Scyther+MorningSun',
            'Scyther+NightSlash+Double-Edge',
            'Scyther+NightSlash+Mimic',
            'Scyther+DoubleHit+Double-Edge',
            'Scyther+DoubleHit+Mimic',
            'Scyther+AirSlash+Double-Edge',
            'Scyther+AirSlash+Mimic',
            'Scyther+Feint+Double-Edge',
            'Scyther+Feint+Mimic',
            'Scyther+RazorWind+BatonPass+Double-Edge',
            'Scyther+RazorWind+BatonPass+Mimic',
            'Scyther+RazorWind+LightScreen+Double-Edge',
            'Scyther+RazorWind+LightScreen+Mimic',
            'Scyther+RazorWind+Reversal+Double-Edge',
            'Scyther+RazorWind+Reversal+Mimic',
            'Scyther+RazorWind+Safeguard+Double-Edge',
            'Scyther+RazorWind+Safeguard+Mimic',
            'Seedot+Refresh',
            'Seel+HelpingHand',
            'Seel+WaterSport+BodySlam',
            'Seel+WaterSport+Double-Edge',
            'Seel+WaterSport+Mimic',
            'Seel+IceShard+BodySlam',
            'Seel+IceShard+Double-Edge',
            'Seel+IceShard+Mimic',
            'Seel+AquaRing+BodySlam',
            'Seel+AquaRing+Double-Edge',
            'Seel+AquaRing+Mimic',
            'Seel+AquaJet+BodySlam',
            'Seel+AquaJet+Double-Edge',
            'Seel+AquaJet+Mimic',
            'Sentret+BatonPass+BodySlam',
            'Sentret+BatonPass+Mimic',
            'Sentret+BatonPass+DynamicPunch',
            'Sentret+MeFirst+BodySlam',
            'Sentret+MeFirst+Mimic',
            'Sentret+MeFirst+DynamicPunch',
            'Sentret+HyperVoice+BodySlam',
            'Sentret+HyperVoice+Mimic',
            'Sentret+HyperVoice+DynamicPunch',
            'Shellder+Refresh',
            'Shellder+IceShard+Double-Edge',
            'Shellder+IceShard+Mimic',
            'Shellder+IceShard+Selfdestruct',
            'Shellder+Whirlpool+Double-Edge',
            'Shellder+Whirlpool+Mimic',
            'Shellder+Whirlpool+Selfdestruct',
            'Shroomish+Refresh',
            'Shroomish+WorrySeed+BodySlam',
            'Shroomish+WorrySeed+Double-Edge',
            'Shroomish+WorrySeed+Mimic',
            'Shuppet+ShadowSneak+BodySlam',
            'Shuppet+ShadowSneak+Double-Edge',
            'Shuppet+ShadowSneak+Mimic',
            'Shuppet+ShadowSneak+Snore',
            'Shuppet+ShadowSneak+Nightmare',
            'Skitty+PayDay+Sing',
            'Skitty+PayDay+DoubleSlap',
            'Skitty+PayDay+Assist',
            'Skitty+PayDay+Charm',
            'Skitty+PayDay+FaintAttack',
            'Skitty+PayDay+Covet',
            'Skitty+PayDay+HealBell',
            'Skitty+PayDay+Copycat',
            'Skitty+PayDay+Wake-UpSlap',
            'Skitty+Copycat+BodySlam',
            'Skitty+Copycat+Mimic',
            'Skitty+Copycat+DefenseCurl',
            'Skitty+Wake-UpSlap+BodySlam',
            'Skitty+Wake-UpSlap+Mimic',
            'Skitty+Wake-UpSlap+DefenseCurl',
            'Slowpoke+SlackOff+BodySlam',
            'Slowpoke+SlackOff+Double-Edge',
            'Slowpoke+SlackOff+Mimic',
            'Slowpoke+SlackOff+IcyWind',
            'Slowpoke+SlackOff+Nightmare',
            'Slugma+Recover+Double-Edge',
            'Slugma+Recover+Mimic',
            'Slugma+Recover+DefenseCurl',
            'Slugma+Recover+Selfdestruct',
            'Slugma+LavaPlume+Double-Edge',
            'Slugma+LavaPlume+Mimic',
            'Slugma+LavaPlume+DefenseCurl',
            'Slugma+LavaPlume+Selfdestruct',
            'Smoochum+PowderSnow',
            'Smoochum+PerishSong',
            'Smoochum+LuckyChant',
            'Smoochum+SweetKiss+MegaPunch',
            'Smoochum+SweetKiss+MegaKick',
            'Smoochum+SweetKiss+BodySlam',
            'Smoochum+SweetKiss+Double-Edge',
            'Smoochum+SweetKiss+Counter',
            'Smoochum+SweetKiss+SeismicToss',
            'Smoochum+SweetKiss+Mimic',
            'Smoochum+SweetKiss+Metronome',
            'Smoochum+SweetKiss+DynamicPunch',
            'Smoochum+SweetKiss+Nightmare',
            'Smoochum+FakeTears+MegaPunch',
            'Smoochum+FakeTears+MegaKick',
            'Smoochum+FakeTears+BodySlam',
            'Smoochum+FakeTears+Double-Edge',
            'Smoochum+FakeTears+Counter',
            'Smoochum+FakeTears+SeismicToss',
            'Smoochum+FakeTears+Mimic',
            'Smoochum+FakeTears+Metronome',
            'Smoochum+FakeTears+DynamicPunch',
            'Smoochum+FakeTears+Nightmare',
            'Smoochum+Copycat+MegaPunch',
            'Smoochum+Copycat+MegaKick',
            'Smoochum+Copycat+BodySlam',
            'Smoochum+Copycat+Double-Edge',
            'Smoochum+Copycat+Counter',
            'Smoochum+Copycat+SeismicToss',
            'Smoochum+Copycat+Mimic',
            'Smoochum+Copycat+Metronome',
            'Smoochum+Copycat+DynamicPunch',
            'Smoochum+Copycat+Nightmare',
            'Smoochum+SweetKiss+Confusion',
            'Smoochum+SweetKiss+Sing',
            'Smoochum+SweetKiss+MeanLook',
            'Smoochum+SweetKiss+Copycat',
            'Smoochum+SweetKiss+Meditate',
            'Smoochum+SweetKiss+Wish',
            'Smoochum+SweetKiss+MiracleEye',
            'Smoochum+Confusion+Sing',
            'Smoochum+Confusion+MeanLook',
            'Smoochum+Confusion+FakeTears',
            'Smoochum+Sing+MeanLook',
            'Smoochum+Sing+FakeTears',
            'Smoochum+Sing+Meditate',
            'Smoochum+Sing+FakeOut',
            'Smoochum+Sing+Wish',
            'Smoochum+Sing+MiracleEye',
            'Smoochum+MeanLook+FakeTears',
            'Smoochum+MeanLook+Copycat',
            'Smoochum+MeanLook+Meditate',
            'Smoochum+MeanLook+Wish',
            'Smoochum+MeanLook+MiracleEye',
            'Smoochum+FakeTears+Copycat',
            'Smoochum+FakeTears+Meditate',
            'Smoochum+FakeTears+Wish',
            'Smoochum+FakeTears+MiracleEye',
            'Smoochum+Copycat+Wish',
            'Smoochum+Copycat+MiracleEye',
            'Smoochum+Confusion+FakeOut+Wish',
            'Sneasel+IceShard+Double-Edge',
            'Sneasel+IceShard+Mimic',
            'Sneasel+IceShard+DefenseCurl',
            'Sneasel+IceShard+DynamicPunch',
            'Sneasel+IceShard+Nightmare',
            'Snorunt+Sing',
            'Snorunt+IceFang+BodySlam',
            'Snorunt+IceFang+Double-Edge',
            'Snorunt+IceFang+Mimic',
            'Snorunt+IceShard+BodySlam',
            'Snorunt+IceShard+Double-Edge',
            'Snorunt+IceShard+Mimic',
            'Snubbull+Headbutt+MegaPunch',
            'Snubbull+Headbutt+MegaKick',
            'Snubbull+Headbutt+BodySlam',
            'Snubbull+Headbutt+Double-Edge',
            'Snubbull+Headbutt+Counter',
            'Snubbull+Headbutt+SeismicToss',
            'Snubbull+Headbutt+Mimic',
            'Snubbull+Headbutt+Metronome',
            'Snubbull+Headbutt+DefenseCurl',
            'Snubbull+Headbutt+DynamicPunch',
            'Spearow+BatonPass',
            'Spearow+Assurance+Double-Edge',
            'Spearow+Assurance+Mimic',
            'Spheal+Charm',
            'Spinarak+Refresh',
            'Spinarak+ShadowSneak+BodySlam',
            'Spinarak+ShadowSneak+Double-Edge',
            'Spinarak+ShadowSneak+Mimic',
            'Spinarak+ShadowSneak+Snore',
            'Spinarak+PinMissile+BodySlam',
            'Spinarak+PinMissile+Double-Edge',
            'Spinarak+PinMissile+Mimic',
            'Spinarak+PinMissile+Snore',
            'Spoink+Uproar+Psywave',
            'Spoink+Uproar+OdorSleuth',
            'Spoink+Uproar+Psybeam',
            'Spoink+Uproar+ConfuseRay',
            'Spoink+Uproar+MagicCoat',
            'Spoink+Uproar+PowerGem',
            'Spoink+PowerGem+BodySlam',
            'Spoink+PowerGem+Double-Edge',
            'Spoink+PowerGem+Mimic',
            'Staryu+WaterGun',
            'Staryu+RapidSpin',
            'Staryu+Recover',
            'Staryu+Camouflage',
            'Staryu+BubbleBeam',
            'Staryu+Minimize',
            'Staryu+PowerGem',
            'Staryu+CosmicPower',
            'Staryu+HydroPump',
            'Sunkern+Mimic+WorrySeed',
            'Sunkern+Mimic+RazorLeaf',
            'Sunkern+Double-Edge+WorrySeed',
            'Sunkern+Double-Edge+RazorLeaf',
            'Surskit+MudSport+QuickAttack',
            'Surskit+MudSport+SweetScent',
            'Surskit+MudSport+WaterSport',
            'Surskit+MudSport+BubbleBeam',
            'Surskit+MudSport+Agility',
            'Surskit+MudSport+Mist',
            'Surskit+MudSport+Haze',
            'Surskit+MudSport+BatonPass',
            'Surskit+BatonPass+Double-Edge',
            'Surskit+BatonPass+Mimic',
            'Swablu+FalseSwipe+Sing',
            'Swablu+FalseSwipe+FuryAttack',
            'Swablu+FalseSwipe+Mist',
            'Swablu+FalseSwipe+TakeDown',
            'Swablu+FalseSwipe+MirrorMove',
            'Swablu+FalseSwipe+Refresh',
            'Swablu+FalseSwipe+PerishSong',
            'Swinub+Charm',
            'Swinub+MudBomb+Mimic',
            'Swinub+MudBomb+DefenseCurl',
            'Swinub+IceShard+Mimic',
            'Swinub+IceShard+DefenseCurl',
            'Taillow+FeatherDance+QuickAttack',
            'Taillow+FeatherDance+WingAttack',
            'Taillow+FeatherDance+Agility',
            'Taillow+FeatherDance+AirSlash',
            'Taillow+AirSlash+Double-Edge',
            'Taillow+AirSlash+Counter',
            'Taillow+AirSlash+Mimic',
            'Tangela+MorningSun',
            'Tangela+WringOut+BodySlam',
            'Tangela+WringOut+Double-Edge',
            'Tangela+WringOut+Mimic',
            'Tangela+PowerWhip+BodySlam',
            'Tangela+PowerWhip+Double-Edge',
            'Tangela+PowerWhip+Mimic',
            'Teddiursa+Refresh',
            'Teddiursa+SweetScent+MegaPunch',
            'Teddiursa+SweetScent+MegaKick',
            'Teddiursa+SweetScent+BodySlam',
            'Teddiursa+SweetScent+SeismicToss',
            'Teddiursa+SweetScent+Mimic',
            'Teddiursa+SweetScent+Metronome',
            'Teddiursa+SweetScent+DefenseCurl',
            'Teddiursa+SweetScent+DynamicPunch',
            'Teddiursa+Charm+MegaPunch',
            'Teddiursa+Charm+MegaKick',
            'Teddiursa+Charm+BodySlam',
            'Teddiursa+Charm+SeismicToss',
            'Teddiursa+Charm+Mimic',
            'Teddiursa+Charm+Metronome',
            'Teddiursa+Charm+DefenseCurl',
            'Teddiursa+Charm+DynamicPunch',
            'Tentacool+ToxicSpikes+Double-Edge',
            'Tentacool+ToxicSpikes+Mimic',
            'Tentacool+WringOut+Double-Edge',
            'Tentacool+WringOut+Mimic',
            'Togepi+TriAttack',
            'Totodile+IceFang+MegaPunch',
            'Totodile+IceFang+MegaKick',
            'Totodile+IceFang+BodySlam',
            'Totodile+IceFang+Double-Edge',
            'Totodile+IceFang+Counter',
            'Totodile+IceFang+SeismicToss',
            'Totodile+IceFang+Mimic',
            'Totodile+IceFang+DynamicPunch',
            'Totodile+IceFang+HydroCannon',
            'Totodile+Flail+MegaPunch',
            'Totodile+Flail+MegaKick',
            'Totodile+Flail+BodySlam',
            'Totodile+Flail+Double-Edge',
            'Totodile+Flail+Counter',
            'Totodile+Flail+SeismicToss',
            'Totodile+Flail+Mimic',
            'Totodile+Flail+DynamicPunch',
            'Totodile+Flail+HydroCannon',
            'Totodile+Superpower+MegaPunch',
            'Totodile+Superpower+MegaKick',
            'Totodile+Superpower+BodySlam',
            'Totodile+Superpower+Double-Edge',
            'Totodile+Superpower+Counter',
            'Totodile+Superpower+SeismicToss',
            'Totodile+Superpower+Mimic',
            'Totodile+Superpower+DynamicPunch',
            'Totodile+Superpower+HydroCannon',
            'Totodile+HydroCannon+WaterGun',
            'Totodile+HydroCannon+Rage',
            'Totodile+HydroCannon+Bite',
            'Totodile+HydroCannon+ScaryFace',
            'Totodile+HydroCannon+Thrash',
            'Totodile+HydroCannon+Slash',
            'Totodile+HydroCannon+Screech',
            'Totodile+HydroCannon+HydroPump',
            'Totodile+Thrash+MudSport+MegaPunch',
            'Totodile+Thrash+MudSport+MegaKick',
            'Totodile+Thrash+MudSport+BodySlam',
            'Totodile+Thrash+MudSport+Double-Edge',
            'Totodile+Thrash+MudSport+Counter',
            'Totodile+Thrash+MudSport+SeismicToss',
            'Totodile+Thrash+MudSport+Mimic',
            'Totodile+Thrash+MudSport+DynamicPunch',
            'Totodile+Thrash+WaterSport+MegaPunch',
            'Totodile+Thrash+WaterSport+MegaKick',
            'Totodile+Thrash+WaterSport+BodySlam',
            'Totodile+Thrash+WaterSport+Double-Edge',
            'Totodile+Thrash+WaterSport+Counter',
            'Totodile+Thrash+WaterSport+SeismicToss',
            'Totodile+Thrash+WaterSport+Mimic',
            'Totodile+Thrash+WaterSport+DynamicPunch',
            'Totodile+Crunch+MudSport+WaterSport+MegaPunch',
            'Totodile+Crunch+MudSport+WaterSport+MegaKick',
            'Totodile+Crunch+MudSport+WaterSport+BodySlam',
            'Totodile+Crunch+MudSport+WaterSport+Double-Edge',
            'Totodile+Crunch+MudSport+WaterSport+Counter',
            'Totodile+Crunch+MudSport+WaterSport+SeismicToss',
            'Totodile+Crunch+MudSport+WaterSport+Mimic',
            'Totodile+Crunch+MudSport+WaterSport+DynamicPunch',
            'Trapinch+Feint+BodySlam',
            'Trapinch+Feint+Double-Edge',
            'Trapinch+Feint+Mimic',
            'Trapinch+Fissure+BodySlam',
            'Trapinch+Fissure+Double-Edge',
            'Trapinch+Fissure+Mimic',
            'Venonat+PoisonFang+Double-Edge',
            'Venonat+PoisonFang+Mimic',
            'Voltorb+Refresh',
            'Voltorb+SonicBoom',
            'Voltorb+Spark',
            'Voltorb+Rollout',
            'Voltorb+Screech',
            'Voltorb+MirrorCoat',
            'Vulpix+Charm',
            'Vulpix+Extrasensory+BodySlam',
            'Vulpix+Extrasensory+Double-Edge',
            'Vulpix+Extrasensory+Mimic',
            'Whismur+TeeterDance+Astonish',
            'Whismur+TeeterDance+Howl',
            'Whismur+TeeterDance+Supersonic',
            'Whismur+TeeterDance+Stomp',
            'Whismur+TeeterDance+Screech',
            'Whismur+TeeterDance+HyperVoice',
            'Wingull+AirSlash+Double-Edge',
            'Wingull+AirSlash+Mimic',
            'Wingull+AirSlash+SkyAttack',
            'Wooper+MudBomb+Double-Edge',
            'Wooper+MudBomb+Mimic',
            'Wooper+MudBomb+DefenseCurl',
            'Wooper+MudBomb+DynamicPunch',
            'Wooper+MuddyWater+Double-Edge',
            'Wooper+MuddyWater+Mimic',
            'Wooper+MuddyWater+DefenseCurl',
            'Wooper+MuddyWater+DynamicPunch',
            'Wynaut+Tickle+Counter',
            'Wynaut+Tickle+MirrorCoat',
            'Wynaut+Tickle+Safeguard',
            'Wynaut+Tickle+DestinyBond',
            'Yanma+Pursuit+Double-Edge',
            'Yanma+Pursuit+Mimic',
            'Yanma+AirSlash+Double-Edge',
            'Yanma+AirSlash+Mimic',
            'Yanma+BugBuzz+Double-Edge',
            'Yanma+BugBuzz+Mimic',
            'Zigzagoon+ExtremeSpeed+Headbutt',
            'Zigzagoon+ExtremeSpeed+Sand-Attack',
            'Zigzagoon+ExtremeSpeed+OdorSleuth',
            'Zigzagoon+ExtremeSpeed+MudSport',
            'Zigzagoon+ExtremeSpeed+PinMissile',
            'Zigzagoon+ExtremeSpeed+Covet',
            'Zigzagoon+ExtremeSpeed+Flail',
            'Zigzagoon+ExtremeSpeed+BellyDrum',
            'Zubat+AirSlash+Double-Edge',
            'Zubat+AirSlash+Mimic'
        ],
        validateSet: function(set) {
            var pokemon = this.getTemplate(set.species);
            var problems = [];

            if (pokemon.prevo !== "")
                problems.push(set.species + " is not the lowest evolution.");
            if (pokemon.nexto.length === 0)
                problems.push(set.species + " is unable to evolve.");

            if (set.level !== 5)
                problems.push(set.species + " is not level 5.");

            return problems;
        }
    },
    LCBans: {
        effectType: 'Banlist',
        banlist: [
            'Carvanha',
            'Meditite',
            'Scyther',
            'Sneasel',
            'Tangela',
            'Vulpix',
            'Yanma'
        ]
    }
};
