'use strict';

/**@type {{[k: string]: {learnset: {[k: string]: MoveSource[]}}}} */
let BattleLearnsets = {
	//Fresh
	botamon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	dodomon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	kuramon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	poyomon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	punimon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	yuramon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	//In Training
	bukamon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	dorimon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	koromon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	motimon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	nyaromon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	tanemon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	tokomon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	tsumemon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	tsunomon: {
		learnset: {
			acidbubble: ["7M"],
			protect: ["7M"],
		},
	},
	//Rookie
	agumon: {
		learnset: {
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			windcutter: ["7M"],
			pepperbreath: ["7M"],
			protect: ["7M"],
		},
	},
	aruraumon: {
		learnset: {
			charmperfume: ["7M"],
			rootbind: ["7M"],
			venomdisaster: ["7M"],
			waterblitz: ["7M"],
			superstinkyjet: ["7M"],
			shadowfall: ["7M"],
			blackout: ["7M"],
			nemesisivy: ["7M"],
			protect: ["7M"],
		},
	},
	betamon: {
		learnset: {
			staticelectricity: ["7M"],
			electriccloud: ["7M"],
			megalospark: ["7M"],
			hailspear: ["7M"],
			waterblitz: ["7M"],
			oceanwave: ["7M"],
			electricshock: ["7M"],
			protect: ["7M"],
		},
	},
	biyomon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			meltdown: ["7M"],
			warcry: ["7M"],
			holyflash: ["7M"],
			rootbind: ["7M"],
			spiraltwister: ["7M"],
			protect: ["7M"],
		},
	},
	clearagumon: {
		learnset: {
			heatbreath: ["7M"],
			saintshield: ["7M"],
			saintray: ["7M"],
			holyflash: ["7M"],
			mechanicalclaw: ["7M"],
			upgrade: ["7M"],
			gigawattlaser: ["7M"],
			preciousflame: ["7M"],
			protect: ["7M"],
		},
	},
	demidevimon: {
		learnset: {
			blackout: ["7M"],
			evilfantasy: ["7M"],
			shadowfall: ["7M"],
			hideandseek: ["7M"],
			windcutter: ["7M"],
			confusedstorm: ["7M"],
			cootieskick: ["7M"],
			demidart: ["7M"],
			protect: ["7M"],
		},
	},
	dokunemon: {
		learnset: {
			staticelectricity: ["7M"],
			shadowfall: ["7M"],
			earthcoat: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			venomdisaster: ["7M"],
			blackout: ["7M"],
			wormvenom: ["7M"],
			protect: ["7M"],
		},
	},
	dorumon: {
		learnset: {
			burningheart: ["7M"],
			megalospark: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			metalcannon: ["7M"],
			protect: ["7M"],
		},
	},
	elecmon: {
		learnset: {
			staticelectricity: ["7M"],
			electriccloud: ["7M"],
			thunderjustice: ["7M"],
			saintheal: ["7M"],
			warcry: ["7M"],
			fightingaura: ["7M"],
			superthunderstrike: ["7M"],
			protect: ["7M"],
		},
	},
	gabumon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			hailspear: ["7M"],
			gigafreeze: ["7M"],
			icestatue: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			blueblaster: ["7M"],
			protect: ["7M"],
		},
	},
	goburimon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			musclecharge: ["7M"],
			burninheart: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			shadowfall: ["7M"],
			pooptoss: ["7M"],
			goblinstrike: ["7M"],
			protect: ["7M"],
		},
	},
	gomamon: {
		learnset: {
			mechanicalclaw: ["7M"],
			waterblitz: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			aurorafreeze: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			marchingfishes: ["7M"],
			protect: ["7M"],
		},
	},
	gotsumon: {
		learnset: {
			earthcoat: ["7M"],
			rockfall: ["7M"],
			charmperfume: ["7M"],
			venomdisaster: ["7M"],
			bug: ["7M"],
			megatonpunch: ["7M"],
			fightingaura: ["7M"],
			rockfist: ["7M"],
			protect: ["7M"],
		},
	},
	kunemon: {
		learnset: {
			staticelectricity: ["7M"],
			megalospark: ["7M"],
			earthcoat: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			venomdisaster: ["7M"],
			superstinkyjet: ["7M"],
			electricthread: ["7M"],
			protect: ["7M"],
		},
	},
	modokibetamon: {
		learnset: {
			staticelectricity: ["7M"],
			electriccloud: ["7M"],
			confusedstorm: ["7M"],
			hailspear: ["7M"],
			icestatue: ["7M"],
			rootbind: ["7M"],
			waterblitz: ["7M"],
			aquatower: ["7M"],
			protect: ["7M"],
		},
	},
	muchomon: {
		learnset: {
			burningheart: ["7M"],
			hailspear: ["7M"],
			waterblitz: ["7M"],
			windcutter: ["7M"],
			infinityburn: ["7M"],
			firewall: ["7M"],
			tropicalbeak: ["7M"],
			protect: ["7M"],
		},
	},
	otamamon: {
		learnset: {
			hailspear: ["7M"],
			waterblitz: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			bug: ["7M"],
			charmperfume: ["7M"],
			warcry: ["7M"],
			lullabybubble: ["7M"],
			protect: ["7M"],
		},
	},
	palmon: {
		learnset: {
			charmperfume: ["7M"],
			rootbind: ["7M"],
			venomdisaster: ["7M"],
			waterblitz: ["7M"],
			superstinkyjet: ["7M"],
			burningheart: ["7M"],
			confusedstorm: ["7M"],
			poisonivy: ["7M"],
			protect: ["7M"],
		},
	},
	patamon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			sonicjab: ["7M"],
			busterdrive: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			holyflash: ["7M"],
			boombubble: ["7M"],
			protect: ["7M"],
		},
	},
	penguinmon: {
		learnset: {
			musclecharge: ["7M"],
			hailspear: ["7M"],
			waterblitz: ["7M"],
			icestatue: ["7M"],
			megalospark: ["7M"],
			earthcoat: ["7M"],
			eternalslapping: ["7M"],
			protect: ["7M"],
		},
	},
	psychemon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			staticelectricity: ["7M"],
			winterblast: ["7M"],
			confusedstorm: ["7M"],
			icestatue: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			coloredsparkle: ["7M"],
			protect: ["7M"],
		},
	},
	salamon: {
		learnset: {
			saintheal: ["7M"],
			holybreath: ["7M"],
			holyflash: ["7M"],
			saintray: ["7M"],
			warcry: ["7M"],
			antiattackfield: ["7M"],
			fightingaura: ["7M"],
			puppyhowl: ["7M"],
			protect: ["7M"],
		},
	},
	shamanmon: {
		learnset: {
			charmperfume: ["7M"],
			rootbind: ["7M"],
			rockfall: ["7M"],
			musclecharge: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			shadowfall: ["7M"],
			pooptoss: ["7M"],
			dancingbone: ["7M"],
			protect: ["7M"],
		},
	},
	snowagumon: {
		learnset: {
			burningheart: ["7M"],
			hailspear: ["7M"],
			winterblast: ["7M"],
			icestatue: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			windcutter: ["7M"],
			littleblizzard: ["7M"],
			protect: ["7M"],
		},
	},
	snowgoburimon: {
		learnset: {
			hailspear: ["7M"],
			winterblast: ["7M"],
			icestatue: ["7M"],
			musclecharge: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			shadowfall: ["7M"],
			pooptoss: ["7M"],
			snowgobbolt: ["7M"],
			protect: ["7M"],
		},
	},
	tentomon: {
		learnset: {
			staticelectricity: ["7M"],
			confusedstorm: ["7M"],
			electriccloud: ["7M"],
			megalospark: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			rockfall: ["7M"],
			fightingaura: ["7M"],
			supershocker: ["7M"],
			protect: ["7M"],
		},
	},
	toyagumon: {
		learnset: {
			heatbreath: ["7M"],
			firewall: ["7M"],
			prominencebeam: ["7M"],
			sonicjab: ["7M"],
			mechanicalclaw: ["7M"],
			upgrade: ["7M"],
			giganticlaser: ["7M"],
			plasticblaze: ["7M"],
			protect: ["7M"],
		},
	},
	tsukaimon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			sonicjab: ["7M"],
			darkspirit: ["7M"],
			blackout: ["7M"],
			evilfantasy: ["7M"],
			chaoscloud: ["7M"],
			evilspell: ["7M"],
			protect: ["7M"],
		},
	},
	//Champion
	airdramon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			meltdown: ["7M"],
			infinityburn: ["7M"],
			wingshoes: ["7M"],
			windcutter: ["7M"],
			confusedstorm: ["7M"],
			holybreath: ["7M"],
			spinningneedle: ["7M"],
			protect: ["7M"],
		},
	},
	akatorimon: {
		learnset: {
			heatbreath: ["7M"],
			firewall: ["7M"],
			wingshoes: ["7M"],
			windcutter: ["7M"],
			megalospark: ["7M"],
			icestatue: ["7M"],
			guerrillapoop: ["7M"],
			scarredeye: ["7M"],
			protect: ["7M"],
		},
	},
	angemon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			sonicjab: ["7M"],
			busterdrive: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			holyflash: ["7M"],
			saintray: ["7M"],
			holyjudgment: ["7M"],
			handoffate: ["7M"],
			protect: ["7M"],
		},
	},
	bakemon: {
		learnset: {
			darkspirit: ["7M"],
			blckout: ["7M"],
			evilfantasy: ["7M"],
			shadowfall: ["7M"],
			massmorph: ["7M"],
			icestatue: ["7M"],
			staticelectricity: ["7M"],
			electriccloud: ["7M"],
			thunderjustice: ["7M"],
			evilcharm: ["7M"],
			protect: ["7M"],
		},
	},
	birdramon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			meltdown: ["7M"],
			infinityburn: ["7M"],
			warcry: ["7M"],
			holyflash: ["7M"],
			meteorwing: ["7M"],
			protect: ["7M"],
		},
	},
	blackgatomon: {
		learnset: {
			warcry: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			evilsquall: ["7M"],
			evilfantasy: ["7M"],
			hideandseek: ["7M"],
			gigafreeze: ["7M"],
			darkpaw: ["7M"],
			protect: ["7M"],
		},
	},
	centarumon: {
		learnset: {
			firetower: ["7M"],
			firewall: ["7M"],
			prominencebeam: ["7M"],
			saintheal: ["7M"],
			saintray: ["7M"],
			fightingaura: ["7M"],
			upgrade: ["7M"],
			gigawattlaser: ["7M"],
			solarray: ["7M"],
			protect: ["7M"],
		},
	},
	coelamon: {
		learnset: {
			waterblitz: ["7M"],
			icestatue: ["7M"],
			mechcanicalclaw: ["7M"],
			upgrade: ["7M"],
			antiattackfield: ["7M"],
			massmorph: ["7M"],
			staticelectricity: ["7M"],
			deleteprogram: ["7M"],
			variabledarts: ["7M"],
			protect: ["7M"],
		},
	},
	darkrizamon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			firewall: ["7M"],
			meltdown: ["7M"],
			darkspirit: ["7M"],
			evilfantasy: ["7M"],
			shadowfall: ["7M"],
			mechanicalclaw: ["7M"],
			dreadfire: ["7M"],
			protect: ["7M"],
		},
	},
	devimon: {
		learnset: {
			darkspirit: ["7M"],
			windcutter: ["7M"],
			evilfantasy: ["7M"],
			chaoscloud: ["7M"],
			aurorafreeze: ["7M"],
			evilsquall: ["7M"],
			confusedstorm: ["7M"],
			wingshoes: ["7M"],
			deathhand: ["7M"],
			protect: ["7M"],

		},
	},
	dolphmon: {
		learnset: {
			waterblitz: ["7M"],
			gigafreeze: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			warcry: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			holybreath: ["7M"],
			saintheal: ["7M"],
			pulseblast: ["7M"],
			protect: ["7M"],

		},
	},
	dorugamon: {
		learnset: {
			burningheart: ["7M"],
			winterblast: ["7M"],
			megalospark: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			powermetal: ["7M"],
			protect: ["7M"],
		},
	},
	drimogemon: {
		learnset: {
			mechanicalclaw: ["7M"],
			deleteprogram: ["7M"],
			earthcoat: ["7M"],
			massmorph: ["7M"],
			rootbind: ["7M"],
			rockfall: ["7M"],
			drillspin: ["7M"],
			protect: ["7M"],
		},
	},
	flarerizamon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			firewall: ["7M"],
			meltdown: ["7M"],
			sonicjab: ["7M"],
			warcry: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			blazebuster: ["7M"],
			protect: ["7M"],
		},
	},
	frigimon: {
		learnset: {
			hailspear: ["7M"],
			icestatue: ["7M"],
			aurorafreeze: ["7M"],
			waterblitz: ["7M"],
			sonicjab: ["7M"],
			musclecharge: ["7M"],
			fightingaura: ["7M"],
			subzeroicepunch: ["7M"],
			protect: ["7M"],
		},
	},
	fugamon: {
		learnset: {
			staticelectricity: ["7M"],
			windcutter: ["7M"],
			megalospark: ["7M"],
			blackout: ["7M"],
			musclecharge: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			evilhurricane: ["7M"],
			protect: ["7M"],
		},
	},
	garurumon: {
		learnset: {
			warcry: ["7M"],
			waterblitz: ["7M"],
			fightingaura: ["7M"],
			burningheart: ["7M"],
			heatbreath: ["7M"],
			gigafreeze: ["7M"],
			hailspear: ["7M"],
			meltdown: ["7M"],
			aurorafreeze: ["7M"],
			howlingblaster: ["7M"],
			protect: ["7M"],
		},
	},
	gatomon: {
		learnset: {
			holybreath: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			saintray: ["7M"],
			saintheal: ["7M"],
			holyflash: ["7M"],
			confusedstorm: ["7M"],
			lightningpaw: ["7M"],
			protect: ["7M"],
		},
	},
	gekomon: {
		learnset: {
			hailspear: ["7M"],
			confusedstorm: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			gigafreeze: ["7M"],
			warcry: ["7M"],
			charmperfume: ["7M"],
			symphonycrusher: ["7M"],
			protect: ["7M"],
		},
	},
	geremon: {
		learnset: {
			gigafreeze: ["7M"],
			earthcoat: ["7M"],
			bug: ["7M"],
			venomdisaster: ["7M"],
			warcry: ["7M"],
			superstinkyjet: ["7M"],
			poopattackfield: ["7M"],
			guerrillapoop: ["7M"],
			extremepoopdeath: ["7M"],
			hypersmell: ["7M"],
			protect: ["7M"],
		},
	},
	greymon: {
		learnset: {
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			megalospark: ["7M"],
			megaflame: ["7M"],
			protect: ["7M"],
		},
	},
	guardromon: {
		learnset: {
			upgrade: ["7M"],
			reverseprogram: ["7M"],
			antiattackfield: ["7M"],
			gigawattlaser: ["7M"],
			megalospark: ["7M"],
			saintshield: ["7M"],
			firetower: ["7M"],
			firewall: ["7M"],
			thunderjustice: ["7M"],
			guardianbarrage: ["7M"],
			protect: ["7M"],
		},
	},
	gururumon: {
		learnset: {
			warcry: ["7M"],
			waterblitz: ["7M"],
			fightingaura: ["7M"],
			burningheart: ["7M"],
			blackout: ["7M"],
			gigafreeze: ["7M"],
			darkspirit: ["7M"],
			evilfantasy: ["7M"],
			aurorafreeze: ["7M"],
			chaosblaster: ["7M"],
			protect: ["7M"],
		},
	},
	hyogamon: {
		learnset: {
			hailspear: ["7M"],
			winterblast: ["7M"],
			icestatue: ["7M"],
			blackout: ["7M"],
			musclecharge: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			snowpunch: ["7M"],
			protect: ["7M"],
		},
	},
	icedevimon: {
		learnset: {
			waterblitz: ["7M"],
			blackout: ["7M"],
			evilfantasy: ["7M"],
			icestatue: ["7M"],
			shadowfall: ["7M"],
			evilsquall: ["7M"],
			winterblast: ["7M"],
			gigafreeze: ["7M"],
			frozenclaw: ["7M"],
			protect: ["7M"],
		},
	},
	icemon: {
		learnset: {
			earthcoat: ["7M"],
			rockfall: ["7M"],
			hailspear: ["7M"],
			aurorafreeze: ["7M"],
			gigafreeze: ["7M"],
			megatonpunch: ["7M"],
			fightingaura: ["7M"],
			iceballbomb: ["7M"],
			protect: ["7M"],
		},
	},
	ikkakumon: {
		learnset: {
			hailspear: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			aurorafreeze: ["7M"],
			mechanicalclaw: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			harpoontorpedo: ["7M"],
			protect: ["7M"],
		},
	},
	junglemojyamon: {
		learnset: {
			earthcoat: ["7M"],
			rootbind: ["7M"],
			warcry: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			superstinkyjet: ["7M"],
			poopfling: ["7M"],
			junglebone: ["7M"],
			protect: ["7M"],
		},
	},
	kabuterimon: {
		learnset: {
			confusedstorm: ["7M"],
			electriccloud: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			rockfall: ["7M"],
			fightingaura: ["7M"],
			electroshocker: ["7M"],
			protect: ["7M"],
		},
	},
	kokatorimon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			megalospark: ["7M"],
			icestatue: ["7M"],
			cootieskick: ["7M"],
			pooptoss: ["7M"],
			guerrillapoop: ["7M"],
			frozenfireshot: ["7M"],
			protect: ["7M"],
		},
	},
	kuwagamon: {
		learnset: {
			sonicjab: ["7M"],
			busterdrive: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			venomdisaster: ["7M"],
			windcutter: ["7M"],
			blackout: ["7M"],
			scissorclaw: ["7M"],
			protect: ["7M"],
		},
	},
	leomon: {
		learnset: {
			musclecharge: ["7M"],
			warcry: ["7M"],
			sonicjab: ["7M"],
			meltdown: ["7M"],
			infinityburn: ["7M"],
			megatonpunch: ["7M"],
			earthcoat: ["7M"],
			saintshield: ["7M"],
			burningheart: ["7M"],
			fistofthebeastking: ["7M"],
			protect: ["7M"],
		},
	},
	meicoomon: {
		learnset: {
			warcry: ["7M"],
			windcutter: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			venomdisaster: ["7M"],
			shadowfall: ["7M"],
			saintray: ["7M"],
			xscratch: ["7M"],
			protect: ["7M"],
		},
	},
	meramon: {
		learnset: {
			burningheart: ["7M"],
			firewall: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			holyflash: ["7M"],
			fightingaura: ["7M"],
			sonicjab: ["7M"],
			megatonpunch: ["7M"],
			burningfist: ["7M"],
			protect: ["7M"],
		},
	},
	mikemon: {
		learnset: {
			warcry: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			venomdisaster: ["7M"],
			evilfantasy: ["7M"],
			holyflash: ["7M"],
			bug: ["7M"],
			catclaw: ["7M"],
			protect: ["7M"],
		},
	},
	mojyamon: {
		learnset: {
			warcry: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			hailspear: ["7M"],
			winterblast: ["7M"],
			superstinkyjet: ["7M"],
			poopfling: ["7M"],
			boneboomerang: ["7M"],
			protect: ["7M"],
		},
	},
	monochromon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			earthcoat: ["7M"],
			rockfall: ["7M"],
			musclecharge: ["7M"],
			busterdrive: ["7M"],
			volcanicstrike: ["7M"],
			protect: ["7M"],
		},
	},
	morishellmon: {
		learnset: {
			waterblitz: ["7M"],
			oceanwave: ["7M"],
			earthcoat: ["7M"],
			charmperfume: ["7M"],
			rootbind: ["7M"],
			venomdisaster: ["7M"],
			sonicjab: ["7M"],
			mindfog: ["7M"],
			protect: ["7M"],
		},
	},
	mudfrigimon: {
		learnset: {
			rootbind: ["7M"],
			bug: ["7M"],
			rockfall: ["7M"],
			massmorph: ["7M"],
			sonicjab: ["7M"],
			earthcoat: ["7M"],
			fightingaura: ["7M"],
			mudball: ["7M"],
			protect: ["7M"],
		},
	},
	nanimon: {
		learnset: {
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			pooptoss: ["7M"],
			poopattackfield: ["7M"],
			superstinkyjet: ["7M"],
			evilfantasy: ["7M"],
			blackout: ["7M"],
			poopdunk: ["7M"],
			protect: ["7M"],
		},
	},
	ninjamon: {
		learnset: {
			warcry: ["7M"],
			sonicjab: ["7M"],
			musclecharge: ["7M"],
			charmperfume: ["7M"],
			rootbind: ["7M"],
			earthcoat: ["7M"],
			reboundstrike: ["7M"],
			dancingleaves: ["7M"],
			protect: ["7M"],
		},
	},
	nisedrimogemon: {
		learnset: {
			warcry: ["7M"],
			sonicjab: ["7M"],
			busterdrive: ["7M"],
			reboundstrike: ["7M"],
			mechanicalclaw: ["7M"],
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			reverseprogram: ["7M"],
			fakedrillspin: ["7M"],
			protect: ["7M"],
		},
	},
	numemon: {
		learnset: {
			oceanwave: ["7M"],
			earthcoat: ["7M"],
			bug: ["7M"],
			icestatue: ["7M"],
			warcry: ["7M"],
			cootieskick: ["7M"],
			pooptoss: ["7M"],
			guerrillapoop: ["7M"],
			extremepoopdeath: ["7M"],
			numesludge: ["7M"],
			protect: ["7M"],
		},
	},
	ogremon: {
		learnset: {
			firetower: ["7M"],
			infinityburn: ["7M"],
			heatbreath: ["7M"],
			blackout: ["7M"],
			musclecharge: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			pummelwhack: ["7M"],
			protect: ["7M"],
		},
	},
	piddomon: {
		learnset: {
			burningheart: ["7M"],
			firewall: ["7M"],
			infinityburn: ["7M"],
			holybreath: ["7M"],
			windcutter: ["7M"],
			sonicjab: ["7M"],
			saintheal: ["7M"],
			saintray: ["7M"],
			holyjudgment: ["7M"],
			firefeather: ["7M"],
			protect: ["7M"],
		},
	},
	platinumsukamon: {
		learnset: {
			earthcoat: ["7M"],
			rockfall: ["7M"],
			holyflash: ["7M"],
			mechanicalclaw: ["7M"],
			reverseprogram: ["7M"],
			deleteprogram: ["7M"],
			cootieskick: ["7M"],
			superstinkyjet: ["7M"],
			guerrillapoop: ["7M"],
			extremepoopdeath: ["7M"],
			raremetalpoop: ["7M"],
			protect: ["7M"],
		},
	},
	redvegiemon: {
		learnset: {
			heatbreath: ["7M"],
			meltdown: ["7M"],
			prominencebeam: ["7M"],
			massmorph: ["7M"],
			charmperfume: ["7M"],
			venomdisaster: ["7M"],
			earthcoat: ["7M"],
			chilipepperpummel: ["7M"],
			protect: ["7M"],
		},
	},
	rockmon: {
		learnset: {
			mechanicalclaw: ["7M"],
			winterblast: ["7M"],
			gigafreeze: ["7M"],
			gigawattlaser: ["7M"],
			dgdimension: ["7M"],
			upgrade: ["7M"],
			sonicjab: ["7M"],
			antidigibeam: ["7M"],
			protect: ["7M"],
		},
	},
	saberdramon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			burningheart: ["7M"],
			blackout: ["7M"],
			firetower: ["7M"],
			shadowfall: ["7M"],
			infinityburn: ["7M"],
			evilfantasy: ["7M"],
			nightroar: ["7M"],
			protect: ["7M"],
		},
	},
	sandyanmamon: {
		learnset: {
			electriccloud: ["7M"],
			windcutter: ["7M"],
			confusedstorm: ["7M"],
			thunderjustice: ["7M"],
			earthcoat: ["7M"],
			massmorph: ["7M"],
			charmperfume: ["7M"],
			bug: ["7M"],
			holyflash: ["7M"],
			stunray: ["7M"],
			protect: ["7M"],
		},
	},
	seadramon: {
		learnset: {
			hailspear: ["7M"],
			waterblitz: ["7M"],
			gigafreeze: ["7M"],
			aurorafreeze: ["7M"],
			heatbreath: ["7M"],
			meltdown: ["7M"],
			holybreath: ["7M"],
			iceblast: ["7M"],
			protect: ["7M"],
		},
	},
	shellmon: {
		learnset: {
			waterblitz: ["7M"],
			winterblast: ["7M"],
			oceanwave: ["7M"],
			aurorafreeze: ["7M"],
			massmorph: ["7M"],
			rockfall: ["7M"],
			sonicjab: ["7M"],
			hydropressure: ["7M"],
			protect: ["7M"],
		},
	},
	shimaunimon: {
		learnset: {
			holybreath: ["7M"],
			electriccloud: ["7M"],
			confusedstorm: ["7M"],
			saintheal: ["7M"],
			holyflash: ["7M"],
			saintray: ["7M"],
			warcry: ["7M"],
			fightingaura: ["7M"],
			aurorafreeze: ["7M"],
			sonicjab: ["7M"],
			busterdrive: ["7M"],
			lustershot: ["7M"],
			protect: ["7M"],
		},
	},
	soulmon: {
		learnset: {
			darkspirit: ["7M"],
			blackout: ["7M"],
			evilfantasy: ["7M"],
			shadowfall: ["7M"],
			massmorph: ["7M"],
			staticelectricity: ["7M"],
			electriccloud: ["7M"],
			aurorafreeze: ["7M"],
			necromagic: ["7M"],
			protect: ["7M"],
		},
	},
	sukamon: {
		learnset: {
			earthcoat: ["7M"],
			bug: ["7M"],
			rockfall: ["7M"],
			warcry: ["7M"],
			cootieskick: ["7M"],
			superstinkyjet: ["7M"],
			guerrillapoop: ["7M"],
			extremepoopdeath: ["7M"],
			hideandseek: ["7M"],
			poop: ["7M"],
			protect: ["7M"],
		},
	},
	tankmon: {
		learnset: {
			burningheart: ["7M"],
			heatbreath: ["7M"],
			infinityburn: ["7M"],
			prominencebeam: ["7M"],
			earthcoat: ["7M"],
			antiattackfield: ["7M"],
			gigawattlaser: ["7M"],
			deleteprogram: ["7M"],
			upgrade: ["7M"],
			hypercannon: ["7M"],
			protect: ["7M"],
		},
	},
	togemon: {
		learnset: {
			massmorph: ["7M"],
			charmperfume: ["7M"],
			rootbind: ["7M"],
			venomdisaster: ["7M"],
			waterblitz: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			needlespray: ["7M"],
			protect: ["7M"],
		},
	},
	tyrannomon: {
		learnset: {
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			prominencebeam: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			reboundstrike: ["7M"],
			rockfall: ["7M"],
			blazeblaster: ["7M"],
			protect: ["7M"],
		},
	},
	unimon: {
		learnset: {
			wingshoes: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			confusedstorm: ["7M"],
			rockfall: ["7M"],
			saintheal: ["7M"],
			holyjudgment: ["7M"],
			saintray: ["7M"],
			musclecharge: ["7M"],
			aerialattack: ["7M"],
			protect: ["7M"],
		},
	},
	vegiemon: {
		learnset: {
			waterblitz: ["7M"],
			gigafreeze: ["7M"],
			oceanwave: ["7M"],
			massmorph: ["7M"],
			charmperfume: ["7M"],
			venomdisaster: ["7M"],
			earthcoat: ["7M"],
			sweetbreath: ["7M"],
			protect: ["7M"],
		},
	},
	weedmon: {
		learnset: {
			superstinkyjet: ["7M"],
			poopattackfield: ["7M"],
			extremepoopdeath: ["7M"],
			massmorph: ["7M"],
			charmperfume: ["7M"],
			venomdisaster: ["7M"],
			earthcoat: ["7M"],
			deadlyweed: ["7M"],
			protect: ["7M"],
		},
	},
	yanmamon: {
		learnset: {
			electriccloud: ["7M"],
			windcutter: ["7M"],
			confusedstorm: ["7M"],
			thunderjustice: ["7M"],
			earthcoat: ["7M"],
			massmorph: ["7M"],
			charmperfume: ["7M"],
			bug: ["7M"],
			holyflash: ["7M"],
			thunderray: ["7M"],
			protect: ["7M"],
		},
	},
	//Ultimate
	andromon: {
		learnset: {
			windcutter: ["7M"],
			electriccloud: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			upgrade: ["7M"],
			antiattackfield: ["7M"],
			deleteprogram: ["7M"],
			gigawattlaser: ["7M"],
			bug: ["7M"],
			spiralsword: ["7M"],
			protect: ["7M"],
		},
	},
	angewomon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			thunderjustice: ["7M"],
			fightingaura: ["7M"],
			electriccloud: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			holyflash: ["7M"],
			saintray: ["7M"],
			warcry: ["7M"],
			celestialarrow: ["7M"],
			protect: ["7M"],
		},
	},
	beastmon: {
		learnset: {
			warcry: ["7M"],
			sonicjab: ["7M"],
			megatonpunch: ["7M"],
			venomdisaster: ["7M"],
			shadowfall: ["7M"],
			gigafreeze: ["7M"],
			bug: ["7M"],
			icestatue: ["7M"],
			vampirewave: ["7M"],
			protect: ["7M"],
		},
	},
	blackweregarurumon: {
		learnset: {
			warcry: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			megatonpunch: ["7M"],
			rockfall: ["7M"],
			burningheart: ["7M"],
			heatbreath: ["7M"],
			evilsquall: ["7M"],
			hideandseek: ["7M"],
			winterblast: ["7M"],
			gigafreeze: ["7M"],
			fullmoonkick: ["7M"],
			protect: ["7M"],
		},
	},
	bluemeramon: {
		learnset: {
			burningheart: ["7M"],
			firewall: ["7M"],
			meltdown: ["7M"],
			infinityburn: ["7M"],
			aurorafreeze: ["7M"],
			holyflash: ["7M"],
			fightingaura: ["7M"],
			gigafreeze: ["7M"],
			coldflame: ["7M"],
			protect: ["7M"],
		},
	},
	digitamamon: {
		learnset: {
			hailspear: ["7M"],
			blackout: ["7M"],
			bug: ["7M"],
			shadowfall: ["7M"],
			firetower: ["7M"],
			poopattackfield: ["7M"],
			poopfling: ["7M"],
			upgrade: ["7M"],
			nightmaresyndrome: ["7M"],
			protect: ["7M"],
		},
	},
	dorugreymon: {
		learnset: {
			burningheart: ["7M"],
			infinityburn: ["7M"],
			megalospark: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			metalmeteor: ["7M"],
			protect: ["7M"],
		},
	},
	etemon: {
		learnset: {
			earthcoat: ["7M"],
			rockfall: ["7M"],
			sonicjab: ["7M"],
			megatonpunch: ["7M"],
			charmperfume: ["7M"],
			bug: ["7M"],
			guerrillapoop: ["7M"],
			extremepoopdeath: ["7M"],
			loveserenade: ["7M"],
			protect: ["7M"],
		},
	},
	garudamon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			burningheart: ["7M"],
			firetower: ["7M"],
			meltdown: ["7M"],
			infinityburn: ["7M"],
			warcry: ["7M"],
			busterdrive: ["7M"],
			holyflash: ["7M"],
			shadowwing: ["7M"],
			protect: ["7M"],
		},
	},
	gigadramon: {
		learnset: {
			upgrade: ["7M"],
			gigawattlaser: ["7M"],
			dgdimension: ["7M"],
			darkspirit: ["7M"],
			hideandseek: ["7M"],
			windcutter: ["7M"],
			electriccloud: ["7M"],
			gigafreeze: ["7M"],
			energyshot: ["7M"],
			protect: ["7M"],
		},
	},
	giromon: {
		learnset: {
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			reverseprogram: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			staticelectricity: ["7M"],
			megalospark: ["7M"],
			firewall: ["7M"],
			deadlybomb: ["7M"],
			protect: ["7M"],
		},
	},
	iceleomon: {
		learnset: {
			musclecharge: ["7M"],
			warcry: ["7M"],
			gigafreeze: ["7M"],
			icestatue: ["7M"],
			megatonpunch: ["7M"],
			winterblast: ["7M"],
			aurorafreeze: ["7M"],
			saintshield: ["7M"],
			burningheart: ["7M"],
			fistofice: ["7M"],
			protect: ["7M"],
		},
	},
	ladydevimon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			evilsquall: ["7M"],
			fightingaura: ["7M"],
			electriccloud: ["7M"],
			evilfantasy: ["7M"],
			charmperfume: ["7M"],
			darkspirit: ["7M"],
			chaoscloud: ["7M"],
			warcry: ["7M"],
			darknesswave: ["7M"],
			protect: ["7M"],
		},
	},
	lillymon: {
		learnset: {
			earthcoat: ["7M"],
			charmperfume: ["7M"],
			rootbind: ["7M"],
			venomdisaster: ["7M"],
			wingshoes: ["7M"],
			windcutter: ["7M"],
			confusedstorm: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			flowercannon: ["7M"],
			protect: ["7M"],
		},
	},
	magnaangemon: {
		learnset: {
			saintheal: ["7M"],
			saintshield: ["7M"],
			shiningnova: ["7M"],
			thunderjustice: ["7M"],
			antiattackfield: ["7M"],
			gigawattlaser: ["7M"],
			deleteprogram: ["7M"],
			sonicjab: ["7M"],
			megalospark: ["7M"],
			reboundstrike: ["7M"],
			holyjudgment: ["7M"],
			wingshoes: ["7M"],
			gateofdestiny: ["7M"],
			protect: ["7M"],
		},
	},
	mamemon: {
		learnset: {
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			fightingaura: ["7M"],
			reboundstrike: ["7M"],
			antiattackfield: ["7M"],
			upgrade: ["7M"],
			reverseprogram: ["7M"],
			gigawattlaser: ["7M"],
			gigafreeze: ["7M"],
			burningheart: ["7M"],
			smilebomber: ["7M"],
			protect: ["7M"],
		},
	},
	megadramon: {
		learnset: {
			mechanicalclaw: ["7M"],
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			blackout: ["7M"],
			shadowfall: ["7M"],
			staticelectricity: ["7M"],
			megalospark: ["7M"],
			firetower: ["7M"],
			genocideattack: ["7M"],
			protect: ["7M"],
		},
	},
	megakabuterimon: {
		learnset: {
			staticelectricity: ["7M"],
			rockfall: ["7M"],
			megatonpunch: ["7M"],
			megalospark: ["7M"],
			reboundstrike: ["7M"],
			earthcoat: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			hornbuster: ["7M"],
			protect: ["7M"],
		},
	},
	megaseadramon: {
		learnset: {
			hailspear: ["7M"],
			waterblitz: ["7M"],
			gigafreeze: ["7M"],
			aurorafreeze: ["7M"],
			heatbreath: ["7M"],
			meltdown: ["7M"],
			shiningnova: ["7M"],
			staticelectricity: ["7M"],
			megalospark: ["7M"],
			lightningjavelin: ["7M"],
			protect: ["7M"],
		},
	},
	meicrackmon: {
		learnset: {
			warcry: ["7M"],
			windcutter: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			venomdisaster: ["7M"],
			holyjudgment: ["7M"],
			saintray: ["7M"],
			holybreath: ["7M"],
			modestlystun: ["7M"],
			protect: ["7M"],
		},
	},
	meicrackmonviciousmode: {
		learnset: {
			warcry: ["7M"],
			windcutter: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			venomdisaster: ["7M"],
			shadowfall: ["7M"],
			evilsquall: ["7M"],
			blackout: ["7M"],
			modestlystun: ["7M"],
			protect: ["7M"],
		},
	},
	metalgreymonvaccine: {
		learnset: {
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			reboundstrike: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			gigawattlaser: ["7M"],
			deleteprogram: ["7M"],
			gigadestroyer: ["7M"],
			protect: ["7M"],
		},
	},
	metalgreymonvirus: {
		learnset: {
			burningheart: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			blackout: ["7M"],
			shadowfall: ["7M"],
			mechanicalclaw: ["7M"],
			gigawattlaser: ["7M"],
			deleteprogram: ["7M"],
			revengeflame: ["7M"],
			protect: ["7M"],
		},
	},
	metalmamemon: {
		learnset: {
			musclecharge: ["7M"],
			mechanicalclaw: ["7M"],
			fightingaura: ["7M"],
			reboundstrike: ["7M"],
			deleteprogram: ["7M"],
			upgrade: ["7M"],
			reverseprogram: ["7M"],
			megalospark: ["7M"],
			winterblast: ["7M"],
			burningheart: ["7M"],
			energybomb: ["7M"],
			protect: ["7M"],
		},
	},
	meteormon: {
		learnset: {
			earthcoat: ["7M"],
			rockfall: ["7M"],
			heatbreath: ["7M"],
			prominencebeam: ["7M"],
			gigafreeze: ["7M"],
			megatonpunch: ["7M"],
			fightingaura: ["7M"],
			galacticflare: ["7M"],
			protect: ["7M"],
		},
	},
	monzaemon: {
		learnset: {
			fightingaura: ["7M"],
			poopattackfield: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			saintshield: ["7M"],
			saintray: ["7M"],
			charmperfume: ["7M"],
			heartsattack: ["7M"],
			protect: ["7M"],
		},
	},
	myotismon: {
		learnset: {
			darkspirit: ["7M"],
			blackout: ["7M"],
			evilfantasy: ["7M"],
			electriccloud: ["7M"],
			aurorafreeze: ["7M"],
			evilsquall: ["7M"],
			wingshoes: ["7M"],
			confusedstorm: ["7M"],
			venomdisaster: ["7M"],
			reverseprogram: ["7M"],
			grislywing: ["7M"],
			protect: ["7M"],
		},
	},
	piximon: {
		learnset: {
			saintheal: ["7M"],
			holybreath: ["7M"],
			saintshield: ["7M"],
			fightingaura: ["7M"],
			shiningnova: ["7M"],
			wingshoes: ["7M"],
			windcutter: ["7M"],
			electriccloud: ["7M"],
			antiattackfield: ["7M"],
			earthcoat: ["7M"],
			bug: ["7M"],
			pitbomb: ["7M"],
			protect: ["7M"],
		},
	},
	shogungekomon: {
		learnset: {
			earthcoat: ["7M"],
			confusedstorm: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			gigafreeze: ["7M"],
			aurorafreeze: ["7M"],
			warcry: ["7M"],
			fightingaura: ["7M"],
			charmperfume: ["7M"],
			musicalfist: ["7M"],
			protect: ["7M"],
		},
	},
	skullgreymon: {
		learnset: {
			blackout: ["7M"],
			shadowfall: ["7M"],
			evilfantasy: ["7M"],
			evilsquall: ["7M"],
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			sonicjab: ["7M"],
			reboundstrike: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			deleteprogram: ["7M"],
			oblivionbird: ["7M"],
			protect: ["7M"],
		},
	},
	tekkamon: {
		learnset: {
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			reverseprogram: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			staticelectricity: ["7M"],
			shadowfall: ["7M"],
			firewall: ["7M"],
			fragbomb: ["7M"],
			protect: ["7M"],
		},
	},
	vademon: {
		learnset: {
			massmorph: ["7M"],
			charmperfume: ["7M"],
			bug: ["7M"],
			rockfall: ["7M"],
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			dgdimension: ["7M"],
			cootieskick: ["7M"],
			unidentifiedflyingkiss: ["7M"],
			protect: ["7M"],
		},
	},
	vermilimon: {
		learnset: {
			heatbreath: ["7M"],
			firetower: ["7M"],
			infinityburn: ["7M"],
			prominencebeam: ["7M"],
			earthcoat: ["7M"],
			rockfall: ["7M"],
			musclecharge: ["7M"],
			busterdrive: ["7M"],
			volcanicstrikes: ["7M"],
			protect: ["7M"],
		},
	},
	warumonzaemon: {
		learnset: {
			fightingaura: ["7M"],
			poopattackfield: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			darkspirit: ["7M"],
			evilfantasy: ["7M"],
			hideandseek: ["7M"],
			charmperfume: ["7M"],
			heartbreakattack: ["7M"],
			protect: ["7M"],
		},
	},
	waruseadramon: {
		learnset: {
			hailspear: ["7M"],
			waterblitz: ["7M"],
			gigafreeze: ["7M"],
			aurorafreeze: ["7M"],
			heatbreath: ["7M"],
			meltdown: ["7M"],
			staticelectricity: ["7M"],
			megalospark: ["7M"],
			evilsquall: ["7M"],
			evilicicle: ["7M"],
			protect: ["7M"],
		},
	},
	weregarurumon: {
		learnset: {
			warcry: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			megatonpunch: ["7M"],
			rockfall: ["7M"],
			burningheart: ["7M"],
			heatbreath: ["7M"],
			icestatue: ["7M"],
			aurorafreeze: ["7M"],
			winterblast: ["7M"],
			gigafreeze: ["7M"],
			wolfclaw: ["7M"],
			protect: ["7M"],
		},
	},
	whamon: {
		learnset: {
			waterblitz: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			aurorafreeze: ["7M"],
			massmorph: ["7M"],
			charmperfume: ["7M"],
			saintshield: ["7M"],
			confusedstorm: ["7M"],
			busterdrive: ["7M"],
			saintheal: ["7M"],
			tidalwave: ["7M"],
			protect: ["7M"],
		},
	},
	zudomon: {
		learnset: {
			electriccloud: ["7M"],
			thunderjustice: ["7M"],
			hailspear: ["7M"],
			icestatue: ["7M"],
			mechanicalclaw: ["7M"],
			aurorafreeze: ["7M"],
			antiattackfield: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			vulcanshammer: ["7M"],
			protect: ["7M"],
		},
	},
	//Mega
	alphamon: {
		learnset: {
			saintshield: ["7M"],
			saintray: ["7M"],
			holyjudgment: ["7M"],
			shiningnova: ["7M"],
			warcry: ["7M"],
			sonicjab: ["7M"],
			reboundstrike: ["7M"],
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			dgdimension: ["7M"],
			burningheart: ["7M"],
			thunderjustice: ["7M"],
			bladeofthedragonking: ["7M"],
			protect: ["7M"],
		},
	},
	blackmetalgarurumon: {
		learnset: {
			warcry: ["7M"],
			mechanicalclaw: ["7M"],
			megalospark: ["7M"],
			winterblast: ["7M"],
			gigafreeze: ["7M"],
			icestatue: ["7M"],
			shadowfall: ["7M"],
			evilfantasy: ["7M"],
			aurorafreeze: ["7M"],
			garurutomahawk: ["7M"],
			protect: ["7M"],
		},
	},
	blackwargreymon: {
		learnset: {
			burningheart: ["7M"],
			firetower: ["7M"],
			firewall: ["7M"],
			shadowfall: ["7M"],
			musclecharge: ["7M"],
			blackout: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			deleteprogram: ["7M"],
			evilfantasy: ["7M"],
			blacktornado: ["7M"],
			protect: ["7M"],
		},
	},
	boltmon: {
		learnset: {
			electriccloud: ["7M"],
			megalospark: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			gigawattlaser: ["7M"],
			meltdown: ["7M"],
			infinityburn: ["7M"],
			tomahawkstinger: ["7M"],
			protect: ["7M"],
		},
	},
	cherubimonevil: {
		learnset: {
			wingshoes: ["7M"],
			thunderjustice: ["7M"],
			megalospark: ["7M"],
			megatonpunch: ["7M"],
			blackout: ["7M"],
			chaoscloud: ["7M"],
			shadowfall: ["7M"],
			evilsquall: ["7M"],
			dgdimension: ["7M"],
			gigawattlaser: ["7M"],
			lightningspear: ["7M"],
			protect: ["7M"],
		},
	},
	cherubimongood: {
		learnset: {
			wingshoes: ["7M"],
			thunderjustice: ["7M"],
			megalospark: ["7M"],
			megatonpunch: ["7M"],
			holybreath: ["7M"],
			saintray: ["7M"],
			holyjudgment: ["7M"],
			shiningnova: ["7M"],
			dgdimension: ["7M"],
			gigawattlaser: ["7M"],
			heavensjudgment: ["7M"],
			protect: ["7M"],
		},
	},
	devitamamon: {
		learnset: {
			hailspear: ["7M"],
			blackout: ["7M"],
			evilfantasy: ["7M"],
			shadowfall: ["7M"],
			evilsquall: ["7M"],
			poopattackfield: ["7M"],
			extremepoopdeath: ["7M"],
			firetower: ["7M"],
			blackdeathcloud: ["7M"],
			protect: ["7M"],
		},
	},
	dorugoramon: {
		learnset: {
			burningheart: ["7M"],
			infinityburn: ["7M"],
			prominencebeam: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			fightingaura: ["7M"],
			busterdrive: ["7M"],
			sonicjab: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			deleteprogram: ["7M"],
			gigawattlaser: ["7M"],
			bravemetal: ["7M"],
			protect: ["7M"],
		},
	},
	ebemon: {
		learnset: {
			confusedstorm: ["7M"],
			electriccloud: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			upgrade: ["7M"],
			gigawattlaser: ["7M"],
			dgdimension: ["7M"],
			cootieskick: ["7M"],
			brainrupture: ["7M"],
			protect: ["7M"],
		},
	},
	herculeskabuterimon: {
		learnset: {
			confusedstorm: ["7M"],
			electriccloud: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			charmperfume: ["7M"],
			massmorph: ["7M"],
			bug: ["7M"],
			saintshield: ["7M"],
			holyflash: ["7M"],
			fightingaura: ["7M"],
			gigablaster: ["7M"],
			protect: ["7M"],
		},
	},
	hiandromon: {
		learnset: {
			sonicjab: ["7M"],
			electriccloud: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			saintheal: ["7M"],
			upgrade: ["7M"],
			antiattackfield: ["7M"],
			deleteprogram: ["7M"],
			gigawattlaser: ["7M"],
			bug: ["7M"],
			busterdrive: ["7M"],
			megatonpunch: ["7M"],
			atomicray: ["7M"],
			protect: ["7M"],
		},
	},
	lilithmon: {
		learnset: {
			evilfantasy: ["7M"],
			chaoscloud: ["7M"],
			shadowfall: ["7M"],
			windcutter: ["7M"],
			confusedstorm: ["7M"],
			charmperfume: ["7M"],
			venomdisaster: ["7M"],
			bug: ["7M"],
			aurorafreeze: ["7M"],
			mechanicalclaw: ["7M"],
			phantompain: ["7M"],
			protect: ["7M"],
		},
	},
	machinedramon: {
		learnset: {
			mechanicalclaw: ["7M"],
			upgrade: ["7M"],
			gigawattlaser: ["7M"],
			dgdimension: ["7M"],
			megalospark: ["7M"],
			thunderjustice: ["7M"],
			electriccloud: ["7M"],
			hideandseek: ["7M"],
			firewall: ["7M"],
			gigafreeze: ["7M"],
			infinitycannon: ["7M"],
			protect: ["7M"],
		},
	},
	magnadramon: {
		learnset: {
			holybreath: ["7M"],
			holyflash: ["7M"],
			holyjudgment: ["7M"],
			burningheart: ["7M"],
			firetower: ["7M"],
			prominencebeam: ["7M"],
			wingshoes: ["7M"],
			busterdrive: ["7M"],
			fightingaura: ["7M"],
			firetornado: ["7M"],
			protect: ["7M"],
		},
	},
	marineangemon: {
		learnset: {
			waterblitz: ["7M"],
			oceanwave: ["7M"],
			aurorafreeze: ["7M"],
			icestatue: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			saintshield: ["7M"],
			shiningnova: ["7M"],
			confusedstorm: ["7M"],
			wingshoes: ["7M"],
			antiattackfield: ["7M"],
			earthcoat: ["7M"],
			oceanlove: ["7M"],
			protect: ["7M"],
		},
	},
	metaletemon: {
		learnset: {
			reverseprogram: ["7M"],
			dgdimension: ["7M"],
			upgrade: ["7M"],
			gigawattlaser: ["7M"],
			charmperfume: ["7M"],
			holyflash: ["7M"],
			guerrillapoop: ["7M"],
			extremepoopdeath: ["7M"],
			darkrecital: ["7M"],
			protect: ["7M"],
		},
	},
	metalgarurumon: {
		learnset: {
			warcry: ["7M"],
			mechanicalclaw: ["7M"],
			busterdrive: ["7M"],
			winterblast: ["7M"],
			gigafreeze: ["7M"],
			icestatue: ["7M"],
			rockfall: ["7M"],
			meltdown: ["7M"],
			aurorafreeze: ["7M"],
			icewolfclaw: ["7M"],
			protect: ["7M"],
		},
	},
	metalseadramon: {
		learnset: {
			waterblitz: ["7M"],
			winterblast: ["7M"],
			oceanwave: ["7M"],
			icestatue: ["7M"],
			infinityburn: ["7M"],
			staticelectricity: ["7M"],
			megalospark: ["7M"],
			upgrade: ["7M"],
			deleteprogram: ["7M"],
			riverofpower: ["7M"],
			protect: ["7M"],
		},
	},
	ophanimon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			thunderjustice: ["7M"],
			fightingaura: ["7M"],
			aurorafreeze: ["7M"],
			saintheal: ["7M"],
			holybreath: ["7M"],
			saintshield: ["7M"],
			saintray: ["7M"],
			warcry: ["7M"],
			edensjavelin: ["7M"],
			protect: ["7M"],
		},
	},
	phoenixmon: {
		learnset: {
			wingshoes: ["7M"],
			windcutter: ["7M"],
			thunderjustice: ["7M"],
			burningheart: ["7M"],
			meltdown: ["7M"],
			prominencebeam: ["7M"],
			warcry: ["7M"],
			busterdrive: ["7M"],
			holyjudgment: ["7M"],
			shiningnova: ["7M"],
			infinityburn: ["7M"],
			starlightexplosion: ["7M"],
			protect: ["7M"],
		},
	},
	princemamemon: {
		learnset: {
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			megatonpunch: ["7M"],
			fightingaura: ["7M"],
			upgrade: ["7M"],
			reverseprogram: ["7M"],
			deleteprogram: ["7M"],
			dgdimension: ["7M"],
			holyflash: ["7M"],
			poopattackfield: ["7M"],
			smilewarhead: ["7M"],
			protect: ["7M"],
		},
	},
	raguelmon: {
		learnset: {
			warcry: ["7M"],
			windcutter: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			venomdisaster: ["7M"],
			shadowfall: ["7M"],
			evilsquall: ["7M"],
			blackout: ["7M"],
			deleteprogram: ["7M"],
			darknesszone: ["7M"],
			protect: ["7M"],
		},
	},
	rasielmon: {
		learnset: {
			warcry: ["7M"],
			windcutter: ["7M"],
			fightingaura: ["7M"],
			megatonpunch: ["7M"],
			mechanicalclaw: ["7M"],
			venomdisaster: ["7M"],
			holyjudgment: ["7M"],
			saintray: ["7M"],
			holybreath: ["7M"],
			dgdimension: ["7M"],
			knowledgestream: ["7M"],
			protect: ["7M"],
		},
	},
	rosemon: {
		learnset: {
			earthcoat: ["7M"],
			charmperfume: ["7M"],
			rootbind: ["7M"],
			venomdisaster: ["7M"],
			wingshoes: ["7M"],
			confusedstorm: ["7M"],
			evilfantasy: ["7M"],
			saintheal: ["7M"],
			shiningnova: ["7M"],
			thornwhip: ["7M"],
			protect: ["7M"],
		},
	},
	saberleomon: {
		learnset: {
			musclecharge: ["7M"],
			warcry: ["7M"],
			fightingaura: ["7M"],
			busterdrive: ["7M"],
			earthcoat: ["7M"],
			venomdisaster: ["7M"],
			saintshield: ["7M"],
			holyjudgment: ["7M"],
			mechanicalclaw: ["7M"],
			burningheart: ["7M"],
			infinityburn: ["7M"],
			shiningnova: ["7M"],
			howlingcrusher: ["7M"],
			protect: ["7M"],
		},
	},
	seraphimon: {
		learnset: {
			saintheal: ["7M"],
			saintshield: ["7M"],
			shiningnova: ["7M"],
			thunderjustice: ["7M"],
			antiattackfield: ["7M"],
			gigawattlaser: ["7M"],
			deleteprogram: ["7M"],
			sonicjab: ["7M"],
			megalospark: ["7M"],
			reboundstrike: ["7M"],
			holyjudgment: ["7M"],
			wingshoes: ["7M"],
			strikeofthesevenstars: ["7M"],
			protect: ["7M"],
		},
	},
	venommyotismon: {
		learnset: {
			darkspirit: ["7M"],
			blackout: ["7M"],
			evilfantasy: ["7M"],
			megalospark: ["7M"],
			icestatue: ["7M"],
			shadowfall: ["7M"],
			wingshoes: ["7M"],
			staticelectricity: ["7M"],
			venomdisaster: ["7M"],
			deleteprogram: ["7M"],
			venominfusion: ["7M"],
			protect: ["7M"],
		},
	},
	vikemon: {
		learnset: {
			hailspear: ["7M"],
			winterblast: ["7M"],
			icestatue: ["7M"],
			aurorafreeze: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			warcry: ["7M"],
			reboundstrike: ["7M"],
			megatonpunch: ["7M"],
			holyflash: ["7M"],
			arcticblizzard: ["7M"],
			protect: ["7M"],
		},
	},
	wargreymon: {
		learnset: {
			burningheart: ["7M"],
			firetower: ["7M"],
			firewall: ["7M"],
			infinityburn: ["7M"],
			musclecharge: ["7M"],
			sonicjab: ["7M"],
			busterdrive: ["7M"],
			mechanicalclaw: ["7M"],
			antiattackfield: ["7M"],
			deleteprogram: ["7M"],
			fightingaura: ["7M"],
			terraforce: ["7M"],
			protect: ["7M"],
		},
	},
};

exports.BattleLearnsets = BattleLearnsets;
