'use strict';
exports.BattlePokedex = {
	botamon: {
		num: -2000,
		species: "Botamon",
		types: ["Flame"],
		gender: "N",
		baseStats: {hp: 44, atk: 28, def: 21, spa: 31, spd: 18, spe: 19},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	dodomon: {
		num: -2001,
		species: "Dodomon",
		types: ["Battle"],
		gender: "N",
		baseStats: {hp: 43, atk: 35, def: 24, spa: 34, spd: 35, spe: 21},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	kuramon: {
		num: -2002,
		species: "Kuramon",
		types: ["Evil"],
		gender: "N",
		baseStats: {hp: 43, atk: 23, def: 18, spa: 23, spd: 19, spe: 19},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.005,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	poyomon: {
		num: -2003,
		species: "Poyomon",
		types: ["Air"],
		gender: "N",
		baseStats: {hp: 47, atk: 19, def: 21, spa: 25, spd: 25, spe: 17},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	punimon: {
		num: -2004,
		species: "Punimon",
		types: ["Air"],
		gender: "N",
		baseStats: {hp: 43, atk: 34, def: 20, spa: 25, spd: 20, spe: 25},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	yuramon: {
		num: -2005,
		species: "Yuramon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 46, atk: 19, def: 24, spa: 17, spd: 24, spe: 18},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	bukamon: {
		num: -2006,
		species: "Bukamon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 43, atk: 25, def: 17, spa: 25, spd: 19, spe: 27},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.007,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	dorimon: {
		num: -2007,
		species: "Dorimon",
		types: ["Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 50, atk: 35, def: 27, spa: 34, spd: 27, spe: 25},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	koromon: {
		num: -2008,
		species: "Koromon",
		types: ["Flame"],
		gender: "N",
		baseStats: {hp: 44, atk: 31, def: 23, spa: 23, spd: 23, spe: 19},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	motimon: {
		num: -2009,
		species: "Motimon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 41, atk: 29, def: 19, spa: 29, spd: 20, spe: 18},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.008,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	nyaromon: {
		num: -2010,
		species: "Nyaromon",
		types: ["Holy"],
		gender: "N",
		baseStats: {hp: 43, atk: 25, def: 16, spa: 27, spd: 17, spe: 21},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.008,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tanemon: {
		num: -2011,
		species: "Tanemon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 42, atk: 25, def: 19, spa: 25, spd: 21, spe: 20},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	tokomon: {
		num: -2012,
		species: "Tokomon",
		types: ["Battle"],
		gender: "N",
		baseStats: {hp: 40, atk: 24, def: 17, spa: 24, spd: 19, spe: 25},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	tsumemon: {
		num: -2013,
		species: "Tsumemon",
		types: ["Evil"],
		gender: "N",
		baseStats: {hp: 50, atk: 37, def: 26, spa: 37, spd: 27, spe: 26},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	tsunomon: {
		num: -2014,
		species: "Tsunomon",
		types: ["Air", "Aqua"],
		gender: "N",
		baseStats: {hp: 43, atk: 34, def: 22, spa: 25, spd: 22, spe: 25},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	agumon: {
		num: -2015,
		species: "Agumon",
		types: ["Flame", "Battle"],
		gender: "N",
		baseStats: {hp: 74, atk: 56, def: 41, spa: 41, spd: 35, spe: 38},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	aruramon: {
		num: -2016,
		species: "Aruramon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 72, atk: 49, def: 42, spa: 47, spd: 42, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	betamon: {
		num: -2017,
		species: "Betamon",
		types: ["Aqua", "Air"],
		gender: "N",
		baseStats: {hp: 57, atk: 51, def: 33, spa: 48, spd: 44, spe: 35},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	biyomon: {
		num: -2018,
		species: "Biyomon",
		types: ["Flame", "Air"],
		gender: "N",
		baseStats: {hp: 66, atk: 47, def: 35, spa: 47, spd: 34, spe: 49},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	clearagumon: {
		num: -2019,
		species: "ClearAgumon",
		types: ["Mech", "Holy"],
		gender: "N",
		baseStats: {hp: 74, atk: 52, def: 44, spa: 52, spd: 42, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	demidevimon: {
		num: -2020,
		species: "DemiDevimon",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 67, atk: 49, def: 45, spa: 50, spd: 45, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.008,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	dokunemon: {
		num: -2021,
		species: "Dokunemon",
		types: ["Nature", "Air"],
		gender: "N",
		baseStats: {hp: 71, atk: 54, def: 43, spa: 52, spd: 43, spe: 37},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	dorumon: {
		num: -2022,
		species: "Dorumon",
		types: ["Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 85, atk: 53, def: 45, spa: 52, spd: 45, spe: 35},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	elecmon: {
		num: -2023,
		species: "Elecmon",
		types: ["Air", "Battle"],
		gender: "N",
		baseStats: {hp: 75, atk: 53, def: 35, spa: 51, spd: 35, spe: 33},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	gabumon: {
		num: -2024,
		species: "Gabumon",
		types: ["Flame", "Aqua"],
		gender: "N",
		baseStats: {hp: 76, atk: 58, def: 39, spa: 56, spd: 39, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	goburimon: {
		num: -2025,
		species: "Goburimon",
		types: ["Nature", "Battle"],
		gender: "N",
		baseStats: {hp: 79, atk: 55, def: 48, spa: 43, spd: 43, spe: 33},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	gomamon: {
		num: -2026,
		species: "Gomamon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 72, atk: 50, def: 44, spa: 50, spd: 42, spe: 37},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	gotsumon: {
		num: -2027,
		species: "Gotsumon",
		types: ["Nature", "Battle"],
		gender: "N",
		baseStats: {hp: 88, atk: 52, def: 54, spa: 54, spd: 40, spe: 32},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	kunemon: {
		num: -2028,
		species: "Kunemon",
		types: ["Nature", "Air"],
		gender: "N",
		baseStats: {hp: 66, atk: 50, def: 45, spa: 48, spd: 45, spe: 35},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	modokibetamon: {
		num: -2029,
		species: "ModokiBetamon",
		types: ["Air", "Aqua"],
		gender: "N",
		baseStats: {hp: 54, atk: 52, def: 33, spa: 49, spd: 45, spe: 37},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	muchomon: {
		num: -2030,
		species: "Muchomon",
		types: ["Flame", "Aqua", "Nature"],
		gender: "N",
		baseStats: {hp: 64, atk: 47, def: 36, spa: 47, spd: 34, spe: 47},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	otamamon: {
		num: -2031,
		species: "Otamamon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 70, atk: 50, def: 31, spa: 47, spd: 42, spe: 35},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	palmon: {
		num: -2032,
		species: "Palmon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 69, atk: 50, def: 38, spa: 47, spd: 38, spe: 41},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	patamon: {
		num: -2033,
		species: "Patamon",
		types: ["Air", "Battle"],
		gender: "N",
		baseStats: {hp: 64, atk: 46, def: 37, spa: 44, spd: 37, spe: 51},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	penguinmon: {
		num: -2034,
		species: "Penguinmon",
		types: ["Aqua", "Nature"],
		gender: "N",
		baseStats: {hp: 72, atk: 50, def: 43, spa: 50, spd: 41, spe: 40},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	psychemon: {
		num: -2035,
		species: "Psychemon",
		types: ["Aqua", "Battle"],
		gender: "N",
		baseStats: {hp: 76, atk: 58, def: 40, spa: 56, spd: 40, spe: 41},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	salamon: {
		num: -2036,
		species: "Salamon",
		types: ["Holy"],
		gender: "N",
		baseStats: {hp: 70, atk: 38, def: 37, spa: 51, spd: 39, spe: 41},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	shamamon: {
		num: -2037,
		species: "Shamamon",
		types: ["Evil", "Flame", "Battle"],
		gender: "N",
		baseStats: {hp: 78, atk: 50, def: 40, spa: 49, spd: 39, spe: 39},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	snowagumon: {
		num: -2038,
		species: "SnowAgumon",
		types: ["Aqua", "Battle"],
		gender: "N",
		baseStats: {hp: 66, atk: 51, def: 44, spa: 38, spd: 38, spe: 36},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	snowgoburimon: {
		num: -2039,
		species: "SnowGoburimon",
		types: ["Aqua", "Battle"],
		gender: "N",
		baseStats: {hp: 74, atk: 53, def: 41, spa: 41, spd: 37, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	tentomon: {
		num: -2040,
		species: "Tentomon",
		types: ["Air", "Nature"],
		gender: "N",
		baseStats: {hp: 71, atk: 45, def: 47, spa: 50, spd: 40, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	toyagumon: {
		num: -2041,
		species: "ToyAgumon",
		types: ["Mech", "Flame"],
		gender: "N",
		baseStats: {hp: 76, atk: 48, def: 47, spa: 49, spd: 45, spe: 37},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	tsukaimon: {
		num: -2042,
		species: "Tsukaimon",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 68, atk: 47, def: 39, spa: 45, spd: 39, spe: 50},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	airdramon: {
		num: -2043,
		species: "Airdramon",
		types: ["Air", "Flame"],
		gender: "N",
		baseStats: {hp: 98, atk: 57, def: 62, spa: 54, spd: 61, spe: 63},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	akatorimon: {
		num: -2044,
		species: "Akatorimon",
		types: ["AIr", "Flame"],
		gender: "N",
		baseStats: {hp: 106, atk: 64, def: 62, spa: 64, spd: 54, spe: 54},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	angemon: {
		num: -2045,
		species: "Angemon",
		types: ["Holy", "Air", "Battle"],
		gender: "N",
		baseStats: {hp: 100, atk: 64, def: 52, spa: 64, spd: 50, spe: 59},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	bakemon: {
		num: -2046,
		species: "Bakemon",
		types: ["Evil"],
		gender: "N",
		baseStats: {hp: 104, atk: 42, def: 56, spa: 58, spd: 62, spe: 56},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	birdramon: {
		num: -2047,
		species: "Birdramon",
		types: ["Flame", "Air"],
		gender: "N",
		baseStats: {hp: 100, atk: 62, def: 50, spa: 62, spd: 49, spe: 60},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	blackgatomon: {
		num: -2048,
		species: "BlackGatomon",
		types: ["Evil"],
		gender: "N",
		baseStats: {hp: 98, atk: 49, def: 44, spa: 66, spd: 49, spe: 60},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	centarumon: {
		num: -2049,
		species: "Centarumon",
		types: ["Mech", "Flame", "Holy"],
		gender: "N",
		baseStats: {hp: 101, atk: 64, def: 65, spa: 64, spd: 57, spe: 59},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	coelamon: {
		num: -2050,
		species: "Coelamon",
		types: ["Aqua", "Nature", "Mech"],
		gender: "N",
		baseStats: {hp: 110, atk: 60, def: 58, spa: 52, spd: 51, spe: 54},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	darkrizamon: {
		num: -2051,
		species: "Darkrizamon",
		types: ["Flame", "Evil"],
		gender: "N",
		baseStats: {hp: 107, atk: 76, def: 54, spa: 76, spd: 62, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	devimon: {
		num: -2052,
		species: "Devimon",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 111, atk: 53, def: 50, spa: 72, spd: 55, spe: 53},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	dolphmon: {
		num: -2053,
		species: "Dolphmon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 98, atk: 56, def: 58, spa: 56, spd: 50, spe: 58},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	dorugamon: {
		num: -2054,
		species: "Dorugamon",
		types: ["Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 114, atk: 75, def: 68, spa: 73, spd: 67, spe: 54},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	drimogemon: {
		num: -2055,
		species: "Drimogemon",
		types: ["Nature", "Mech"],
		gender: "N",
		baseStats: {hp: 112, atk: 73, def: 64, spa: 64, spd: 56, spe: 49},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	flarerizamon: {
		num: -2056,
		species: "Flarerizamon",
		types: ["Flame"],
		gender: "N",
		baseStats: {hp: 108, atk: 74, def: 52, spa: 74, spd: 60, spe: 54},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	frigimon: {
		num: -2057,
		species: "Frigimon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 104, atk: 59, def: 68, spa: 59, spd: 67, spe: 45},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	fugamon: {
		num: -2058,
		species: "Fugamon",
		types: ["Air", "Battle"],
		gender: "N",
		baseStats: {hp: 112, atk: 76, def: 58, spa: 77, spd: 58, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	garurumon: {
		num: -2059,
		species: "Garurumon",
		types: ["Aqua", "Flame", "Battle"],
		gender: "N",
		baseStats: {hp: 111, atk: 60, def: 54, spa: 68, spd: 52, spe: 56},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	gatomon: {
		num: -2060,
		species: "Gatomon",
		types: ["Holy"],
		gender: "N",
		baseStats: {hp: 101, atk: 49, def: 47, spa: 65, spd: 51, spe: 57},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	gekomon: {
		num: -2061,
		species: "Gekomon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 100, atk: 56, def: 54, spa: 55, spd: 56, spe: 54},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	geremon: {
		num: -2062,
		species: "Geremon",
		types: ["Filth", "Aqua"],
		gender: "N",
		baseStats: {hp: 100, atk: 61, def: 66, spa: 62, spd: 66, spe: 48},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	greymon: {
		num: -2063,
		species: "Greymon",
		types: ["Flame", "Battle"],
		gender: "N",
		baseStats: {hp: 114, atk: 77, def: 62, spa: 58, spd: 54, spe: 54},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	guardromon: {
		num: -2064,
		species: "Guardromon",
		types: ["Mech", "Flame"],
		gender: "N",
		baseStats: {hp: 115, atk: 62, def: 70, spa: 71, spd: 52, spe: 49},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.032,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	gururumon: {
		num: -2065,
		species: "Gururumon",
		types: ["Evil", "Battle", "Aqua"],
		gender: "N",
		baseStats: {hp: 108, atk: 60, def: 51, spa: 68, spd: 50, spe: 61},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	hyogamon: {
		num: -2066,
		species: "Hyogamon",
		types: ["Aqua", "Battle"],
		gender: "N",
		baseStats: {hp: 110, atk: 74, def: 62, spa: 76, spd: 62, spe: 48},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	icedevimon: {
		num: -2067,
		species: "IceDevimon",
		types: ["Evil", "Aqua"],
		gender: "N",
		baseStats: {hp: 108, atk: 68, def: 60, spa: 70, spd: 60, spe: 50},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	icemon: {
		num: -2068,
		species: "Icemon",
		types: ["Aqua", "Battle"],
		gender: "N",
		baseStats: {hp: 106, atk: 54, def: 69, spa: 55, spd: 68, spe: 50},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ikkakumon: {
		num: -2069,
		species: "Ikkakumon",
		types: ["Aqua", "Mech"],
		gender: "N",
		baseStats: {hp: 114, atk: 79, def: 64, spa: 74, spd: 63, spe: 45},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	junglemojyamon: {
		num: -2070,
		species: "JungleMojyamon",
		types: ["Battle", "Nature"],
		gender: "N",
		baseStats: {hp: 108, atk: 70, def: 62, spa: 62, spd: 62, spe: 56},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	kabuterimon: {
		num: -2071,
		species: "Kabuterimon",
		types: ["Air", "Nature"],
		gender: "N",
		baseStats: {hp: 112, atk: 64, def: 68, spa: 71, spd: 68, spe: 54},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	kokatorimon: {
		num: -2072,
		species: "Kokatorimon",
		types: ["Air", "Filth"],
		gender: "N",
		baseStats: {hp: 106, atk: 68, def: 51, spa: 68, spd: 44, spe: 54},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	kuwagamon: {
		num: -2073,
		species: "Kuwagamon",
		types: ["Nature", "Battle", "Air"],
		gender: "N",
		baseStats: {hp: 107, atk: 72, def: 48, spa: 74, spd: 48, spe: 55},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	leomon: {
		num: -2074,
		species: "Leomon",
		types: ["Nature", "Battle"],
		gender: "N",
		baseStats: {hp: 112, atk: 79, def: 52, spa: 60, spd: 46, spe: 50},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meicoomon: {
		num: -2075,
		species: "Meicoomon",
		types: ["Battle"],
		gender: "N",
		baseStats: {hp: 98, atk: 68, def: 46, spa: 68, spd: 47, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meramon: {
		num: -2076,
		species: "Meramon",
		types: ["Flame"],
		gender: "N",
		baseStats: {hp: 114, atk: 80, def: 47, spa: 59, spd: 42, spe: 51},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	mikemon: {
		num: -2077,
		species: "Mikemon",
		types: ["Battle"],
		gender: "N",
		baseStats: {hp: 104, atk: 50, def: 47, spa: 66, spd: 51, spe: 54},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	mojyamon: {
		num: -2078,
		species: "Mojyamon",
		types: ["Battle", "Aqua"],
		gender: "N",
		baseStats: {hp: 105, atk: 63, def: 68, spa: 55, spd: 68, spe: 45},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	monochromon: {
		num: -2079,
		species: "Monochromon",
		types: ["Flame", "Nature"],
		gender: "N",
		baseStats: {hp: 114, atk: 76, def: 66, spa: 66, spd: 58, spe: 49},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	morishellmon: {
		num: -2080,
		species: "MoriShellmon",
		types: ["Aqua", "Nature"],
		gender: "N",
		baseStats: {hp: 110, atk: 68, def: 67, spa: 68, spd: 59, spe: 45},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	mudfrigimon: {
		num: -2081,
		species: "MudFrigimon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 102, atk: 64, def: 66, spa: 64, spd: 65, spe: 44},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	nanimon: {
		num: -2082,
		species: "Nanimon",
		types: ["Filth", "Battle"],
		gender: "N",
		baseStats: {hp: 106, atk: 62, def: 57, spa: 71, spd: 43, spe: 47},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	ninjamon: {
		num: -2083,
		species: "Ninjamon",
		types: ["Nature", "Battle", "Flame"],
		gender: "N",
		baseStats: {hp: 106, atk: 72, def: 52, spa: 63, spd: 52, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	nisedrimogemon: {
		num: -2084,
		species: "NiseDrimogemon",
		types: ["Nature", "Mech"],
		gender: "N",
		baseStats: {hp: 109, atk: 62, def: 62, spa: 54, spd: 54, spe: 51},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	numemon: {
		num: -2085,
		species: "Numemon",
		types: ["Filth", "Aqua"],
		gender: "N",
		baseStats: {hp: 96, atk: 55, def: 49, spa: 51, spd: 65, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	ogremon: {
		num: -2086,
		species: "Ogremon",
		types: ["Nature", "Battle"],
		gender: "N",
		baseStats: {hp: 112, atk: 76, def: 64, spa: 78, spd: 64, spe: 47},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	piddomon: {
		num: -2087,
		species: "Piddomon",
		types: ["Holy", "Air", "Flame"],
		gender: "N",
		baseStats: {hp: 100, atk: 68, def: 53, spa: 64, spd: 52, spe: 56},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	platinumsukamon: {
		num: -2088,
		species: "PlatinumSukamon",
		types: ["Mech", "Filth"],
		gender: "N",
		baseStats: {hp: 115, atk: 70, def: 64, spa: 70, spd: 66, spe: 45},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	redvegiemon: {
		num: -2089,
		species: "RedVegiemon",
		types: ["Nature", "Flame"],
		gender: "N",
		baseStats: {hp: 106, atk: 68, def: 54, spa: 70, spd: 54, spe: 51},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	rockmon: {
		num: -2090,
		species: "Rockmon",
		types: ["Mech"],
		gender: "N",
		baseStats: {hp: 107, atk: 70, def: 60, spa: 70, spd: 58, spe: 38},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	saberdramon: {
		num: -2091,
		species: "Saberdramon",
		types: ["AIr", "Evil"],
		gender: "N",
		baseStats: {hp: 99, atk: 76, def: 48, spa: 63, spd: 47, spe: 60},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	sandyanmamon: {
		num: -2092,
		species: "SandYanmamon",
		types: ["Air", "Nature"],
		gender: "N",
		baseStats: {hp: 104, atk: 54, def: 70, spa: 62, spd: 61, spe: 51},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	seadramon: {
		num: -2093,
		species: "Seadramon",
		types: ["Aqua", "Flame"],
		gender: "N",
		baseStats: {hp: 101, atk: 70, def: 60, spa: 70, spd: 63, spe: 49},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.021,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	shellmon: {
		num: -2094,
		species: "Shellmon",
		types: ["Aqua", "Nature"],
		gender: "N",
		baseStats: {hp: 114, atk: 69, def: 68, spa: 69, spd: 60, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	shimaunimon: {
		num: -2095,
		species: "ShimaUnimon",
		types: ["Air", "Battle"],
		gender: "N",
		baseStats: {hp: 93, atk: 62, def: 50, spa: 70, spd: 44, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	soulmon: {
		num: -2096,
		species: "Soulmon",
		types: ["Evil"],
		gender: "N",
		baseStats: {hp: 104, atk: 33, def: 55, spa: 66, spd: 66, spe: 54},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	sukamon: {
		num: -2097,
		species: "Sukamon",
		types: ["Flith"],
		gender: "N",
		baseStats: {hp: 106, atk: 55, def: 59, spa: 56, spd: 59, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tankmon: {
		num: -2098,
		species: "Tankmon",
		types: ["Mech", "Flame"],
		gender: "N",
		baseStats: {hp: 115, atk: 69, def: 68, spa: 75, spd: 51, spe: 50},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.035,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	togemon: {
		num: -2099,
		species: "Togemon",
		types: ["Nature", "Battle"],
		gender: "N",
		baseStats: {hp: 111, atk: 72, def: 64, spa: 70, spd: 64, spe: 47},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	tyrannomon: {
		num: -2100,
		species: "Tyrannomon",
		types: ["Flame", "Battle"],
		gender: "N",
		baseStats: {hp: 112, atk: 75, def: 52, spa: 73, spd: 52, spe: 50},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	unimon: {
		num: -2101,
		species: "Unimon",
		types: ["Air", "Holy"],
		gender: "N",
		baseStats: {hp: 100, atk: 64, def: 50, spa: 64, spd: 44, spe: 58},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.3,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	vegiemon: {
		num: -2102,
		species: "Vegiemon",
		types: ["Nature"],
		gender: "N",
		baseStats: {hp: 102, atk: 54, def: 62, spa: 55, spd: 62, spe: 49},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	weedmon: {
		num: -2103,
		species: "Weedmon",
		types: ["Nature", "Filth"],
		gender: "N",
		baseStats: {hp: 104, atk: 68, def: 55, spa: 69, spd: 55, spe: 47},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	yanmamon: {
		num: -2104,
		species: "Yanmamon",
		types: ["Air", "Nature"],
		gender: "N",
		baseStats: {hp: 100, atk: 61, def: 54, spa: 70, spd: 47, spe: 53},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	andromon: {
		num: -2105,
		species: "Andromon",
		types: ["Mech", "Air"],
		gender: "N",
		baseStats: {hp: 144, atk: 79, def: 82, spa: 88, spd: 61, spe: 66},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	angewomon: {
		num: -2106,
		species: "Angewomon",
		types: ["Holy", "Air", "Battle"],
		gender: "N",
		baseStats: {hp: 148, atk: 66, def: 60, spa: 87, spd: 66, spe: 76},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	beastmon: {
		num: -2107,
		species: "Beastmon",
		types: ["Evil", "Battle"],
		gender: "N",
		baseStats: {hp: 138, atk: 90, def: 60, spa: 79, spd: 53, spe: 81},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	blackweregarurumon: {
		num: -2108,
		species: "BlackWereGarurumon",
		types: ["Evil", "Battle", "Nature"],
		gender: "N",
		baseStats: {hp: 147, atk: 86, def: 77, spa: 87, spd: 77, spe: 76},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	bluemeramon: {
		num: -2109,
		species: "BlueMeramon",
		types: ["Flame", "Aqua"],
		gender: "N",
		baseStats: {hp: 157, atk: 87, def: 66, spa: 88, spd: 66, spe: 71},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	digitamamon: {
		num: -2110,
		species: "Digitamamon",
		types: ["Filth", "Evil"],
		gender: "N",
		baseStats: {hp: 149, atk: 80, def: 87, spa: 59, spd: 78, spe: 58},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	dorugreymon: {
		num: -2111,
		species: "DoruGreymon",
		types: ["Battle", "Mech", "Flame"],
		gender: "N",
		baseStats: {hp: 155, atk: 91, def: 82, spa: 88, spd: 81, spe: 70},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.036,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	etemon: {
		num: -2112,
		species: "Etemon",
		types: ["Nature", "Battle", "Filth"],
		gender: "N",
		baseStats: {hp: 136, atk: 76, def: 84, spa: 78, spd: 84, spe: 62},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	garudamon: {
		num: -2113,
		species: "Garudamon",
		types: ["Air", "Flame", "Battle"],
		gender: "N",
		baseStats: {hp: 144, atk: 86, def: 66, spa: 86, spd: 66, spe: 77},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	gigadramon: {
		num: -2114,
		species: "Gigadramon",
		types: ["Mech", "Air", "Evil"],
		gender: "N",
		baseStats: {hp: 153, atk: 82, def: 84, spa: 93, spd: 63, spe: 70},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	giromon: {
		num: -2115,
		species: "Giromon",
		types: ["Mech", "Air", "Battle"],
		gender: "N",
		baseStats: {hp: 143, atk: 93, def: 69, spa: 82, spd: 69, spe: 65},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	iceleomon: {
		num: -2116,
		species: "IceLeomon",
		types: ["Aqua", "Battle"],
		gender: "N",
		baseStats: {hp: 149, atk: 101, def: 69, spa: 76, spd: 61, spe: 66},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ladydevimon: {
		num: -2117,
		species: "LadyDevimon",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 145, atk: 66, def: 62, spa: 90, spd: 69, spe: 72},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	lillymon: {
		num: -2118,
		species: "Lillymon",
		types: ["Nature", "Air"],
		gender: "N",
		baseStats: {hp: 140, atk: 75, def: 72, spa: 74, spd: 72, spe: 76},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.016,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	magnaangemon: {
		num: -2119,
		species: "MagnaAngemon",
		types: ["Holy", "Air", "Mech"],
		gender: "N",
		baseStats: {hp: 147, atk: 89, def: 53, spa: 80, spd: 69, spe: 76},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	mamemon: {
		num: -2120,
		species: "Mamemon",
		types: ["Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 146, atk: 78, def: 78, spa: 86, spd: 59, spe: 68},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	megadramon: {
		num: -2121,
		species: "Megadramon",
		types: ["Mech", "Air", "Evil"],
		gender: "N",
		baseStats: {hp: 150, atk: 90, def: 78, spa: 69, spd: 70, spe: 64},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	megakabuterimon: {
		num: -2122,
		species: "MegaKabuterimon",
		types: ["Air", "Nature"],
		gender: "N",
		baseStats: {hp: 159, atk: 90, def: 81, spa: 68, spd: 72, spe: 63},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	megaseadramon: {
		num: -2123,
		species: "MegaSeadramon",
		types: ["Aqua", "Air", "Flame"],
		gender: "N",
		baseStats: {hp: 151, atk: 86, def: 70, spa: 85, spd: 70, spe: 70},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	meicrackmon: {
		num: -2124,
		species: "Meicrackmon",
		types: ["Battle", "Holy"],
		gender: "N",
		baseStats: {hp: 126, atk: 88, def: 61, spa: 86, spd: 62, spe: 78},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meicrackmonvm: {
		num: -2125,
		species: "MeicrackmonVM",
		types: ["Battle", "Evil"],
		gender: "N",
		baseStats: {hp: 126, atk: 88, def: 61, spa: 86, spd: 62, spe: 78},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	metalgreymon: {
		num: -2126,
		species: "MetalGreymon",
		types: ["Flame", "Mech", "Battle"],
		gender: "N",
		baseStats: {hp: 149, atk: 91, def: 78, spa: 68, spd: 70, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	metalgreymonvirus: {
		num: -2127,
		species: "MetalGreymon(Virus)",
		types: ["Flame", "Mech", "Evil"],
		gender: "N",
		baseStats: {hp: 149, atk: 91, def: 78, spa: 68, spd: 70, spe: 67},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	metalmamemon: {
		num: -2128,
		species: "MetalMamemon",
		types: ["Mech", "Battle"],
		gender: "N",
		baseStats: {hp: 141, atk: 87, def: 80, spa: 86, spd: 80, spe: 71},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	meteormon: {
		num: -2129,
		species: "Meteormon",
		types: ["Nature", "Flame"],
		gender: "N",
		baseStats: {hp: 155, atk: 74, def: 86, spa: 81, spd: 65, spe: 72},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	monzaemon: {
		num: -2130,
		species: "Monzaemon",
		types: ["Battle", "Filth", "Holy"],
		gender: "N",
		baseStats: {hp: 154, atk: 62, def: 75, spa: 82, spd: 82, spe: 60},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	myotismon: {
		num: -2131,
		species: "Myotismon",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 156, atk: 66, def: 73, spa: 88, spd: 81, spe: 64},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	piximon: {
		num: -2132,
		species: "Piximon",
		types: ["Holy", "Nature", "Air"],
		gender: "N",
		baseStats: {hp: 136, atk: 75, def: 72, spa: 74, spd: 72, spe: 75},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	shogungekomon: {
		num: -2133,
		species: "ShogunGekomon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 150, atk: 82, def: 84, spa: 85, spd: 84, spe: 59},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	skullgreymon: {
		num: -2134,
		species: "SkullGreymon",
		types: ["Evil"],
		gender: "N",
		baseStats: {hp: 158, atk: 98, def: 84, spa: 74, spd: 76, spe: 60},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	tekkamon: {
		num: -2135,
		species: "Tekkamon",
		types: ["Mech", "Battle", "Evil"],
		gender: "N",
		baseStats: {hp: 140, atk: 81, def: 77, spa: 71, spd: 77, spe: 70},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.05,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	vademon: {
		num: -2136,
		species: "Vademon",
		types: ["Nature", "Mech"],
		gender: "N",
		baseStats: {hp: 136, atk: 90, def: 60, spa: 82, spd: 80, spe: 62},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	vermilimon: {
		num: -2137,
		species: "Vermilimon",
		types: ["Flame", "Nature"],
		gender: "N",
		baseStats: {hp: 149, atk: 90, def: 84, spa: 78, spd: 74, spe: 66},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	warumonzaemon: {
		num: -2138,
		species: "WaruMonzaemon",
		types: ["Battle", "Filth", "Evil"],
		gender: "N",
		baseStats: {hp: 152, atk: 62, def: 74, spa: 82, spd: 80, spe: 64},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.024,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	waruseadramon: {
		num: -2139,
		species: "WaruSeadramon",
		types: ["Evil", "Aqua", "Air"],
		gender: "N",
		baseStats: {hp: 151, atk: 67, def: 64, spa: 89, spd: 70, spe: 68},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	weregarurumon: {
		num: -2140,
		species: "WereGarurumon",
		types: ["Battle", "Nature"],
		gender: "N",
		baseStats: {hp: 145, atk: 85, def: 68, spa: 85, spd: 67, spe: 77},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.018,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	whamon: {
		num: -2141,
		species: "Whamon",
		types: ["Aqua"],
		gender: "N",
		baseStats: {hp: 161, atk: 86, def: 82, spa: 86, spd: 80, spe: 60},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	zudomon: {
		num: -2142,
		species: "Zudomon",
		types: ["Aqua", "Battle", "Air"],
		gender: "N",
		baseStats: {hp: 157, atk: 92, def: 82, spa: 92, spd: 81, spe: 59},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	alphamon: {
		num: -2143,
		species: "Alphamon",
		types: ["Holy", "Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 212, atk: 122, def: 116, spa: 122, spd: 112, spe: 94},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.07,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackmetalgarurumon: {
		num: -2144,
		species: "BlackMetalGarurumon",
		types: ["Evil", "Aqua", "Mech"],
		gender: "N",
		baseStats: {hp: 210, atk: 113, def: 76, spa: 103, spd: 58, spe: 91},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.028,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackwargreymon: {
		num: -2145,
		species: "BlackWarGreymon",
		types: ["Flame", "Mech", "Evil"],
		gender: "N",
		baseStats: {hp: 215, atk: 116, def: 93, spa: 90, spd: 80, spe: 85},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	boltmon: {
		num: -2146,
		species: "Boltmon",
		types: ["Mech", "Battle", "Air"],
		gender: "N",
		baseStats: {hp: 219, atk: 115, def: 96, spa: 86, spd: 87, spe: 84},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	cherubimonevil: {
		num: -2147,
		species: "Cherubimon(Evil)",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 223, atk: 121, def: 73, spa: 110, spd: 98, spe: 90},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.035,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	cherubimongood: {
		num: -2148,
		species: "Cherubimon(Good)",
		types: ["Holy", "Air"],
		gender: "N",
		baseStats: {hp: 209, atk: 117, def: 80, spa: 106, spd: 105, spe: 86},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	devitamamon: {
		num: -2149,
		species: "Devitamamon",
		types: ["Filth", "Evil"],
		gender: "N",
		baseStats: {hp: 210, atk: 114, def: 100, spa: 112, spd: 100, spe: 87},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	dorugoramon: {
		num: -2150,
		species: "Dorugoramon",
		types: ["Flame", "Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 215, atk: 116, def: 96, spa: 113, spd: 115, spe: 82},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.064,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ebemon: {
		num: -2151,
		species: "Ebemon",
		types: ["Mech", "Air"],
		gender: "N",
		baseStats: {hp: 211, atk: 87, def: 78, spa: 112, spd: 90, spe: 76},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	herculeskabuterimon: {
		num: -2152,
		species: "HerculesKabuterimon",
		types: ["Air", "Nature", "Battle"],
		gender: "N",
		baseStats: {hp: 215, atk: 102, def: 104, spa: 119, spd: 104, spe: 92},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	hiandromon: {
		num: -2153,
		species: "HiAndromon",
		types: ["Mech", "Air"],
		gender: "N",
		baseStats: {hp: 207, atk: 111, def: 94, spa: 100, spd: 70, spe: 85},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	lilithmon: {
		num: -2154,
		species: "Lilithmon",
		types: ["Evil", "Nature"],
		gender: "N",
		baseStats: {hp: 219, atk: 66, def: 80, spa: 119, spd: 102, spe: 92},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	machinedramon: {
		num: -2155,
		species: "Machinedramon",
		types: ["Mech", "Air"],
		gender: "N",
		baseStats: {hp: 216, atk: 104, def: 99, spa: 116, spd: 74, spe: 83},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	magnadramon: {
		num: -2156,
		species: "Magnadramon",
		types: ["Holy", "Flame"],
		gender: "N",
		baseStats: {hp: 217, atk: 117, def: 97, spa: 116, spd: 100, spe: 94},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	marineangemon: {
		num: -2157,
		species: "MarineAngemon",
		types: ["Aqua", "Holy"],
		gender: "N",
		baseStats: {hp: 195, atk: 60, def: 83, spa: 94, spd: 82, spe: 86},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.005,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	metaletemon: {
		num: -2158,
		species: "MetalEtemon",
		types: ["Filth", "Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 196, atk: 86, def: 96, spa: 97, spd: 72, spe: 79},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	metalgarurumon: {
		num: -2159,
		species: "MetalGarurumon",
		types: ["Aqua", "Mech"],
		gender: "N",
		baseStats: {hp: 209, atk: 112, def: 81, spa: 110, spd: 81, spe: 88},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.028,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	metalseadramon: {
		num: -2160,
		species: "MetalSeadramon",
		types: ["Aqua", "Mech", "Air"],
		gender: "N",
		baseStats: {hp: 212, atk: 108, def: 71, spa: 96, spd: 94, spe: 80},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	ophanimon: {
		num: -2161,
		species: "Ophanimon",
		types: ["Holy", "Air", "Battle"],
		gender: "N",
		baseStats: {hp: 206, atk: 83, def: 99, spa: 119, spd: 98, spe: 92},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	phoenixmon: {
		num: -2162,
		species: "Phoenixmon",
		types: ["Flame", "Air", "Holy"],
		gender: "N",
		baseStats: {hp: 217, atk: 86, def: 86, spa: 114, spd: 94, spe: 94},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	princemamemon: {
		num: -2163,
		species: "PrinceMamemon",
		types: ["Mech", "Battle"],
		gender: "N",
		baseStats: {hp: 201, atk: 95, def: 100, spa: 94, spd: 100, spe: 80},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	raguelmon: {
		num: -2164,
		species: "Raguelmon",
		types: ["Battle", "Evil"],
		gender: "N",
		baseStats: {hp: 215, atk: 109, def: 76, spa: 105, spd: 116, spe: 96},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	rasielmon: {
		num: -2165,
		species: "Rasielmon",
		types: ["Battle", "Holy"],
		gender: "N",
		baseStats: {hp: 216, atk: 105, def: 76, spa: 109, spd: 116, spe: 96},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	rosemon: {
		num: -2166,
		species: "Rosemon",
		types: ["Nature", "Air"],
		gender: "N",
		baseStats: {hp: 195, atk: 102, def: 80, spa: 101, spd: 80, spe: 86},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.019,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	saberleomon: {
		num: -2167,
		species: "SaberLeomon",
		types: ["Battle", "Nature", "Holy"],
		gender: "N",
		baseStats: {hp: 208, atk: 112, def: 80, spa: 111, spd: 80, spe: 88},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	seraphimon: {
		num: -2168,
		species: "Seraphimon",
		types: ["Holy", "Air"],
		gender: "N",
		baseStats: {hp: 211, atk: 110, def: 71, spa: 122, spd: 93, spe: 94},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	venommyotismon: {
		num: -2169,
		species: "VenomMyotismon",
		types: ["Evil", "Air"],
		gender: "N",
		baseStats: {hp: 217, atk: 120, def: 105, spa: 92, spd: 94, spe: 80},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.038,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	vikemon: {
		num: -2170,
		species: "Vikemon",
		types: ["Aqua", "Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 221, atk: 114, def: 98, spa: 103, spd: 89, spe: 78},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	wargreymon: {
		num: -2171,
		species: "WarGreymon",
		types: ["Flame", "Battle", "Mech"],
		gender: "N",
		baseStats: {hp: 214, atk: 114, def: 98, spa: 86, spd: 87, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
};
