'use strict';

const RandomTeams = require('../../data/random-teams');

class RandomDigimonTeams extends RandomTeams {
	randomDigimonTeam() {
		let team = [];
		let sets = {
			//Fresh//
			"Botamon": {
				species: "Botamon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Dodomon": {
				species: "Dodomon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Kuramon": {
				species: "Kuramon",
				ability: "Virus",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Poyomon": {
				species: "Poyomon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Punimon": {
				species: "Punimon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Yuramon": {
				species: "Yuramon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			//In-Traning//
			"Bukamon": {
				species: "Bukamon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Dorimon": {
				species: "Dorimon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Koromon": {
				species: "Koromon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Motimon": {
				species: "Motimon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Nyaromon": {
				species: "Nyaromon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Tanemon": {
				species: "Tanemon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Tokomon": {
				species: "Tokomon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Tsumemon": {
				species: "Tsumemon",
				ability: "Virus",
				rarity: 3,
				moves: ['acidbubble'],
			},
			"Tsunomon": {
				species: "Tsunomon",
				ability: "Data",
				rarity: 3,
				moves: ['acidbubble'],
			},
			//Rookies//
			"Agumon": {
				species: "Agumon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['burningheart', 'heatbreath', 'firetower', 'infinityburn', 'musclecharge', 'sonicjab', 'windcutter'],
				baseSignatureMove: "pepperbreath",
				signatureMove: "Pepper Breath",
			},
			"Aruramon": {
				species: "Aruramon",
				ability: "Virus",
				rarity: 2,
				moves: ['charmperfume', 'rootbind', 'venomdisaster', 'waterblitz', 'superstinkyjet', 'shadowfall', 'blackout'],
				baseSignatureMove: "nemesisivy",
				signatureMove: "Nemesis Ivy",
			},
			"Betamon": {
				species: "Betamon",
				ability: "Virus",
				rarity: 2,
				moves: ['staticelectricity', 'electriccloud', 'megalospark', 'hailspear', 'waterblitz', 'oceanwave'],
				baseSignatureMove: "electricshock",
				signatureMove: "Electric Shock",
			},
			"Biyomon": {
				species: "Biyomon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['wingshoes', 'windcutter', 'burningheart', 'heatbreath', 'firetower', 'meltdown', 'warcry', 'holyflash', 'rootbind'],
				baseSignatureMove: "spiraltwister",
				signatureMove: "Spiral Twister",
			},
			"ClearAgumon": {
				species: "ClearAgumon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['heatbreath', 'saintshield', 'saintray', 'holyflash', 'mechanicalclaw', 'upgrade', 'gigawattlaser'],
				baseSignatureMove: "preciousflame",
				signatureMove: "Precious Flame",
			},
			"DemiDevimon": {
				species: "DemiDevimon",
				ability: "Virus",
				rarity: 2,
				moves: ['blackout', 'evilfantasy', 'shadowfall', 'hideandseek', 'windcutter', 'confusedstorm', 'cootieskick'],
				baseSignatureMove: "demidart",
				signatureMove: "Demi Dart",
			},
			"Dokunemon": {
				species: "Dokunemon",
				ability: "Virus",
				rarity: 2,
				moves: ['staticelectricity', 'shadowfall', 'earthcoat', 'massmorph', 'bug', 'venomdisaster', 'blackout'],
				baseSignatureMove: "wormvenom",
				signatureMove: "Worm Venom",
			},
			"Dorumon": {
				species: "Dorumon",
				ability: "Data",
				rarity: 2,
				moves: ['burningheart', 'megalospark', 'musclecharge', 'sonicjab', 'fightingaura', 'busterdrive', 'mechanicalclaw', 'antiattackfield'],
				baseSignatureMove: "metalcannon",
				signatureMove: "Metal Cannon",
			},
			"Elecmon": {
				species: "Elecmon",
				ability: "Data",
				rarity: 2,
				moves: ['staticelectricity', 'electriccloud', 'megalospark', 'thunderjustice', 'saintheal', 'warcry', 'fightingaura'],
				baseSignatureMove: "superthunderstrike",
				signatureMove: "Super Thunder Strike",
			},
			"Gabumon": {
				species: "Gabumon",
				ability: "Data",
				rarity: 2,
				moves: ['heatbreath', 'firetower', 'hailspear', 'winterblast', 'gigafreeze', 'icestatue', 'musclecharge', 'sonicjab'],
				baseSignatureMove: "blueblaster",
				signatureMove: "Blue Blaster",
			},
			"Goburimon": {
				species: "Goburimon",
				ability: "Virus",
				rarity: 2,
				moves: ['heatbreath', 'firetower', 'infinityburn', 'musclecharge', 'burningheart', 'reboundstrike', 'megatonpunch', 'shadowfall', 'pooptoss'],
				baseSignatureMove: "goblinstrike",
				signatureMove: "Goblin Strike",
			},
			"Gomamon": {
				species: "Gomamon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['mechanicalclaw', 'waterblitz', 'oceanwave', 'icestatue', 'aurorafreeze', 'warcry', 'reboundstrike'],
				baseSignatureMove: "marchingfishes",
				signatureMove: "Marching Fishes",
			},
			"Gotsumon": {
				species: "Gotsumon",
				ability: "Data",
				rarity: 2,
				moves: ['earthcoat', 'rockfall', 'charmperfume', 'venomdisaster', 'bug', 'megatonpunch', 'fightingaura'],
				baseSignatureMove: "rockfist",
				signatureMove: "Rock Fist",
			},
			"Kunemon": {
				species: "Kunemon",
				ability: "Virus",
				rarity: 2,
				moves: ['staticelectricity', 'megalospark', 'earthcoat', 'massmorph', 'bug', 'venomdisaster', 'superstinkyjet'],
				baseSignatureMove: "electricthread",
				signatureMove: "Electric Thread",
			},
			"ModokiBetamon": {
				species: "ModokiBetamon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['staticelectricity', 'electriccloud', 'confusedstorm', 'hailspear', 'icestatue', 'rootbind', 'waterblitz'],
				baseSignatureMove: "aquatower",
				signatureMove: "Aqua Tower",
			},
			"Muchomon": {
				species: "Muchomon",
				ability: "Data",
				rarity: 2,
				moves: ['burningheart', 'hailspear', 'waterblitz', 'icestatue', 'windcutter', 'infinityburn', 'firewall'],
				baseSignatureMove: "tropicalbeak",
				signatureMove: "Tropical Beak",
			},
			"Otamamon": {
				species: "Otamamon",
				ability: "Data",
				rarity: 2,
				moves: ['hailspear', 'waterblitz', 'oceanwave', 'icestatue', 'bug', 'charmperfume', 'warcry'],
				baseSignatureMove: "lullabybubble",
				signatureMove: "Lullaby Bubble",
			},
			"Palmon": {
				species: "Palmon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['charmperfume', 'rootbind', 'venomdisaster', 'waterblitz', 'superstinkyjet', 'burningheart', 'confusedstorm'],
				baseSignatureMove: "poisonivy",
				signatureMove: "Poison Ivy",
			},
			"Patamon": {
				species: "Patamon",
				ability: "Data",
				rarity: 2,
				moves: ['wingshoes', 'windcutter', 'sonicjab', 'busterdrive', 'saintheal', 'holybreath', 'holyflash'],
				baseSignatureMove: "boombubble",
				signatureMove: "Boom Bubble",
			},
			"Penguinmon": {
				species: "Penguinmon",
				ability: "Data",
				rarity: 2,
				moves: ['musclecharge', 'hailspear', 'waterblitz', 'icestatue', 'windcutter', 'megalospark', 'earthcoat'],
				baseSignatureMove: "eternalslapping",
				signatureMove: "Eternal Slapping",
			},
			"Psychemon": {
				species: "Psychemon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['heatbreath', 'firetower', 'staticelectricity', 'winterblast', 'confusedstorm', 'icestatue', 'musclecharge', 'sonicjab'],
				baseSignatureMove: "coloredsparkle",
				signatureMove: "Colored Sparkle",
			},
			"Salamon": {
				species: "Salamon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['saintheal', 'holybreath', 'holyflash', 'saintray', 'warcry', 'antiattackfield', 'fightingaura'],
				baseSignatureMove: "puppyhowl",
				signatureMove: "Puppy Howl",
			},
			"Shamamon": {
				species: "Shamamon",
				ability: "Virus",
				rarity: 2,
				moves: ['charmperfume', 'rootbind', 'rockfall', 'musclecharge', 'warcry', 'reboundstrike', 'megatonpunch', 'shadowfall', 'pooptoss'],
				baseSignatureMove: "dancingbone",
				signatureMove: "Dancing Bone",
			},
			"SnowAgumon": {
				species: "SnowAgumon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['burningheart', 'hailspear', 'winterblast', 'icestatue', 'musclecharge', 'sonicjab', 'windcutter'],
				baseSignatureMove: "littleblizzard",
				signatureMove: "Little Blizzard",
			},
			"SnowGoburimon": {
				species: "SnowGoburimon",
				ability: "Virus",
				rarity: 2,
				moves: ['hailspear', 'winterblast', 'icestatue', 'musclecharge', 'warcry', 'reboundstrike', 'megatonpunch', 'shadowfall', 'pooptoss'],
				baseSignatureMove: "snowgobbolt",
				signatureMove: "SnowGob Bolt",
			},
			"Tentomon": {
				species: "Tentomon",
				ability: "Data",
				rarity: 2,
				moves: ['staticelectricity', 'confusedstorm', 'electriccloud', 'megalospark', 'massmorph', 'bug', 'rockfall', 'fightingaura'],
				baseSignatureMove: "supershocker",
				signatureMove: "Super Shocker",
			},
			"ToyAgumon": {
				species: "ToyAgumon",
				ability: "Data",
				rarity: 2,
				moves: ['heatbreath', 'firewall', 'prominencebeam', 'sonicjab', 'mechanicalclaw', 'upgrade', 'gigawattlaser'],
				baseSignatureMove: "plasticblaze",
				signatureMove: "Plastic Blaze",
			},
			"Tsukaimon": {
				species: "Tsukaimon",
				ability: "Virus",
				rarity: 2,
				moves: ['wingshoes', 'windcutter', 'sonicjab', 'darkspirit', 'blackout', 'evilfantasy', 'chaoscloud'],
				baseSignatureMove: "evilspell",
				signatureMove: "Evil Spell",
			},
			//Champions//
			"Airdramon": {
				species: "Airdramon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['heatbreath', 'firetower', 'meltdown', 'infinityburn', 'wingshoes', 'windcutter', 'confusedstorm', 'holybreath'],
				baseSignatureMove: "spinningneedle",
				signatureMove: "Spinning Needle",
			},
			"Akatorimon": {
				species: "Akatorimon",
				ability: "Data",
				rarity: 1,
				moves: ['heatbreath', 'firewall', 'wingshoes', 'windcutter', 'megalospark', 'icestatue', 'guerrillapoop'],
				baseSignatureMove: "scarredeye",
				signatureMove: "Scar-Red Eye",
			},
			"Angemon": {
				species: "Angemon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['wingshoes', 'windcutter', 'sonicjab', 'busterdrive', 'saintheal', 'holybreath', 'holyflash', 'saintray', 'holyjudgment'],
				baseSignatureMove: "handoffate",
				signatureMove: "Hand of Fate",
			},
			"Bakemon": {
				species: "Bakemon",
				ability: "Virus",
				rarity: 1,
				moves: ['darkspirit', 'blackout', 'evilfantasy', 'shadowfall', 'massmorph', 'icestatue', 'staticelectricity', 'electriccloud', 'thunderjustice'],
				baseSignatureMove: "evilcharm",
				signatureMove: "Evil Charm",
			},
			"Birdramon": {
				species: "Birdramon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['wingshoes', 'windcutter', 'burningheart', 'heatbreath', 'firetower', 'meltdown', 'infinityburn', 'warcry', 'holyflash'],
				baseSignatureMove: "meteorwing",
				signatureMove: "Meteor Wing",
			},
			"BlackGatomon": {
				species: "BlackGatomon",
				ability: "Virus",
				rarity: 1,
				moves: ['warcry', 'sonicjab', 'fightingaura', 'evilsquall', 'evilfantasy', 'hideandseek', 'gigafreeze'],
				baseSignatureMove: "darkpaw",
				signatureMove: "Dark Paw",
			},
			"Centarumon": {
				species: "Centarumon",
				ability: "Data",
				rarity: 1,
				moves: ['firetower', 'firewall', 'prominencebeam', 'saintheal', 'saintray', 'fightingaura', 'upgrade', 'gigawattlaser'],
				baseSignatureMove: "solarray",
				signatureMove: "Solar Ray",
			},
			"Coelamon": {
				species: "Coelamon",
				ability: "Data",
				rarity: 1,
				moves: ['waterblitz', 'icestatue', 'mechanicalclaw', 'upgrade', 'antiattackfield', 'massmorph', 'staticelectricity', 'deleteprogram'],
				baseSignatureMove: "variabledarts",
				signatureMove: "Variable Darts",
			},
			"Darkrizamon": {
				species: "Darkrizamon",
				ability: "Virus",
				rarity: 1,
				moves: ['heatbreath', 'firetower', 'firewall', 'meltdown', 'darkspirit', 'evilfantasy', 'shadowfall', 'mechanicalclaw'],
				baseSignatureMove: "dreadfire",
				signatureMove: "Dread Fire",
			},
			"Devimon": {
				species: "Devimon",
				ability: "Virus",
				rarity: 1,
				moves: ['darkspirit', 'windcutter', 'evilfantasy', 'chaoscloud', 'aurorafreeze', 'evilsquall', 'confusedstorm', 'wingshoes'],
				baseSignatureMove: "deathhand",
				signatureMove: "Death Hand",
			},
			"Dolphmon": {
				species: "Dolphmon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['waterblitz', 'gigafreeze', 'oceanwave', 'icestatue', 'warcry', 'sonicjab', 'fightingaura', 'holybreath', 'saintheal'],
				baseSignatureMove: "pulseblast",
				signatureMove: "Pulse Blast",
			},
			"Dorugamon": {
				species: "Dorugamon",
				ability: "Data",
				rarity: 1,
				moves: ['burningheart', 'winterblast', 'megalospark', 'musclecharge', 'sonicjab', 'fightingaura', 'busterdrive', 'mechanicalclaw', 'antiattackfield'],
				baseSignatureMove: "powermetal",
				signatureMove: "Power Metal",
			},
			"Drimogemon": {
				species: "Drimogemon",
				ability: "Data",
				rarity: 1,
				moves: ['mechanicalclaw', 'deleteprogram', 'earthcoat', 'massmorph', 'rootbind', 'rockfall'],
				baseSignatureMove: "drillspin",
				signatureMove: "Drill Spin",
			},
			"Flarerizamon": {
				species: "Flarerizamon",
				ability: "Data",
				rarity: 1,
				moves: ['heatbreath', 'firetower', 'firewall', 'meltdown', 'sonicjab', 'warcry', 'megatonpunch', 'mechanicalclaw'],
				baseSignatureMove: "blazebuster",
				signatureMove: "Blaze Buster",
			},
			"Frigimon": {
				species: "Frigimon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['hailspear', 'icestatue', 'aurorafreeze', 'waterblitz', 'sonicjab', 'musclecharge', 'fightingaura'],
				baseSignatureMove: "subzeroicepunch",
				signatureMove: "Sub Zero Ice Punch",
			},
			"Fugamon": {
				species: "Fugamon",
				ability: "Virus",
				rarity: 1,
				moves: ['staticelectricity', 'windcutter', 'megalospark', 'blackout', 'musclecharge', 'warcry', 'reboundstrike', 'megatonpunch'],
				baseSignatureMove: "subzeroicepunch",
				signatureMove: "Sub Zero Ice Punch",
			},
			"Garurumon": {
				species: "Garurumon",
				ability: "Data",
				rarity: 1,
				moves: ['warcry', 'waterblitz', 'fightingaura', 'burningheart', 'heatbreath', 'gigafreeze', 'hailspear', 'meltdown', 'aurorafreeze'],
				baseSignatureMove: "howlingblaster",
				signatureMove: "Howling Blaster",
			},
			"Gatomon": {
				species: "Gatomon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['holybreath', 'sonicjab', 'fightingaura', 'saintray', 'saintheal', 'holyflash', 'confusedstorm'],
				baseSignatureMove: "lightningpaw",
				signatureMove: "Lightning Paw",
			},
			"Gekomon": {
				species: "Gekomon",
				ability: "Data",
				rarity: 1,
				moves: ['hailspear', 'confusedstorm', 'oceanwave', 'icestatue', 'gigafreeze', 'warcry', 'charmperfume'],
				baseSignatureMove: "symphonycrusher",
				signatureMove: "Symphony Crusher",
			},
			"Geremon": {
				species: "Geremon",
				ability: "Virus",
				rarity: 1,
				moves: ['gigafreeze', 'earthcoat', 'bug', 'venomdisaster', 'warcry', 'superstinkyjet', 'poopattackfield', 'guerrillapoop', 'extremepoopdeath'],
				baseSignatureMove: "hypersmell",
				signatureMove: "Hyper Smell",
			},
			"Greymon": {
				species: "Greymon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['burningheart', 'heatbreath', 'firetower', 'infinityburn', 'musclecharge', 'sonicjab', 'megalospark'],
				baseSignatureMove: "megaflame",
				signatureMove: "Mega Flame",
			},
			"Guardromon": {
				species: "Guardromon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['upgrade', 'reverseprogram', 'antiattackfield', 'gigawattlaser', 'megalospark', 'saintshield', 'firetower', 'firewall', 'thunderjustice'],
				baseSignatureMove: "guardianbarrage",
				signatureMove: "Guardian Barrage",
			},
			"Gururumon": {
				species: "Gururumon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['warcry', 'waterblitz', 'fightingaura', 'burningheart', 'blackout', 'gigafreeze', 'darkspirit', 'evilfantasy', 'aurorafreeze'],
				baseSignatureMove: "chaosblaster",
				signatureMove: "Chaos Blaster",
			},
			"Hyogamon": {
				species: "Hyogamon",
				ability: "Virus",
				rarity: 1,
				moves: ['hailspear', 'winterblast', 'icestatue', 'blackout', 'musclecharge', 'warcry', 'reboundstrike', 'megatonpunch'],
				baseSignatureMove: "snowpunch",
				signatureMove: "snowpunch",
			},
			"IceDevimon": {
				species: "IceDevimon",
				ability: "Virus",
				rarity: 1,
				moves: ['darkspirit', 'blackout', 'evilfantasy', 'chaoscloud', 'shadowfall', 'evilsquall', 'winterblast', 'gigafreeze'],
				baseSignatureMove: "frozenclaw",
				signatureMove: "Frozen Claw",
			},
			"Icemon": {
				species: "Icemon",
				ability: "Data",
				rarity: 1,
				moves: ['earthcoat', 'rockfall', 'hailspear', 'aurorafreeze', 'gigafreeze', 'megatonpunch', 'fightingaura'],
				baseSignatureMove: "iceballbomb",
				signatureMove: "Iceball Bomb",
			},
			"Ikkakumon": {
				species: "Ikkakumon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['hailspear', 'oceanwave', 'icestatue', 'aurorafreeze', 'mechanicalclaw', 'warcry', 'reboundstrike'],
				baseSignatureMove: "harpoontorpedo",
				signatureMove: "Harpoon Torpedo",
			},
			"JungleMojyamon": {
				species: "JungleMojyamon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['earthcoat', 'rootbind', 'warcry', 'musclecharge', 'sonicjab', 'fightingaura', 'superstinkyjet', 'poopfling'],
				baseSignatureMove: "junglebone",
				signatureMove: "Jungle Bone",
			},
			"Kabuterimon": {
				species: "Kabuterimon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['confusedstorm', 'electriccloud', 'megalospark', 'thunderjustice', 'massmorph', 'bug', 'rockfall', 'fightingaura'],
				baseSignatureMove: "electroshocker",
				signatureMove: "Electro Shocker",
			},
			"Kokatorimon": {
				species: "Kokatorimon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['wingshoes', 'windcutter', 'megalospark', 'icestatue', 'cootieskick', 'pooptoss', 'guerrillapoop'],
				baseSignatureMove: "frozenfireshot",
				signatureMove: "Frozen Fire Shot",
			},
			"Kuwagamon": {
				species: "Kuwagamon",
				ability: "Virus",
				rarity: 1,
				moves: ['sonicjab', 'busterdrive', 'massmorph', 'bug', 'venomdisaster', 'windcutter', 'blackout'],
				baseSignatureMove: "scissorclaw",
				signatureMove: "Scissor Claw",
			},
			"Leomon": {
				species: "Leomon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['musclecharge', 'warcry', 'sonicjab', 'meltdown', 'infinityburn', 'megatonpunch', 'earthcoat', 'saintshield', 'burningheart'],
				baseSignatureMove: "fistofthebeastking",
				signatureMove: "Fist of the Beast King",
			},
			"Meicoomon": {
				species: "Meicoomon",
				ability: "Data",
				rarity: 1,
				moves: ['warcry', 'windcutter', 'fightingaura', 'megatonpunch', 'mechanicalclaw', 'venomdisaster', 'shadowfall', 'saintray'],
				baseSignatureMove: "xscratch",
				signatureMove: "X Scratch",
			},
			"Meramon": {
				species: "Meramon",
				ability: "Data",
				rarity: 1,
				moves: ['burningheart', 'firewall', 'firetower', 'infinityburn', 'holyflash', 'fightingaura', 'sonicjab', 'megatonpunch'],
				baseSignatureMove: "burningfist",
				signatureMove: "Burning Fist",
			},
			"Mikemon": {
				species: "Mikemon",
				ability: "Data",
				rarity: 1,
				moves: ['warcry', 'sonicjab', 'fightingaura', 'venomdisaster', 'evilfantasy', 'holyflash', 'bug'],
				baseSignatureMove: "catclaw",
				signatureMove: "Cat Claw",
			},
			"Mojyamon": {
				species: "Mojyamon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['warcry', 'musclecharge', 'sonicjab', 'fightingaura', 'hailspear', 'winterblast', 'superstinkyjet', 'poopfling'],
				baseSignatureMove: "boneboomerang",
				signatureMove: "Bone Boomerang",
			},
			"Monochromon": {
				species: "Monochromon",
				ability: "Data",
				rarity: 1,
				moves: ['heatbreath', 'firetower', 'infinityburn', 'earthcoat', 'rockfall', 'musclecharge', 'busterdrive'],
				baseSignatureMove: "volcanicstrike",
				signatureMove: "Volcanic Strike",
			},
			"MoriShellmon": {
				species: "MoriShellmon",
				ability: "Data",
				rarity: 1,
				moves: ['waterblitz', 'oceanwave', 'earthcoat', 'charmperfume', 'rootbind', 'venomdisaster', 'sonicjab'],
				baseSignatureMove: "mindfog",
				signatureMove: "Mind Fog",
			},
			"MudFrigimon": {
				species: "MudFrigimon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['rootbind', 'bug', 'rockfall', 'massmorph', 'sonicjab', 'earthcoat', 'fightingaura'],
				baseSignatureMove: "mudball",
				signatureMove: "Mud Ball",
			},
			"Nanimon": {
				species: "Nanimon",
				ability: "Virus",
				rarity: 1,
				moves: ['musclecharge', 'sonicjab', 'fightingaura', 'pooptoss', 'poopattackfield', 'superstinkyjet', 'evilfantasy', 'blackout'],
				baseSignatureMove: "poopdunk",
				signatureMove: "Poop Dunk",
			},
			"Ninjamon": {
				species: "Ninjamon",
				ability: "Data",
				rarity: 1,
				moves: ['warcry', 'sonicjab', 'musclecharge', 'charmperfume', 'rootbind', 'earthcoat', 'reboundstrike'],
				baseSignatureMove: "dancingleaves",
				signatureMove: "Dancing Leaves",
			},
			"NiseDrimogemon": {
				species: "NiseDrimogemon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['warcry', 'sonicjab', 'busterdrive', 'reboundstrike', 'mechanicalclaw', 'upgrade', 'deleteprogram', 'reverseprogram'],
				baseSignatureMove: "fakedrillspin",
				signatureMove: "Fake Drill Spin",
			},
			"Numemon": {
				species: "Numemon",
				ability: "Virus",
				rarity: 1,
				moves: ['oceanwave', 'earthcoat', 'bug', 'icestatue', 'warcry', 'cootieskick', 'pooptoss', 'guerrillapoop', 'extremepoopdeath'],
				baseSignatureMove: "numesludge",
				signatureMove: "Nume-Sludge",
			},
			"Ogremon": {
				species: "Ogremon",
				ability: "Virus",
				rarity: 1,
				moves: ['firetower', 'infinityburn', 'heatbreath', 'blackout', 'musclecharge', 'warcry', 'reboundstrike', 'megatonpunch'],
				baseSignatureMove: "pummelwhack",
				signatureMove: "Pummel Whack",
			},
			"Piddomon": {
				species: "Piddomon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['burningheart', 'firewall', 'infinityburn', 'holybreath', 'windcutter', 'sonicjab', 'saintheal', 'saintray', 'holyjudgment'],
				baseSignatureMove: "firefeather",
				signatureMove: "Fire Feather",
			},
			"PlatinumSukamon": {
				species: "PlatinumSukamon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['earthcoat', 'rockfall', 'holyflash', 'mechanicalclaw', 'reverseprogram', 'deleteprogram', 'cootieskick', 'superstinkyjet', 'guerrillapoop', 'extremepoopdeath'],
				baseSignatureMove: "raremetalpoop",
				signatureMove: "Rare Metal Poop",
			},
			"RedVegiemon": {
				species: "RedVegiemon",
				ability: "Virus",
				rarity: 1,
				moves: ['heatbreath', 'meltdown', 'prominencebeam', 'massmorph', 'charmeperfume', 'venomdisaster', 'earthcoat'],
				baseSignatureMove: "chilipepperpummel",
				signatureMove: "Chili Pepper Pummel",
			},
			"Rockmon": {
				species: "Rockmon",
				ability: "Virus",
				rarity: 1,
				moves: ['mechanicalclaw', 'winterblast', 'gigafreeze', 'gigawattlaser', 'dgdimension', 'upgrade', 'sonicjab'],
				baseSignatureMove: "antidigibeam",
				signatureMove: "Anti-Digi Beam",
			},
			"Saberdramon": {
				species: "Saberdramon",
				ability: "Virus",
				rarity: 1,
				moves: ['wingshoes', 'windcutter', 'burningheart', 'blackout', 'firetower', 'shadowfall', 'infinityburn', 'evilfantasy'],
				baseSignatureMove: "nightroar",
				signatureMove: "Night Roar",
			},
			"SandYanmamon": {
				species: "SandYanmamon",
				ability: "Virus",
				rarity: 1,
				moves: ['electriccloud', 'windcutter', 'confusedstorm', 'thunderjustice', 'earthcoat', 'massmorph', 'charmperfume', 'bug', 'holyflash'],
				baseSignatureMove: "stunray",
				signatureMove: "Stun Ray",
			},
			"Seadramon": {
				species: "Seadramon",
				ability: "Data",
				rarity: 1,
				moves: ['hailspear', 'waterblitz', 'gigafreeze', 'aurorafreeze', 'heatbreath', 'meltdown', 'holybreath'],
				baseSignatureMove: "iceblast",
				signatureMove: "Ice Blast",
			},
			"Shellmon": {
				species: "Shellmon",
				ability: "Data",
				rarity: 1,
				moves: ['waterblitz', 'winterblast', 'oceanwave', 'aurorafreeze', 'massmorph', 'rockfall', 'sonicjab'],
				baseSignatureMove: "hydropressure",
				signatureMove: "Hydro Pressure",
			},
			"ShimaUnimon": {
				species: "ShimaUnimon",
				ability: "Data",
				rarity: 1,
				moves: ['holybreath', 'electriccloud', 'confusedstorm', 'saintheal', 'holyflash', 'saintray', 'warcry', 'fightingaura', 'sonicjab', 'busterdrive'],
				baseSignatureMove: "lustershot",
				signatureMove: "Luster Shot",
			},
			"Soulmon": {
				species: "Soulmon",
				ability: "Virus",
				rarity: 1,
				moves: ['darkspirit', 'blackout', 'evilfantasy', 'shadowfall', 'massmorph', 'staticelectricity', 'electriccloud', 'aurorafreeze'],
				baseSignatureMove: "necromagic",
				signatureMove: "Necro Magic",
			},
			"Sukamon": {
				species: "Sukamon",
				ability: "Virus",
				rarity: 1,
				moves: ['earthcoat', 'bug', 'rockfall', 'warcry', 'cootieskick', 'superstinkyjet', 'guerrillapoop', 'extremepoopdeath', 'hideandseek'],
				baseSignatureMove: "poop",
				signatureMove: "Poop",
			},
			"Tankmon": {
				species: "Tankmon",
				ability: "Data",
				rarity: 1,
				moves: ['burningheart', 'heatbreath', 'infinityburn', 'prominencebeam', 'earthcoat', 'antiattackfield', 'gigawattlaser', 'deleteprogram', 'upgrade'],
				baseSignatureMove: "hypercannon",
				signatureMove: "Hyper Cannon",
			},
			"Togemon": {
				species: "Togemon",
				ability: "Data",
				rarity: 1,
				moves: ['massmorph', 'charmperfume', 'rootbind', 'venomdisaster', 'waterblitz', 'musclecharge', 'sonicjab', 'fightingaura', 'megatonpunch'],
				baseSignatureMove: "needlespray",
				signatureMove: "Needle Spray",
			},
			"Tyrannomon": {
				species: "Tyrannomon",
				ability: "Data",
				rarity: 1,
				moves: ['burningheart', 'heatbreath', 'firetower', 'prominencebeam', 'musclechage', 'sonicjab', 'reboundstrike', 'rockfall'],
				baseSignatureMove: "blazeblaster",
				signatureMove: "Blaze Blaster",
			},
			"Unimon": {
				species: "Unimon",
				ability: "Vaccine",
				rarity: 1,
				moves: ['wingshoes', 'megalospark', 'thunderjustice', 'confusedstorm', 'rockfall', 'saintheal', 'holyjudgement', 'saintray', 'musclecharge'],
				baseSignatureMove: "aerialattack",
				signatureMove: "Aerial Attack",
			},
			"Vegiemon": {
				species: "Vegiemon",
				ability: "Virus",
				rarity: 1,
				moves: ['waterblitz', 'gigafreeze', 'oceanwave', 'massmorph', 'charmperfume', 'venomdisaster', 'earthcoat'],
				baseSignatureMove: "sweetbreath",
				signatureMove: "Sweet Breath",
			},
			"Weedmon": {
				species: "Weedmon",
				ability: "Virus",
				rarity: 1,
				moves: ['superstinkyjet', 'poopattackfield', 'extremepoopdeath', 'massmorph', 'charmeperfume', 'venomdisaster', 'earthcoat'],
				baseSignatureMove: "deadlyweed",
				signatureMove: "Deadly Weed",
			},
			"Yanmamon": {
				species: "Yanmamon",
				ability: "Virus",
				rarity: 1,
				moves: ['electriccloud', 'windcutter', 'confusedstorm', 'thunderjustice', 'earthcoat', 'massmorph', 'charmperfume', 'bug', 'holyflash'],
				baseSignatureMove: "thunderray",
				signatureMove: "Thunder Ray",
			},
			//Ultimates//
			"Andromon": {
				species: "Andromon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['windcutter', 'electriccloud', 'megalospark', 'thunderjustice', 'upgrade', 'antiattackfield', 'deleteprogram', 'gigawattlaser', 'bug'],
				baseSignatureMove: "spiralsword",
				signatureMove: "Spiral Sword",
			},
			"Angewomon": {
				species: "Angewomon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['wingshoes', 'windcutter', 'thunderjustice', 'fightingaura', 'electriccloud', 'saintheal', 'holybreath', 'holyflash', 'saintray', 'warcry'],
				baseSignatureMove: "celestialarrow",
				signatureMove: "Celestial Arrow",
			},
			"Beastmon": {
				species: "Beastmon",
				ability: "Virus",
				rarity: 2,
				moves: ['warcry', 'sonicjab', 'megatonpunch', 'venomdisaster', 'shadowfall', 'gigafreeze', 'bug', 'icestatue'],
				baseSignatureMove: "vampirewave",
				signatureMove: "Vampire Wave",
			},
			"BlackWereGarurumon": {
				species: "BlackWereGarurumon",
				ability: "Virus",
				rarity: 2,
				moves: ['warcry', 'musclecharge', 'sonicjab', 'megatonpunch', 'rockfall', 'burningheart', 'heatbreath', 'evilsquall', 'hideandseek', 'winterblast', 'gigafreeze'],
				baseSignatureMove: "fullmoonkick",
				signatureMove: "Full Moon Kick",
			},
			"BlueMeramon": {
				species: "BlueMeramon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['burningheart', 'firewall', 'meltdown', 'infinityburn', 'aurorafreeze', 'holyflash', 'fightingaura', 'gigafreeze'],
				baseSignatureMove: "coldflame",
				signatureMove: "Cold Flame",
			},
			"Digitamamon": {
				species: "DigiTamamon",
				ability: "Data",
				rarity: 2,
				moves: ['hailspear', 'blackout', 'bug', 'shadowfall', 'firetower', 'poopattackfield', 'poopfling', 'upgrade'],
				baseSignatureMove: "nightmaresyndrome",
				signatureMove: "Nightmare Syndrome",
			},
			"DoruGreymon": {
				species: "DoruGreymon",
				ability: "Data",
				rarity: 2,
				moves: ['burningheart', 'infinityburn', 'megalospark', 'musclecharge', 'sonicjab', 'fightingaura', 'busterdrive', 'mechanicalclaw', 'antiattackfield'],
				baseSignatureMove: "metalmeteor",
				signatureMove: "Metal Meteor",
			},
			"Etemon": {
				species: "Etemon",
				ability: "Virus",
				rarity: 2,
				moves: ['earthcoat', 'rockfall', 'sonicjab', 'megatonpunch', 'charmperfume', 'bug', 'guerrillapoop', 'extremepoopdeath'],
				baseSignatureMove: "loveserenade",
				signatureMove: "Love Serenade",
			},
			"Garudamon": {
				species: "Garudamon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['wingshoes', 'windcutter', 'burningheart', 'firetower', 'meltdown', 'infinityburn', 'warcry', 'busterdrive', 'holyflash'],
				baseSignatureMove: "shadowwing",
				signatureMove: "Shadow Wing",
			},
			"Gigadramon": {
				species: "Gigadramon",
				ability: "Data",
				rarity: 2,
				moves: ['upgrade', 'gigawattlaser', 'dgdimension', 'darkspirit', 'hideandseek', 'windcutter', 'electriccloud', 'gigafreeze'],
				baseSignatureMove: "energyshot",
				signatureMove: "Energy Shot",
			},
			"Giromon": {
				species: "Giromon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['upgrade', 'deleteprogram', 'reverseprogram', 'reboundstrike', 'megatonpunch', 'staticelectricity', 'megalospark', 'firewall'],
				baseSignatureMove: "deadlybomb",
				signatureMove: "Deadly Bomb",
			},
			"IceLeomon": {
				species: "IceLeomon",
				ability: "Data",
				rarity: 2,
				moves: ['musclecharge', 'warcry', 'gigafreeze', 'icestatue', 'megatonpunch', 'winterblast', 'aurorafreeze', 'saintshield', 'burningheart'],
				baseSignatureMove: "fistofice",
				signatureMove: "Fist of Ice",
			},
			"LadyDevimon": {
				species: "LadyDevimon",
				ability: "Virus",
				rarity: 2,
				moves: ['wingshoes', 'windcutter', 'evilsquall', 'fightingaura', 'electriccloud', 'evilfantasy', 'charmperfume', 'darkspirit', 'chaoscloud', 'warcry'],
				baseSignatureMove: "darknesswave",
				signatureMove: "Darkness Wave",
			},
			"Lillymon": {
				species: "Lillymon",
				ability: "Data",
				rarity: 2,
				moves: ['earthcoat', 'charmperfume', 'rootbind', 'venomdisaster', 'wingshoes', 'windcutter', 'confusedstorm', 'saintheal', 'holybreath'],
				baseSignatureMove: "flowercannon",
				signatureMove: "Flower Cannon",
			},
			"MagnaAngemon": {
				species: "MagnaAngemon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['saintheal', 'saintshield', 'shiningnova', 'thunderjustice', 'antiattackfield', 'gigawattlaser', 'deleteprogram', 'sonicjab', 'megalospark', 'reboundstrike', 'holyjudgment', 'wingshoes'],
				baseSignatureMove: "gateofdestiny",
				signatureMove: "Gate of Destiny",
			},
			"Mamemon": {
				species: "Mamemon",
				ability: "Data",
				rarity: 2,
				moves: ['musclecharge', 'sonicjab', 'fightingaura', 'reboundstrike', 'antiattackfield', 'upgrade', 'reverseprogram', 'gigawattlaser', 'gigafreeze', 'burningheart'],
				baseSignatureMove: "smilebomber",
				signatureMove: "Smile Bomber",
			},
			"Megadramon": {
				species: "Megadramon",
				ability: "Virus",
				rarity: 2,
				moves: ['mechanicalclaw', 'upgrade', 'deleteprogram', 'blackout', 'shadowfall', 'staticelectricity', 'megalospark', 'firetower'],
				baseSignatureMove: "genocideattack",
				signatureMove: "Genocide Attack",
			},
			"MegaKabuterimon": {
				species: "MegaKabuterimon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['staticelectricity', 'rockfall', 'megatonpunch', 'megalospark', 'reboundstrike', 'earthcoat', 'massmorph', 'bug'],
				baseSignatureMove: "hornbuster",
				signatureMove: "Horn Buster",
			},
			"MegaSeadramon": {
				species: "MegaSeadramon",
				ability: "Data",
				rarity: 2,
				moves: ['hailspear', 'waterblitz', 'gigafreeze', 'aurorafreeze', 'heatbreath', 'meltdown', 'shiningnova', 'staticelectricity', 'megalospark'],
				baseSignatureMove: "lightningjavelin",
				signatureMove: "Lightning Javelin",
			},
			"Meicrackmon": {
				species: "meicrackmon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['warcry', 'windcutter', 'fightingaura', 'megatonpunch', 'mechanicalclaw', 'venomdisaster', 'holyjudgment', 'saintray', 'holybreath'],
				baseSignatureMove: "modestlystun",
				signatureMove: "Modestly Stun",
			},
			"MeicrackmonVM": {
				name: "Meicrackmon",
				species: "meicrackmonvm",
				ability: "Virus",
				rarity: 2,
				moves: ['warcry', 'windcutter', 'fightingaura', 'megatonpunch', 'mechanicalclaw', 'venomdisaster', 'shadowfall', 'evilsquall', 'blackout'],
				baseSignatureMove: "berserkthinking",
				signatureMove: "Berserk Thinking",
			},
			"MetalGreymon": {
				species: "metalgreymon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['burningheart', 'heatbreath', 'firetower', 'infinityburn', 'musclecharge', 'sonicjab', 'reboundstrike', 'busterdrive', 'mechanicalclaw', 'gigawattlaser', 'deleteprogram'],
				baseSignatureMove: "gigadestroyer",
				signatureMove: "Giga Destroyer",
			},
			"MetalGreymonV": {
				name: "MetalGreymon",
				species: "metalgreymonvirus",
				ability: "Virus",
				rarity: 2,
				moves: ['burningheart', 'heatbreath', 'firetower', 'infinityburn', 'musclecharge', 'sonicjab', 'blackout', 'shadowfall', 'mechanicalclaw', 'gigawattlaser', 'deleteprogram'],
				baseSignatureMove: "revengeflame",
				signatureMove: "Revenge Flame",
			},
			"MetalMamemon": {
				species: "MetalMamemon",
				ability: "Data",
				rarity: 2,
				moves: ['musclecharge', 'mechanicalclaw', 'fightingaura', 'reboundstrike', 'deleteprogram', 'upgrade', 'reverseprogram', 'megalospark', 'winterblast', 'burningheart'],
				baseSignatureMove: "energybomb",
				signatureMove: "Energy Bomb",
			},
			"Meteormon": {
				species: "Meteormon",
				ability: "Data",
				rarity: 2,
				moves: ['earthcoat', 'rockfall', 'heatbreath', 'prominencebeam', 'gigafreeze', 'megatonpunch', 'fightingaura'],
				baseSignatureMove: "galacticflare",
				signatureMove: "Galactic Flare",
			},
			"Monzaemon": {
				species: "Monzaemon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['fightingaura', 'poopattackfield', 'reboundstrike', 'megatonpunch', 'saintheal', 'holybreath', 'saintshield', 'saintray', 'charmperfume'],
				baseSignatureMove: "heartattack",
				signatureMove: "Heart Attack",
			},
			"Myotismon": {
				species: "Myotismon",
				ability: "Virus",
				rarity: 2,
				moves: ['darkspirit', 'blackout', 'evilfantasy', 'electriccloud', 'aurorafreeze', 'evilsquall', 'wingshoes', 'confusedstorm', 'venomdisaster', 'reverseprogram'],
				baseSignatureMove: "grislywing",
				signatureMove: "Grisly Wing",
			},
			"Piximon": {
				species: "Piximon",
				ability: "Data",
				rarity: 2,
				moves: ['saintheal', 'holybreath', 'saintshield', 'fightingaura', 'shiningnova', 'wingshoes', 'windcutter', 'electriccloud', 'antiattackfield', 'earthcoat', 'bug'],
				baseSignatureMove: "pitbomb",
				signatureMove: "Pit Bomb",
			},
			"ShogunGekomon": {
				species: "ShogunGekomon",
				ability: "Data",
				rarity: 2,
				moves: ['earthcoat', 'confusedstorm', 'oceanwave', 'icestatue', 'gigafreeze', 'aurorafreeze', 'warcry', 'fightingaura', 'charmperfume'],
				baseSignatureMove: "musicalfist",
				signatureMove: "Musical Fist",
			},
			"SkullGreymon": {
				species: "SkullGreymon",
				ability: "Virus",
				rarity: 2,
				moves: ['blackout', 'shadowfall', 'evilfantasy', 'evilsquall', 'heatbreath', 'firetower', 'infinityburn', 'sonicjab', 'reboundstrike', 'busterdrive', 'mechanicalclaw', 'deleteprogram'],
				baseSignatureMove: "oblivionbird",
				signatureMove: "Oblivion Bird",
			},
			"Tekkamon": {
				species: "Tekkamon",
				ability: "Virus",
				rarity: 2,
				moves: ['upgrade', 'deleteprogram', 'reverseprogram', 'reboundstrike', 'megatonpunch', 'staticelectricity', 'shadowfall', 'firewall'],
				baseSignatureMove: "fragbomb",
				signatureMove: "Frag Bomb",
			},
			"Vademon": {
				species: "Vademon",
				ability: "Virus",
				rarity: 2,
				moves: ['massmorph', 'charmperfume', 'bug', 'rockfall', 'upgrade', 'deleteprogram', 'dgdimension', 'cootieskick'],
				baseSignatureMove: "unidentifiedflyingkiss",
				signatureMove: "Unidentified Flying Kiss",
			},
			"Vermilimon": {
				species: "Vermilimon",
				ability: "Data",
				rarity: 2,
				moves: ['heatbreath', 'firetower', 'infinityburn', 'prominencebeam', 'earthcoat', 'rockfall', 'musclecharge', 'busterdrive'],
				baseSignatureMove: "volcanicstrikes",
				signatureMove: "Volcanic Strike S",
			},
			"WaruMonzaemon": {
				species: "WaruMonzaemon",
				ability: "Virus",
				rarity: 2,
				moves: ['fightingaura', 'poopattackfield', 'reboundstrike', 'megatonpunch', 'darkspirit', 'evilfantasy', 'hideandseek', 'charmperfume'],
				baseSignatureMove: "heartbreakattack",
				signatureMove: "Heartbreak Attack",
			},
			"WaruSeadramon": {
				species: "WaruSeadramon",
				ability: "Virus",
				rarity: 2,
				moves: ['hailspear', 'waterblitz', 'gigafreeze', 'aurorafreeze', 'heatbreath', 'meltdown', 'staticelectricity', 'megalospark', 'evilsquall'],
				baseSignatureMove: "evilicicle",
				signatureMove: "Evil Icicle",
			},
			"WereGarurumon": {
				species: "WereGarurumon",
				ability: "Data",
				rarity: 2,
				moves: ['warcry', 'musclecharge', 'sonicjab', 'megatonpunch', 'rockfall', 'burningheart', 'heatbreath', 'icestatue', 'aurorafreeze', 'winterblast', 'gigafreeze'],
				baseSignatureMove: "wolfclaw",
				signatureMove: "Wolf Claw",
			},
			"Whamon": {
				species: "Whamon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['waterblitz', 'oceanwave', 'icestatue', 'aurorafreeze', 'massmorph', 'charmperfume', 'saintshield', 'confusedstorm', 'busterdrive', 'saintheal'],
				baseSignatureMove: "tidalwave",
				signatureMove: "Tidal Wave",
			},
			"Zudomon": {
				species: "Zudomon",
				ability: "Vaccine",
				rarity: 2,
				moves: ['electriccloud', 'thunderjustice', 'hailspear', 'icestatue', 'mechanicalclaw', 'aurorafreeze', 'antiattackfield', 'warcry', 'reboundstrike'],
				baseSignatureMove: "vulcanshammer",
				signatureMove: "Vulcan's Hammer",
			},
			//Mega//
			"Alphamon": {
				species: "Alphamon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['saintshield', 'saintray', 'holyjudgment', 'shiningnova', 'warcry', 'sonicjab', 'reboundstrike', 'upgrade', 'deleteprogram', 'dgdimension', 'burningheart', 'thunderjustice'],
				baseSignatureMove: "bladeofthedragonking",
				signatureMove: "Blade of the Dragon King",
			},
			"BlackMetalGarurumon": {
				species: "BlackMetalGarurumon",
				ability: "Virus",
				rarity: 3,
				moves: ['warcry', 'mechanicalclaw', 'megalospark', 'winterblast', 'gigafreeze', 'icestatue', 'shadowfall', 'evilfantasy', 'aurorafreeze'],
				baseSignatureMove: "garurutomahawk",
				signatureMove: "Garuru Tomahawk",
			},
			"BlackWarGreymon": {
				species: "BlackWarGreymon",
				ability: "Virus",
				rarity: 3,
				moves: ['burningheart', 'firetower', 'firewall', 'shadowfall', 'musclecharge', 'blackout', 'busterdrive', 'mechanicalclaw', 'antiattackfield', 'deleteprogram', 'evilfantasy'],
				baseSignatureMove: "blacktornado",
				signatureMove: "Black Tornado",
			},
			"Boltmon": {
				species: "Boltmon",
				ability: "Data",
				rarity: 3,
				moves: ['electriccloud', 'megalospark', 'fightingaura', 'megatonpunch', 'mechanicalclaw', 'gigawattlaser', 'meltdown', 'infinityburn'],
				baseSignatureMove: "tomahawkstinger",
				signatureMove: "Tomahawk Stinger",
			},
			"Cherubimon": {
				species: "Cherubimonevil",
				ability: "Virus",
				rarity: 3,
				moves: ['wingshoes', 'thunderjustice', 'megalospark', 'megatonpunch', 'blackout', 'chaoscloud', 'shadowfall', 'evilsquall', 'dgdimension', 'gigawattlaser'],
				baseSignatureMove: "lightningspear",
				signatureMove: "Lightning Spear",
			},
			"CherubimonG": {
				name: "Cherubimon",
				species: "Cherubimongood",
				ability: "Vaccine",
				rarity: 3,
				moves: ['wingshoes', 'thunderjustice', 'megalospark', 'megatonpunch', 'holybreath', 'saintray', 'holyjudgment', 'shiningnova', 'dgdimension', 'gigawattlaser'],
				baseSignatureMove: "heavensjudgment",
				signatureMove: "Heaven's Judgment",
			},
			"Devitamamon": {
				species: "Devitamamon",
				ability: "Data",
				rarity: 3,
				moves: ['hailspear', 'blackout', 'evilfantasy', 'shadowfall', 'evilsquall', 'poopattackfield', 'extremepoopdeath', 'firetower'],
				baseSignatureMove: "blackdeathcloud",
				signatureMove: "Black Death Cloud",
			},
			"Dorugoramon": {
				species: "Dorugoramon",
				ability: "Data",
				rarity: 3,
				moves: ['burningheart', 'infinityburn', 'prominencebeam', 'megalospark', 'thunderjustice', 'fightingaura', 'busterdrive', 'sonicjab', 'mechanicalclaw', 'antiattackfield', 'deleteprogram', 'gigawattlaser'],
				baseSignatureMove: "bravemetal",
				signatureMove: "Brave Metal",
			},
			"Ebemon": {
				species: "Ebemon",
				ability: "Virus",
				rarity: 3,
				moves: ['confusedstorm', 'electriccloud', 'massmorph', 'bug', 'upgrade', 'gigawattlaser', 'dgdimension', 'cootieskick'],
				baseSignatureMove: "brainrupture",
				signatureMove: "Brain Rupture",
			},
			"HerculesKabuterimon": {
				species: "HerculesKabuterimon",
				ability: "Data",
				rarity: 3,
				moves: ['confusedstorm', 'electriccloud', 'megalospark', 'thunderjustice', 'charmperfume', 'massmorph', 'bug', 'saintshield', 'holyflash', 'fightingaura'],
				baseSignatureMove: "gigablaster",
				signatureMove: "Giga Blaster",
			},
			"HiAndromon": {
				species: "HiAndromon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['sonicjab', 'electriccloud', 'megalospark', 'thunderjustice', 'saintheal', 'upgrade', 'antiattackfield', 'deleteprogram', 'gigawattlaser', 'bug', 'busterdrive', 'megatonpunch'],
				baseSignatureMove: "atomicray",
				signatureMove: "Atomic Ray",
			},
			"Lilithmon": {
				species: "Lilithmon",
				ability: "Virus",
				rarity: 3,
				moves: ['evilfantasy', 'chaoscloud', 'shadowfall', 'windcutter', 'confusedstorm', 'charmperfume', 'venomdisaster', 'bug', 'aurorafreeze', 'mechanicalclaw'],
				baseSignatureMove: "phantompain",
				signatureMove: "Phantom Pain",
			},
			"Machinedramon": {
				species: "Machinedramon",
				ability: "Virus",
				rarity: 3,
				moves: ['mechanicalclaw', 'upgrade', 'gigawattlaser', 'dgdimension', 'megalospark', 'thunderjustice', 'electricloud', 'hideandseek', 'firewall', 'gigafreeze'],
				baseSignatureMove: "infinitycannon",
				signatureMove: "Infinity Cannon",
			},
			"Magnadramon": {
				species: "Magnadramon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['saintheal', 'holybreath', 'holyflash', 'holyjudgment', 'burningheart', 'firetower', 'prominencebeam', 'wingshoes', 'busterdrive', 'fightingaura'],
				baseSignatureMove: "firetornado",
				signatureMove: "Fire Tornado",
			},
			"MarineAngemon": {
				species: "MarineAngemon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['waterblitz', 'oceanwave', 'aurorafreeze', 'icestatue', 'saintheal', 'holybreath', 'saintshield', 'shiningnova', 'confusedstorm', 'wingshoes', 'antiattackfield', 'earthcoat'],
				baseSignatureMove: "oceanlove",
				signatureMove: "Ocean Love",
			},
			"MetalEtemon": {
				species: "MetalEtemon",
				ability: "Virus",
				rarity: 3,
				moves: ['reverseprogram', 'dgdimension', 'upgrade', 'gigawattlaser', 'charmperfume', 'holyflash', 'guerrillapoop', 'extremepoopdeath'],
				baseSignatureMove: "darkrecital",
				signatureMove: "Dark Recital",
			},
			"MetalGarurumon": {
				species: "MetalGarurumon",
				ability: "Data",
				rarity: 3,
				moves: ['warcry', 'mechanicalclaw', 'busterdrive', 'winterblast', 'gigafreeze', 'icestatue', 'rockfall', 'meltdown', 'aurorafreeze'],
				baseSignatureMove: "icewolfclaw",
				signatureMove: "Ice Wolf Claw",
			},
			"MetalSeadramon": {
				species: "MetalSeadramon",
				ability: "Data",
				rarity: 3,
				moves: ['waterblitz', 'winterblast', 'oceanwave', 'icestatue', 'infinityburn', 'staticelectricity', 'megalospark', 'upgrade', 'deleteprogram'],
				baseSignatureMove: "riverofpower",
				signatureMove: "River of Power",
			},
			"Ophanimon": {
				species: "Ophanimon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['wingshoes', 'windcutter', 'thunderjustice', 'fightingaura', 'aurorafreeze', 'saintheal', 'holybreath', 'saintshield', 'saintray', 'warcry'],
				baseSignatureMove: "edensjavelin",
				signatureMove: "Eden's Javelin",
			},
			"Phoenixmon": {
				species: "Phoenixmon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['wingshoes', 'windcutter', 'thunderjustice', 'burningheart', 'meltdown', 'prominencebeam', 'warcry', 'busterdrive', 'holyjudgment', 'shiningnova', 'infinityburn'],
				baseSignatureMove: "starlightexplosion",
				signatureMove: "Starlight Explosion",
			},
			"PrinceMamemon": {
				species: "PrinceMamemon",
				ability: "Data",
				rarity: 3,
				moves: ['musclecharge', 'sonicjab', 'megatonpunch', 'fightingaura', 'upgrade', 'reverseprogram', 'deleteprogram', 'dgdimension', 'holyflash', 'poopattackfield'],
				baseSignatureMove: "smilewarhead",
				signatureMove: "Smile Warhead",
			},
			"Raguelmon": {
				species: "Raguelmon",
				ability: "Virus",
				rarity: 3,
				moves: ['warcry', 'windcutter', 'fightingaura', 'megatonpunch', 'mechanicalclaw', 'venomdisaster', 'shadowfall', 'evilsquall', 'blackout', 'deleteprogram'],
				baseSignatureMove: "darknesszone",
				signatureMove: "Darkness Zone",
			},
			"Rasielmon": {
				species: "Rasielmon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['warcry', 'windcutter', 'fightingaura', 'megatonpunch', 'mechanicalclaw', 'venomdisaster', 'holyjudgment', 'saintray', 'holybreath', 'dgdimension'],
				baseSignatureMove: "knowledgestream",
				signatureMove: "Knowledge Stream",
			},
			"Rosemon": {
				species: "Rosemon",
				ability: "Data",
				rarity: 3,
				moves: ['earthcoat', 'charmperfume', 'rootbind', 'venomdisaster', 'wingshoes', 'confusedstorm', 'evilfantasy', 'saintheal', 'shiningnova'],
				baseSignatureMove: "thornwhip",
				signatureMove: "Thorn Whip",
			},
			"SaberLeomon": {
				species: "SaberLeomon",
				ability: "Data",
				rarity: 3,
				moves: ['musclecharge', 'warcry', 'fightingaura', 'busterdrive', 'earthcoat', 'venomdisaster', 'saintshield', 'holyjudgment', 'mechanicalclaw', 'burningheart', 'infinityburn', 'shiningnova'],
				baseSignatureMove: "howlingcrusher",
				signatureMove: "Howling Crusher",
			},
			"Seraphimon": {
				species: "Seraphimon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['saintheal', 'saintshield', 'shiningnova', 'thunderjustice', 'antiattackfield', 'gigawattlaser', 'deleteprogram', 'sonicjab', 'megalospark', 'reboundstrike', 'holyjudgment', 'wingshoes'],
				baseSignatureMove: "strikeofthesevenstars",
				signatureMove: "Strike of the Seven Stars",
			},
			"VenomMyotismon": {
				species: "VenomMyotismon",
				ability: "Virus",
				rarity: 3,
				moves: ['darkspirit', 'blackout', 'evilfantasy', 'megalospark', 'icestatue', 'shadowfall', 'wingshoes', 'staticelectricity', 'venomdisaster', 'deleteprogram'],
				baseSignatureMove: "venominfusion",
				signatureMove: "Venom Infusion",
			},
			"Vikemon": {
				species: "Vikemon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['hailspear', 'winterblast', 'icestatue', 'aurorafreeze', 'mechanicalclaw', 'antiattackfield', 'warcry', 'reboundstrike', 'megatonpunch', 'holyflash'],
				baseSignatureMove: "arcticblizzard",
				signatureMove: "Arctic Blizzard",
			},
			"WarGreymon": {
				species: "WarGreymon",
				ability: "Vaccine",
				rarity: 3,
				moves: ['burningheart', 'firetower', 'firewall', 'infinityburn', 'musclecharge', 'sonicjab', 'busterdrive', 'mechanicalclaw', 'antiattackfield', 'deleteprogram', 'fightingaura'],
				baseSignatureMove: "terraforce",
				signatureMove: "Terra Force",
			},
		};
		//Generate the team randomly.
		let pool = Object.keys(sets);
		let weakmonclause = false;
		for (let i = 0; i < 6; i++) {
			let name = this.sampleNoReplace(pool);
			let set = sets[name];
			if (!(this.random(set.rarity) === 0)) {
				// Skip this digimon
				i--;
				continue;
			}
			if (set.moves.includes('bubble')) {
				if (weakmonclause === true) {
					// Skip this digimon
					i--;
					continue;
				} else {
					weakmonclause = true;
				}
			}
			set.level = 100;
			if (!set.name) set.name = name;
			set.nature = "Serious";
			set.moves = [this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves), this.sampleNoReplace(set.moves), 'Protect', set.signatureMove];
			team.push(set);
		}
		return team;
	}
}

module.exports = RandomDigimonTeams;
