// @pokebedrock - This file is AUTO-GENERATED by `tools/build-utils.js`.

export const DexMods: string[] = [
	'blankcanvas', 'chatbats', 'fullpotential', 'gen1', 'gen1jpn', 'gen1stadium', 'gen2',
	'gen2stadium2', 'gen3', 'gen3colosseum', 'gen3rs', 'gen4', 'gen4pt', 'gen5',
	'gen5bw1', 'gen5pokebilities', 'gen6', 'gen6xy', 'gen7', 'gen7letsgo', 'gen7pokebilities',
	'gen7sm', 'gen8', 'gen8bdsp', 'gen8dlc1', 'gen8legends', 'gen8linked', 'gen9dlc1',
	'gen9predlc', 'gen9ssb', 'mixandmega', 'monkeyspaw', 'partnersincrime', 'passiveaggressive', 'pokebedrock',
	'pokebilities', 'pokemoves', 'randomroulette', 'sharedpower', 'sharingiscaring', 'teraoverride', 'thecardgame',
	'trademarked', 'vaporemons',
];

export const DexModuleMap: Record<string, any> = {
	'../data/abilities': require('../data/abilities'),
	'../data/rulesets': require('../data/rulesets'),
	'../data/formats-data': require('../data/formats-data'),
	'../data/items': require('../data/items'),
	'../data/learnsets': require('../data/learnsets'),
	'../data/moves': require('../data/moves'),
	'../data/natures': require('../data/natures'),
	'../data/pokedex': require('../data/pokedex'),
	'../data/pokemongo': require('../data/pokemongo'),
	'../data/scripts': require('../data/scripts'),
	'../data/conditions': require('../data/conditions'),
	'../data/typechart': require('../data/typechart'),

	// blankcanvas
	'../data/mods/blankcanvas/rulesets': require('../data/mods/blankcanvas/rulesets'),
	'../data/mods/blankcanvas/formats-data': require('../data/mods/blankcanvas/formats-data'),
	'../data/mods/blankcanvas/learnsets': require('../data/mods/blankcanvas/learnsets'),
	'../data/mods/blankcanvas/moves': require('../data/mods/blankcanvas/moves'),
	'../data/mods/blankcanvas/pokedex': require('../data/mods/blankcanvas/pokedex'),
	'../data/mods/blankcanvas/scripts': require('../data/mods/blankcanvas/scripts'),

	// chatbats
	'../data/mods/chatbats/abilities': require('../data/mods/chatbats/abilities'),
	'../data/mods/chatbats/items': require('../data/mods/chatbats/items'),
	'../data/mods/chatbats/moves': require('../data/mods/chatbats/moves'),
	'../data/mods/chatbats/pokedex': require('../data/mods/chatbats/pokedex'),
	'../data/mods/chatbats/scripts': require('../data/mods/chatbats/scripts'),
	'../data/mods/chatbats/conditions': require('../data/mods/chatbats/conditions'),

	// fullpotential
	'../data/mods/fullpotential/abilities': require('../data/mods/fullpotential/abilities'),
	'../data/mods/fullpotential/scripts': require('../data/mods/fullpotential/scripts'),

	// gen1
	'../data/mods/gen1/rulesets': require('../data/mods/gen1/rulesets'),
	'../data/mods/gen1/formats-data': require('../data/mods/gen1/formats-data'),
	'../data/mods/gen1/moves': require('../data/mods/gen1/moves'),
	'../data/mods/gen1/pokedex': require('../data/mods/gen1/pokedex'),
	'../data/mods/gen1/scripts': require('../data/mods/gen1/scripts'),
	'../data/mods/gen1/conditions': require('../data/mods/gen1/conditions'),
	'../data/mods/gen1/typechart': require('../data/mods/gen1/typechart'),

	// gen1jpn
	'../data/mods/gen1jpn/rulesets': require('../data/mods/gen1jpn/rulesets'),
	'../data/mods/gen1jpn/moves': require('../data/mods/gen1jpn/moves'),
	'../data/mods/gen1jpn/scripts': require('../data/mods/gen1jpn/scripts'),
	'../data/mods/gen1jpn/conditions': require('../data/mods/gen1jpn/conditions'),

	// gen1stadium
	'../data/mods/gen1stadium/rulesets': require('../data/mods/gen1stadium/rulesets'),
	'../data/mods/gen1stadium/formats-data': require('../data/mods/gen1stadium/formats-data'),
	'../data/mods/gen1stadium/moves': require('../data/mods/gen1stadium/moves'),
	'../data/mods/gen1stadium/scripts': require('../data/mods/gen1stadium/scripts'),
	'../data/mods/gen1stadium/conditions': require('../data/mods/gen1stadium/conditions'),

	// gen2
	'../data/mods/gen2/rulesets': require('../data/mods/gen2/rulesets'),
	'../data/mods/gen2/formats-data': require('../data/mods/gen2/formats-data'),
	'../data/mods/gen2/items': require('../data/mods/gen2/items'),
	'../data/mods/gen2/learnsets': require('../data/mods/gen2/learnsets'),
	'../data/mods/gen2/moves': require('../data/mods/gen2/moves'),
	'../data/mods/gen2/pokedex': require('../data/mods/gen2/pokedex'),
	'../data/mods/gen2/scripts': require('../data/mods/gen2/scripts'),
	'../data/mods/gen2/conditions': require('../data/mods/gen2/conditions'),
	'../data/mods/gen2/typechart': require('../data/mods/gen2/typechart'),

	// gen2stadium2
	'../data/mods/gen2stadium2/rulesets': require('../data/mods/gen2stadium2/rulesets'),
	'../data/mods/gen2stadium2/items': require('../data/mods/gen2stadium2/items'),
	'../data/mods/gen2stadium2/moves': require('../data/mods/gen2stadium2/moves'),
	'../data/mods/gen2stadium2/scripts': require('../data/mods/gen2stadium2/scripts'),
	'../data/mods/gen2stadium2/conditions': require('../data/mods/gen2stadium2/conditions'),

	// gen3
	'../data/mods/gen3/abilities': require('../data/mods/gen3/abilities'),
	'../data/mods/gen3/rulesets': require('../data/mods/gen3/rulesets'),
	'../data/mods/gen3/formats-data': require('../data/mods/gen3/formats-data'),
	'../data/mods/gen3/items': require('../data/mods/gen3/items'),
	'../data/mods/gen3/moves': require('../data/mods/gen3/moves'),
	'../data/mods/gen3/scripts': require('../data/mods/gen3/scripts'),
	'../data/mods/gen3/conditions': require('../data/mods/gen3/conditions'),

	// gen3colosseum
	'../data/mods/gen3colosseum/moves': require('../data/mods/gen3colosseum/moves'),
	'../data/mods/gen3colosseum/scripts': require('../data/mods/gen3colosseum/scripts'),

	// gen3rs
	'../data/mods/gen3rs/formats-data': require('../data/mods/gen3rs/formats-data'),
	'../data/mods/gen3rs/items': require('../data/mods/gen3rs/items'),
	'../data/mods/gen3rs/learnsets': require('../data/mods/gen3rs/learnsets'),
	'../data/mods/gen3rs/scripts': require('../data/mods/gen3rs/scripts'),

	// gen4
	'../data/mods/gen4/abilities': require('../data/mods/gen4/abilities'),
	'../data/mods/gen4/rulesets': require('../data/mods/gen4/rulesets'),
	'../data/mods/gen4/formats-data': require('../data/mods/gen4/formats-data'),
	'../data/mods/gen4/items': require('../data/mods/gen4/items'),
	'../data/mods/gen4/moves': require('../data/mods/gen4/moves'),
	'../data/mods/gen4/pokedex': require('../data/mods/gen4/pokedex'),
	'../data/mods/gen4/scripts': require('../data/mods/gen4/scripts'),
	'../data/mods/gen4/conditions': require('../data/mods/gen4/conditions'),

	// gen4pt
	'../data/mods/gen4pt/formats-data': require('../data/mods/gen4pt/formats-data'),
	'../data/mods/gen4pt/learnsets': require('../data/mods/gen4pt/learnsets'),
	'../data/mods/gen4pt/scripts': require('../data/mods/gen4pt/scripts'),

	// gen5
	'../data/mods/gen5/abilities': require('../data/mods/gen5/abilities'),
	'../data/mods/gen5/rulesets': require('../data/mods/gen5/rulesets'),
	'../data/mods/gen5/formats-data': require('../data/mods/gen5/formats-data'),
	'../data/mods/gen5/items': require('../data/mods/gen5/items'),
	'../data/mods/gen5/moves': require('../data/mods/gen5/moves'),
	'../data/mods/gen5/pokedex': require('../data/mods/gen5/pokedex'),
	'../data/mods/gen5/scripts': require('../data/mods/gen5/scripts'),
	'../data/mods/gen5/conditions': require('../data/mods/gen5/conditions'),
	'../data/mods/gen5/typechart': require('../data/mods/gen5/typechart'),

	// gen5bw1
	'../data/mods/gen5bw1/formats-data': require('../data/mods/gen5bw1/formats-data'),
	'../data/mods/gen5bw1/items': require('../data/mods/gen5bw1/items'),
	'../data/mods/gen5bw1/learnsets': require('../data/mods/gen5bw1/learnsets'),
	'../data/mods/gen5bw1/pokedex': require('../data/mods/gen5bw1/pokedex'),
	'../data/mods/gen5bw1/scripts': require('../data/mods/gen5bw1/scripts'),

	// gen5pokebilities
	'../data/mods/gen5pokebilities/abilities': require('../data/mods/gen5pokebilities/abilities'),
	'../data/mods/gen5pokebilities/moves': require('../data/mods/gen5pokebilities/moves'),
	'../data/mods/gen5pokebilities/scripts': require('../data/mods/gen5pokebilities/scripts'),

	// gen6
	'../data/mods/gen6/abilities': require('../data/mods/gen6/abilities'),
	'../data/mods/gen6/formats-data': require('../data/mods/gen6/formats-data'),
	'../data/mods/gen6/items': require('../data/mods/gen6/items'),
	'../data/mods/gen6/learnsets': require('../data/mods/gen6/learnsets'),
	'../data/mods/gen6/moves': require('../data/mods/gen6/moves'),
	'../data/mods/gen6/pokedex': require('../data/mods/gen6/pokedex'),
	'../data/mods/gen6/scripts': require('../data/mods/gen6/scripts'),
	'../data/mods/gen6/conditions': require('../data/mods/gen6/conditions'),
	'../data/mods/gen6/typechart': require('../data/mods/gen6/typechart'),

	// gen6xy
	'../data/mods/gen6xy/formats-data': require('../data/mods/gen6xy/formats-data'),
	'../data/mods/gen6xy/items': require('../data/mods/gen6xy/items'),
	'../data/mods/gen6xy/learnsets': require('../data/mods/gen6xy/learnsets'),
	'../data/mods/gen6xy/moves': require('../data/mods/gen6xy/moves'),
	'../data/mods/gen6xy/pokedex': require('../data/mods/gen6xy/pokedex'),
	'../data/mods/gen6xy/scripts': require('../data/mods/gen6xy/scripts'),

	// gen7
	'../data/mods/gen7/abilities': require('../data/mods/gen7/abilities'),
	'../data/mods/gen7/rulesets': require('../data/mods/gen7/rulesets'),
	'../data/mods/gen7/formats-data': require('../data/mods/gen7/formats-data'),
	'../data/mods/gen7/items': require('../data/mods/gen7/items'),
	'../data/mods/gen7/moves': require('../data/mods/gen7/moves'),
	'../data/mods/gen7/pokedex': require('../data/mods/gen7/pokedex'),
	'../data/mods/gen7/scripts': require('../data/mods/gen7/scripts'),

	// gen7letsgo
	'../data/mods/gen7letsgo/rulesets': require('../data/mods/gen7letsgo/rulesets'),
	'../data/mods/gen7letsgo/formats-data': require('../data/mods/gen7letsgo/formats-data'),
	'../data/mods/gen7letsgo/learnsets': require('../data/mods/gen7letsgo/learnsets'),
	'../data/mods/gen7letsgo/moves': require('../data/mods/gen7letsgo/moves'),
	'../data/mods/gen7letsgo/pokedex': require('../data/mods/gen7letsgo/pokedex'),
	'../data/mods/gen7letsgo/scripts': require('../data/mods/gen7letsgo/scripts'),

	// gen7pokebilities
	'../data/mods/gen7pokebilities/abilities': require('../data/mods/gen7pokebilities/abilities'),
	'../data/mods/gen7pokebilities/moves': require('../data/mods/gen7pokebilities/moves'),
	'../data/mods/gen7pokebilities/scripts': require('../data/mods/gen7pokebilities/scripts'),

	// gen7sm
	'../data/mods/gen7sm/formats-data': require('../data/mods/gen7sm/formats-data'),
	'../data/mods/gen7sm/items': require('../data/mods/gen7sm/items'),
	'../data/mods/gen7sm/learnsets': require('../data/mods/gen7sm/learnsets'),
	'../data/mods/gen7sm/moves': require('../data/mods/gen7sm/moves'),
	'../data/mods/gen7sm/pokedex': require('../data/mods/gen7sm/pokedex'),
	'../data/mods/gen7sm/scripts': require('../data/mods/gen7sm/scripts'),

	// gen8
	'../data/mods/gen8/abilities': require('../data/mods/gen8/abilities'),
	'../data/mods/gen8/rulesets': require('../data/mods/gen8/rulesets'),
	'../data/mods/gen8/formats-data': require('../data/mods/gen8/formats-data'),
	'../data/mods/gen8/items': require('../data/mods/gen8/items'),
	'../data/mods/gen8/learnsets': require('../data/mods/gen8/learnsets'),
	'../data/mods/gen8/moves': require('../data/mods/gen8/moves'),
	'../data/mods/gen8/pokedex': require('../data/mods/gen8/pokedex'),
	'../data/mods/gen8/scripts': require('../data/mods/gen8/scripts'),
	'../data/mods/gen8/typechart': require('../data/mods/gen8/typechart'),

	// gen8bdsp
	'../data/mods/gen8bdsp/abilities': require('../data/mods/gen8bdsp/abilities'),
	'../data/mods/gen8bdsp/formats-data': require('../data/mods/gen8bdsp/formats-data'),
	'../data/mods/gen8bdsp/items': require('../data/mods/gen8bdsp/items'),
	'../data/mods/gen8bdsp/learnsets': require('../data/mods/gen8bdsp/learnsets'),
	'../data/mods/gen8bdsp/moves': require('../data/mods/gen8bdsp/moves'),
	'../data/mods/gen8bdsp/pokedex': require('../data/mods/gen8bdsp/pokedex'),
	'../data/mods/gen8bdsp/scripts': require('../data/mods/gen8bdsp/scripts'),

	// gen8dlc1
	'../data/mods/gen8dlc1/abilities': require('../data/mods/gen8dlc1/abilities'),
	'../data/mods/gen8dlc1/rulesets': require('../data/mods/gen8dlc1/rulesets'),
	'../data/mods/gen8dlc1/formats-data': require('../data/mods/gen8dlc1/formats-data'),
	'../data/mods/gen8dlc1/items': require('../data/mods/gen8dlc1/items'),
	'../data/mods/gen8dlc1/learnsets': require('../data/mods/gen8dlc1/learnsets'),
	'../data/mods/gen8dlc1/moves': require('../data/mods/gen8dlc1/moves'),
	'../data/mods/gen8dlc1/pokedex': require('../data/mods/gen8dlc1/pokedex'),
	'../data/mods/gen8dlc1/scripts': require('../data/mods/gen8dlc1/scripts'),

	// gen8legends
	'../data/mods/gen8legends/formats-data': require('../data/mods/gen8legends/formats-data'),
	'../data/mods/gen8legends/learnsets': require('../data/mods/gen8legends/learnsets'),
	'../data/mods/gen8legends/scripts': require('../data/mods/gen8legends/scripts'),

	// gen8linked
	'../data/mods/gen8linked/items': require('../data/mods/gen8linked/items'),
	'../data/mods/gen8linked/moves': require('../data/mods/gen8linked/moves'),
	'../data/mods/gen8linked/scripts': require('../data/mods/gen8linked/scripts'),
	'../data/mods/gen8linked/conditions': require('../data/mods/gen8linked/conditions'),

	// gen9dlc1
	'../data/mods/gen9dlc1/abilities': require('../data/mods/gen9dlc1/abilities'),
	'../data/mods/gen9dlc1/formats-data': require('../data/mods/gen9dlc1/formats-data'),
	'../data/mods/gen9dlc1/items': require('../data/mods/gen9dlc1/items'),
	'../data/mods/gen9dlc1/learnsets': require('../data/mods/gen9dlc1/learnsets'),
	'../data/mods/gen9dlc1/moves': require('../data/mods/gen9dlc1/moves'),
	'../data/mods/gen9dlc1/pokedex': require('../data/mods/gen9dlc1/pokedex'),
	'../data/mods/gen9dlc1/scripts': require('../data/mods/gen9dlc1/scripts'),
	'../data/mods/gen9dlc1/typechart': require('../data/mods/gen9dlc1/typechart'),

	// gen9predlc
	'../data/mods/gen9predlc/abilities': require('../data/mods/gen9predlc/abilities'),
	'../data/mods/gen9predlc/formats-data': require('../data/mods/gen9predlc/formats-data'),
	'../data/mods/gen9predlc/items': require('../data/mods/gen9predlc/items'),
	'../data/mods/gen9predlc/learnsets': require('../data/mods/gen9predlc/learnsets'),
	'../data/mods/gen9predlc/moves': require('../data/mods/gen9predlc/moves'),
	'../data/mods/gen9predlc/pokedex': require('../data/mods/gen9predlc/pokedex'),
	'../data/mods/gen9predlc/scripts': require('../data/mods/gen9predlc/scripts'),

	// gen9ssb
	'../data/mods/gen9ssb/abilities': require('../data/mods/gen9ssb/abilities'),
	'../data/mods/gen9ssb/rulesets': require('../data/mods/gen9ssb/rulesets'),
	'../data/mods/gen9ssb/items': require('../data/mods/gen9ssb/items'),
	'../data/mods/gen9ssb/moves': require('../data/mods/gen9ssb/moves'),
	'../data/mods/gen9ssb/pokedex': require('../data/mods/gen9ssb/pokedex'),
	'../data/mods/gen9ssb/scripts': require('../data/mods/gen9ssb/scripts'),
	'../data/mods/gen9ssb/conditions': require('../data/mods/gen9ssb/conditions'),
	'../data/mods/gen9ssb/typechart': require('../data/mods/gen9ssb/typechart'),

	// mixandmega
	'../data/mods/mixandmega/items': require('../data/mods/mixandmega/items'),
	'../data/mods/mixandmega/scripts': require('../data/mods/mixandmega/scripts'),

	// monkeyspaw
	'../data/mods/monkeyspaw/abilities': require('../data/mods/monkeyspaw/abilities'),
	'../data/mods/monkeyspaw/scripts': require('../data/mods/monkeyspaw/scripts'),
	'../data/mods/monkeyspaw/conditions': require('../data/mods/monkeyspaw/conditions'),

	// partnersincrime
	'../data/mods/partnersincrime/abilities': require('../data/mods/partnersincrime/abilities'),
	'../data/mods/partnersincrime/items': require('../data/mods/partnersincrime/items'),
	'../data/mods/partnersincrime/moves': require('../data/mods/partnersincrime/moves'),
	'../data/mods/partnersincrime/scripts': require('../data/mods/partnersincrime/scripts'),

	// passiveaggressive
	'../data/mods/passiveaggressive/abilities': require('../data/mods/passiveaggressive/abilities'),
	'../data/mods/passiveaggressive/items': require('../data/mods/passiveaggressive/items'),
	'../data/mods/passiveaggressive/moves': require('../data/mods/passiveaggressive/moves'),
	'../data/mods/passiveaggressive/scripts': require('../data/mods/passiveaggressive/scripts'),
	'../data/mods/passiveaggressive/conditions': require('../data/mods/passiveaggressive/conditions'),

	// pokebedrock
	'../data/mods/pokebedrock/pokedex': require('../data/mods/pokebedrock/pokedex'),
	'../data/mods/pokebedrock/scripts': require('../data/mods/pokebedrock/scripts'),

	// pokebilities
	'../data/mods/pokebilities/abilities': require('../data/mods/pokebilities/abilities'),
	'../data/mods/pokebilities/moves': require('../data/mods/pokebilities/moves'),
	'../data/mods/pokebilities/pokedex': require('../data/mods/pokebilities/pokedex'),
	'../data/mods/pokebilities/scripts': require('../data/mods/pokebilities/scripts'),

	// pokemoves
	'../data/mods/pokemoves/abilities': require('../data/mods/pokemoves/abilities'),
	'../data/mods/pokemoves/moves': require('../data/mods/pokemoves/moves'),
	'../data/mods/pokemoves/scripts': require('../data/mods/pokemoves/scripts'),

	// randomroulette
	'../data/mods/randomroulette/scripts': require('../data/mods/randomroulette/scripts'),

	// sharedpower
	'../data/mods/sharedpower/abilities': require('../data/mods/sharedpower/abilities'),
	'../data/mods/sharedpower/moves': require('../data/mods/sharedpower/moves'),
	'../data/mods/sharedpower/scripts': require('../data/mods/sharedpower/scripts'),

	// sharingiscaring
	'../data/mods/sharingiscaring/items': require('../data/mods/sharingiscaring/items'),
	'../data/mods/sharingiscaring/moves': require('../data/mods/sharingiscaring/moves'),
	'../data/mods/sharingiscaring/scripts': require('../data/mods/sharingiscaring/scripts'),
	'../data/mods/sharingiscaring/conditions': require('../data/mods/sharingiscaring/conditions'),

	// teraoverride
	'../data/mods/teraoverride/abilities': require('../data/mods/teraoverride/abilities'),
	'../data/mods/teraoverride/items': require('../data/mods/teraoverride/items'),
	'../data/mods/teraoverride/moves': require('../data/mods/teraoverride/moves'),
	'../data/mods/teraoverride/scripts': require('../data/mods/teraoverride/scripts'),
	'../data/mods/teraoverride/conditions': require('../data/mods/teraoverride/conditions'),

	// thecardgame
	'../data/mods/thecardgame/abilities': require('../data/mods/thecardgame/abilities'),
	'../data/mods/thecardgame/items': require('../data/mods/thecardgame/items'),
	'../data/mods/thecardgame/moves': require('../data/mods/thecardgame/moves'),
	'../data/mods/thecardgame/scripts': require('../data/mods/thecardgame/scripts'),
	'../data/mods/thecardgame/conditions': require('../data/mods/thecardgame/conditions'),
	'../data/mods/thecardgame/typechart': require('../data/mods/thecardgame/typechart'),

	// trademarked
	'../data/mods/trademarked/scripts': require('../data/mods/trademarked/scripts'),

	// vaporemons
	'../data/mods/vaporemons/abilities': require('../data/mods/vaporemons/abilities'),
	'../data/mods/vaporemons/moves': require('../data/mods/vaporemons/moves'),
};
