// @pokebedrock - This file is AUTO-GENERATED by `tools/build-utils.js`.

export const RandomBattlesMods: string[] = [
	'blankcanvas', 'chatbats', 'gen1', 'gen2', 'gen3', 'gen4', 'gen5',
	'gen5pokebilities', 'gen6', 'gen7', 'gen7letsgo', 'gen8', 'gen8bdsp', 'gen9',
	'gen9baby', 'gen9cap', 'gen9ffa', 'partnersincrime', 'randomroulette', 'sharedpower',
];

export const getRandomBattlesModule = (module: typeof RandomBattlesMods[number]) => {
	return {
		'blankcanvas': require('../data/random-battles/blankcanvas/teams'),
		'chatbats': require('../data/random-battles/chatbats/teams'),
		'gen1': require('../data/random-battles/gen1/teams'),
		'gen2': require('../data/random-battles/gen2/teams'),
		'gen3': require('../data/random-battles/gen3/teams'),
		'gen4': require('../data/random-battles/gen4/teams'),
		'gen5': require('../data/random-battles/gen5/teams'),
		'gen5pokebilities': require('../data/random-battles/gen5pokebilities/teams'),
		'gen6': require('../data/random-battles/gen6/teams'),
		'gen7': require('../data/random-battles/gen7/teams'),
		'gen7letsgo': require('../data/random-battles/gen7letsgo/teams'),
		'gen8': require('../data/random-battles/gen8/teams'),
		'gen8bdsp': require('../data/random-battles/gen8bdsp/teams'),
		'gen9': require('../data/random-battles/gen9/teams'),
		'gen9baby': require('../data/random-battles/gen9baby/teams'),
		'gen9cap': require('../data/random-battles/gen9cap/teams'),
		'gen9ffa': require('../data/random-battles/gen9ffa/teams'),
		'partnersincrime': require('../data/random-battles/partnersincrime/teams'),
		'randomroulette': require('../data/random-battles/randomroulette/teams'),
		'sharedpower': require('../data/random-battles/sharedpower/teams'),
	}[module];
};
