// @pokebedrock - This file is AUTO-GENERATED by `tools/build-utils.js`.

export const RandomBattlesMods: string[] = [
	'gen1', 'gen2', 'gen3', 'gen4', 'gen5', 'gen6', 'gen7',
	'gen7letsgo', 'gen8', 'gen8bdsp', 'gen9', 'gen9baby', 'gen9cap', 'partnersincrime',
	'randomroulette', 'sharedpower',
];

export const RandomBattlesModuleMap: Record<string, any> = {
	'gen1': require('../data/random-battles/gen1/teams'),
	'gen2': require('../data/random-battles/gen2/teams'),
	'gen3': require('../data/random-battles/gen3/teams'),
	'gen4': require('../data/random-battles/gen4/teams'),
	'gen5': require('../data/random-battles/gen5/teams'),
	'gen6': require('../data/random-battles/gen6/teams'),
	'gen7': require('../data/random-battles/gen7/teams'),
	'gen7letsgo': require('../data/random-battles/gen7letsgo/teams'),
	'gen8': require('../data/random-battles/gen8/teams'),
	'gen8bdsp': require('../data/random-battles/gen8bdsp/teams'),
	'gen9': require('../data/random-battles/gen9/teams'),
	'gen9baby': require('../data/random-battles/gen9baby/teams'),
	'gen9cap': require('../data/random-battles/gen9cap/teams'),
	'partnersincrime': require('../data/random-battles/partnersincrime/teams'),
	'randomroulette': require('../data/random-battles/randomroulette/teams'),
	'sharedpower': require('../data/random-battles/sharedpower/teams'),
};
