export const MANUAL_EVOLUTIONS: { [key: string]: { evoTo: string, evoLevel: number, evoItem?: string }[] } = {

	'bulbasaur': [{ evoTo: 'ivysaur', evoLevel: 16 }],
	'ivysaur': [{ evoTo: 'venusaur', evoLevel: 32 }],
	'charmander': [{ evoTo: 'charmeleon', evoLevel: 16 }],
	'charmeleon': [{ evoTo: 'charizard', evoLevel: 36 }],
	'squirtle': [{ evoTo: 'wartortle', evoLevel: 16 }],
	'wartortle': [{ evoTo: 'blastoise', evoLevel: 36 }],

	'chikorita': [{ evoTo: 'bayleef', evoLevel: 16 }],
	'bayleef': [{ evoTo: 'meganium', evoLevel: 32 }],
	'cyndaquil': [{ evoTo: 'quilava', evoLevel: 14 }],
	'quilava': [{ evoTo: 'typhlosion', evoLevel: 36 }],
	'totodile': [{ evoTo: 'croconaw', evoLevel: 18 }],
	'croconaw': [{ evoTo: 'feraligatr', evoLevel: 30 }],

	'treecko': [{ evoTo: 'grovyle', evoLevel: 16 }],
	'grovyle': [{ evoTo: 'sceptile', evoLevel: 36 }],
	'torchic': [{ evoTo: 'combusken', evoLevel: 16 }],
	'combusken': [{ evoTo: 'blaziken', evoLevel: 36 }],
	'mudkip': [{ evoTo: 'marshtomp', evoLevel: 16 }],
	'marshtomp': [{ evoTo: 'swampert', evoLevel: 36 }],

	'turtwig': [{ evoTo: 'grotle', evoLevel: 18 }],
	'grotle': [{ evoTo: 'torterra', evoLevel: 32 }],
	'chimchar': [{ evoTo: 'monferno', evoLevel: 14 }],
	'monferno': [{ evoTo: 'infernape', evoLevel: 36 }],
	'piplup': [{ evoTo: 'prinplup', evoLevel: 16 }],
	'prinplup': [{ evoTo: 'empoleon', evoLevel: 36 }],

	'snivy': [{ evoTo: 'servine', evoLevel: 17 }],
	'servine': [{ evoTo: 'serperior', evoLevel: 36 }],
	'tepig': [{ evoTo: 'pignite', evoLevel: 17 }],
	'pignite': [{ evoTo: 'emboar', evoLevel: 36 }],
	'oshawott': [{ evoTo: 'dewott', evoLevel: 17 }],
	'dewott': [{ evoTo: 'samurott', evoLevel: 36 }],

	'chespin': [{ evoTo: 'quilladin', evoLevel: 16 }],
	'quilladin': [{ evoTo: 'chesnaught', evoLevel: 36 }],
	'fennekin': [{ evoTo: 'braixen', evoLevel: 16 }],
	'braixen': [{ evoTo: 'delphox', evoLevel: 36 }],
	'froakie': [{ evoTo: 'frogadier', evoLevel: 16 }],
	'frogadier': [{ evoTo: 'greninja', evoLevel: 36 }],

	'rowlet': [{ evoTo: 'dartrix', evoLevel: 17 }],
	'dartrix': [{ evoTo: 'decidueye', evoLevel: 34 }],
	'litten': [{ evoTo: 'torracat', evoLevel: 17 }],
	'torracat': [{ evoTo: 'incineroar', evoLevel: 34 }],
	'popplio': [{ evoTo: 'brionne', evoLevel: 17 }],
	'brionne': [{ evoTo: 'primarina', evoLevel: 34 }],

	'grookey': [{ evoTo: 'thwackey', evoLevel: 16 }],
	'thwackey': [{ evoTo: 'rillaboom', evoLevel: 35 }],
	'scorbunny': [{ evoTo: 'cinderace', evoLevel: 16 }],
	'cinderace': [{ evoTo: 'raboot', evoLevel: 35 }],
	'sobble': [{ evoTo: 'drizzile', evoLevel: 16 }],
	'drizzile': [{ evoTo: 'inteleon', evoLevel: 35 }],

	'sprigatito': [{ evoTo: 'floragato', evoLevel: 16 }],
	'floragato': [{ evoTo: 'meowscarada', evoLevel: 36 }],
	'fuecoco': [{ evoTo: 'crocalor', evoLevel: 16 }],
	'crocalor': [{ evoTo: 'skeledirge', evoLevel: 36 }],
	'quaxly': [{ evoTo: 'quaxwell', evoLevel: 16 }],
	'quaxwell': [{ evoTo: 'quaquaval', evoLevel: 36 }],

	'caterpie': [{ evoTo: 'metapod', evoLevel: 7 }],
	'metapod': [{ evoTo: 'butterfree', evoLevel: 10 }],
	'weedle': [{ evoTo: 'kakuna', evoLevel: 7 }],
	'kakuna': [{ evoTo: 'beedrill', evoLevel: 10 }],
	'paras': [{ evoTo: 'parasect', evoLevel: 24 }],
	'venonat': [{ evoTo: 'venomoth', evoLevel: 31 }],
	'ledyba': [{ evoTo: 'ledian', evoLevel: 18 }],
	'spinarak': [{ evoTo: 'ariados', evoLevel: 18 }],
	'wurmple': [
		{ evoTo: 'silcoon', evoLevel: 7 },
		{ evoTo: 'cascoon', evoLevel: 7 },
	],
	'silcoon': [{ evoTo: 'beautifly', evoLevel: 10 }],
	'cascoon': [{ evoTo: 'dustox', evoLevel: 10 }],
	'nincada': [
		{ evoTo: 'ninjask', evoLevel: 20 },
		{ evoTo: 'shedinja', evoLevel: 20, evoItem: 'pokeball' },
	],
	'surskit': [{ evoTo: 'masquerain', evoLevel: 22 }],
	'volbeat': [{ evoTo: 'illumise', evoLevel: 99 }],
	'trapinch': [{ evoTo: 'vibrava', evoLevel: 35 }],
	'vibrava': [{ evoTo: 'flygon', evoLevel: 45 }],
	'anorith': [{ evoTo: 'armaldo', evoLevel: 40 }],
	'kricketot': [{ evoTo: 'kricketune', evoLevel: 10 }],
	'burmy': [
		{ evoTo: 'wormadam', evoLevel: 20 },
		{ evoTo: 'mothim', evoLevel: 20 },
	],
	'combee': [{ evoTo: 'vespiquen', evoLevel: 21 }],
	'skorupi': [{ evoTo: 'drapion', evoLevel: 40 }],
	'sewaddle': [{ evoTo: 'swadloon', evoLevel: 20 }],
	'swadloon': [{ evoTo: 'leavanny', evoLevel: 30 }],
	'venipede': [{ evoTo: 'whirlipede', evoLevel: 22 }],
	'whirlipede': [{ evoTo: 'scolipede', evoLevel: 30 }],
	'dwebble': [{ evoTo: 'crustle', evoLevel: 34 }],
	'joltik': [{ evoTo: 'galvantula', evoLevel: 36 }],
	'karrablast': [{ evoTo: 'escavalier', evoLevel: 36, evoItem: 'tradehelmet' }],
	'shelmet': [{ evoTo: 'accelgor', evoLevel: 36, evoItem: 'tradekarrablast' }],
	'larvesta': [{ evoTo: 'volcarona', evoLevel: 59 }],
	'scatterbug': [{ evoTo: 'spewpa', evoLevel: 9 }],
	'spewpa': [{ evoTo: 'vivillon', evoLevel: 12 }],
	'dewpider': [{ evoTo: 'araquanid', evoLevel: 22 }],
	'wimpod': [{ evoTo: 'golisopod', evoLevel: 30 }],
	'blipbug': [{ evoTo: 'dottler', evoLevel: 10 }],
	'dottler': [{ evoTo: 'orbeetle', evoLevel: 30 }],
	'sizzlipede': [{ evoTo: 'centiskorch', evoLevel: 28 }],
	'tarountula': [{ evoTo: 'spidops', evoLevel: 17 }],
	'nymble': [{ evoTo: 'lokix', evoLevel: 24 }],
	'rellor': [{ evoTo: 'rabsca', evoLevel: 36 }],
	'applin': [
		{ evoTo: 'flapple', evoLevel: 99, evoItem: 'tartapple' },
		{ evoTo: 'appletun', evoLevel: 99, evoItem: 'sweetapple' },
		{ evoTo: 'dipplin', evoLevel: 36, evoItem: 'syruppyapple' },
	],
	'dipplin': [{ evoTo: 'hydrapple', evoLevel: 42, evoItem: 'dragonchesto' }],

	'pidgey': [{ evoTo: 'pidgeotto', evoLevel: 18 }],
	'pidgeotto': [{ evoTo: 'pidgeot', evoLevel: 36 }],
	'rattata': [{ evoTo: 'raticate', evoLevel: 20 }],
	'spearow': [{ evoTo: 'fearow', evoLevel: 20 }],
	'meowth': [{ evoTo: 'persian', evoLevel: 28 }],
	'doduo': [{ evoTo: 'dodrio', evoLevel: 31 }],
	'lickitung': [{ evoTo: 'lickilicky', evoLevel: 36 }],
	'sentret': [{ evoTo: 'furret', evoLevel: 15 }],
	'hoothoot': [{ evoTo: 'noctowl', evoLevel: 20 }],
	'aipom': [{ evoTo: 'ambipom', evoLevel: 36 }],
	'dunsparce': [{ evoTo: 'dudunsparce', evoLevel: 36 }],
	'zigzagoon': [{ evoTo: 'linoone', evoLevel: 20 }],
	'taillow': [{ evoTo: 'swellow', evoLevel: 22 }],
	'skitty': [{ evoTo: 'delcatty', evoLevel: 99, evoItem: 'moonstone' }],
	'whismur': [{ evoTo: 'loudred', evoLevel: 20 }],
	'loudred': [{ evoTo: 'exploud', evoLevel: 40 }],
	'bidoof': [{ evoTo: 'bibarel', evoLevel: 15 }],
	'starly': [{ evoTo: 'staravia', evoLevel: 14 }],
	'staravia': [{ evoTo: 'staraptor', evoLevel: 34 }],
	'buneary': [{ evoTo: 'lopunny', evoLevel: 30 }],
	'glameow': [{ evoTo: 'purugly', evoLevel: 38 }],
	'happiny': [{ evoTo: 'chansey', evoLevel: 30, evoItem: 'ovalstone' }],
	'lillipup': [{ evoTo: 'herdier', evoLevel: 16 }],
	'herdier': [{ evoTo: 'stoutland', evoLevel: 32 }],
	'minccino': [{ evoTo: 'cinccino', evoLevel: 99, evoItem: 'shinystone' }],
	'rufflet': [{ evoTo: 'braviary', evoLevel: 54 }],
	'vullaby': [{ evoTo: 'mandibuzz', evoLevel: 54 }],
	'fletchling': [{ evoTo: 'fletchinder', evoLevel: 17 }],
	'fletchinder': [{ evoTo: 'talonflame', evoLevel: 35 }],
	'goomy': [{ evoTo: 'sliggoo', evoLevel: 40 }],
	'sliggoo': [{ evoTo: 'goodra', evoLevel: 50 }],
	'yungoos': [{ evoTo: 'gumshoos', evoLevel: 20 }],
	'pikipek': [{ evoTo: 'trumbeak', evoLevel: 14 }],
	'trumbeak': [{ evoTo: 'toucannon', evoLevel: 28 }],
	'stufful': [{ evoTo: 'bewear', evoLevel: 27 }],
	'wooloo': [{ evoTo: 'dubwool', evoLevel: 24 }],
	'nickit': [{ evoTo: 'thievul', evoLevel: 18 }],
	'lechonk': [{ evoTo: 'oinkologne', evoLevel: 18 }],
	'tandemaus': [{ evoTo: 'maushold', evoLevel: 25 }],

	'ekans': [{ evoTo: 'arbok', evoLevel: 22 }],
	'nidoranf': [{ evoTo: 'nidorina', evoLevel: 16 }],
	'nidorina': [{ evoTo: 'nidoqueen', evoLevel: 99, evoItem: 'moonstone' }],
	'nidoranm': [{ evoTo: 'nidorino', evoLevel: 16 }],
	'nidorino': [{ evoTo: 'nidoking', evoLevel: 99, evoItem: 'moonstone' }],
	'zubat': [{ evoTo: 'golbat', evoLevel: 22 }],
	'oddish': [{ evoTo: 'gloom', evoLevel: 21 }],
	'gloom': [
		{ evoTo: 'vileplume', evoLevel: 99, evoItem: 'leafstone' },
		{ evoTo: 'bellossom', evoLevel: 99, evoItem: 'sunstone' },
	],
	'bellsprout': [{ evoTo: 'weepinbell', evoLevel: 21 }],
	'weepinbell': [{ evoTo: 'victreebel', evoLevel: 99, evoItem: 'leafstone' }],
	'grimer': [{ evoTo: 'muk', evoLevel: 38 }],
	'koffing': [{ evoTo: 'weezing', evoLevel: 35 }],
	'gastly': [{ evoTo: 'haunter', evoLevel: 25 }],
	'haunter': [{ evoTo: 'gengar', evoLevel: 36 }],
	'golbat': [{ evoTo: 'crobat', evoLevel: 30 }],
	'salandit': [{ evoTo: 'salazzle', evoLevel: 33 }],
	'toxel': [
		{ evoTo: 'toxtricity', evoLevel: 30 },
		{ evoTo: 'toxtricitylowkey', evoLevel: 30 },
	],

	'sandshrew': [{ evoTo: 'sandslash', evoLevel: 22 }],
	'diglett': [{ evoTo: 'dugtrio', evoLevel: 26 }],
	'geodude': [{ evoTo: 'graveler', evoLevel: 25 }],
	'graveler': [{ evoTo: 'golem', evoLevel: 36 }],
	'cubone': [{ evoTo: 'marowak', evoLevel: 28 }],
	'rhyhorn': [{ evoTo: 'rhydon', evoLevel: 42 }],
	'rhydon': [{ evoTo: 'rhyperior', evoLevel: 36, evoItem: 'protector' }],
	'onix': [{ evoTo: 'steelix', evoLevel: 36, evoItem: 'metalcoat' }],
	'makuhita': [{ evoTo: 'hariyama', evoLevel: 24 }],
	'numel': [{ evoTo: 'camerupt', evoLevel: 33 }],
	'aron': [{ evoTo: 'lairon', evoLevel: 32 }],
	'lairon': [{ evoTo: 'aggron', evoLevel: 42 }],
	'lileep': [{ evoTo: 'cradily', evoLevel: 40 }],
	'cranidos': [{ evoTo: 'rampardos', evoLevel: 30 }],
	'shieldon': [{ evoTo: 'bastiodon', evoLevel: 30 }],
	'gible': [{ evoTo: 'gabite', evoLevel: 24 }],
	'gabite': [{ evoTo: 'garchomp', evoLevel: 48 }],
	'nosepass': [{ evoTo: 'probopass', evoLevel: 36, evoItem: 'magnet' }],
	'roggenrola': [{ evoTo: 'boldore', evoLevel: 25 }],
	'boldore': [{ evoTo: 'gigalith', evoLevel: 36 }],
	'drillbur': [{ evoTo: 'excadrill', evoLevel: 31 }],
	'tirtouga': [{ evoTo: 'carracosta', evoLevel: 37 }],
	'archen': [{ evoTo: 'archeops', evoLevel: 37 }],
	'golett': [{ evoTo: 'golurk', evoLevel: 43 }],
	'tyrunt': [{ evoTo: 'tyrantrum', evoLevel: 39 }],
	'amaura': [{ evoTo: 'aurorus', evoLevel: 39 }],
	'rockruff': [
		{ evoTo: 'lycanroc-midday', evoLevel: 25 },
		{ evoTo: 'lycanroc-midnight', evoLevel: 25 },
		{ evoTo: 'lycanroc-dusk', evoLevel: 25 },
	],
	'ferroseed': [{ evoTo: 'ferrothorn', evoLevel: 40 }],
	'rolycoly': [{ evoTo: 'carkol', evoLevel: 18 }],
	'carkol': [{ evoTo: 'coalossal', evoLevel: 34 }],
	'silicobra': [{ evoTo: 'sandaconda', evoLevel: 36 }],
	'wiglett': [{ evoTo: 'wugtrio', evoLevel: 26 }],
	'nacli': [{ evoTo: 'naclstack', evoLevel: 24 }],
	'naclstack': [{ evoTo: 'garganacl', evoLevel: 38 }],
	'duraludon': [{ evoTo: 'archaludon', evoLevel: 36, evoItem: 'metalalloy' }],

	'vulpix': [{ evoTo: 'ninetales', evoLevel: 99, evoItem: 'firestone' }],
	'growlithe': [{ evoTo: 'arcanine', evoLevel: 99, evoItem: 'firestone' }],
	'ponyta': [{ evoTo: 'rapidash', evoLevel: 40 }],
	'magmar': [{ evoTo: 'magmortar', evoLevel: 36, evoItem: 'magmarizer' }],

	'psyduck': [{ evoTo: 'golduck', evoLevel: 33 }],
	'poliwag': [{ evoTo: 'poliwhirl', evoLevel: 25 }],
	'poliwhirl': [
		{ evoTo: 'poliwrath', evoLevel: 99, evoItem: 'waterstone' },
		{ evoTo: 'politoed', evoLevel: 36, evoItem: 'kingsrock' },
	],
	'tentacool': [{ evoTo: 'tentacruel', evoLevel: 30 }],
	'slowpoke': [
		{ evoTo: 'slowbro', evoLevel: 37 },
		{ evoTo: 'slowking', evoLevel: 36, evoItem: 'kingsrock' },
	],
	'seel': [{ evoTo: 'dewgong', evoLevel: 34 }],
	'shellder': [{ evoTo: 'cloyster', evoLevel: 99, evoItem: 'waterstone' }],
	'krabby': [{ evoTo: 'kingler', evoLevel: 28 }],
	'horsea': [{ evoTo: 'seadra', evoLevel: 32 }],
	'goldeen': [{ evoTo: 'seaking', evoLevel: 33 }],
	'staryu': [{ evoTo: 'starmie', evoLevel: 99, evoItem: 'waterstone' }],
	'magikarp': [{ evoTo: 'gyarados', evoLevel: 20 }],
	'seadra': [{ evoTo: 'kingdra', evoLevel: 36, evoItem: 'dragonscale' }],
	'lotad': [{ evoTo: 'lombre', evoLevel: 14 }],
	'lombre': [{ evoTo: 'ludicolo', evoLevel: 99, evoItem: 'waterstone' }],
	'barboach': [{ evoTo: 'whiscash', evoLevel: 30 }],
	'corphish': [{ evoTo: 'crawdaunt', evoLevel: 30 }],
	'buizel': [{ evoTo: 'floatzel', evoLevel: 26 }],
	'finneon': [{ evoTo: 'lumineon', evoLevel: 31 }],
	'tympole': [{ evoTo: 'palpitoad', evoLevel: 25 }],
	'palpitoad': [{ evoTo: 'seismitoad', evoLevel: 36 }],
	'frillish': [{ evoTo: 'jellicent', evoLevel: 40 }],
	'clauncher': [{ evoTo: 'clawitzer', evoLevel: 37 }],
	'binacle': [{ evoTo: 'barbaracle', evoLevel: 39 }],
	'arrokuda': [{ evoTo: 'barraskewda', evoLevel: 26 }],
	'finizen': [{ evoTo: 'palafin', evoLevel: 38 }],

	'abra': [{ evoTo: 'kadabra', evoLevel: 16 }],
	'kadabra': [{ evoTo: 'alakazam', evoLevel: 36 }],
	'drowzee': [{ evoTo: 'hypno', evoLevel: 26 }],
	'exeggcute': [{ evoTo: 'exeggutor', evoLevel: 99, evoItem: 'leafstone' }],
	'ralts': [
		{ evoTo: 'kirlia', evoLevel: 20 },
	],
	'kirlia': [
		{ evoTo: 'gardevoir', evoLevel: 30 },
		{ evoTo: 'gallade', evoLevel: 30, evoItem: 'dawnstone' },
	],
	'wynaut': [{ evoTo: 'wobbuffet', evoLevel: 15 }],
	'munna': [{ evoTo: 'musharna', evoLevel: 99, evoItem: 'moonstone' }],
	'gothita': [{ evoTo: 'gothorita', evoLevel: 32 }],
	'gothorita': [{ evoTo: 'gothitelle', evoLevel: 41 }],
	'solosis': [{ evoTo: 'duosion', evoLevel: 32 }],
	'duosion': [{ evoTo: 'reuniclus', evoLevel: 41 }],
	'espurr': [{ evoTo: 'meowstic', evoLevel: 25 }],
	'inkay': [{ evoTo: 'malamar', evoLevel: 30 }],
	'hatenna': [{ evoTo: 'hattrem', evoLevel: 32 }],
	'hattrem': [{ evoTo: 'hatterene', evoLevel: 42 }],
	'flittle': [{ evoTo: 'espathra', evoLevel: 35 }],

	'mankey': [{ evoTo: 'primeape', evoLevel: 28 }],
	'machop': [{ evoTo: 'machoke', evoLevel: 28 }],
	'machoke': [{ evoTo: 'machamp', evoLevel: 36 }],
	'tyrogue': [
		{ evoTo: 'hitmonlee', evoLevel: 30 },
		{ evoTo: 'hitmonchan', evoLevel: 30 },
		{ evoTo: 'hitmontop', evoLevel: 30 },
	],
	'meditite': [{ evoTo: 'medicham', evoLevel: 37 }],
	'riolu': [{ evoTo: 'lucario', evoLevel: 30 }],
	'timburr': [{ evoTo: 'gurdurr', evoLevel: 25 }],
	'gurdurr': [{ evoTo: 'conkeldurr', evoLevel: 36 }],
	'crabrawler': [{ evoTo: 'crabominable', evoLevel: 36, evoItem: 'icestone' }],
	'cufant': [{ evoTo: 'copperajah', evoLevel: 34 }],
	'clobbopus': [{ evoTo: 'grapploct', evoLevel: 36 }],
	'kubfu': [
		{ evoTo: 'urshifu', evoLevel: 70, evoItem: 'towerscrolls' },
		{ evoTo: 'urshifu-rapidstrike', evoLevel: 70, evoItem: 'waterscroll' },
	],
	'primeape': [{ evoTo: 'annihilape', evoLevel: 36 }],
	'pawmi': [{ evoTo: 'pawmo', evoLevel: 18 }],
	'pawmo': [{ evoTo: 'pawmot', evoLevel: 36 }],

	'pikachu': [{ evoTo: 'raichu', evoLevel: 99, evoItem: 'thunderstone' }],
	'magnemite': [{ evoTo: 'magneton', evoLevel: 30 }],
	'voltorb': [{ evoTo: 'electrode', evoLevel: 30 }],
	'electabuzz': [{ evoTo: 'electivire', evoLevel: 36, evoItem: 'electirizer' }],
	'pichu': [{ evoTo: 'pikachu', evoLevel: 30 }],
	'electrike': [{ evoTo: 'manectric', evoLevel: 26 }],
	'magneton': [{ evoTo: 'magnezone', evoLevel: 36, evoItem: 'magnet' }],
	'blitzle': [{ evoTo: 'zebstrika', evoLevel: 27 }],
	'helioptile': [{ evoTo: 'heliolisk', evoLevel: 99, evoItem: 'sunstone' }],
	'grubbin': [{ evoTo: 'charjabug', evoLevel: 20 }],
	'charjabug': [{ evoTo: 'vikavolt', evoLevel: 36, evoItem: 'magnet' }],
	'tadbulb': [{ evoTo: 'bellibolt', evoLevel: 25 }],
	'wattrel': [{ evoTo: 'kilowattrel', evoLevel: 25 }],

	'clefairy': [{ evoTo: 'clefable', evoLevel: 99, evoItem: 'moonstone' }],
	'jigglypuff': [{ evoTo: 'wigglytuff', evoLevel: 99, evoItem: 'moonstone' }],
	'cleffa': [{ evoTo: 'clefairy', evoLevel: 30 }],
	'igglybuff': [{ evoTo: 'jigglypuff', evoLevel: 30 }],
	'togepi': [{ evoTo: 'togetic', evoLevel: 30 }],
	'togetic': [{ evoTo: 'togekiss', evoLevel: 36, evoItem: 'shinystone' }],
	'spritzee': [{ evoTo: 'aromatisse', evoLevel: 36, evoItem: 'sachet' }],
	'swirlix': [{ evoTo: 'slurpuff', evoLevel: 36, evoItem: 'whippeddream' }],
	'eevee': [
		{ evoTo: 'vaporeon', evoLevel: 99, evoItem: 'waterstone' },
		{ evoTo: 'espeon', evoLevel: 30 },
		{ evoTo: 'umbreon', evoLevel: 30 },
		{ evoTo: 'leafeon', evoLevel: 36 },
		{ evoTo: 'glaceon', evoLevel: 36 },
		{ evoTo: 'sylveon', evoLevel: 30 },
	],
	'milcery': [{ evoTo: 'alcremie', evoLevel: 30 }],
	'tinkatink': [{ evoTo: 'tinkatuff', evoLevel: 24 }],
	'tinkatuff': [{ evoTo: 'tinkaton', evoLevel: 38 }],
	'fidough': [{ evoTo: 'dachsbun', evoLevel: 26 }],

	'duskull': [{ evoTo: 'dusclops', evoLevel: 37 }],
	'dusclops': [{ evoTo: 'dusknoir', evoLevel: 36, evoItem: 'reapercloth' }],
	'drifloon': [{ evoTo: 'drifblim', evoLevel: 27 }],
	'litwick': [{ evoTo: 'lampent', evoLevel: 41 }],
	'lampent': [{ evoTo: 'chandelure', evoLevel: 99, evoItem: 'duskstone' }],
	'yamask': [{ evoTo: 'cofagrigus', evoLevel: 34 }],
	'phantump': [{ evoTo: 'trevenant', evoLevel: 36 }],
	'pumpkaboo': [{ evoTo: 'gourgeist', evoLevel: 36 }],
	'dreepy': [{ evoTo: 'drakloak', evoLevel: 50 }],
	'drakloak': [{ evoTo: 'dragapult', evoLevel: 60 }],
	'sinistea': [
		{ evoTo: 'polteageist', evoLevel: 36, evoItem: 'chipseal' },
		{ evoTo: 'polteageist-antique', evoLevel: 36, evoItem: 'masterpiece' },
	],
	'impidimp': [{ evoTo: 'morgrem', evoLevel: 32 }],
	'morgrem': [{ evoTo: 'grimmsnarl', evoLevel: 42 }],
	'gimmighoul': [{ evoTo: 'gholdengo', evoLevel: 36 }],
	'poltchageist': [{ evoTo: 'sinistcha', evoLevel: 36, evoItem: 'masterpiece' }],

	'sunkern': [{ evoTo: 'sunflora', evoLevel: 99, evoItem: 'sunstone' }],
	'murkrow': [{ evoTo: 'honchkrow', evoLevel: 36, evoItem: 'duskstone' }],
	'misdreavus': [{ evoTo: 'mismagius', evoLevel: 36, evoItem: 'duskstone' }],
	'sneasel': [{ evoTo: 'weavile', evoLevel: 36, evoItem: 'razorclaw' }],
	'scyther': [
		{ evoTo: 'scizor', evoLevel: 36, evoItem: 'metalcoat' },
		{ evoTo: 'kleavor', evoLevel: 36, evoItem: 'blackaugurite' },
	],
	'porygon': [{ evoTo: 'porygon2', evoLevel: 36, evoItem: 'upgrade' }],
	'porygon2': [{ evoTo: 'porygonz', evoLevel: 36, evoItem: 'dubiousdisc' }],
	'larvitar': [{ evoTo: 'pupitar', evoLevel: 30 }],
	'pupitar': [{ evoTo: 'tyranitar', evoLevel: 55 }],
	'tangela': [{ evoTo: 'tangrowth', evoLevel: 36 }],
	'yanma': [{ evoTo: 'yanmega', evoLevel: 36 }],
	'swinub': [{ evoTo: 'piloswine', evoLevel: 33 }],
	'piloswine': [{ evoTo: 'mamoswine', evoLevel: 36 }],
	'roselia': [{ evoTo: 'roserade', evoLevel: 36, evoItem: 'shinystone' }],
	'budew': [{ evoTo: 'roselia', evoLevel: 30 }],
	'elekid': [{ evoTo: 'electabuzz', evoLevel: 30 }],
	'magby': [{ evoTo: 'magmar', evoLevel: 30 }],
	'bonsly': [{ evoTo: 'sudowoodo', evoLevel: 36 }],
	'mimejr': [{ evoTo: 'mrmime', evoLevel: 36 }],
	'munchlax': [{ evoTo: 'snorlax', evoLevel: 30 }],
	'chingling': [{ evoTo: 'chimecho', evoLevel: 30 }],
	'capsakid': [{ evoTo: 'scovillain', evoLevel: 99, evoItem: 'firestone' }],
	'cetoddle': [{ evoTo: 'cetitan', evoLevel: 30, evoItem: 'icestone' }],

	'omanyte': [{ evoTo: 'omastar', evoLevel: 40 }],
	'kabuto': [{ evoTo: 'kabutops', evoLevel: 40 }],

	'dratini': [{ evoTo: 'dragonair', evoLevel: 30 }],
	'dragonair': [{ evoTo: 'dragonite', evoLevel: 55 }],
	'bagon': [{ evoTo: 'shelgon', evoLevel: 30 }],
	'shelgon': [{ evoTo: 'salamence', evoLevel: 50 }],
	'deino': [{ evoTo: 'zweilous', evoLevel: 50 }],
	'zweilous': [{ evoTo: 'hydreigon', evoLevel: 64 }],
};

export const MANUAL_BASE_EXP: Record<string, number> = {
	'bulbasaur': 64,
	'ivysaur': 142,
	'venusaur': 236,
	'charmander': 62,
	'charmeleon': 142,
	'charizard': 240,
	'squirtle': 63,
	'wartortle': 142,
	'blastoise': 239,
	'caterpie': 39,
	'metapod': 72,
	'butterfree': 178,
	'weedle': 39,
	'kakuna': 72,
	'beedrill': 178,
	'pidgey': 50,
	'pidgeotto': 122,
	'pidgeot': 216,
	'rattata': 51,
	'raticate': 145,
	'spearow': 52,
	'fearow': 155,
	'ekans': 58,
	'arbok': 157,
	'pikachu': 112,
	'raichu': 218,
	'sandshrew': 60,
	'sandslash': 158,
	'nidoranf': 55,
	'nidorina': 128,
	'nidoqueen': 227,
	'nidoranm': 55,
	'nidorino': 128,
	'nidoking': 227,
	'clefairy': 113,
	'clefable': 217,
	'vulpix': 60,
	'ninetales': 177,
	'jigglypuff': 95,
	'wigglytuff': 196,
	'zubat': 49,
	'golbat': 159,
	'oddish': 64,
	'gloom': 138,
	'vileplume': 221,
	'paras': 57,
	'parasect': 142,
	'venonat': 61,
	'venomoth': 158,
	'diglett': 53,
	'dugtrio': 149,
	'meowth': 58,
	'persian': 154,
	'psyduck': 64,
	'golduck': 175,
	'mankey': 61,
	'primeape': 159,
	'growlithe': 70,
	'arcanine': 194,
	'poliwag': 60,
	'poliwhirl': 135,
	'poliwrath': 230,
	'abra': 62,
	'kadabra': 140,
	'alakazam': 225,
	'machop': 61,
	'machoke': 142,
	'machamp': 227,
	'bellsprout': 60,
	'weepinbell': 137,
	'victreebel': 221,
	'tentacool': 67,
	'tentacruel': 180,
	'geodude': 60,
	'graveler': 137,
	'golem': 223,
	'ponyta': 82,
	'rapidash': 175,
	'slowpoke': 63,
	'slowbro': 172,
	'magnemite': 65,
	'magneton': 163,
	'farfetchd': 132,
	'doduo': 62,
	'dodrio': 165,
	'seel': 65,
	'dewgong': 166,
	'grimer': 65,
	'muk': 175,
	'shellder': 61,
	'cloyster': 184,
	'gastly': 62,
	'haunter': 142,
	'gengar': 225,
	'onix': 77,
	'drowzee': 66,
	'hypno': 169,
	'krabby': 65,
	'kingler': 166,
	'voltorb': 66,
	'electrode': 172,
	'exeggcute': 65,
	'exeggutor': 186,
	'cubone': 64,
	'marowak': 149,
	'hitmonlee': 159,
	'hitmonchan': 159,
	'lickitung': 77,
	'koffing': 68,
	'weezing': 172,
	'rhyhorn': 69,
	'rhydon': 170,
	'chansey': 395,
	'tangela': 87,
	'kangaskhan': 172,
	'horsea': 59,
	'seadra': 154,
	'goldeen': 64,
	'seaking': 158,
	'staryu': 68,
	'starmie': 182,
	'mrmime': 161,
	'scyther': 100,
	'jynx': 159,
	'electabuzz': 172,
	'magmar': 173,
	'pinsir': 175,
	'tauros': 172,
	'magikarp': 40,
	'gyarados': 189,
	'lapras': 187,
	'ditto': 101,
	'eevee': 65,
	'vaporeon': 184,
	'jolteon': 184,
	'flareon': 184,
	'porygon': 79,
	'omanyte': 71,
	'omastar': 173,
	'kabuto': 71,
	'kabutops': 173,
	'aerodactyl': 180,
	'snorlax': 189,
	'articuno': 261,
	'zapdos': 261,
	'moltres': 261,
	'dratini': 60,
	'dragonair': 147,
	'dragonite': 270,
	'mewtwo': 306,
	'mew': 270,
	'chikorita': 64,
	'bayleef': 142,
	'meganium': 236,
	'cyndaquil': 62,
	'quilava': 142,
	'typhlosion': 240,
	'totodile': 63,
	'croconaw': 142,
	'feraligatr': 239,
	'sentret': 43,
	'furret': 145,
	'hoothoot': 52,
	'noctowl': 158,
	'ledyba': 53,
	'ledian': 137,
	'spinarak': 50,
	'ariados': 140,
	'crobat': 241,
	'chinchou': 66,
	'lanturn': 161,
	'pichu': 41,
	'cleffa': 44,
	'igglybuff': 42,
	'togepi': 49,
	'togetic': 142,
	'natu': 64,
	'xatu': 165,
	'mareep': 56,
	'flaaffy': 128,
	'ampharos': 230,
	'bellossom': 221,
	'marill': 88,
	'azumarill': 189,
	'sudowoodo': 144,
	'politoed': 225,
	'hoppip': 50,
	'skiploom': 119,
	'jumpluff': 207,
	'aipom': 72,
	'sunkern': 36,
	'sunflora': 149,
	'yanma': 78,
	'wooper': 42,
	'quagsire': 151,
	'espeon': 184,
	'umbreon': 184,
	'murkrow': 81,
	'slowking': 172,
	'misdreavus': 87,
	'unown': 118,
	'wobbuffet': 142,
	'girafarig': 159,
	'pineco': 58,
	'forretress': 163,
	'dunsparce': 145,
	'gligar': 86,
	'steelix': 179,
	'snubbull': 60,
	'granbull': 158,
	'qwilfish': 88,
	'scizor': 175,
	'shuckle': 177,
	'heracross': 175,
	'sneasel': 86,
	'teddiursa': 66,
	'ursaring': 175,
	'slugma': 50,
	'magcargo': 151,
	'swinub': 50,
	'piloswine': 158,
	'corsola': 144,
	'remoraid': 60,
	'octillery': 168,
	'delibird': 116,
	'mantine': 170,
	'skarmory': 163,
	'houndour': 66,
	'houndoom': 175,
	'kingdra': 243,
	'phanpy': 66,
	'donphan': 175,
	'porygon2': 180,
	'stantler': 163,
	'smeargle': 88,
	'tyrogue': 42,
	'hitmontop': 159,
	'smoochum': 61,
	'elekid': 72,
	'magby': 73,
	'miltank': 172,
	'blissey': 608,
	'raikou': 261,
	'entei': 261,
	'suicune': 261,
	'larvitar': 60,
	'pupitar': 144,
	'tyranitar': 270,
	'lugia': 306,
	'hooh': 306,
	'celebi': 270,
	'treecko': 62,
	'grovyle': 142,
	'sceptile': 239,
	'torchic': 62,
	'combusken': 142,
	'blaziken': 239,
	'mudkip': 62,
	'marshtomp': 142,
	'swampert': 241,
	'poochyena': 56,
	'mightyena': 147,
	'zigzagoon': 56,
	'linoone': 147,
	'wurmple': 56,
	'silcoon': 72,
	'beautifly': 178,
	'cascoon': 72,
	'dustox': 173,
	'lotad': 44,
	'lombre': 119,
	'ludicolo': 216,
	'seedot': 44,
	'nuzleaf': 119,
	'shiftry': 216,
	'taillow': 54,
	'swellow': 159,
	'wingull': 54,
	'pelipper': 154,
	'ralts': 40,
	'kirlia': 97,
	'gardevoir': 233,
	'surskit': 54,
	'masquerain': 159,
	'shroomish': 59,
	'breloom': 161,
	'slakoth': 56,
	'vigoroth': 154,
	'slaking': 252,
	'nincada': 53,
	'ninjask': 160,
	'shedinja': 83,
	'whismur': 48,
	'loudred': 126,
	'exploud': 221,
	'makuhita': 47,
	'hariyama': 166,
	'azurill': 38,
	'nosepass': 75,
	'skitty': 52,
	'delcatty': 140,
	'sableye': 133,
	'mawile': 133,
	'aron': 66,
	'lairon': 151,
	'aggron': 239,
	'meditite': 56,
	'medicham': 144,
	'electrike': 59,
	'manectric': 166,
	'plusle': 142,
	'minun': 142,
	'volbeat': 151,
	'illumise': 151,
	'roselia': 140,
	'gulpin': 60,
	'swalot': 163,
	'carvanha': 61,
	'sharpedo': 161,
	'wailmer': 80,
	'wailord': 175,
	'numel': 61,
	'camerupt': 161,
	'torkoal': 165,
	'spoink': 66,
	'grumpig': 165,
	'spinda': 126,
	'trapinch': 58,
	'vibrava': 119,
	'flygon': 234,
	'cacnea': 67,
	'cacturne': 166,
	'swablu': 62,
	'altaria': 172,
	'zangoose': 160,
	'seviper': 160,
	'lunatone': 161,
	'solrock': 161,
	'barboach': 58,
	'whiscash': 164,
	'corphish': 62,
	'crawdaunt': 164,
	'baltoy': 60,
	'claydol': 175,
	'lileep': 71,
	'cradily': 173,
	'anorith': 71,
	'armaldo': 173,
	'feebas': 40,
	'milotic': 189,
	'castform': 147,
	'kecleon': 154,
	'shuppet': 59,
	'banette': 159,
	'duskull': 59,
	'dusclops': 159,
	'tropius': 161,
	'chimecho': 159,
	'absol': 163,
	'wynaut': 52,
	'snorunt': 60,
	'glalie': 168,
	'spheal': 58,
	'sealeo': 144,
	'walrein': 239,
	'clamperl': 69,
	'huntail': 170,
	'gorebyss': 170,
	'relicanth': 170,
	'luvdisc': 116,
	'bagon': 60,
	'shelgon': 147,
	'salamence': 270,
	'beldum': 60,
	'metang': 147,
	'metagross': 270,
	'regirock': 261,
	'regice': 261,
	'registeel': 261,
	'latias': 270,
	'latios': 270,
	'kyogre': 302,
	'groudon': 302,
	'rayquaza': 306,
	'jirachi': 270,
	'deoxysnormal': 270,
	'turtwig': 64,
	'grotle': 142,
	'torterra': 236,
	'chimchar': 62,
	'monferno': 142,
	'infernape': 240,
	'piplup': 63,
	'prinplup': 142,
	'empoleon': 239,
	'starly': 49,
	'staravia': 119,
	'staraptor': 218,
	'bidoof': 50,
	'bibarel': 144,
	'kricketot': 39,
	'kricketune': 134,
	'shinx': 53,
	'luxio': 127,
	'luxray': 235,
	'budew': 56,
	'roserade': 232,
	'cranidos': 70,
	'rampardos': 173,
	'shieldon': 70,
	'bastiodon': 173,
	'burmy': 45,
	'wormadamplant': 148,
	'mothim': 148,
	'combee': 49,
	'vespiquen': 166,
	'pachirisu': 142,
	'buizel': 66,
	'floatzel': 173,
	'cherubi': 55,
	'cherrim': 158,
	'shellos': 65,
	'gastrodon': 166,
	'ambipom': 169,
	'drifloon': 70,
	'drifblim': 174,
	'buneary': 70,
	'lopunny': 168,
	'mismagius': 173,
	'honchkrow': 177,
	'glameow': 62,
	'purugly': 158,
	'chingling': 57,
	'stunky': 66,
	'skuntank': 168,
	'bronzor': 60,
	'bronzong': 175,
	'bonsly': 58,
	'mimejr': 62,
	'happiny': 110,
	'chatot': 144,
	'spiritomb': 170,
	'gible': 60,
	'gabite': 144,
	'garchomp': 270,
	'munchlax': 78,
	'riolu': 57,
	'lucario': 184,
	'hippopotas': 66,
	'hippowdon': 184,
	'skorupi': 66,
	'drapion': 175,
	'croagunk': 60,
	'toxicroak': 172,
	'carnivine': 159,
	'finneon': 66,
	'lumineon': 161,
	'mantyke': 69,
	'snover': 67,
	'abomasnow': 173,
	'weavile': 179,
	'magnezone': 241,
	'lickilicky': 180,
	'rhyperior': 241,
	'tangrowth': 187,
	'electivire': 243,
	'magmortar': 243,
	'togekiss': 245,
	'yanmega': 180,
	'leafeon': 184,
	'glaceon': 184,
	'gliscor': 179,
	'mamoswine': 239,
	'porygonz': 241,
	'gallade': 233,
	'probopass': 184,
	'dusknoir': 236,
	'froslass': 168,
	'rotom': 154,
	'uxie': 261,
	'mesprit': 261,
	'azelf': 261,
	'dialga': 306,
	'palkia': 306,
	'heatran': 270,
	'regigigas': 302,
	'giratinaaltered': 306,
	'cresselia': 270,
	'phione': 216,
	'manaphy': 270,
	'darkrai': 270,
	'shayminland': 270,
	'arceus': 324,
	'victini': 270,
	'snivy': 62,
	'servine': 145,
	'serperior': 238,
	'tepig': 62,
	'pignite': 146,
	'emboar': 238,
	'oshawott': 62,
	'dewott': 145,
	'samurott': 238,
	'patrat': 51,
	'watchog': 147,
	'lillipup': 55,
	'herdier': 130,
	'stoutland': 225,
	'purrloin': 56,
	'liepard': 156,
	'pansage': 63,
	'simisage': 174,
	'pansear': 63,
	'simisear': 174,
	'panpour': 63,
	'simipour': 174,
	'munna': 58,
	'musharna': 170,
	'pidove': 53,
	'tranquill': 125,
	'unfezant': 220,
	'blitzle': 59,
	'zebstrika': 174,
	'roggenrola': 56,
	'boldore': 137,
	'gigalith': 232,
	'woobat': 65,
	'swoobat': 149,
	'drilbur': 66,
	'excadrill': 178,
	'audino': 390,
	'timburr': 61,
	'gurdurr': 142,
	'conkeldurr': 227,
	'tympole': 59,
	'palpitoad': 134,
	'seismitoad': 229,
	'throh': 163,
	'sawk': 163,
	'sewaddle': 62,
	'swadloon': 133,
	'leavanny': 225,
	'venipede': 52,
	'whirlipede': 126,
	'scolipede': 218,
	'cottonee': 56,
	'whimsicott': 168,
	'petilil': 56,
	'lilligant': 168,
	'basculinredstriped': 161,
	'sandile': 58,
	'krokorok': 123,
	'krookodile': 234,
	'darumaka': 63,
	'darmanitanstandard': 168,
	'maractus': 161,
	'dwebble': 65,
	'crustle': 170,
	'scraggy': 70,
	'scrafty': 171,
	'sigilyph': 172,
	'yamask': 61,
	'cofagrigus': 169,
	'tirtouga': 71,
	'carracosta': 173,
	'archen': 71,
	'archeops': 177,
	'trubbish': 66,
	'garbodor': 166,
	'zorua': 66,
	'zoroark': 179,
	'minccino': 60,
	'cinccino': 165,
	'gothita': 58,
	'gothorita': 137,
	'gothitelle': 221,
	'solosis': 58,
	'duosion': 130,
	'reuniclus': 221,
	'ducklett': 61,
	'swanna': 166,
	'vanillite': 61,
	'vanillish': 138,
	'vanilluxe': 241,
	'deerling': 67,
	'sawsbuck': 166,
	'emolga': 150,
	'karrablast': 63,
	'escavalier': 173,
	'foongus': 59,
	'amoonguss': 162,
	'frillish': 67,
	'jellicent': 168,
	'alomomola': 165,
	'joltik': 64,
	'galvantula': 165,
	'ferroseed': 61,
	'ferrothorn': 171,
	'klink': 60,
	'klang': 154,
	'klinklang': 234,
	'tynamo': 55,
	'eelektrik': 142,
	'eelektross': 232,
	'elgyem': 67,
	'beheeyem': 170,
	'litwick': 55,
	'lampent': 130,
	'chandelure': 234,
	'axew': 64,
	'fraxure': 144,
	'haxorus': 243,
	'cubchoo': 61,
	'beartic': 177,
	'cryogonal': 180,
	'shelmet': 61,
	'accelgor': 173,
	'stunfisk': 165,
	'mienfoo': 70,
	'mienshao': 179,
	'druddigon': 170,
	'golett': 61,
	'golurk': 169,
	'pawniard': 68,
	'bisharp': 172,
	'bouffalant': 172,
	'rufflet': 70,
	'braviary': 179,
	'vullaby': 74,
	'mandibuzz': 179,
	'heatmor': 169,
	'durant': 169,
	'deino': 60,
	'zweilous': 147,
	'hydreigon': 270,
	'larvesta': 72,
	'volcarona': 248,
	'cobalion': 261,
	'terrakion': 261,
	'virizion': 261,
	'tornadusincarnate': 261,
	'thundurusincarnate': 261,
	'reshiram': 306,
	'zekrom': 306,
	'landorusincarnate': 270,
	'kyurem': 297,
	'keldeoordinary': 261,
	'meloettaaria': 270,
	'genesect': 270,
	'chespin': 63,
	'quilladin': 142,
	'chesnaught': 239,
	'fennekin': 61,
	'braixen': 143,
	'delphox': 240,
	'froakie': 63,
	'frogadier': 142,
	'greninja': 239,
	'bunnelby': 47,
	'diggersby': 148,
	'fletchling': 56,
	'fletchinder': 134,
	'talonflame': 175,
	'scatterbug': 40,
	'spewpa': 75,
	'vivillon': 185,
	'litleo': 74,
	'pyroar': 177,
	'flabebe': 61,
	'floette': 130,
	'florges': 248,
	'skiddo': 70,
	'gogoat': 186,
	'pancham': 70,
	'pangoro': 173,
	'furfrou': 165,
	'espurr': 71,
	'meowsticmale': 163,
	'honedge': 65,
	'doublade': 157,
	'aegislashshield': 234,
	'spritzee': 68,
	'aromatisse': 162,
	'swirlix': 68,
	'slurpuff': 168,
	'inkay': 58,
	'malamar': 169,
	'binacle': 61,
	'barbaracle': 175,
	'skrelp': 64,
	'dragalge': 173,
	'clauncher': 66,
	'clawitzer': 100,
	'helioptile': 58,
	'heliolisk': 168,
	'tyrunt': 72,
	'tyrantrum': 182,
	'amaura': 72,
	'aurorus': 104,
	'sylveon': 184,
	'hawlucha': 175,
	'dedenne': 151,
	'carbink': 100,
	'goomy': 60,
	'sliggoo': 158,
	'goodra': 270,
	'klefki': 165,
	'phantump': 62,
	'trevenant': 166,
	'pumpkabooaverage': 67,
	'gourgeistaverage': 173,
	'bergmite': 61,
	'avalugg': 180,
	'noibat': 49,
	'noivern': 187,
	'xerneas': 306,
	'yveltal': 306,
	'zygarde50': 270,
	'diancie': 270,
	'hoopa': 270,
	'volcanion': 270,
	'rowlet': 64,
	'dartrix': 147,
	'decidueye': 239,
	'litten': 64,
	'torracat': 147,
	'incineroar': 239,
	'popplio': 64,
	'brionne': 147,
	'primarina': 239,
	'pikipek': 53,
	'trumbeak': 124,
	'toucannon': 218,
	'yungoos': 51,
	'gumshoos': 146,
	'grubbin': 60,
	'charjabug': 140,
	'vikavolt': 225,
	'crabrawler': 68,
	'crabominable': 167,
	'oricoriobaile': 167,
	'cutiefly': 61,
	'ribombee': 162,
	'rockruff': 56,
	'lycanrocmidday': 170,
	'wishiwashisolo': 61,
	'mareanie': 61,
	'toxapex': 173,
	'mudbray': 77,
	'mudsdale': 175,
	'dewpider': 54,
	'araquanid': 159,
	'fomantis': 50,
	'lurantis': 168,
	'morelull': 57,
	'shiinotic': 142,
	'salandit': 64,
	'salazzle': 168,
	'stufful': 68,
	'bewear': 175,
	'bounsweet': 42,
	'steenee': 102,
	'tsareena': 230,
	'comfey': 170,
	'oranguru': 172,
	'passimian': 172,
	'wimpod': 46,
	'golisopod': 186,
	'sandygast': 64,
	'palossand': 168,
	'pyukumuku': 144,
	'typenull': 107,
	'silvally': 257,
	'miniorredmeteor': 154,
	'komala': 168,
	'turtonator': 170,
	'togedemaru': 152,
	'mimikyudisguised': 167,
	'bruxish': 166,
	'drampa': 170,
	'dhelmise': 181,
	'jangmoo': 60,
	'hakamoo': 147,
	'kommoo': 270,
	'tapukoko': 257,
	'tapulele': 257,
	'tapubulu': 257,
	'tapufini': 257,
	'cosmog': 40,
	'cosmoem': 140,
	'solgaleo': 306,
	'lunala': 306,
	'nihilego': 257,
	'buzzwole': 257,
	'pheromosa': 257,
	'xurkitree': 257,
	'celesteela': 257,
	'kartana': 257,
	'guzzlord': 257,
	'necrozma': 270,
	'magearna': 270,
	'marshadow': 270,
	'poipole': 189,
	'naganadel': 243,
	'stakataka': 257,
	'blacephalon': 257,
	'zeraora': 270,
	'meltan': 135,
	'melmetal': 270,
	'grookey': 62,
	'thwackey': 147,
	'rillaboom': 265,
	'scorbunny': 62,
	'raboot': 147,
	'cinderace': 265,
	'sobble': 62,
	'drizzile': 147,
	'inteleon': 265,
	'skwovet': 55,
	'greedent': 161,
	'rookidee': 49,
	'corvisquire': 128,
	'corviknight': 248,
	'blipbug': 36,
	'dottler': 117,
	'orbeetle': 253,
	'nickit': 49,
	'thievul': 159,
	'gossifleur': 50,
	'eldegoss': 161,
	'wooloo': 122,
	'dubwool': 172,
	'chewtle': 57,
	'drednaw': 170,
	'yamper': 54,
	'boltund': 172,
	'rolycoly': 48,
	'carkol': 144,
	'coalossal': 255,
	'applin': 52,
	'flapple': 170,
	'appletun': 170,
	'silicobra': 63,
	'sandaconda': 179,
	'cramorant': 166,
	'arrokuda': 56,
	'barraskewda': 172,
	'toxel': 48,
	'toxtricityamped': 176,
	'sizzlipede': 61,
	'centiskorch': 184,
	'clobbopus': 62,
	'grapploct': 168,
	'sinistea': 62,
	'polteageist': 178,
	'hatenna': 53,
	'hattrem': 130,
	'hatterene': 255,
	'impidimp': 53,
	'morgrem': 130,
	'grimmsnarl': 255,
	'obstagoon': 260,
	'perrserker': 154,
	'cursola': 179,
	'sirfetchd': 177,
	'mrrime': 182,
	'runerigus': 169,
	'milcery': 54,
	'alcremie': 173,
	'falinks': 165,
	'pincurchin': 152,
	'snom': 37,
	'frosmoth': 166,
	'stonjourner': 165,
	'eiscueice': 165,
	'indeedeemale': 166,
	'morpekofullbelly': 153,
	'cufant': 66,
	'copperajah': 175,
	'dracozolt': 177,
	'arctozolt': 177,
	'dracovish': 177,
	'arctovish': 177,
	'duraludon': 187,
	'dreepy': 54,
	'drakloak': 144,
	'dragapult': 300,
	'zacian': 335,
	'zamazenta': 335,
	'eternatus': 345,
	'kubfu': 77,
	'urshifusinglestrike': 275,
	'zarude': 300,
	'regieleki': 290,
	'regidrago': 290,
	'glastrier': 290,
	'spectrier': 290,
	'calyrex': 250,
	'wyrdeer': 263,
	'kleavor': 175,
	'ursaluna': 275,
	'basculegionmale': 265,
	'sneasler': 102,
	'overqwil': 179,
	'enamorusincarnate': 116,
	'sprigatito': 62,
	'floragato': 144,
	'meowscarada': 265,
	'fuecoco': 62,
	'crocalor': 144,
	'skeledirge': 265,
	'quaxly': 62,
	'quaxwell': 144,
	'quaquaval': 265,
	'lechonk': 51,
	'oinkolognemale': 171,
	'tarountula': 42,
	'spidops': 141,
	'nymble': 42,
	'lokix': 158,
	'pawmi': 48,
	'pawmo': 123,
	'pawmot': 245,
	'tandemaus': 61,
	'mausholdfamilyoffour': 165,
	'fidough': 62,
	'dachsbun': 167,
	'smoliv': 52,
	'dolliv': 124,
	'arboliva': 255,
	'squawkabillygreenplumage': 146,
	'nacli': 56,
	'naclstack': 124,
	'garganacl': 250,
	'charcadet': 51,
	'armarouge': 263,
	'ceruledge': 263,
	'tadbulb': 54,
	'bellibolt': 173,
	'wattrel': 56,
	'kilowattrel': 172,
	'maschiff': 68,
	'mabosstiff': 177,
	'shroodle': 58,
	'grafaiai': 170,
	'bramblin': 55,
	'brambleghast': 168,
	'toedscool': 67,
	'toedscruel': 180,
	'klawf': 158,
	'capsakid': 61,
	'scovillain': 170,
	'rellor': 54,
	'rabsca': 165,
	'flittle': 51,
	'espathra': 168,
	'tinkatink': 59,
	'tinkatuff': 133,
	'tinkaton': 253,
	'wiglett': 49,
	'wugtrio': 149,
	'bombirdier': 243,
	'finizen': 63,
	'palafinzero': 160,
	'varoom': 60,
	'revavroom': 175,
	'cyclizar': 175,
	'orthworm': 240,
	'glimmet': 70,
	'glimmora': 184,
	'greavard': 58,
	'houndstone': 171,
	'flamigo': 175,
	'cetoddle': 67,
	'cetitan': 182,
	'veluza': 167,
	'dondozo': 265,
	'tatsugiricurly': 166,
	'annihilape': 268,
	'clodsire': 151,
	'farigiraf': 260,
	'dudunsparcetwosegment': 182,
	'kingambit': 275,
	'greattusk': 285,
	'screamtail': 285,
	'brutebonnet': 285,
	'fluttermane': 285,
	'slitherwing': 285,
	'sandyshocks': 285,
	'irontreads': 285,
	'ironbundle': 285,
	'ironhands': 285,
	'ironjugulis': 285,
	'ironmoth': 285,
	'ironthorns': 285,
	'frigibax': 64,
	'arctibax': 148,
	'baxcalibur': 300,
	'gimmighoul': 60,
	'gholdengo': 275,
	'wochien': 285,
	'chienpao': 285,
	'tinglu': 285,
	'chiyu': 285,
	'roaringmoon': 295,
	'ironvaliant': 295,
	'koraidon': 335,
	'miraidon': 335,
	'walkingwake': 295,
	'ironleaves': 295,
	'dipplin': 170,
	'poltchageist': 62,
	'sinistcha': 178,
	'okidogi': 278,
	'munkidori': 278,
	'fezandipiti': 278,
	'ogerpon': 275,
	'archaludon': 300,
	'hydrapple': 270,
	'gougingfire': 295,
	'ragingbolt': 295,
	'ironboulder': 295,
	'ironcrown': 295,
	'terapagos': 90,
	'pecharunt': 300,
};

export const MANUAL_CATCH_RATES: Record<string, number> = {
	'bulbasaur': 45,
	'ivysaur': 45,
	'venusaur': 45,
	'charmander': 45,
	'charmeleon': 45,
	'charizard': 45,
	'squirtle': 45,
	'wartortle': 45,
	'blastoise': 45,
	'caterpie': 255,
	'metapod': 120,
	'butterfree': 45,
	'weedle': 255,
	'kakuna': 120,
	'beedrill': 45,
	'pidgey': 255,
	'pidgeotto': 120,
	'pidgeot': 45,
	'rattata': 255,
	'raticate': 127,
	'spearow': 255,
	'fearow': 90,
	'ekans': 255,
	'arbok': 90,
	'pikachu': 190,
	'raichu': 75,
	'sandshrew': 255,
	'sandslash': 90,
	'nidoranf': 235,
	'nidorina': 120,
	'nidoqueen': 45,
	'nidoranm': 235,
	'nidorino': 120,
	'nidoking': 45,
	'clefairy': 150,
	'clefable': 25,
	'vulpix': 190,
	'ninetales': 75,
	'jigglypuff': 170,
	'wigglytuff': 50,
	'zubat': 255,
	'golbat': 90,
	'oddish': 255,
	'gloom': 120,
	'vileplume': 45,
	'paras': 190,
	'parasect': 75,
	'venonat': 190,
	'venomoth': 75,
	'diglett': 255,
	'dugtrio': 50,
	'meowth': 255,
	'persian': 90,
	'psyduck': 190,
	'golduck': 75,
	'mankey': 190,
	'primeape': 75,
	'growlithe': 190,
	'arcanine': 75,
	'poliwag': 255,
	'poliwhirl': 120,
	'poliwrath': 45,
	'abra': 200,
	'kadabra': 100,
	'alakazam': 50,
	'machop': 180,
	'machoke': 90,
	'machamp': 45,
	'bellsprout': 255,
	'weepinbell': 120,
	'victreebel': 45,
	'tentacool': 190,
	'tentacruel': 60,
	'geodude': 255,
	'graveler': 120,
	'golem': 45,
	'ponyta': 190,
	'rapidash': 60,
	'slowpoke': 190,
	'slowbro': 75,
	'magnemite': 190,
	'magneton': 60,
	'farfetchd': 45,
	'doduo': 190,
	'dodrio': 45,
	'seel': 190,
	'dewgong': 75,
	'grimer': 190,
	'muk': 75,
	'shellder': 190,
	'cloyster': 60,
	'gastly': 190,
	'haunter': 90,
	'gengar': 45,
	'onix': 45,
	'drowzee': 190,
	'hypno': 75,
	'krabby': 225,
	'kingler': 60,
	'voltorb': 190,
	'electrode': 60,
	'exeggcute': 90,
	'exeggutor': 45,
	'cubone': 190,
	'marowak': 75,
	'hitmonlee': 45,
	'hitmonchan': 45,
	'lickitung': 45,
	'koffing': 190,
	'weezing': 60,
	'rhyhorn': 120,
	'rhydon': 60,
	'chansey': 30,
	'tangela': 45,
	'kangaskhan': 45,
	'horsea': 225,
	'seadra': 75,
	'goldeen': 225,
	'seaking': 60,
	'staryu': 225,
	'starmie': 60,
	'mrmime': 45,
	'scyther': 45,
	'jynx': 45,
	'electabuzz': 45,
	'magmar': 45,
	'pinsir': 45,
	'tauros': 45,
	'magikarp': 255,
	'gyarados': 45,
	'lapras': 45,
	'ditto': 35,
	'eevee': 45,
	'vaporeon': 45,
	'jolteon': 45,
	'flareon': 45,
	'porygon': 45,
	'omanyte': 45,
	'omastar': 45,
	'kabuto': 45,
	'kabutops': 45,
	'aerodactyl': 45,
	'snorlax': 25,
	'articuno': 3,
	'zapdos': 3,
	'moltres': 3,
	'dratini': 45,
	'dragonair': 45,
	'dragonite': 45,
	'mewtwo': 3,
	'mew': 45,
	'chikorita': 45,
	'bayleef': 45,
	'meganium': 45,
	'cyndaquil': 45,
	'quilava': 45,
	'typhlosion': 45,
	'totodile': 45,
	'croconaw': 45,
	'feraligatr': 45,
	'sentret': 255,
	'furret': 90,
	'hoothoot': 255,
	'noctowl': 90,
	'ledyba': 255,
	'ledian': 90,
	'spinarak': 255,
	'ariados': 90,
	'crobat': 90,
	'chinchou': 190,
	'lanturn': 75,
	'pichu': 190,
	'cleffa': 150,
	'igglybuff': 170,
	'togepi': 190,
	'togetic': 75,
	'natu': 190,
	'xatu': 75,
	'mareep': 235,
	'flaaffy': 120,
	'ampharos': 45,
	'bellossom': 45,
	'marill': 190,
	'azumarill': 75,
	'sudowoodo': 65,
	'politoed': 45,
	'hoppip': 255,
	'skiploom': 120,
	'jumpluff': 45,
	'aipom': 45,
	'sunkern': 235,
	'sunflora': 120,
	'yanma': 75,
	'wooper': 255,
	'quagsire': 90,
	'espeon': 45,
	'umbreon': 45,
	'murkrow': 30,
	'slowking': 70,
	'misdreavus': 45,
	'unown': 225,
	'wobbuffet': 45,
	'girafarig': 60,
	'pineco': 190,
	'forretress': 75,
	'dunsparce': 190,
	'gligar': 60,
	'steelix': 25,
	'snubbull': 190,
	'granbull': 75,
	'qwilfish': 45,
	'scizor': 25,
	'shuckle': 190,
	'heracross': 45,
	'sneasel': 60,
	'teddiursa': 120,
	'ursaring': 60,
	'slugma': 190,
	'magcargo': 75,
	'swinub': 225,
	'piloswine': 75,
	'corsola': 60,
	'remoraid': 190,
	'octillery': 75,
	'delibird': 45,
	'mantine': 25,
	'skarmory': 25,
	'houndour': 120,
	'houndoom': 45,
	'kingdra': 45,
	'phanpy': 120,
	'donphan': 60,
	'porygon2': 45,
	'stantler': 45,
	'smeargle': 45,
	'tyrogue': 75,
	'hitmontop': 45,
	'smoochum': 45,
	'elekid': 45,
	'magby': 45,
	'miltank': 45,
	'blissey': 30,
	'raikou': 3,
	'entei': 3,
	'suicune': 3,
	'larvitar': 45,
	'pupitar': 45,
	'tyranitar': 45,
	'lugia': 3,
	'hooh': 3,
	'celebi': 45,
	'treecko': 45,
	'grovyle': 45,
	'sceptile': 45,
	'torchic': 45,
	'combusken': 45,
	'blaziken': 45,
	'mudkip': 45,
	'marshtomp': 45,
	'swampert': 45,
	'poochyena': 255,
	'mightyena': 127,
	'zigzagoon': 255,
	'linoone': 90,
	'wurmple': 255,
	'silcoon': 120,
	'beautifly': 45,
	'cascoon': 120,
	'dustox': 45,
	'lotad': 255,
	'lombre': 120,
	'ludicolo': 45,
	'seedot': 255,
	'nuzleaf': 120,
	'shiftry': 45,
	'taillow': 200,
	'swellow': 45,
	'wingull': 190,
	'pelipper': 45,
	'ralts': 235,
	'kirlia': 120,
	'gardevoir': 45,
	'surskit': 200,
	'masquerain': 75,
	'shroomish': 255,
	'breloom': 90,
	'slakoth': 255,
	'vigoroth': 120,
	'slaking': 45,
	'nincada': 255,
	'ninjask': 120,
	'shedinja': 45,
	'whismur': 190,
	'loudred': 120,
	'exploud': 45,
	'makuhita': 180,
	'hariyama': 200,
	'azurill': 150,
	'nosepass': 255,
	'skitty': 255,
	'delcatty': 60,
	'sableye': 45,
	'mawile': 45,
	'aron': 180,
	'lairon': 90,
	'aggron': 45,
	'meditite': 180,
	'medicham': 90,
	'electrike': 120,
	'manectric': 45,
	'plusle': 200,
	'minun': 200,
	'volbeat': 150,
	'illumise': 150,
	'roselia': 150,
	'gulpin': 225,
	'swalot': 75,
	'carvanha': 225,
	'sharpedo': 60,
	'wailmer': 125,
	'wailord': 60,
	'numel': 255,
	'camerupt': 150,
	'torkoal': 90,
	'spoink': 255,
	'grumpig': 60,
	'spinda': 255,
	'trapinch': 255,
	'vibrava': 120,
	'flygon': 45,
	'cacnea': 190,
	'cacturne': 60,
	'swablu': 255,
	'altaria': 45,
	'zangoose': 90,
	'seviper': 90,
	'lunatone': 45,
	'solrock': 45,
	'barboach': 190,
	'whiscash': 75,
	'corphish': 205,
	'crawdaunt': 155,
	'baltoy': 255,
	'claydol': 90,
	'lileep': 45,
	'cradily': 45,
	'anorith': 45,
	'armaldo': 45,
	'feebas': 255,
	'milotic': 60,
	'castform': 45,
	'kecleon': 200,
	'shuppet': 225,
	'banette': 45,
	'duskull': 190,
	'dusclops': 90,
	'tropius': 200,
	'chimecho': 45,
	'absol': 30,
	'wynaut': 125,
	'snorunt': 190,
	'glalie': 75,
	'spheal': 255,
	'sealeo': 120,
	'walrein': 45,
	'clamperl': 255,
	'huntail': 60,
	'gorebyss': 60,
	'relicanth': 25,
	'luvdisc': 225,
	'bagon': 45,
	'shelgon': 45,
	'salamence': 45,
	'beldum': 3,
	'metang': 3,
	'metagross': 3,
	'regirock': 3,
	'regice': 3,
	'registeel': 3,
	'latias': 3,
	'latios': 3,
	'kyogre': 3,
	'groudon': 3,
	'rayquaza': 45,
	'jirachi': 3,
	'deoxysnormal': 3,
	'turtwig': 45,
	'grotle': 45,
	'torterra': 45,
	'chimchar': 45,
	'monferno': 45,
	'infernape': 45,
	'piplup': 45,
	'prinplup': 45,
	'empoleon': 45,
	'starly': 255,
	'staravia': 120,
	'staraptor': 45,
	'bidoof': 255,
	'bibarel': 127,
	'kricketot': 255,
	'kricketune': 45,
	'shinx': 235,
	'luxio': 120,
	'luxray': 45,
	'budew': 255,
	'roserade': 75,
	'cranidos': 45,
	'rampardos': 45,
	'shieldon': 45,
	'bastiodon': 45,
	'burmy': 120,
	'wormadamplant': 45,
	'mothim': 45,
	'combee': 120,
	'vespiquen': 45,
	'pachirisu': 200,
	'buizel': 190,
	'floatzel': 75,
	'cherubi': 190,
	'cherrim': 75,
	'shellos': 190,
	'gastrodon': 75,
	'ambipom': 45,
	'drifloon': 125,
	'drifblim': 60,
	'buneary': 190,
	'lopunny': 60,
	'mismagius': 45,
	'honchkrow': 30,
	'glameow': 190,
	'purugly': 75,
	'chingling': 120,
	'stunky': 225,
	'skuntank': 60,
	'bronzor': 255,
	'bronzong': 90,
	'bonsly': 255,
	'mimejr': 145,
	'happiny': 130,
	'chatot': 30,
	'spiritomb': 100,
	'gible': 45,
	'gabite': 45,
	'garchomp': 45,
	'munchlax': 50,
	'riolu': 75,
	'lucario': 45,
	'hippopotas': 140,
	'hippowdon': 60,
	'skorupi': 120,
	'drapion': 45,
	'croagunk': 140,
	'toxicroak': 75,
	'carnivine': 200,
	'finneon': 190,
	'lumineon': 75,
	'mantyke': 25,
	'snover': 120,
	'abomasnow': 60,
	'weavile': 45,
	'magnezone': 30,
	'lickilicky': 30,
	'rhyperior': 30,
	'tangrowth': 30,
	'electivire': 30,
	'magmortar': 30,
	'togekiss': 30,
	'yanmega': 30,
	'leafeon': 45,
	'glaceon': 45,
	'gliscor': 30,
	'mamoswine': 50,
	'porygonz': 30,
	'gallade': 45,
	'probopass': 60,
	'dusknoir': 45,
	'froslass': 75,
	'rotom': 45,
	'uxie': 3,
	'mesprit': 3,
	'azelf': 3,
	'dialga': 3,
	'palkia': 3,
	'heatran': 3,
	'regigigas': 3,
	'giratinaaltered': 3,
	'cresselia': 3,
	'phione': 30,
	'manaphy': 3,
	'darkrai': 3,
	'shayminland': 45,
	'arceus': 3,
	'victini': 3,
	'snivy': 45,
	'servine': 45,
	'serperior': 45,
	'tepig': 45,
	'pignite': 45,
	'emboar': 45,
	'oshawott': 45,
	'dewott': 45,
	'samurott': 45,
	'patrat': 255,
	'watchog': 255,
	'lillipup': 255,
	'herdier': 120,
	'stoutland': 45,
	'purrloin': 255,
	'liepard': 90,
	'pansage': 190,
	'simisage': 75,
	'pansear': 190,
	'simisear': 75,
	'panpour': 190,
	'simipour': 75,
	'munna': 190,
	'musharna': 75,
	'pidove': 255,
	'tranquill': 120,
	'unfezant': 45,
	'blitzle': 190,
	'zebstrika': 75,
	'roggenrola': 255,
	'boldore': 120,
	'gigalith': 45,
	'woobat': 190,
	'swoobat': 45,
	'drilbur': 120,
	'excadrill': 60,
	'audino': 255,
	'timburr': 180,
	'gurdurr': 90,
	'conkeldurr': 45,
	'tympole': 255,
	'palpitoad': 120,
	'seismitoad': 45,
	'throh': 45,
	'sawk': 45,
	'sewaddle': 255,
	'swadloon': 120,
	'leavanny': 45,
	'venipede': 255,
	'whirlipede': 120,
	'scolipede': 45,
	'cottonee': 190,
	'whimsicott': 75,
	'petilil': 190,
	'lilligant': 75,
	'basculinredstriped': 25,
	'sandile': 180,
	'krokorok': 90,
	'krookodile': 45,
	'darumaka': 120,
	'darmanitanstandard': 60,
	'maractus': 255,
	'dwebble': 190,
	'crustle': 75,
	'scraggy': 180,
	'scrafty': 90,
	'sigilyph': 45,
	'yamask': 190,
	'cofagrigus': 90,
	'tirtouga': 45,
	'carracosta': 45,
	'archen': 45,
	'archeops': 45,
	'trubbish': 190,
	'garbodor': 60,
	'zorua': 75,
	'zoroark': 45,
	'minccino': 255,
	'cinccino': 60,
	'gothita': 200,
	'gothorita': 100,
	'gothitelle': 50,
	'solosis': 200,
	'duosion': 100,
	'reuniclus': 50,
	'ducklett': 190,
	'swanna': 45,
	'vanillite': 255,
	'vanillish': 120,
	'vanilluxe': 45,
	'deerling': 190,
	'sawsbuck': 75,
	'emolga': 200,
	'karrablast': 200,
	'escavalier': 75,
	'foongus': 190,
	'amoonguss': 75,
	'frillish': 190,
	'jellicent': 60,
	'alomomola': 75,
	'joltik': 190,
	'galvantula': 75,
	'ferroseed': 255,
	'ferrothorn': 90,
	'klink': 130,
	'klang': 60,
	'klinklang': 30,
	'tynamo': 190,
	'eelektrik': 60,
	'eelektross': 30,
	'elgyem': 255,
	'beheeyem': 90,
	'litwick': 190,
	'lampent': 90,
	'chandelure': 45,
	'axew': 75,
	'fraxure': 60,
	'haxorus': 45,
	'cubchoo': 120,
	'beartic': 60,
	'cryogonal': 25,
	'shelmet': 200,
	'accelgor': 75,
	'stunfisk': 75,
	'mienfoo': 180,
	'mienshao': 45,
	'druddigon': 45,
	'golett': 190,
	'golurk': 90,
	'pawniard': 120,
	'bisharp': 45,
	'bouffalant': 45,
	'rufflet': 190,
	'braviary': 60,
	'vullaby': 190,
	'mandibuzz': 60,
	'heatmor': 90,
	'durant': 90,
	'deino': 45,
	'zweilous': 45,
	'hydreigon': 45,
	'larvesta': 45,
	'volcarona': 15,
	'cobalion': 3,
	'terrakion': 3,
	'virizion': 3,
	'tornadusincarnate': 3,
	'thundurusincarnate': 3,
	'reshiram': 3,
	'zekrom': 3,
	'landorusincarnate': 3,
	'kyurem': 3,
	'keldeoordinary': 3,
	'meloettaaria': 3,
	'genesect': 3,
	'chespin': 45,
	'quilladin': 45,
	'chesnaught': 45,
	'fennekin': 45,
	'braixen': 45,
	'delphox': 45,
	'froakie': 45,
	'frogadier': 45,
	'greninja': 45,
	'bunnelby': 255,
	'diggersby': 127,
	'fletchling': 255,
	'fletchinder': 120,
	'talonflame': 45,
	'scatterbug': 255,
	'spewpa': 120,
	'vivillon': 45,
	'litleo': 220,
	'pyroar': 65,
	'flabebe': 225,
	'floette': 120,
	'florges': 45,
	'skiddo': 200,
	'gogoat': 45,
	'pancham': 220,
	'pangoro': 65,
	'furfrou': 160,
	'espurr': 190,
	'meowsticmale': 75,
	'honedge': 180,
	'doublade': 90,
	'aegislashshield': 45,
	'spritzee': 200,
	'aromatisse': 140,
	'swirlix': 200,
	'slurpuff': 140,
	'inkay': 190,
	'malamar': 80,
	'binacle': 120,
	'barbaracle': 45,
	'skrelp': 225,
	'dragalge': 55,
	'clauncher': 225,
	'clawitzer': 55,
	'helioptile': 190,
	'heliolisk': 75,
	'tyrunt': 45,
	'tyrantrum': 45,
	'amaura': 45,
	'aurorus': 45,
	'sylveon': 45,
	'hawlucha': 100,
	'dedenne': 180,
	'carbink': 60,
	'goomy': 45,
	'sliggoo': 45,
	'goodra': 45,
	'klefki': 75,
	'phantump': 120,
	'trevenant': 60,
	'pumpkabooaverage': 120,
	'gourgeistaverage': 60,
	'bergmite': 190,
	'avalugg': 55,
	'noibat': 190,
	'noivern': 45,
	'xerneas': 45,
	'yveltal': 45,
	'zygarde50': 3,
	'diancie': 3,
	'hoopa': 3,
	'volcanion': 3,
	'rowlet': 45,
	'dartrix': 45,
	'decidueye': 45,
	'litten': 45,
	'torracat': 45,
	'incineroar': 45,
	'popplio': 45,
	'brionne': 45,
	'primarina': 45,
	'pikipek': 255,
	'trumbeak': 120,
	'toucannon': 45,
	'yungoos': 255,
	'gumshoos': 127,
	'grubbin': 255,
	'charjabug': 120,
	'vikavolt': 45,
	'crabrawler': 225,
	'crabominable': 60,
	'oricoriobaile': 45,
	'cutiefly': 190,
	'ribombee': 75,
	'rockruff': 190,
	'lycanrocmidday': 90,
	'wishiwashisolo': 60,
	'mareanie': 190,
	'toxapex': 75,
	'mudbray': 190,
	'mudsdale': 60,
	'dewpider': 200,
	'araquanid': 100,
	'fomantis': 190,
	'lurantis': 75,
	'morelull': 190,
	'shiinotic': 75,
	'salandit': 120,
	'salazzle': 45,
	'stufful': 140,
	'bewear': 70,
	'bounsweet': 235,
	'steenee': 120,
	'tsareena': 45,
	'comfey': 60,
	'oranguru': 45,
	'passimian': 45,
	'wimpod': 90,
	'golisopod': 45,
	'sandygast': 140,
	'palossand': 60,
	'pyukumuku': 60,
	'typenull': 3,
	'silvally': 3,
	'miniorredmeteor': 30,
	'komala': 45,
	'turtonator': 70,
	'togedemaru': 180,
	'mimikyudisguised': 45,
	'bruxish': 80,
	'drampa': 70,
	'dhelmise': 25,
	'jangmoo': 45,
	'hakamoo': 45,
	'kommoo': 45,
	'tapukoko': 3,
	'tapulele': 3,
	'tapubulu': 3,
	'tapufini': 3,
	'cosmog': 45,
	'cosmoem': 45,
	'solgaleo': 45,
	'lunala': 45,
	'nihilego': 45,
	'buzzwole': 45,
	'pheromosa': 45,
	'xurkitree': 45,
	'celesteela': 45,
	'kartana': 45,
	'guzzlord': 45,
	'necrozma': 255,
	'magearna': 3,
	'marshadow': 3,
	'poipole': 45,
	'naganadel': 45,
	'stakataka': 30,
	'blacephalon': 30,
	'zeraora': 3,
	'meltan': 3,
	'melmetal': 3,
	'grookey': 45,
	'thwackey': 45,
	'rillaboom': 45,
	'scorbunny': 45,
	'raboot': 45,
	'cinderace': 45,
	'sobble': 45,
	'drizzile': 45,
	'inteleon': 45,
	'skwovet': 255,
	'greedent': 90,
	'rookidee': 255,
	'corvisquire': 120,
	'corviknight': 45,
	'blipbug': 255,
	'dottler': 120,
	'orbeetle': 45,
	'nickit': 255,
	'thievul': 127,
	'gossifleur': 190,
	'eldegoss': 75,
	'wooloo': 255,
	'dubwool': 127,
	'chewtle': 255,
	'drednaw': 75,
	'yamper': 255,
	'boltund': 45,
	'rolycoly': 255,
	'carkol': 120,
	'coalossal': 45,
	'applin': 255,
	'flapple': 45,
	'appletun': 45,
	'silicobra': 255,
	'sandaconda': 120,
	'cramorant': 45,
	'arrokuda': 255,
	'barraskewda': 60,
	'toxel': 75,
	'toxtricityamped': 45,
	'sizzlipede': 190,
	'centiskorch': 75,
	'clobbopus': 180,
	'grapploct': 45,
	'sinistea': 120,
	'polteageist': 60,
	'hatenna': 235,
	'hattrem': 120,
	'hatterene': 45,
	'impidimp': 255,
	'morgrem': 120,
	'grimmsnarl': 45,
	'obstagoon': 45,
	'perrserker': 90,
	'cursola': 30,
	'sirfetchd': 45,
	'mrrime': 45,
	'runerigus': 90,
	'milcery': 200,
	'alcremie': 100,
	'falinks': 45,
	'pincurchin': 75,
	'snom': 190,
	'frosmoth': 75,
	'stonjourner': 60,
	'eiscueice': 60,
	'indeedeemale': 30,
	'morpekofullbelly': 180,
	'cufant': 190,
	'copperajah': 90,
	'dracozolt': 45,
	'arctozolt': 45,
	'dracovish': 45,
	'arctovish': 45,
	'duraludon': 45,
	'dreepy': 45,
	'drakloak': 45,
	'dragapult': 45,
	'zacian': 10,
	'zamazenta': 10,
	'eternatus': 255,
	'kubfu': 3,
	'urshifusinglestrike': 3,
	'zarude': 3,
	'regieleki': 3,
	'regidrago': 3,
	'glastrier': 3,
	'spectrier': 3,
	'calyrex': 3,
	'wyrdeer': 135,
	'kleavor': 115,
	'ursaluna': 75,
	'basculegionmale': 135,
	'sneasler': 135,
	'overqwil': 135,
	'enamorusincarnate': 3,
	'sprigatito': 45,
	'floragato': 45,
	'meowscarada': 45,
	'fuecoco': 45,
	'crocalor': 45,
	'skeledirge': 45,
	'quaxly': 45,
	'quaxwell': 45,
	'quaquaval': 45,
	'lechonk': 255,
	'oinkolognemale': 100,
	'tarountula': 255,
	'spidops': 120,
	'nymble': 190,
	'lokix': 30,
	'pawmi': 190,
	'pawmo': 80,
	'pawmot': 45,
	'tandemaus': 150,
	'mausholdfamilyoffour': 75,
	'fidough': 190,
	'dachsbun': 90,
	'smoliv': 255,
	'dolliv': 120,
	'arboliva': 45,
	'squawkabillygreenplumage': 190,
	'nacli': 255,
	'naclstack': 120,
	'garganacl': 45,
	'charcadet': 90,
	'armarouge': 25,
	'ceruledge': 25,
	'tadbulb': 190,
	'bellibolt': 50,
	'wattrel': 180,
	'kilowattrel': 90,
	'maschiff': 150,
	'mabosstiff': 75,
	'shroodle': 190,
	'grafaiai': 90,
	'bramblin': 190,
	'brambleghast': 45,
	'toedscool': 190,
	'toedscruel': 90,
	'klawf': 120,
	'capsakid': 190,
	'scovillain': 75,
	'rellor': 190,
	'rabsca': 45,
	'flittle': 120,
	'espathra': 60,
	'tinkatink': 190,
	'tinkatuff': 90,
	'tinkaton': 45,
	'wiglett': 255,
	'wugtrio': 50,
	'bombirdier': 25,
	'finizen': 200,
	'palafinzero': 45,
	'varoom': 190,
	'revavroom': 75,
	'cyclizar': 190,
	'orthworm': 25,
	'glimmet': 70,
	'glimmora': 25,
	'greavard': 120,
	'houndstone': 60,
	'flamigo': 100,
	'cetoddle': 150,
	'cetitan': 50,
	'veluza': 100,
	'dondozo': 25,
	'tatsugiricurly': 100,
	'annihilape': 45,
	'clodsire': 90,
	'farigiraf': 45,
	'dudunsparcetwosegment': 45,
	'kingambit': 25,
	'greattusk': 30,
	'screamtail': 50,
	'brutebonnet': 50,
	'fluttermane': 30,
	'slitherwing': 30,
	'sandyshocks': 30,
	'irontreads': 30,
	'ironbundle': 50,
	'ironhands': 50,
	'ironjugulis': 30,
	'ironmoth': 30,
	'ironthorns': 30,
	'frigibax': 45,
	'arctibax': 25,
	'baxcalibur': 10,
	'gimmighoul': 45,
	'gholdengo': 45,
	'wochien': 6,
	'chienpao': 6,
	'tinglu': 6,
	'chiyu': 6,
	'roaringmoon': 10,
	'ironvaliant': 10,
	'koraidon': 3,
	'miraidon': 3,
	'walkingwake': 5,
	'ironleaves': 5,
	'dipplin': 45,
	'poltchageist': 120,
	'sinistcha': 60,
	'okidogi': 3,
	'munkidori': 3,
	'fezandipiti': 3,
	'ogerpon': 5,
	'archaludon': 10,
	'hydrapple': 10,
	'gougingfire': 10,
	'ragingbolt': 10,
	'ironboulder': 10,
	'ironcrown': 10,
	'terapagos': 255,
	'pecharunt': 3,
};

export const MANUAL_EV_YIELDS: Record<string, {
	hp?: number,
	atk?: number,
	def?: number,
	spa?: number,
	spd?: number,
	spe?: number,
}> = {
	'bulbasaur': { spa: 1 },
	'ivysaur': { spa: 1, spd: 1 },
	'venusaur': { spa: 2, spd: 1 },
	'charmander': { spe: 1 },
	'charmeleon': { spa: 1, spe: 1 },
	'charizard': { spa: 3 },
	'squirtle': { def: 1 },
	'wartortle': { def: 1, spd: 1 },
	'blastoise': { spd: 3 },
	'caterpie': { hp: 1 },
	'metapod': { def: 2 },
	'butterfree': { spa: 2, spd: 1 },
	'weedle': { spe: 1 },
	'kakuna': { def: 2 },
	'beedrill': { atk: 2, spd: 1 },
	'pidgey': { spe: 1 },
	'pidgeotto': { spe: 2 },
	'pidgeot': { spe: 3 },
	'rattata': { spe: 1 },
	'raticate': { spe: 2 },
	'spearow': { spe: 1 },
	'fearow': { spe: 2 },
	'ekans': { atk: 1 },
	'arbok': { atk: 2 },
	'pikachu': { spe: 2 },
	'raichu': { spe: 3 },
	'sandshrew': { def: 1 },
	'sandslash': { def: 2 },
	'nidoranf': { hp: 1 },
	'nidorina': { hp: 2 },
	'nidoqueen': { hp: 3 },
	'nidoranm': { atk: 1 },
	'nidorino': { atk: 2 },
	'nidoking': { atk: 3 },
	'clefairy': { hp: 2 },
	'clefable': { hp: 3 },
	'vulpix': { spe: 1 },
	'ninetales': { spd: 1, spe: 1 },
	'jigglypuff': { hp: 2 },
	'wigglytuff': { hp: 3 },
	'zubat': { spe: 1 },
	'golbat': { spe: 2 },
	'oddish': { spa: 1 },
	'gloom': { spa: 2 },
	'vileplume': { spa: 3 },
	'paras': { atk: 1 },
	'parasect': { atk: 2, def: 1 },
	'venonat': { spd: 1 },
	'venomoth': { spa: 1, spe: 1 },
	'diglett': { spe: 1 },
	'dugtrio': { spe: 2 },
	'meowth': { spe: 1 },
	'persian': { spe: 2 },
	'psyduck': { spa: 1 },
	'golduck': { spa: 2 },
	'mankey': { atk: 1 },
	'primeape': { atk: 2 },
	'growlithe': { atk: 1 },
	'arcanine': { atk: 2 },
	'poliwag': { spe: 1 },
	'poliwhirl': { spe: 2 },
	'poliwrath': { def: 3 },
	'abra': { spa: 1 },
	'kadabra': { spa: 2 },
	'alakazam': { spa: 3 },
	'machop': { atk: 1 },
	'machoke': { atk: 2 },
	'machamp': { atk: 3 },
	'bellsprout': { atk: 1 },
	'weepinbell': { atk: 2 },
	'victreebel': { atk: 3 },
	'tentacool': { spd: 1 },
	'tentacruel': { spd: 2 },
	'geodude': { def: 1 },
	'graveler': { def: 2 },
	'golem': { def: 3 },
	'ponyta': { spe: 1 },
	'rapidash': { spe: 2 },
	'slowpoke': { hp: 1 },
	'slowbro': { def: 2 },
	'magnemite': { spa: 1 },
	'magneton': { spa: 2 },
	'farfetchd': { atk: 1 },
	'doduo': { atk: 1 },
	'dodrio': { atk: 2 },
	'seel': { spd: 1 },
	'dewgong': { spd: 2 },
	'grimer': { hp: 1 },
	'muk': { hp: 1, atk: 1 },
	'shellder': { def: 1 },
	'cloyster': { def: 2 },
	'gastly': { spa: 1 },
	'haunter': { spa: 2 },
	'gengar': { spa: 3 },
	'onix': { def: 1 },
	'drowzee': { spd: 1 },
	'hypno': { spd: 2 },
	'krabby': { atk: 1 },
	'kingler': { atk: 2 },
	'voltorb': { spe: 1 },
	'electrode': { spe: 2 },
	'exeggcute': { def: 1 },
	'exeggutor': { spa: 2 },
	'cubone': { def: 1 },
	'marowak': { def: 2 },
	'hitmonlee': { atk: 2 },
	'hitmonchan': { spd: 2 },
	'lickitung': { hp: 2 },
	'koffing': { def: 1 },
	'weezing': { def: 2 },
	'rhyhorn': { def: 1 },
	'rhydon': { atk: 2 },
	'chansey': { hp: 2 },
	'tangela': { def: 1 },
	'kangaskhan': { hp: 2 },
	'horsea': { spa: 1 },
	'seadra': { def: 1, spa: 1 },
	'goldeen': { atk: 1 },
	'seaking': { atk: 2 },
	'staryu': { spe: 1 },
	'starmie': { spe: 2 },
	'mrmime': { spd: 2 },
	'scyther': { atk: 1 },
	'jynx': { spa: 2 },
	'electabuzz': { spe: 2 },
	'magmar': { spa: 2 },
	'pinsir': { atk: 2 },
	'tauros': { atk: 1, spe: 1 },
	'magikarp': { spe: 1 },
	'gyarados': { atk: 2 },
	'lapras': { hp: 2 },
	'ditto': { hp: 1 },
	'eevee': { spd: 1 },
	'vaporeon': { hp: 2 },
	'jolteon': { spe: 2 },
	'flareon': { atk: 2 },
	'porygon': { spa: 1 },
	'omanyte': { def: 1 },
	'omastar': { def: 2 },
	'kabuto': { def: 1 },
	'kabutops': { atk: 2 },
	'aerodactyl': { spe: 2 },
	'snorlax': { hp: 2 },
	'articuno': { spd: 3 },
	'zapdos': { spa: 3 },
	'moltres': { spa: 3 },
	'dratini': { atk: 1 },
	'dragonair': { atk: 2 },
	'dragonite': { atk: 3 },
	'mewtwo': { spa: 3 },
	'mew': { hp: 3 },
	'chikorita': { spd: 1 },
	'bayleef': { def: 1, spd: 1 },
	'meganium': { def: 1, spd: 2 },
	'cyndaquil': { spe: 1 },
	'quilava': { spa: 1, spe: 1 },
	'typhlosion': { spa: 3 },
	'totodile': { atk: 1 },
	'croconaw': { atk: 1, def: 1 },
	'feraligatr': { atk: 2, def: 1 },
	'sentret': { atk: 1 },
	'furret': { spe: 2 },
	'hoothoot': { hp: 1 },
	'noctowl': { hp: 2 },
	'ledyba': { spd: 1 },
	'ledian': { spd: 2 },
	'spinarak': { atk: 1 },
	'ariados': { atk: 2 },
	'crobat': { spe: 3 },
	'chinchou': { hp: 1 },
	'lanturn': { hp: 2 },
	'pichu': { spe: 1 },
	'cleffa': { spd: 1 },
	'igglybuff': { hp: 1 },
	'togepi': { spd: 1 },
	'togetic': { spd: 2 },
	'natu': { spa: 1 },
	'xatu': { spa: 1, spe: 1 },
	'mareep': { spa: 1 },
	'flaaffy': { spa: 2 },
	'ampharos': { spa: 3 },
	'bellossom': { spd: 3 },
	'marill': { hp: 2 },
	'azumarill': { hp: 3 },
	'sudowoodo': { def: 2 },
	'politoed': { spd: 3 },
	'hoppip': { spd: 1 },
	'skiploom': { spe: 2 },
	'jumpluff': { spe: 3 },
	'aipom': { spe: 1 },
	'sunkern': { spa: 1 },
	'sunflora': { spa: 2 },
	'yanma': { spe: 1 },
	'wooper': { hp: 1 },
	'quagsire': { hp: 2 },
	'espeon': { spa: 2 },
	'umbreon': { spd: 2 },
	'murkrow': { spe: 1 },
	'slowking': { spd: 2 },
	'misdreavus': { spd: 1 },
	'unown': { atk: 1, spa: 1 },
	'wobbuffet': { hp: 2 },
	'girafarig': { spa: 2 },
	'pineco': { def: 1 },
	'forretress': { def: 2 },
	'dunsparce': { hp: 1 },
	'gligar': { def: 1 },
	'steelix': { def: 2 },
	'snubbull': { atk: 1 },
	'granbull': { atk: 2 },
	'qwilfish': { atk: 1 },
	'scizor': { atk: 2 },
	'shuckle': { def: 1, spd: 1 },
	'heracross': { atk: 2 },
	'sneasel': { spe: 1 },
	'teddiursa': { atk: 1 },
	'ursaring': { atk: 2 },
	'slugma': { spa: 1 },
	'magcargo': { def: 2 },
	'swinub': { atk: 1 },
	'piloswine': { hp: 1, atk: 1 },
	'corsola': { def: 1, spd: 1 },
	'remoraid': { spa: 1 },
	'octillery': { atk: 1, spa: 1 },
	'delibird': { spe: 1 },
	'mantine': { spd: 2 },
	'skarmory': { def: 2 },
	'houndour': { spa: 1 },
	'houndoom': { spa: 2 },
	'kingdra': { atk: 1, spa: 1, spd: 1 },
	'phanpy': { hp: 1 },
	'donphan': { atk: 1, def: 1 },
	'porygon2': { spa: 2 },
	'stantler': { atk: 1 },
	'smeargle': { spe: 1 },
	'tyrogue': { atk: 1 },
	'hitmontop': { spd: 2 },
	'smoochum': { spa: 1 },
	'elekid': { spe: 1 },
	'magby': { spe: 1 },
	'miltank': { def: 2 },
	'blissey': { hp: 3 },
	'raikou': { spa: 1, spe: 2 },
	'entei': { hp: 1, atk: 2 },
	'suicune': { def: 1, spd: 2 },
	'larvitar': { atk: 1 },
	'pupitar': { atk: 2 },
	'tyranitar': { atk: 3 },
	'lugia': { spd: 3 },
	'hooh': { spd: 3 },
	'celebi': { hp: 3 },
	'treecko': { spe: 1 },
	'grovyle': { spe: 2 },
	'sceptile': { spe: 3 },
	'torchic': { spa: 1 },
	'combusken': { atk: 1, spa: 1 },
	'blaziken': { atk: 3 },
	'mudkip': { atk: 1 },
	'marshtomp': { atk: 2 },
	'swampert': { atk: 3 },
	'poochyena': { atk: 1 },
	'mightyena': { atk: 2 },
	'zigzagoon': { spe: 1 },
	'linoone': { spe: 2 },
	'wurmple': { hp: 1 },
	'silcoon': { def: 2 },
	'beautifly': { spa: 3 },
	'cascoon': { def: 2 },
	'dustox': { spd: 3 },
	'lotad': { spd: 1 },
	'lombre': { spd: 2 },
	'ludicolo': { spd: 3 },
	'seedot': { def: 1 },
	'nuzleaf': { atk: 2 },
	'shiftry': { atk: 3 },
	'taillow': { spe: 1 },
	'swellow': { spe: 2 },
	'wingull': { spe: 1 },
	'pelipper': { def: 2 },
	'ralts': { spa: 1 },
	'kirlia': { spa: 2 },
	'gardevoir': { spa: 3 },
	'surskit': { spe: 1 },
	'masquerain': { spa: 1, spd: 1 },
	'shroomish': { hp: 1 },
	'breloom': { atk: 2 },
	'slakoth': { hp: 1 },
	'vigoroth': { spe: 2 },
	'slaking': { hp: 3 },
	'nincada': { def: 1 },
	'ninjask': { spe: 2 },
	'shedinja': { hp: 2 },
	'whismur': { hp: 1 },
	'loudred': { hp: 2 },
	'exploud': { hp: 3 },
	'makuhita': { hp: 1 },
	'hariyama': { hp: 2 },
	'azurill': { hp: 1 },
	'nosepass': { def: 1 },
	'skitty': { spe: 1 },
	'delcatty': { hp: 1, spe: 1 },
	'sableye': { atk: 1, def: 1 },
	'mawile': { atk: 1, def: 1 },
	'aron': { def: 1 },
	'lairon': { def: 2 },
	'aggron': { def: 3 },
	'meditite': { spe: 1 },
	'medicham': { spe: 2 },
	'electrike': { spe: 1 },
	'manectric': { spe: 2 },
	'plusle': { spe: 1 },
	'minun': { spe: 1 },
	'volbeat': { spe: 1 },
	'illumise': { spe: 1 },
	'roselia': { spa: 2 },
	'gulpin': { hp: 1 },
	'swalot': { hp: 2 },
	'carvanha': { atk: 1 },
	'sharpedo': { atk: 2 },
	'wailmer': { hp: 1 },
	'wailord': { hp: 2 },
	'numel': { spa: 1 },
	'camerupt': { atk: 1, spa: 1 },
	'torkoal': { def: 2 },
	'spoink': { spd: 1 },
	'grumpig': { spd: 2 },
	'spinda': { spa: 1 },
	'trapinch': { atk: 1 },
	'vibrava': { atk: 1, spe: 1 },
	'flygon': { atk: 1, spe: 2 },
	'cacnea': { spa: 1 },
	'cacturne': { atk: 1, spa: 1 },
	'swablu': { spd: 1 },
	'altaria': { spd: 2 },
	'zangoose': { atk: 2 },
	'seviper': { atk: 1, spa: 1 },
	'lunatone': { spa: 2 },
	'solrock': { atk: 2 },
	'barboach': { hp: 1 },
	'whiscash': { hp: 2 },
	'corphish': { atk: 1 },
	'crawdaunt': { atk: 2 },
	'baltoy': { spd: 1 },
	'claydol': { spd: 2 },
	'lileep': { spd: 1 },
	'cradily': { spd: 2 },
	'anorith': { atk: 1 },
	'armaldo': { atk: 2 },
	'feebas': { spe: 1 },
	'milotic': { spd: 2 },
	'castform': { hp: 1 },
	'kecleon': { spd: 1 },
	'shuppet': { atk: 1 },
	'banette': { atk: 2 },
	'duskull': { spd: 1 },
	'dusclops': { def: 1, spd: 1 },
	'tropius': { hp: 2 },
	'chimecho': { spa: 1, spd: 1 },
	'absol': { atk: 2 },
	'wynaut': { hp: 1 },
	'snorunt': { hp: 1 },
	'glalie': { hp: 2 },
	'spheal': { hp: 1 },
	'sealeo': { hp: 2 },
	'walrein': { hp: 3 },
	'clamperl': { def: 1 },
	'huntail': { atk: 1, def: 1 },
	'gorebyss': { spa: 2 },
	'relicanth': { hp: 1, def: 1 },
	'luvdisc': { spe: 1 },
	'bagon': { atk: 1 },
	'shelgon': { def: 2 },
	'salamence': { atk: 3 },
	'beldum': { def: 1 },
	'metang': { def: 2 },
	'metagross': { def: 3 },
	'regirock': { def: 3 },
	'regice': { spd: 3 },
	'registeel': { def: 2, spd: 1 },
	'latias': { spd: 3 },
	'latios': { spa: 3 },
	'kyogre': { spa: 3 },
	'groudon': { atk: 3 },
	'rayquaza': { atk: 2, spa: 1 },
	'jirachi': { hp: 3 },
	'deoxysnormal': { atk: 1, spa: 1, spe: 1 },
	'turtwig': { atk: 1 },
	'grotle': { atk: 1, def: 1 },
	'torterra': { atk: 2, def: 1 },
	'chimchar': { spe: 1 },
	'monferno': { spa: 1, spe: 1 },
	'infernape': { atk: 1, spa: 1, spe: 1 },
	'piplup': { spa: 1 },
	'prinplup': { spa: 2 },
	'empoleon': { spa: 3 },
	'starly': { spe: 1 },
	'staravia': { spe: 2 },
	'staraptor': { atk: 3 },
	'bidoof': { hp: 1 },
	'bibarel': { atk: 2 },
	'kricketot': { def: 1 },
	'kricketune': { atk: 2 },
	'shinx': { atk: 1 },
	'luxio': { atk: 2 },
	'luxray': { atk: 3 },
	'budew': { spa: 1 },
	'roserade': { spa: 3 },
	'cranidos': { atk: 1 },
	'rampardos': { atk: 2 },
	'shieldon': { def: 1 },
	'bastiodon': { def: 2 },
	'burmy': { spd: 1 },
	'wormadamplant': { spd: 2 },
	'mothim': { atk: 1, spa: 1 },
	'combee': { spe: 1 },
	'vespiquen': { def: 1, spd: 1 },
	'pachirisu': { spe: 1 },
	'buizel': { spe: 1 },
	'floatzel': { spe: 2 },
	'cherubi': { spa: 1 },
	'cherrim': { spa: 2 },
	'shellos': { hp: 1 },
	'gastrodon': { hp: 2 },
	'ambipom': { spe: 2 },
	'drifloon': { hp: 1 },
	'drifblim': { hp: 2 },
	'buneary': { spe: 1 },
	'lopunny': { spe: 2 },
	'mismagius': { spa: 1, spd: 1 },
	'honchkrow': { atk: 2 },
	'glameow': { spe: 1 },
	'purugly': { spe: 2 },
	'chingling': { spa: 1 },
	'stunky': { spe: 1 },
	'skuntank': { hp: 2 },
	'bronzor': { def: 1 },
	'bronzong': { def: 1, spd: 1 },
	'bonsly': { def: 1 },
	'mimejr': { spd: 1 },
	'happiny': { hp: 1 },
	'chatot': { atk: 1 },
	'spiritomb': { def: 1, spd: 1 },
	'gible': { atk: 1 },
	'gabite': { atk: 2 },
	'garchomp': { atk: 3 },
	'munchlax': { hp: 1 },
	'riolu': { atk: 1 },
	'lucario': { atk: 1, spa: 1 },
	'hippopotas': { def: 1 },
	'hippowdon': { def: 2 },
	'skorupi': { def: 1 },
	'drapion': { def: 2 },
	'croagunk': { atk: 1 },
	'toxicroak': { atk: 2 },
	'carnivine': { atk: 2 },
	'finneon': { spe: 1 },
	'lumineon': { spe: 2 },
	'mantyke': { spd: 1 },
	'snover': { atk: 1 },
	'abomasnow': { atk: 1, spa: 1 },
	'weavile': { atk: 1, spe: 1 },
	'magnezone': { spa: 3 },
	'lickilicky': { hp: 3 },
	'rhyperior': { atk: 3 },
	'tangrowth': { def: 2 },
	'electivire': { atk: 3 },
	'magmortar': { spa: 3 },
	'togekiss': { spa: 2, spd: 1 },
	'yanmega': { atk: 2 },
	'leafeon': { def: 2 },
	'glaceon': { spa: 2 },
	'gliscor': { def: 2 },
	'mamoswine': { atk: 3 },
	'porygonz': { spa: 3 },
	'gallade': { atk: 3 },
	'probopass': { def: 1, spd: 2 },
	'dusknoir': { def: 1, spd: 2 },
	'froslass': { spe: 2 },
	'rotom': { spa: 1, spe: 1 },
	'uxie': { def: 2, spd: 1 },
	'mesprit': { atk: 1, spa: 1, spd: 1 },
	'azelf': { atk: 2, spa: 1 },
	'dialga': { spa: 3 },
	'palkia': { spa: 3 },
	'heatran': { spa: 3 },
	'regigigas': { atk: 3 },
	'giratinaaltered': { hp: 3 },
	'cresselia': { spd: 3 },
	'phione': { hp: 1 },
	'manaphy': { hp: 3 },
	'darkrai': { spa: 2, spe: 1 },
	'shayminland': { hp: 3 },
	'arceus': { hp: 3 },
	'victini': { hp: 3 },
	'snivy': { spe: 1 },
	'servine': { spe: 2 },
	'serperior': { spe: 3 },
	'tepig': { hp: 1 },
	'pignite': { atk: 2 },
	'emboar': { atk: 3 },
	'oshawott': { spa: 1 },
	'dewott': { spa: 2 },
	'samurott': { spa: 3 },
	'patrat': { atk: 1 },
	'watchog': { atk: 2 },
	'lillipup': { atk: 1 },
	'herdier': { atk: 2 },
	'stoutland': { atk: 3 },
	'purrloin': { spe: 1 },
	'liepard': { spe: 2 },
	'pansage': { spe: 1 },
	'simisage': { spe: 2 },
	'pansear': { spe: 1 },
	'simisear': { spe: 2 },
	'panpour': { spe: 1 },
	'simipour': { spe: 2 },
	'munna': { hp: 1 },
	'musharna': { hp: 2 },
	'pidove': { atk: 1 },
	'tranquill': { atk: 2 },
	'unfezant': { atk: 3 },
	'blitzle': { spe: 1 },
	'zebstrika': { spe: 2 },
	'roggenrola': { def: 1 },
	'boldore': { atk: 1, def: 1 },
	'gigalith': { atk: 3 },
	'woobat': { spe: 1 },
	'swoobat': { spe: 2 },
	'drilbur': { atk: 1 },
	'excadrill': { atk: 2 },
	'audino': { hp: 2 },
	'timburr': { atk: 1 },
	'gurdurr': { atk: 2 },
	'conkeldurr': { atk: 3 },
	'tympole': { spe: 1 },
	'palpitoad': { hp: 2 },
	'seismitoad': { hp: 3 },
	'throh': { hp: 2 },
	'sawk': { atk: 2 },
	'sewaddle': { def: 1 },
	'swadloon': { def: 2 },
	'leavanny': { atk: 3 },
	'venipede': { def: 1 },
	'whirlipede': { def: 2 },
	'scolipede': { spe: 3 },
	'cottonee': { spe: 1 },
	'whimsicott': { spe: 2 },
	'petilil': { spa: 1 },
	'lilligant': { spa: 2 },
	'basculinredstriped': { spe: 2 },
	'sandile': { atk: 1 },
	'krokorok': { atk: 2 },
	'krookodile': { atk: 3 },
	'darumaka': { atk: 1 },
	'darmanitanstandard': { atk: 2 },
	'maractus': { spa: 2 },
	'dwebble': { def: 1 },
	'crustle': { def: 2 },
	'scraggy': { atk: 1 },
	'scrafty': { def: 1, spd: 1 },
	'sigilyph': { spa: 2 },
	'yamask': { def: 1 },
	'cofagrigus': { def: 2 },
	'tirtouga': { def: 1 },
	'carracosta': { def: 2 },
	'archen': { atk: 1 },
	'archeops': { atk: 2 },
	'trubbish': { spe: 1 },
	'garbodor': { atk: 2 },
	'zorua': { spa: 1 },
	'zoroark': { spa: 2 },
	'minccino': { spe: 1 },
	'cinccino': { spe: 2 },
	'gothita': { spd: 1 },
	'gothorita': { spd: 2 },
	'gothitelle': { spd: 3 },
	'solosis': { spa: 1 },
	'duosion': { spa: 2 },
	'reuniclus': { spa: 3 },
	'ducklett': { hp: 1 },
	'swanna': { spe: 2 },
	'vanillite': { spa: 1 },
	'vanillish': { spa: 2 },
	'vanilluxe': { spa: 3 },
	'deerling': { spe: 1 },
	'sawsbuck': { atk: 2 },
	'emolga': { spe: 2 },
	'karrablast': { atk: 1 },
	'escavalier': { atk: 2 },
	'foongus': { hp: 1 },
	'amoonguss': { hp: 2 },
	'frillish': { spd: 1 },
	'jellicent': { spd: 2 },
	'alomomola': { hp: 2 },
	'joltik': { spe: 1 },
	'galvantula': { spe: 2 },
	'ferroseed': { def: 1 },
	'ferrothorn': { def: 2 },
	'klink': { def: 1 },
	'klang': { def: 2 },
	'klinklang': { def: 3 },
	'tynamo': { spe: 1 },
	'eelektrik': { atk: 2 },
	'eelektross': { atk: 3 },
	'elgyem': { spa: 1 },
	'beheeyem': { spa: 2 },
	'litwick': { spa: 1 },
	'lampent': { spa: 2 },
	'chandelure': { spa: 3 },
	'axew': { atk: 1 },
	'fraxure': { atk: 2 },
	'haxorus': { atk: 3 },
	'cubchoo': { atk: 1 },
	'beartic': { atk: 2 },
	'cryogonal': { spd: 2 },
	'shelmet': { def: 1 },
	'accelgor': { spe: 2 },
	'stunfisk': { hp: 2 },
	'mienfoo': { atk: 1 },
	'mienshao': { atk: 2 },
	'druddigon': { atk: 2 },
	'golett': { atk: 1 },
	'golurk': { atk: 2 },
	'pawniard': { atk: 1 },
	'bisharp': { atk: 2 },
	'bouffalant': { atk: 2 },
	'rufflet': { atk: 1 },
	'braviary': { atk: 2 },
	'vullaby': { def: 1 },
	'mandibuzz': { spa: 2 },
	'heatmor': { spa: 2 },
	'durant': { def: 2 },
	'deino': { atk: 1 },
	'zweilous': { atk: 2 },
	'hydreigon': { spa: 3 },
	'larvesta': { atk: 1 },
	'volcarona': { spa: 3 },
	'cobalion': { def: 3 },
	'terrakion': { atk: 3 },
	'virizion': { spd: 3 },
	'tornadusincarnate': { atk: 3 },
	'thundurusincarnate': { atk: 3 },
	'reshiram': { spa: 3 },
	'zekrom': { atk: 3 },
	'landorusincarnate': { spa: 3 },
	'kyurem': { hp: 1, atk: 1, spa: 1 },
	'keldeoordinary': { spa: 3 },
	'meloettaaria': { spa: 1, spd: 1, spe: 1 },
	'genesect': { atk: 1, spa: 1, spe: 1 },
	'chespin': { def: 1 },
	'quilladin': { def: 2 },
	'chesnaught': { def: 3 },
	'fennekin': { spa: 1 },
	'braixen': { spa: 2 },
	'delphox': { spa: 3 },
	'froakie': { spe: 1 },
	'frogadier': { spe: 2 },
	'greninja': { spe: 3 },
	'bunnelby': { spe: 1 },
	'diggersby': { hp: 2 },
	'fletchling': { spe: 1 },
	'fletchinder': { spe: 2 },
	'talonflame': { spe: 3 },
	'scatterbug': { def: 1 },
	'spewpa': { def: 2 },
	'vivillon': { hp: 1, spa: 1, spe: 1 },
	'litleo': { spa: 1 },
	'pyroar': { spa: 2 },
	'flabebe': { spd: 1 },
	'floette': { spd: 2 },
	'florges': { spd: 3 },
	'skiddo': { hp: 1 },
	'gogoat': { hp: 2 },
	'pancham': { atk: 1 },
	'pangoro': { atk: 2 },
	'furfrou': { spe: 1 },
	'espurr': { spe: 1 },
	'meowsticmale': { spe: 2 },
	'honedge': { def: 1 },
	'doublade': { def: 2 },
	'aegislashshield': { def: 2, spd: 1 },
	'spritzee': { hp: 1 },
	'aromatisse': { hp: 2 },
	'swirlix': { def: 1 },
	'slurpuff': { def: 2 },
	'inkay': { atk: 1 },
	'malamar': { atk: 2 },
	'binacle': { atk: 1 },
	'barbaracle': { atk: 2 },
	'skrelp': { spd: 1 },
	'dragalge': { spd: 2 },
	'clauncher': { spa: 1 },
	'clawitzer': { spa: 2 },
	'helioptile': { spe: 1 },
	'heliolisk': { spa: 1, spe: 1 },
	'tyrunt': { atk: 1 },
	'tyrantrum': { atk: 2 },
	'amaura': { hp: 1 },
	'aurorus': { hp: 2 },
	'sylveon': { spd: 2 },
	'hawlucha': { atk: 2 },
	'dedenne': { spe: 2 },
	'carbink': { def: 1, spd: 1 },
	'goomy': { spd: 1 },
	'sliggoo': { spd: 2 },
	'goodra': { spd: 3 },
	'klefki': { def: 1 },
	'phantump': { atk: 1 },
	'trevenant': { atk: 2 },
	'pumpkabooaverage': { def: 1 },
	'gourgeistaverage': { def: 2 },
	'bergmite': { def: 1 },
	'avalugg': { def: 2 },
	'noibat': { spe: 1 },
	'noivern': { spe: 2 },
	'xerneas': { hp: 3 },
	'yveltal': { hp: 3 },
	'zygarde50': { hp: 3 },
	'diancie': { def: 1, spd: 2 },
	'hoopa': { spa: 3 },
	'volcanion': { spa: 3 },
	'rowlet': { hp: 1 },
	'dartrix': { hp: 2 },
	'decidueye': { atk: 3 },
	'litten': { spe: 1 },
	'torracat': { spe: 2 },
	'incineroar': { atk: 3 },
	'popplio': { spa: 1 },
	'brionne': { spa: 2 },
	'primarina': { spa: 3 },
	'pikipek': { atk: 1 },
	'trumbeak': { atk: 2 },
	'toucannon': { atk: 3 },
	'yungoos': { atk: 1 },
	'gumshoos': { atk: 2 },
	'grubbin': { atk: 1 },
	'charjabug': { def: 2 },
	'vikavolt': { spa: 3 },
	'crabrawler': { atk: 1 },
	'crabominable': { atk: 2 },
	'oricoriobaile': { spa: 2 },
	'cutiefly': { spe: 1 },
	'ribombee': { spe: 2 },
	'rockruff': { atk: 1 },
	'lycanrocmidday': { atk: 2 },
	'wishiwashisolo': { hp: 1 },
	'mareanie': { def: 1 },
	'toxapex': { def: 2 },
	'mudbray': { atk: 1 },
	'mudsdale': { atk: 2 },
	'dewpider': { spd: 1 },
	'araquanid': { spd: 2 },
	'fomantis': { atk: 1 },
	'lurantis': { atk: 2 },
	'morelull': { spd: 1 },
	'shiinotic': { spd: 2 },
	'salandit': { spe: 1 },
	'salazzle': { spe: 2 },
	'stufful': { atk: 1 },
	'bewear': { atk: 2 },
	'bounsweet': { hp: 1 },
	'steenee': { spe: 2 },
	'tsareena': { atk: 3 },
	'comfey': { spd: 2 },
	'oranguru': { spd: 2 },
	'passimian': { atk: 2 },
	'wimpod': { spe: 1 },
	'golisopod': { def: 2 },
	'sandygast': { def: 1 },
	'palossand': { def: 2 },
	'pyukumuku': { spd: 2 },
	'typenull': { hp: 2 },
	'silvally': { hp: 3 },
	'miniorredmeteor': { def: 1, spd: 1 },
	'komala': { atk: 2 },
	'turtonator': { def: 2 },
	'togedemaru': { atk: 2 },
	'mimikyudisguised': { spd: 2 },
	'bruxish': { atk: 2 },
	'drampa': { spa: 2 },
	'dhelmise': { atk: 2 },
	'jangmoo': { def: 1 },
	'hakamoo': { def: 2 },
	'kommoo': { def: 3 },
	'tapukoko': { spe: 3 },
	'tapulele': { spa: 3 },
	'tapubulu': { atk: 3 },
	'tapufini': { spd: 3 },
	'cosmog': { hp: 1 },
	'cosmoem': { def: 1, spd: 1 },
	'solgaleo': { atk: 3 },
	'lunala': { spa: 3 },
	'nihilego': { spd: 3 },
	'buzzwole': { atk: 1, def: 2 },
	'pheromosa': { spe: 3 },
	'xurkitree': { spa: 3 },
	'celesteela': { atk: 1, def: 1, spa: 1 },
	'kartana': { atk: 3 },
	'guzzlord': { hp: 3 },
	'necrozma': { atk: 1, spa: 2 },
	'magearna': { spa: 3 },
	'marshadow': { atk: 2, spe: 1 },
	'poipole': { spe: 1 },
	'naganadel': { spa: 3 },
	'stakataka': { def: 3 },
	'blacephalon': { spa: 3 },
	'zeraora': { spe: 3 },
	'meltan': { atk: 1 },
	'melmetal': { atk: 3 },
	'grookey': { atk: 1 },
	'thwackey': { atk: 2 },
	'rillaboom': { atk: 3 },
	'scorbunny': { spe: 1 },
	'raboot': { spe: 2 },
	'cinderace': { spe: 3 },
	'sobble': { spd: 1, spe: 1 },
	'drizzile': { spa: 2 },
	'inteleon': { spe: 3 },
	'skwovet': { hp: 1 },
	'greedent': { hp: 2 },
	'rookidee': { spe: 1 },
	'corvisquire': { spe: 2 },
	'corviknight': { def: 3 },
	'blipbug': { spd: 1 },
	'dottler': { spd: 2 },
	'orbeetle': { spd: 3 },
	'nickit': { spd: 1 },
	'thievul': { spd: 2 },
	'gossifleur': { spd: 1 },
	'eldegoss': { spd: 2 },
	'wooloo': { def: 1 },
	'dubwool': { def: 2 },
	'chewtle': { atk: 1 },
	'drednaw': { atk: 2 },
	'yamper': { hp: 1 },
	'boltund': { spe: 2 },
	'rolycoly': { def: 1 },
	'carkol': { def: 2 },
	'coalossal': { def: 3 },
	'applin': { def: 1 },
	'flapple': { atk: 2 },
	'appletun': { hp: 2 },
	'silicobra': { def: 1 },
	'sandaconda': { def: 2 },
	'cramorant': { spd: 2 },
	'arrokuda': { spe: 1 },
	'barraskewda': { spe: 2 },
	'toxel': { spa: 1 },
	'toxtricityamped': { spa: 2 },
	'sizzlipede': { atk: 1 },
	'centiskorch': { atk: 2 },
	'clobbopus': { atk: 1 },
	'grapploct': { atk: 2 },
	'sinistea': { spa: 1 },
	'polteageist': { spa: 2 },
	'hatenna': { spa: 1 },
	'hattrem': { spa: 2 },
	'hatterene': { spa: 3 },
	'impidimp': { spa: 1 },
	'morgrem': { spa: 2 },
	'grimmsnarl': { atk: 3 },
	'obstagoon': { def: 3 },
	'perrserker': { atk: 2 },
	'cursola': { spa: 2 },
	'sirfetchd': { atk: 2 },
	'mrrime': { spa: 3 },
	'runerigus': { def: 2 },
	'milcery': { spd: 1 },
	'alcremie': { spd: 2 },
	'falinks': { atk: 2, spd: 1 },
	'pincurchin': { atk: 2 },
	'snom': { spa: 1 },
	'frosmoth': { spa: 2 },
	'stonjourner': { def: 2 },
	'eiscueice': { def: 2 },
	'indeedeemale': { spa: 2 },
	'morpekofullbelly': { spe: 2 },
	'cufant': { atk: 1 },
	'copperajah': { atk: 2 },
	'dracozolt': { atk: 2 },
	'arctozolt': { atk: 2 },
	'dracovish': { def: 2 },
	'arctovish': { def: 2 },
	'duraludon': { spa: 2 },
	'dreepy': { spe: 1 },
	'drakloak': { spe: 2 },
	'dragapult': { spe: 3 },
	'zacian': { spe: 3 },
	'zamazenta': { spe: 3 },
	'eternatus': { hp: 3 },
	'kubfu': { atk: 1 },
	'urshifusinglestrike': { atk: 3 },
	'zarude': { atk: 3 },
	'regieleki': { spe: 3 },
	'regidrago': { hp: 3 },
	'glastrier': { atk: 3 },
	'spectrier': { spa: 3 },
	'calyrex': { hp: 3 },
	'wyrdeer': { atk: 1 },
	'kleavor': { atk: 2 },
	'ursaluna': { atk: 3 },
	'basculegionmale': { hp: 2 },
	'sneasler': { atk: 1, spe: 1 },
	'overqwil': { atk: 1 },
	'enamorusincarnate': { spa: 3 },
	'sprigatito': { spe: 1 },
	'floragato': { spe: 2 },
	'meowscarada': { spe: 3 },
	'fuecoco': { hp: 1 },
	'crocalor': { spa: 2 },
	'skeledirge': { spa: 3 },
	'quaxly': { atk: 1 },
	'quaxwell': { atk: 2 },
	'quaquaval': { atk: 3 },
	'lechonk': { hp: 1 },
	'oinkolognemale': { hp: 2 },
	'tarountula': { def: 1 },
	'spidops': { def: 2 },
	'nymble': { atk: 1 },
	'lokix': { atk: 2 },
	'pawmi': { spe: 1 },
	'pawmo': { spe: 2 },
	'pawmot': { atk: 3 },
	'tandemaus': { spe: 1 },
	'mausholdfamilyoffour': { spe: 2 },
	'fidough': { spe: 1 },
	'dachsbun': { spe: 2 },
	'smoliv': { spa: 1 },
	'dolliv': { spa: 2 },
	'arboliva': { spa: 3 },
	'squawkabillygreenplumage': { atk: 1 },
	'nacli': { def: 1 },
	'naclstack': { def: 2 },
	'garganacl': { def: 3 },
	'charcadet': { spa: 1 },
	'armarouge': { spa: 2 },
	'ceruledge': { atk: 2 },
	'tadbulb': { hp: 1 },
	'bellibolt': { hp: 2 },
	'wattrel': { spe: 1 },
	'kilowattrel': { spe: 2 },
	'maschiff': { atk: 1 },
	'mabosstiff': { atk: 2 },
	'shroodle': { spe: 1 },
	'grafaiai': { spe: 2 },
	'bramblin': { atk: 1 },
	'brambleghast': { atk: 2 },
	'toedscool': { spd: 1 },
	'toedscruel': { spd: 2 },
	'klawf': { def: 2 },
	'capsakid': { atk: 1 },
	'scovillain': { atk: 2 },
	'rellor': { def: 1 },
	'rabsca': { spa: 2 },
	'flittle': { spe: 1 },
	'espathra': { spe: 2 },
	'tinkatink': { spd: 1 },
	'tinkatuff': { spd: 2 },
	'tinkaton': { spd: 3 },
	'wiglett': { spe: 1 },
	'wugtrio': { spe: 2 },
	'bombirdier': { atk: 2 },
	'finizen': { spe: 1 },
	'palafinzero': { hp: 2 },
	'varoom': { atk: 1 },
	'revavroom': { atk: 2 },
	'cyclizar': { spe: 2 },
	'orthworm': { def: 2 },
	'glimmet': { spa: 1 },
	'glimmora': { spa: 2 },
	'greavard': { atk: 1 },
	'houndstone': { atk: 2 },
	'flamigo': { atk: 2 },
	'cetoddle': { hp: 1 },
	'cetitan': { hp: 2 },
	'veluza': { atk: 2 },
	'dondozo': { hp: 3 },
	'tatsugiricurly': { spa: 2 },
	'annihilape': { atk: 3 },
	'clodsire': { hp: 2 },
	'farigiraf': { hp: 3 },
	'dudunsparcetwosegment': { hp: 2 },
	'kingambit': { atk: 3 },
	'greattusk': { atk: 3 },
	'screamtail': { hp: 3 },
	'brutebonnet': { atk: 3 },
	'fluttermane': { spa: 1, spd: 1, spe: 1 },
	'slitherwing': { atk: 3 },
	'sandyshocks': { spa: 3 },
	'irontreads': { def: 3 },
	'ironbundle': { spe: 3 },
	'ironhands': { atk: 3 },
	'ironjugulis': { spa: 3 },
	'ironmoth': { spa: 3 },
	'ironthorns': { atk: 3 },
	'frigibax': { atk: 1 },
	'arctibax': { atk: 2 },
	'baxcalibur': { atk: 3 },
	'gimmighoul': { spa: 1 },
	'gholdengo': { spa: 2 },
	'wochien': { spd: 3 },
	'chienpao': { spe: 3 },
	'tinglu': { def: 3 },
	'chiyu': { spa: 3 },
	'roaringmoon': { atk: 3 },
	'ironvaliant': { atk: 3 },
	'koraidon': { atk: 3 },
	'miraidon': { spa: 3 },
	'walkingwake': { spa: 3 },
	'ironleaves': { atk: 3 },
	'dipplin': { def: 2 },
	'poltchageist': { spa: 1 },
	'sinistcha': { spa: 2 },
	'okidogi': { atk: 3 },
	'munkidori': { spa: 3 },
	'fezandipiti': { spd: 3 },
	'ogerpon': { atk: 3 },
	'archaludon': { def: 3 },
	'hydrapple': { spa: 3 },
	'gougingfire': { def: 3 },
	'ragingbolt': { spa: 3 },
	'ironboulder': { spe: 3 },
	'ironcrown': { spa: 3 },
	'terapagos': { def: 1 },
	'pecharunt': { def: 3 },
};
