/*
* Pokemon Showdown
* RPG Handlers - Central Export
*
* This file re-exports all NPC action handlers and scripted event handlers
* to make them easily accessible from data files (locations.ts, npcs.ts, story-events.ts)
* and other modules that need to process game events.
*
* Usage:
*   import * as Handlers from './handlers';
*   const result = Handlers.NPC.handleHeal(player);
*   const result = Handlers.Events.handleCutscene(player, event);
*/

// Re-export all NPC action handlers
export * as NPC from './npc-actions';

// Re-export all scripted event handlers  
export * as Events from './scripted-events';

// Re-export for convenience - individual imports
export {
	// NPC Action Handlers
	handleFossilRevival,
	handleDailyReward,
	handleBattleRequest,
	completeBattleRequest,
	handleQuestChain,
	advanceQuestStage,
	handleItemCraft,
	handleBerryPlant,
	checkBerryHarvest,
	handlePokemonGrooming,
	handleFortuneTeller,
	checkActiveFortune,
	handlePokemonBreeder,
	handleMoveRelearner,
	handleAbilityCapsule,
	handleEVTrainer,
	handleIVChecker,
	handleMysteryGift,
	handleLottery,
	handleMasseuse,
	handleHairCutter,
	handleFishing,
	handleBikeShop,
	handleCoinExchange,
	handleTutorCombo,
	handleApricornCrafter,
	handlePokeathlon,
	handleBerryBlender,
	handlePokeblockMixer,
	handlePoffinCooking,
	handleRivalBattle,
	handleGymRematch,
	handleShardTrader,
	handleWingCollector,
	handleScaleCollector,
	handleOPower,
	handleHeal,
	handleChooseStarter,
	handleCollectionQuest,
	handleReputation,
	addReputationPoints,
	handleDeliveryQuest,
	handleTimeBasedAction,
	handleConditionalDialogue,
	handleEscortQuest,
	handleAchievement,
	handleBattleGauntlet,
	advanceBattleGauntlet,
	handleBattleArena,
	recordArenaWin,
	handleTrainingBattle,
	recordTrainingAttempt,
	handleBattleChallenge,
	handleSurvivalBattle,
	recordSurvivalResult,
	handleRematchTracker,
	recordRematch,
} from './npc-actions';

export {
	// Scripted Event Handlers
	handleCutscene,
	handleChoice,
	handleQuiz,
	handlePuzzle,
	handleRiddle,
	handleMinigame,
	handleWeatherChange,
	handleEarthquake,
	handleExplosion,
	handleFlood,
	handleMeteor,
	handleEclipse,
	handleTimeWarp,
	handleDimensionRift,
	handlePokemonSwarm,
	checkActiveSwarm,
	handleBossBattle,
	handleTournament,
	advanceTournamentRound,
	handleContest,
	handleRace,
	handleScavengerHunt,
	markScavengerItemFound,
	handleInvestigation,
	markClueFound,
	handleStealth,
	handleEscape,
	handleRescue,
	handleDefense,
	handleAmbush,
	handleBetrayal,
	handleAlliance,
	handleNegotiation,
	handleDiscovery,
	handleRevelation,
	handleTransformation,
	handleEvolutionCeremony,
	handleLegendaryAwakening,
	handleAncientSeal,
	handlePortalOpening,
	handleDimensionMerge,
	handleTimeLoop,
	handleProphecy,
	handleFishingEvent,
	handleSurfingEvent,
	handleDivingEvent,
	handleItemBall,
	handleHiddenItemEvent,
	handleRoamingEvent,
	handleMultiBattle,
	handleFestivalEvent,
	handleSecretArea,
	handleWarpEvent,
	handleGymChallengeEvent,
	handleEliteFourChallengeEvent,
	handleHallOfFameEvent,
	handleSafariZoneEvent,
	handleBugCatchingContestEvent,
	handleBattleFrontierEvent,
	handleFlashback,
	handleDreamSequence,
	handleReputationChange,
	handleCompanionJoin,
	handleCompanionLeave,
	handleMoralChoice,
	handleLoreDiscovery,
	handleBranchingPath,
	handleChapterTransition,
	handleEpilogue,
	handleCollectibleItem,
	handleVoiceFromAbove,
	handleMemoryRestoration,
	handleHordeBattle,
	handleInverseBattle,
	handleRotationBattle,
	handleBattleRoyale,
	handleTripleBattle,
	handleSkyBattle,
	handleUnderwaterBattle,
	handleRaidBattle,
	handleGauntletBattle,
	advanceGauntletEvent,
	handleChampionDefense,
	recordChampionDefense,
	handleBattleTest,
	handleWarBattle,
	advanceWarWave,
} from './scripted-events';
