// This file contains the manual EV yields for all Pokémon.
// The format is a key-value map where the key is the species ID (lowercase)
// and the value is an object containing the EV yields for each stat.

export const MANUAL_EV_YIELDS: Record<string, {
	hp?: number;
	atk?: number;
	def?: number;
	spa?: number;
	spd?: number;
	spe?: number;
}> = {
	// --- Generation 1 ---
	'bulbasaur': { spa: 1 },
	'ivysaur': { spa: 1, spd: 1 },
	'venusaur': { spa: 2, spd: 1 },
	'charmander': { spe: 1 },
	'charmeleon': { spa: 1, spe: 1 },
	'charizard': { spa: 3 },
	'squirtle': { def: 1 },
	'wartortle': { def: 1, spd: 1 },
	'blastoise': { spd: 3 },
	'caterpie': { hp: 1 },
	'metapod': { def: 2 },
	'butterfree': { spa: 2, spd: 1 },
	'weedle': { spe: 1 },
	'kakuna': { def: 2 },
	'beedrill': { atk: 2, spd: 1 },
	'pidgey': { spe: 1 },
	'pidgeotto': { spe: 2 },
	'pidgeot': { spe: 3 },
	'rattata': { spe: 1 },
	'raticate': { spe: 2 },
	'spearow': { spe: 1 },
	'fearow': { spe: 2 },
	'ekans': { atk: 1 },
	'arbok': { atk: 2 },
	'pikachu': { spe: 2 },
	'raichu': { spe: 3 },
	'sandshrew': { def: 1 },
	'sandslash': { def: 2 },
	'nidoranf': { hp: 1 },
	'nidorina': { hp: 2 },
	'nidoqueen': { hp: 3 },
	'nidoranm': { atk: 1 },
	'nidorino': { atk: 2 },
	'nidoking': { atk: 3 },
	'clefairy': { hp: 2 },
	'clefable': { hp: 3 },
	'vulpix': { spe: 1 },
	'ninetales': { spd: 1, spe: 1 },
	'jigglypuff': { hp: 2 },
	'wigglytuff': { hp: 3 },
	'zubat': { spe: 1 },
	'golbat': { spe: 2 },
	'oddish': { spa: 1 },
	'gloom': { spa: 2 },
	'vileplume': { spa: 3 },
	'paras': { atk: 1 },
	'parasect': { atk: 2, def: 1 },
	'venonat': { spd: 1 },
	'venomoth': { spa: 1, spe: 1 },
	'diglett': { spe: 1 },
	'dugtrio': { spe: 2 },
	'meowth': { spe: 1 },
	'persian': { spe: 2 },
	'psyduck': { spa: 1 },
	'golduck': { spa: 2 },
	'mankey': { atk: 1 },
	'primeape': { atk: 2 },
	'growlithe': { atk: 1 },
	'arcanine': { atk: 2 },
	'poliwag': { spe: 1 },
	'poliwhirl': { spe: 2 },
	'poliwrath': { def: 3 },
	'abra': { spa: 1 },
	'kadabra': { spa: 2 },
	'alakazam': { spa: 3 },
	'machop': { atk: 1 },
	'machoke': { atk: 2 },
	'machamp': { atk: 3 },
	'bellsprout': { atk: 1 },
	'weepinbell': { atk: 2 },
	'victreebel': { atk: 3 },
	'tentacool': { spd: 1 },
	'tentacruel': { spd: 2 },
	'geodude': { def: 1 },
	'graveler': { def: 2 },
	'golem': { def: 3 },
	'ponyta': { spe: 1 },
	'rapidash': { spe: 2 },
	'slowpoke': { hp: 1 },
	'slowbro': { def: 2 },
	'magnemite': { spa: 1 },
	'magneton': { spa: 2 },
	'farfetchd': { atk: 1 },
	'doduo': { atk: 1 },
	'dodrio': { atk: 2 },
	'seel': { spd: 1 },
	'dewgong': { spd: 2 },
	'grimer': { hp: 1 },
	'muk': { hp: 1, atk: 1 },
	'shellder': { def: 1 },
	'cloyster': { def: 2 },
	'gastly': { spa: 1 },
	'haunter': { spa: 2 },
	'gengar': { spa: 3 },
	'onix': { def: 1 },
	'drowzee': { spd: 1 },
	'hypno': { spd: 2 },
	'krabby': { atk: 1 },
	'kingler': { atk: 2 },
	'voltorb': { spe: 1 },
	'electrode': { spe: 2 },
	'exeggcute': { def: 1 },
	'exeggutor': { spa: 2 },
	'cubone': { def: 1 },
	'marowak': { def: 2 },
	'hitmonlee': { atk: 2 },
	'hitmonchan': { spd: 2 },
	'lickitung': { hp: 2 },
	'koffing': { def: 1 },
	'weezing': { def: 2 },
	'rhyhorn': { def: 1 },
	'rhydon': { atk: 2 },
	'chansey': { hp: 2 },
	'tangela': { def: 1 },
	'kangaskhan': { hp: 2 },
	'horsea': { spa: 1 },
	'seadra': { def: 1, spa: 1 },
	'goldeen': { atk: 1 },
	'seaking': { atk: 2 },
	'staryu': { spe: 1 },
	'starmie': { spe: 2 },
	'mrmime': { spd: 2 },
	'scyther': { atk: 1 },
	'jynx': { spa: 2 },
	'electabuzz': { spe: 2 },
	'magmar': { spa: 2 },
	'pinsir': { atk: 2 },
	'tauros': { atk: 1, spe: 1 },
	'magikarp': { spe: 1 },
	'gyarados': { atk: 2 },
	'lapras': { hp: 2 },
	'ditto': { hp: 1 },
	'eevee': { spd: 1 },
	'vaporeon': { hp: 2 },
	'jolteon': { spe: 2 },
	'flareon': { atk: 2 },
	'porygon': { spa: 1 },
	'omanyte': { def: 1 },
	'omastar': { def: 2 },
	'kabuto': { def: 1 },
	'kabutops': { atk: 2 },
	'aerodactyl': { spe: 2 },
	'snorlax': { hp: 2 },
	'articuno': { spd: 3 },
	'zapdos': { spa: 3 },
	'moltres': { spa: 3 },
	'dratini': { atk: 1 },
	'dragonair': { atk: 2 },
	'dragonite': { atk: 3 },
	'mewtwo': { spa: 3 },
	'mew': { hp: 3 },

	// --- Generation 2 ---
	'chikorita': { spd: 1 },
	'bayleef': { def: 1, spd: 1 },
	'meganium': { def: 1, spd: 2 },
	'cyndaquil': { spe: 1 },
	'quilava': { spa: 1, spe: 1 },
	'typhlosion': { spa: 3 },
	'totodile': { atk: 1 },
	'croconaw': { atk: 1, def: 1 },
	'feraligatr': { atk: 2, def: 1 },
	'sentret': { atk: 1 },
	'furret': { spe: 2 },
	'hoothoot': { hp: 1 },
	'noctowl': { hp: 2 },
	'ledyba': { spd: 1 },
	'ledian': { spd: 2 },
	'spinarak': { atk: 1 },
	'ariados': { atk: 2 },
	'crobat': { spe: 3 },
	'chinchou': { hp: 1 },
	'lanturn': { hp: 2 },
	'pichu': { spe: 1 },
	'cleffa': { spd: 1 },
	'igglybuff': { hp: 1 },
	'togepi': { spd: 1 },
	'togetic': { spd: 2 },
	'natu': { spa: 1 },
	'xatu': { spa: 1, spe: 1 },
	'mareep': { spa: 1 },
	'flaaffy': { spa: 2 },
	'ampharos': { spa: 3 },
	'bellossom': { spd: 3 },
	'marill': { hp: 2 },
	'azumarill': { hp: 3 },
	'sudowoodo': { def: 2 },
	'politoed': { spd: 3 },
	'hoppip': { spd: 1 },
	'skiploom': { spe: 2 },
	'jumpluff': { spe: 3 },
	'aipom': { spe: 1 },
	'sunkern': { spa: 1 },
	'sunflora': { spa: 2 },
	'yanma': { spe: 1 },
	'wooper': { hp: 1 },
	'quagsire': { hp: 2 },
	'espeon': { spa: 2 },
	'umbreon': { spd: 2 },
	'murkrow': { spe: 1 },
	'slowking': { spd: 2 },
	'misdreavus': { spd: 1 },
	'unown': { atk: 1, spa: 1 },
	'wobbuffet': { hp: 2 },
	'girafarig': { spa: 2 },
	'pineco': { def: 1 },
	'forretress': { def: 2 },
	'dunsparce': { hp: 1 },
	'gligar': { def: 1 },
	'steelix': { def: 2 },
	'snubbull': { atk: 1 },
	'granbull': { atk: 2 },
	'qwilfish': { atk: 1 },
	'scizor': { atk: 2 },
	'shuckle': { def: 1, spd: 1 },
	'heracross': { atk: 2 },
	'sneasel': { spe: 1 },
	'teddiursa': { atk: 1 },
	'ursaring': { atk: 2 },
	'slugma': { spa: 1 },
	'magcargo': { def: 2 },
	'swinub': { atk: 1 },
	'piloswine': { hp: 1, atk: 1 },
	'corsola': { def: 1, spd: 1 },
	'remoraid': { spa: 1 },
	'octillery': { atk: 1, spa: 1 },
	'delibird': { spe: 1 },
	'mantine': { spd: 2 },
	'skarmory': { def: 2 },
	'houndour': { spa: 1 },
	'houndoom': { spa: 2 },
	'kingdra': { atk: 1, spa: 1, spd: 1 },
	'phanpy': { hp: 1 },
	'donphan': { atk: 1, def: 1 },
	'porygon2': { spa: 2 },
	'stantler': { atk: 1 },
	'smeargle': { spe: 1 },
	'tyrogue': { atk: 1 },
	'hitmontop': { spd: 2 },
	'smoochum': { spa: 1 },
	'elekid': { spe: 1 },
	'magby': { spe: 1 },
	'miltank': { def: 2 },
	'blissey': { hp: 3 },
	'raikou': { spa: 1, spe: 2 },
	'entei': { hp: 1, atk: 2 },
	'suicune': { def: 1, spd: 2 },
	'larvitar': { atk: 1 },
	'pupitar': { atk: 2 },
	'tyranitar': { atk: 3 },
	'lugia': { spd: 3 },
	'hooh': { spd: 3 },
	'celebi': { hp: 3 },

	// --- Generation 3 ---
	'treecko': { spe: 1 },
	'grovyle': { spe: 2 },
	'sceptile': { spe: 3 },
	'torchic': { spa: 1 },
	'combusken': { spa: 1, spe: 1 },
	'blaziken': { atk: 3 },
	'mudkip': { atk: 1 },
	'marshtomp': { atk: 2 },
	'swampert': { atk: 3 },
	'poochyena': { atk: 1 },
	'mightyena': { atk: 2 },
	'zigzagoon': { spe: 1 },
	'linoone': { spe: 2 },
	'wurmple': { hp: 1 },
	'silcoon': { def: 2 },
	'beautifly': { spa: 3 },
	'cascoon': { def: 2 },
	'dustox': { spd: 3 },
	'lotad': { spd: 1 },
	'lombre': { spd: 2 },
	'ludicolo': { spd: 3 },
	'seedot': { def: 1 },
	'nuzleaf': { atk: 2 },
	'shiftry': { atk: 3 },
	'taillow': { spe: 1 },
	'swellow': { spe: 2 },
	'wingull': { spe: 1 },
	'pelipper': { def: 2 },
	'ralts': { spa: 1 },
	'kirlia': { spa: 2 },
	'gardevoir': { spa: 3 },
	'surskit': { spe: 1 },
	'masquerain': { spa: 1, spd: 1 },
	'shroomish': { hp: 1 },
	'breloom': { atk: 2 },
	'slakoth': { hp: 1 },
	'vigoroth': { spe: 2 },
	'slaking': { hp: 3 },
	'nincada': { def: 1 },
	'ninjask': { spe: 2 },
	'shedinja': { hp: 2 },
	'whismur': { hp: 1 },
	'loudred': { hp: 2 },
	'exploud': { hp: 3 },
	'makuhita': { hp: 1 },
	'hariyama': { hp: 2 },
	'azurill': { hp: 1 },
	'nosepass': { def: 1 },
	'skitty': { spe: 1 },
	'delcatty': { hp: 1, spe: 1 },
	'sableye': { atk: 1, def: 1 },
	'mawile': { atk: 1, def: 1 },
	'aron': { def: 1 },
	'lairon': { def: 2 },
	'aggron': { def: 3 },
	'meditite': { spe: 1 },
	'medicham': { spe: 2 },
	'electrike': { spe: 1 },
	'manectric': { spe: 2 },
	'plusle': { spe: 1 },
	'minun': { spe: 1 },
	'volbeat': { spe: 1 },
	'illumise': { spe: 1 },
	'roselia': { spa: 2 },
	'gulpin': { hp: 1 },
	'swalot': { hp: 2 },
	'carvanha': { atk: 1 },
	'sharpedo': { atk: 2 },
	'wailmer': { hp: 1 },
	'wailord': { hp: 2 },
	'numel': { spa: 1 },
	'camerupt': { atk: 1, spa: 1 },
	'torkoal': { def: 2 },
	'spoink': { spd: 1 },
	'grumpig': { spd: 2 },
	'spinda': { spa: 1 },
	'trapinch': { atk: 1 },
	'vibrava': { atk: 1, spe: 1 },
	'flygon': { atk: 1, spe: 2 },
	'cacnea': { spa: 1 },
	'cacturne': { atk: 1, spa: 1 },
	'swablu': { spd: 1 },
	'altaria': { spd: 2 },
	'zangoose': { atk: 2 },
	'seviper': { atk: 1, spa: 1 },
	'lunatone': { spa: 2 },
	'solrock': { atk: 2 },
	'barboach': { hp: 1 },
	'whiscash': { hp: 2 },
	'corphish': { atk: 1 },
	'crawdaunt': { atk: 2 },
	'baltoy': { spd: 1 },
	'claydol': { spd: 2 },
	'lileep': { spd: 1 },
	'cradily': { spd: 2 },
	'anorith': { atk: 1 },
	'armaldo': { atk: 2 },
	'feebas': { spe: 1 },
	'milotic': { spd: 2 },
	'castform': { hp: 1 },
	'kecleon': { spd: 1 },
	'shuppet': { atk: 1 },
	'banette': { atk: 2 },
	'duskull': { spd: 1 },
	'dusclops': { def: 1, spd: 1 },
	'tropius': { hp: 2 },
	'chimecho': { spa: 1, spd: 1 },
	'absol': { atk: 2 },
	'wynaut': { hp: 1 },
	'snorunt': { hp: 1 },
	'glalie': { hp: 2 },
	'spheal': { hp: 1 },
	'sealeo': { hp: 2 },
	'walrein': { hp: 3 },
	'clamperl': { def: 1 },
	'huntail': { atk: 1, def: 1 },
	'gorebyss': { spa: 2 },
	'relicanth': { hp: 1, def: 1 },
	'luvdisc': { spe: 1 },
	'bagon': { atk: 1 },
	'shelgon': { def: 2 },
	'salamence': { atk: 3 },
	'beldum': { def: 1 },
	'metang': { def: 2 },
	'metagross': { def: 3 },
	'regirock': { def: 3 },
	'regice': { spd: 3 },
	'registeel': { def: 2, spd: 1 },
	'latias': { spd: 3 },
	'latios': { spa: 3 },
	'kyogre': { spa: 3 },
	'groudon': { atk: 3 },
	'rayquaza': { atk: 2, spa: 1 },
	'jirachi': { hp: 3 },
	'deoxys': { atk: 1, spa: 1, spe: 1 },

	// --- Generation 4 ---
	'turtwig': { atk: 1 },
	'grotle': { atk: 1, def: 1 },
	'torterra': { atk: 2, def: 1 },
	'chimchar': { spe: 1 },
	'monferno': { spa: 1, spe: 1 },
	'infernape': { atk: 1, spa: 1, spe: 1 },
	'piplup': { spa: 1 },
	'prinplup': { spa: 2 },
	'empoleon': { spa: 3 },
	'starly': { spe: 1 },
	'staravia': { spe: 2 },
	'staraptor': { atk: 3 },
	'bidoof': { hp: 1 },
	'bibarel': { atk: 2 },
	'kricketot': { def: 1 },
	'kricketune': { atk: 2 },
	'shinx': { atk: 1 },
	'luxio': { atk: 2 },
	'luxray': { atk: 3 },
	'budew': { spa: 1 },
	'roserade': { spa: 3 },
	'cranidos': { atk: 1 },
	'rampardos': { atk: 2 },
	'shieldon': { def: 1 },
	'bastiodon': { def: 2 },
	'burmy': { spd: 1 },
	'wormadam': { spd: 2 }, // Plant Cloak
	'mothim': { atk: 1, spa: 1 },
	'combee': { spe: 1 },
	'vespiquen': { def: 1, spd: 1 },
	'pachirisu': { spe: 1 },
	'buizel': { spe: 1 },
	'floatzel': { spe: 2 },
	'cherubi': { spa: 1 },
	'cherrim': { spa: 2 },
	'shellos': { hp: 1 },
	'gastrodon': { hp: 2 },
	'ambipom': { spe: 2 },
	'drifloon': { hp: 1 },
	'drifblim': { hp: 2 },
	'buneary': { spe: 1 },
	'lopunny': { spe: 2 },
	'mismagius': { spa: 1, spd: 1 },
	'honchkrow': { atk: 2 },
	'glameow': { spe: 1 },
	'purugly': { spe: 2 },
	'chingling': { spa: 1 },
	'stunky': { spe: 1 },
	'skuntank': { hp: 2 },
	'bronzor': { def: 1 },
	'bronzong': { def: 1, spd: 1 },
	'bonsly': { def: 1 },
	'mimejr': { spd: 1 },
	'happiny': { hp: 1 },
	'chatot': { atk: 1 },
	'spiritomb': { def: 1, spd: 1 },
	'gible': { atk: 1 },
	'gabite': { atk: 2 },
	'garchomp': { atk: 3 },
	'munchlax': { hp: 1 },
	'riolu': { atk: 1 },
	'lucario': { atk: 1, spa: 1 },
	'hippopotas': { def: 1 },
	'hippowdon': { def: 2 },
	'skorupi': { def: 1 },
	'drapion': { def: 2 },
	'croagunk': { atk: 1 },
	'toxicroak': { atk: 2 },
	'carnivine': { atk: 2 },
	'finneon': { spe: 1 },
	'lumineon': { spe: 2 },
	'mantyke': { spd: 1 },
	'snover': { atk: 1 },
	'abomasnow': { atk: 1, spa: 1 },
	'weavile': { atk: 1, spe: 1 },
	'magnezone': { spa: 3 },
	'lickilicky': { hp: 3 },
	'rhyperior': { atk: 3 },
	'tangrowth': { def: 2 },
	'electivire': { atk: 3 },
	'magmortar': { spa: 3 },
	'togekiss': { spa: 2, spd: 1 },
	'yanmega': { atk: 2 },
	'leafeon': { def: 2 },
	'glaceon': { spa: 2 },
	'gliscor': { def: 2 },
	'mamoswine': { atk: 3 },
	'porygonz': { spa: 3 },
	'gallade': { atk: 3 },
	'probopass': { def: 1, spd: 2 },
	'dusknoir': { def: 1, spd: 2 },
	'froslass': { spe: 2 },
	'rotom': { spa: 1, spe: 1 },
	'uxie': { def: 2, spd: 1 },
	'mesprit': { atk: 1, spa: 1, spd: 1 },
	'azelf': { atk: 2, spa: 1 },
	'dialga': { spa: 3 },
	'palkia': { spa: 3 },
	'heatran': { spa: 3 },
	'regigigas': { atk: 3 },
	'giratina': { hp: 3 },
	'cresselia': { spd: 3 },
	'phione': { hp: 1 },
	'manaphy': { hp: 3 },
	'darkrai': { spa: 2, spe: 1 },
	'shaymin': { hp: 3 },
	'arceus': { hp: 3 },

	// --- Generation 5 ---
	'victini': { hp: 3 },
	'snivy': { spe: 1 },
	'servine': { spe: 2 },
	'serperior': { spe: 3 },
	'tepig': { hp: 1 },
	'pignite': { atk: 2 },
	'emboar': { atk: 3 },
	'oshawott': { spa: 1 },
	'dewott': { spa: 2 },
	'samurott': { spa: 3 },
	'patrat': { atk: 1 },
	'watchog': { atk: 2 },
	'lillipup': { atk: 1 },
	'herdier': { atk: 2 },
	'stoutland': { atk: 3 },
	'purrloin': { spe: 1 },
	'liepard': { spe: 2 },
	'pansage': { spe: 1 },
	'simisage': { spe: 2 },
	'pansear': { spe: 1 },
	'simisear': { spe: 2 },
	'panpour': { spe: 1 },
	'simipour': { spe: 2 },
	'munna': { hp: 1 },
	'musharna': { hp: 2 },
	'pidove': { atk: 1 },
	'tranquill': { atk: 2 },
	'unfezant': { atk: 3 },
	'blitzle': { spe: 1 },
	'zebstrika': { spe: 2 },
	'roggenrola': { def: 1 },
	'boldore': { atk: 1, def: 1 },
	'gigalith': { atk: 3 },
	'woobat': { spe: 1 },
	'swoobat': { spe: 2 },
	'drilbur': { atk: 1 },
	'excadrill': { atk: 2 },
	'audino': { hp: 2 },
	'timburr': { atk: 1 },
	'gurdurr': { atk: 2 },
	'conkeldurr': { atk: 3 },
	'tympole': { spe: 1 },
	'palpitoad': { hp: 2 },
	'seismitoad': { hp: 3 },
	'throh': { hp: 2 },
	'sawk': { atk: 2 },
	'sewaddle': { def: 1 },
	'swadloon': { def: 2 },
	'leavanny': { atk: 3 },
	'venipede': { def: 1 },
	'whirlipede': { def: 2 },
	'scolipede': { spe: 3 },
	'cottonee': { spe: 1 },
	'whimsicott': { spe: 2 },
	'petilil': { spa: 1 },
	'lilligant': { spa: 2 },
	'basculin': { spe: 2 },
	'sandile': { atk: 1 },
	'krokorok': { atk: 2 },
	'krookodile': { atk: 3 },
	'darumaka': { atk: 1 },
	'darmanitan': { atk: 2 },
	'maractus': { spa: 2 },
	'dwebble': { def: 1 },
	'crustle': { def: 2 },
	'scraggy': { atk: 1 },
	'scrafty': { def: 1, spd: 1 },
	'sigilyph': { spa: 2 },
	'yamask': { def: 1 },
	'cofagrigus': { def: 2 },
	'tirtouga': { def: 1 },
	'carracosta': { def: 2 },
	'archen': { atk: 1 },
	'archeops': { atk: 2 },
	'trubbish': { def: 1 },
	'garbodor': { atk: 2 },
	'zorua': { spa: 1 },
	'zoroark': { spa: 2 },
	'minccino': { spe: 1 },
	'cinccino': { spe: 2 },
	'gothita': { spd: 1 },
	'gothorita': { spd: 2 },
	'gothitelle': { spd: 3 },
	'solosis': { spa: 1 },
	'duosion': { spa: 2 },
	'reuniclus': { spa: 3 },
	'ducklett': { hp: 1 },
	'swanna': { spe: 2 },
	'vanillite': { spa: 1 },
	'vanillish': { spa: 2 },
	'vanilluxe': { spa: 3 },
	'deerling': { spe: 1 },
	'sawsbuck': { atk: 2 },
	'emolga': { spe: 2 },
	'karrablast': { atk: 1 },
	'escavalier': { atk: 2 },
	'foongus': { hp: 1 },
	'amoonguss': { hp: 2 },
	'frillish': { spd: 1 },
	'jellicent': { spd: 2 },
	'alomomola': { hp: 2 },
	'joltik': { spe: 1 },
	'galvantula': { spe: 2 },
	'ferroseed': { def: 1 },
	'ferrothorn': { def: 2 },
	'klink': { def: 1 },
	'klang': { def: 2 },
	'klinklang': { def: 3 },
	'tynamo': { spe: 1 },
	'eelektrik': { atk: 2 },
	'eelektross': { atk: 3 },
	'elgyem': { spa: 1 },
	'beheeyem': { spa: 2 },
	'litwick': { spa: 1 },
	'lampent': { spa: 2 },
	'chandelure': { spa: 3 },
	'axew': { atk: 1 },
	'fraxure': { atk: 2 },
	'haxorus': { atk: 3 },
	'cubchoo': { atk: 1 },
	'beartic': { atk: 2 },
	'cryogonal': { spd: 2 },
	'shelmet': { def: 1 },
	'accelgor': { spe: 2 },
	'stunfisk': { hp: 2 },
	'mienfoo': { atk: 1 },
	'mienshao': { atk: 2 },
	'druddigon': { atk: 2 },
	'golett': { atk: 1 },
	'golurk': { atk: 2 },
	'pawniard': { atk: 1 },
	'bisharp': { atk: 2 },
	'bouffalant': { atk: 2 },
	'rufflet': { atk: 1 },
	'braviary': { atk: 2 },
	'vullaby': { def: 1 },
	'mandibuzz': { spa: 2 },
	'heatmor': { spa: 2 },
	'durant': { def: 2 },
	'deino': { atk: 1 },
	'zweilous': { atk: 2 },
	'hydreigon': { spa: 3 },
	'larvesta': { atk: 1 },
	'volcarona': { spa: 3 },
	'cobalion': { def: 3 },
	'terrakion': { atk: 3 },
	'virizion': { spe: 3 },
	'tornadus': { atk: 3 },
	'thundurus': { atk: 3 },
	'reshiram': { spa: 3 },
	'zekrom': { atk: 3 },
	'landorus': { spa: 3 },
	'kyurem': { atk: 1, spa: 1, spd: 1 },
	'keldeo': { spa: 3 },
	'meloetta': { spa: 1, spd: 1, spe: 1 },
	'genesect': { atk: 1, spa: 1, spe: 1 },

	// --- Generation 6 ---
	'chespin': { def: 1 },
	'quilladin': { def: 2 },
	'chesnaught': { def: 3 },
	'fennekin': { spa: 1 },
	'braixen': { spa: 2 },
	'delphox': { spa: 3 },
	'froakie': { spe: 1 },
	'frogadier': { spe: 2 },
	'greninja': { spe: 3 },
	'bunnelby': { spe: 1 },
	'diggersby': { atk: 2 },
	'fletchling': { spe: 1 },
	'fletchinder': { spe: 2 },
	'talonflame': { spe: 3 },
	'scatterbug': { def: 1 },
	'spewpa': { def: 2 },
	'vivillon': { hp: 1, spa: 1, spe: 1 },
	'litleo': { spa: 1 },
	'pyroar': { spa: 2 },
	'flabebe': { spd: 1 },
	'floette': { spd: 2 },
	'florges': { spd: 3 },
	'skiddo': { hp: 1 },
	'gogoat': { hp: 2 },
	'pancham': { atk: 1 },
	'pangoro': { atk: 2 },
	'furfrou': { def: 1 },
	'espurr': { spe: 1 },
	'meowstic': { spe: 2 },
	'honedge': { def: 1 },
	'doublade': { def: 2 },
	'aegislash': { def: 2, spd: 1 },
	'spritzee': { hp: 1 },
	'aromatisse': { hp: 2 },
	'swirlix': { def: 1 },
	'slurpuff': { def: 2 },
	'inkay': { atk: 1 },
	'malamar': { atk: 2 },
	'binacle': { atk: 1 },
	'barbaracle': { atk: 2 },
	'skrelp': { spd: 1 },
	'dragalge': { spd: 2 },
	'clauncher': { spa: 1 },
	'clawitzer': { spa: 2 },
	'helioptile': { spe: 1 },
	'heliolisk': { spa: 1, spe: 1 },
	'tyrunt': { atk: 1 },
	'tyrantrum': { atk: 2 },
	'amaura': { hp: 1 },
	'aurorus': { hp: 2 },
	'sylveon': { spd: 2 },
	'hawlucha': { atk: 2 },
	'dedenne': { spe: 2 },
	'carbink': { def: 1, spd: 1 },
	'goomy': { spd: 1 },
	'sliggoo': { spd: 2 },
	'goodra': { spd: 3 },
	'klefki': { def: 1 },
	'phantump': { atk: 1 },
	'trevenant': { atk: 2 },
	'pumpkaboo': { def: 1 },
	'gourgeist': { def: 2 },
	'bergmite': { def: 1 },
	'avalugg': { def: 2 },
	'noibat': { spe: 1 },
	'noivern': { spe: 2 },
	'xerneas': { hp: 3 },
	'yveltal': { spa: 3 },
	'zygarde': { hp: 3 },
	'diancie': { def: 1, spd: 2 },
	'hoopa': { spa: 3 },
	'volcanion': { spa: 3 },

	// --- Generation 7 ---
	'rowlet': { hp: 1 },
	'dartrix': { hp: 2 },
	'decidueye': { atk: 3 },
	'litten': { spe: 1 },
	'torracat': { spe: 2 },
	'incineroar': { atk: 3 },
	'popplio': { spa: 1 },
	'brionne': { spa: 2 },
	'primarina': { spa: 3 },
	'pikipek': { atk: 1 },
	'trumbeak': { atk: 2 },
	'toucannon': { atk: 3 },
	'yungoos': { atk: 1 },
	'gumshoos': { atk: 2 },
	'grubbin': { atk: 1 },
	'charjabug': { def: 2 },
	'vikavolt': { spa: 3 },
	'crabrawler': { atk: 1 },
	'crabominable': { atk: 2 },
	'oricorio': { spa: 2 },
	'cutiefly': { spe: 1 },
	'ribombee': { spe: 2 },
	'rockruff': { atk: 1 },
	'lycanroc': { atk: 2 },
	'wishiwashi': { hp: 1 },
	'mareanie': { def: 1 },
	'toxapex': { def: 2 },
	'mudbray': { def: 1 },
	'mudsdale': { def: 2 },
	'dewpider': { spd: 1 },
	'araquanid': { spd: 2 },
	'fomantis': { atk: 1 },
	'lurantis': { atk: 2 },
	'morelull': { spd: 1 },
	'shiinotic': { spd: 2 },
	'salandit': { spe: 1 },
	'salazzle': { spe: 2 },
	'stufful': { atk: 1 },
	'bewear': { atk: 2 },
	'bounsweet': { hp: 1 },
	'steenee': { spe: 2 },
	'tsareena': { atk: 3 },
	'comfey': { spd: 2 },
	'oranguru': { spd: 2 },
	'passimian': { atk: 2 },
	'wimpod': { spe: 1 },
	'golisopod': { def: 2 },
	'sandygast': { def: 1 },
	'palossand': { def: 2 },
	'pyukumuku': { spd: 2 },
	'typenull': { hp: 2 },
	'silvally': { hp: 3 },
	'minior': { def: 1, spd: 1 },
	'komala': { atk: 2 },
	'turtonator': { def: 2 },
	'togedemaru': { atk: 2 },
	'mimikyu': { spd: 2 },
	'bruxish': { atk: 2 },
	'drampa': { spa: 2 },
	'dhelmise': { atk: 2 },
	'jangmoo': { def: 1 },
	'hakamoo': { def: 2 },
	'kommoo': { def: 3 },
	'tapukoko': { spe: 3 },
	'tapulele': { spa: 3 },
	'tapubulu': { atk: 3 },
	'tapufini': { spd: 3 },
	'cosmog': { hp: 1 },
	'cosmoem': { def: 1, spd: 1 },
	'solgaleo': { atk: 3 },
	'lunala': { spa: 3 },
	'nihilego': { spd: 3 },
	'buzzwole': { atk: 1, def: 2 },
	'pheromosa': { spe: 3 },
	'xurkitree': { spa: 3 },
	'celesteela': { atk: 1, def: 1, spa: 1 },
	'kartana': { atk: 3 },
	'guzzlord': { hp: 3 },
	'necrozma': { atk: 1, spa: 2 },
	'magearna': { spa: 3 },
	'marshadow': { atk: 2, spe: 1 },
	'poipole': { spe: 1 },
	'naganadel': { spa: 3 },
	'stakataka': { def: 3 },
	'blacephalon': { spa: 3 },
	'zeraora': { spe: 3 },
	'meltan': { atk: 1 },
	'melmetal': { atk: 3 },

	// --- Generation 8 ---
	'grookey': { atk: 1 },
	'thwackey': { atk: 2 },
	'rillaboom': { atk: 3 },
	'scorbunny': { spe: 1 },
	'raboot': { spe: 2 },
	'cinderace': { spe: 3 },
	'sobble': { spd: 1, spe: 1 },
	'drizzile': { spd: 2 },
	'inteleon': { spe: 3 },
	'skwovet': { hp: 1 },
	'greedent': { hp: 2 },
	'rookidee': { atk: 1 },
	'corvisquire': { def: 2 },
	'corviknight': { def: 3 },
	'blipbug': { spd: 1 },
	'dottler': { spd: 2 },
	'orbeetle': { spd: 3 },
	'nickit': { spd: 1 },
	'thievul': { spd: 2 },
	'gossifleur': { spd: 1 },
	'eldegoss': { spd: 2 },
	'wooloo': { def: 1 },
	'dubwool': { def: 2 },
	'chewtle': { atk: 1 },
	'drednaw': { atk: 2 },
	'yamper': { spe: 1 },
	'boltund': { spe: 2 },
	'rolycoly': { def: 1 },
	'carkol': { def: 2 },
	'coalossal': { def: 3 },
	'applin': { def: 1 },
	'flapple': { atk: 2 },
	'appletun': { hp: 2 },
	'silicobra': { def: 1 },
	'sandaconda': { def: 2 },
	'cramorant': { spd: 2 },
	'arrokuda': { spe: 1 },
	'barraskewda': { spe: 2 },
	'toxel': { spa: 1 },
	'toxtricity': { spa: 2 },
	'sizzlipede': { atk: 1 },
	'centiskorch': { atk: 2 },
	'clobbopus': { atk: 1 },
	'grapploct': { atk: 2 },
	'sinistea': { spa: 1 },
	'polteageist': { spa: 2 },
	'hatenna': { spa: 1 },
	'hattrem': { spa: 2 },
	'hatterene': { spa: 3 },
	'impidimp': { spa: 1 },
	'morgrem': { spa: 2 },
	'grimmsnarl': { atk: 3 },
	'obstagoon': { def: 3 },
	'perrserker': { atk: 2 },
	'cursola': { spa: 2 },
	'sirfetchd': { atk: 2 },
	'mrrime': { spa: 3 },
	'runerigus': { def: 2 },
	'milcery': { spd: 1 },
	'alcremie': { spd: 2 },
	'falinks': { atk: 2, spd: 1 },
	'pincurchin': { atk: 2 },
	'snom': { spa: 1 },
	'frosmoth': { spa: 2 },
	'stonjourner': { def: 2 },
	'eiscue': { def: 2 },
	'indeedee': { spa: 2 },
	'morpeko': { spe: 2 },
	'cufant': { atk: 1 },
	'copperajah': { atk: 2 },
	'dracozolt': { atk: 2 },
	'arctozolt': { atk: 2 },
	'dracovish': { def: 2 },
	'arctovish': { def: 2 },
	'duraludon': { spa: 2 },
	'dreepy': { spe: 1 },
	'drakloak': { spe: 2 },
	'dragapult': { spe: 3 },
	'zacian': { spe: 3 },
	'zamazenta': { spe: 3 },
	'eternatus': { hp: 3 },
	'kubfu': { atk: 1 },
	'urshifu': { atk: 3 },
	'zarude': { atk: 3 },
	'regieleki': { spe: 3 },
	'regidrago': { hp: 3 },
	'glastrier': { atk: 3 },
	'spectrier': { spa: 3 },
	'calyrex': { hp: 3 },
	'enamorus': { spd: 3 },

	// --- Generation 9 ---
	'sprigatito': { spe: 1 },
	'floragato': { spe: 2 },
	'meowscarada': { spe: 3 },
	'fuecoco': { hp: 1 },
	'crocalor': { hp: 2 },
	'skeledirge': { spa: 3 },
	'quaxly': { atk: 1 },
	'quaxwell': { atk: 2 },
	'quaquaval': { atk: 3 },
	'lechonk': { hp: 1 },
	'oinkologne': { hp: 2 },
	'tarountula': { def: 1 },
	'spidops': { def: 2 },
	'nymble': { atk: 1 },
	'lokix': { atk: 2 },
	'pawmi': { spe: 1 },
	'pawmo': { spe: 2 },
	'pawmot': { atk: 3 },
	'tandemaus': { spe: 1 },
	'maushold': { spe: 2 },
	'fidough': { spe: 1 },
	'dachsbun': { spe: 2 },
	'smoliv': { spa: 1 },
	'dolliv': { spa: 2 },
	'arboliva': { spa: 3 },
	'squawkabilly': { atk: 1 },
	'nacli': { def: 1 },
	'naclstack': { def: 2 },
	'garganacl': { def: 3 },
	'charcadet': { spa: 1 },
	'armarouge': { spa: 2 },
	'ceruledge': { atk: 2 },
	'tadbulb': { hp: 1 },
	'bellibolt': { hp: 2 },
	'wattrel': { spe: 1 },
	'kilowattrel': { spe: 2 },
	'maschiff': { atk: 1 },
	'mabosstiff': { atk: 2 },
	'shroodle': { spe: 1 },
	'grafaiai': { spe: 2 },
	'bramblin': { atk: 1 },
	'brambleghast': { atk: 2 },
	'toedscool': { spd: 1 },
	'toedscruel': { spd: 2 },
	'klawf': { def: 2 },
	'capsakid': { atk: 1 },
	'scovillain': { atk: 2 },
	'rellor': { def: 1 },
	'rabsca': { spa: 2 },
	'flittle': { spe: 1 },
	'espathra': { spe: 2 },
	'tinkatink': { spd: 1 },
	'tinkatuff': { spa: 2 },
	'tinkaton': { spd: 3 },
	'wiglett': { spe: 1 },
	'wugtrio': { spe: 2 },
	'bombirdier': { atk: 2 },
	'finizen': { spe: 1 },
	'palafin': { hp: 2 },
	'varoom': { atk: 1 },
	'revavroom': { atk: 2 },
	'cyclizar': { spe: 2 },
	'orthworm': { def: 2 },
	'glimmet': { spa: 1 },
	'glimmora': { spa: 2 },
	'greavard': { atk: 1 },
	'houndstone': { atk: 2 },
	'flamigo': { atk: 2 },
	'cetoddle': { hp: 1 },
	'cetitan': { hp: 2 },
	'veluza': { atk: 2 },
	'dondozo': { hp: 3 },
	'tatsugiri': { spa: 2 },
	'annihilape': { atk: 3 },
	'clodsire': { hp: 2 },
	'farigiraf': { hp: 3 },
	'dudunsparce': { hp: 2 },
	'kingambit': { atk: 3 },
	'greattusk': { atk: 1, def: 2 },
	'screamtail': { hp: 3 },
	'brutebonnet': { atk: 3 },
	'fluttermane': { spa: 1, spd: 1, spe: 1 },
	'slitherwing': { atk: 3 },
	'sandyshocks': { spa: 3 },
	'irontreads': { def: 3 },
	'ironbundle': { spe: 3 },
	'ironhands': { atk: 3 },
	'ironjugulis': { spa: 3 },
	'ironmoth': { spa: 3 },
	'ironthorns': { atk: 3 },
	'frigibax': { atk: 1 },
	'arctibax': { atk: 2 },
	'baxcalibur': { atk: 3 },
	'gimmighoul': { spa: 1 },
	'gholdengo': { spa: 2 },
	'wochien': { spd: 3 },
	'chienpao': { spe: 3 },
	'tinglu': { def: 3 },
	'chiyu': { spa: 3 },
	'roaringmoon': { atk: 3 },
	'ironvaliant': { atk: 3 },
	'koraidon': { atk: 3 },
	'miraidon': { spa: 3 },
	'walkingwake': { spa: 3 },
	'ironleaves': { atk: 3 },
	'dipplin': { def: 2 },
	'poltchageist': { spa: 1 },
	'sinistcha': { spa: 2 },
	'okidogi': { atk: 3 },
	'munkidori': { spa: 3 },
	'fezandipiti': { spd: 3 },
	'ogerpon': { atk: 3 },
	'archaludon': { def: 2 },
	'hydrapple': { spa: 3 },
	'gougingfire': { def: 3 },
	'ragingbolt': { spa: 3 },
	'ironboulder': { atk: 3 },
	'ironcrown': { spd: 3 },
	'terapagos': { def: 1, spd: 1 },
	'pecharunt': { def: 3 },
};
