// Auto-generated Gen 1 Pokémon Learnsets from Pokémon Ultra Sun/Ultra Moon
// Format: { [pokemonId]: { levelup: [{level, move}, ...], egg: [move, ...], tm: [move, ...] } }

export const MANUAL_LEARNSETS = {
	bulbasaur: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 3, move: 'leechseed' },
			{ level: 6, move: 'vinewhip' },
			{ level: 9, move: 'poisonpowder' },
			{ level: 12, move: 'sleep' },
			{ level: 15, move: 'solarbeam' },
			{ level: 18, move: 'growth' },
			{ level: 21, move: 'synthesis' },
		],
		egg: ['amnesia', 'aromatherapy', 'curse', 'grasswhistle', 'leafstorm', 'magical leaf', 'nature power'],
		tm: ['solarbeam', 'toxic', 'rest', 'round', 'shadowball', 'sludgebomb', 'scald', 'thunderbolt'],
	},
	ivysaur: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 3, move: 'leechseed' },
			{ level: 6, move: 'vinewhip' },
			{ level: 9, move: 'poisonpowder' },
			{ level: 12, move: 'sleep' },
			{ level: 15, move: 'razorleaf' },
			{ level: 18, move: 'growth' },
			{ level: 21, move: 'synthesis' },
		],
		egg: [],
		tm: ['solarbeam', 'toxic', 'rest', 'round', 'shadowball', 'sludgebomb', 'scald'],
	},
	venusaur: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 3, move: 'leechseed' },
			{ level: 6, move: 'vinewhip' },
			{ level: 9, move: 'poisonpowder' },
			{ level: 12, move: 'sleep' },
			{ level: 15, move: 'razorleaf' },
			{ level: 18, move: 'growth' },
			{ level: 21, move: 'synthesis' },
			{ level: 29, move: 'solarbeam' },
		],
		egg: [],
		tm: ['solarbeam', 'toxic', 'rest', 'round', 'shadowball', 'sludgebomb', 'scald'],
	},
	charmander: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 6, move: 'ember' },
			{ level: 11, move: 'smokescreen' },
			{ level: 16, move: 'dragonrage' },
			{ level: 21, move: 'firefang' },
			{ level: 26, move: 'slash' },
			{ level: 31, move: 'flamethrower' },
			{ level: 36, move: 'swordsdance' },
		],
		egg: ['ancientpower', 'bellydrum', 'bite', 'crunch', 'curse', 'dragondance', 'flareblitz'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower', 'thunderbolt', 'earthquake'],
	},
	charmeleon: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 6, move: 'ember' },
			{ level: 11, move: 'smokescreen' },
			{ level: 16, move: 'dragonrage' },
			{ level: 21, move: 'firefang' },
			{ level: 26, move: 'slash' },
			{ level: 31, move: 'flamethrower' },
			{ level: 36, move: 'swordsdance' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower', 'thunderbolt'],
	},
	charizard: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 6, move: 'ember' },
			{ level: 11, move: 'smokescreen' },
			{ level: 16, move: 'dragonrage' },
			{ level: 21, move: 'firefang' },
			{ level: 26, move: 'slash' },
			{ level: 31, move: 'flamethrower' },
			{ level: 36, move: 'swordsdance' },
			{ level: 41, move: 'dragonclaw' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower', 'thunderbolt', 'earthquake'],
	},
	squirtle: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'tailwhip' },
			{ level: 3, move: 'flipturn' },
			{ level: 4, move: 'withdraw' },
			{ level: 8, move: 'bubble' },
			{ level: 13, move: 'bite' },
			{ level: 19, move: 'bubblebeam' },
			{ level: 26, move: 'protect' },
			{ level: 34, move: 'scald' },
			{ level: 43, move: 'hydropump' },
		],
		egg: ['aquaring', 'aquajet', 'curse', 'dragondance', 'liquidation', 'refresh', 'yawn'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'icebeam', 'earthquake'],
	},
	wartortle: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'tailwhip' },
			{ level: 4, move: 'withdraw' },
			{ level: 8, move: 'bubble' },
			{ level: 13, move: 'bite' },
			{ level: 19, move: 'bubblebeam' },
			{ level: 26, move: 'protect' },
			{ level: 34, move: 'scald' },
			{ level: 43, move: 'hydropump' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'icebeam'],
	},
	blastoise: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'tailwhip' },
			{ level: 4, move: 'withdraw' },
			{ level: 8, move: 'bubble' },
			{ level: 13, move: 'bite' },
			{ level: 19, move: 'bubblebeam' },
			{ level: 26, move: 'protect' },
			{ level: 34, move: 'scald' },
			{ level: 43, move: 'hydropump' },
			{ level: 51, move: 'raindance' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'icebeam', 'earthquake'],
	},
	pidgey: {
		levelup: [
			{ level: 1, move: 'gust' },
			{ level: 5, move: 'sandattack' },
			{ level: 10, move: 'quickattack' },
			{ level: 15, move: 'whirlwind' },
			{ level: 20, move: 'wingattack' },
			{ level: 25, move: 'roost' },
			{ level: 30, move: 'agility' },
			{ level: 35, move: 'bravebird' },
		],
		egg: [],
		tm: ['toxic', 'roost', 'rest', 'round'],
	},
	pidgeotto: {
		levelup: [
			{ level: 1, move: 'gust' },
			{ level: 5, move: 'sandattack' },
			{ level: 10, move: 'quickattack' },
			{ level: 15, move: 'whirlwind' },
			{ level: 20, move: 'wingattack' },
			{ level: 25, move: 'roost' },
			{ level: 30, move: 'agility' },
		],
		egg: [],
		tm: ['toxic', 'roost', 'rest', 'round'],
	},
	pidgeot: {
		levelup: [
			{ level: 1, move: 'gust' },
			{ level: 5, move: 'sandattack' },
			{ level: 10, move: 'quickattack' },
			{ level: 15, move: 'whirlwind' },
			{ level: 20, move: 'wingattack' },
			{ level: 25, move: 'roost' },
			{ level: 30, move: 'agility' },
			{ level: 35, move: 'bravebird' },
		],
		egg: [],
		tm: ['toxic', 'roost', 'rest', 'round'],
	},
	rattata: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'tailwhip' },
			{ level: 5, move: 'quickattack' },
			{ level: 9, move: 'focusenergy' },
			{ level: 13, move: 'bite' },
			{ level: 17, move: 'irontail' },
			{ level: 21, move: 'superpower' },
		],
		egg: ['bite', 'curse', 'lastresort', 'revenge', 'thunderwave'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	raticate: {
		levelup: [
			{ level: 1, move: 'swordsdance' },
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'tailwhip' },
			{ level: 5, move: 'quickattack' },
			{ level: 9, move: 'focusenergy' },
			{ level: 13, move: 'bite' },
			{ level: 17, move: 'irontail' },
			{ level: 21, move: 'superpower' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	spearow: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'leer' },
			{ level: 13, move: 'furyattack' },
			{ level: 19, move: 'mirrormove' },
			{ level: 25, move: 'swordsdance' },
			{ level: 31, move: 'agility' },
			{ level: 37, move: 'drillpeck' },
		],
		egg: ['drillpeck', 'mirrormove'],
		tm: ['toxic', 'rest', 'round'],
	},
	fearow: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'leer' },
			{ level: 13, move: 'furyattack' },
			{ level: 19, move: 'mirrormove' },
			{ level: 25, move: 'swordsdance' },
			{ level: 31, move: 'agility' },
			{ level: 37, move: 'drillpeck' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round'],
	},
	ekans: {
		levelup: [
			{ level: 1, move: 'wrap' },
			{ level: 1, move: 'leer' },
			{ level: 6, move: 'poisongas' },
			{ level: 11, move: 'bite' },
			{ level: 16, move: 'toxicspikes' },
			{ level: 21, move: 'glare' },
			{ level: 26, move: 'screech' },
			{ level: 31, move: 'sludgebomb' },
		],
		egg: ['astonish', 'childsnap', 'copycats', 'dragontail', 'enable', 'poisontail'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	arbok: {
		levelup: [
			{ level: 1, move: 'wrap' },
			{ level: 1, move: 'leer' },
			{ level: 6, move: 'poisongas' },
			{ level: 11, move: 'bite' },
			{ level: 16, move: 'toxicspikes' },
			{ level: 21, move: 'glare' },
			{ level: 26, move: 'screech' },
			{ level: 31, move: 'sludgebomb' },
			{ level: 41, move: 'coil' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	pikachu: {
		levelup: [
			{ level: 1, move: 'thunderbolt' },
			{ level: 1, move: 'quickattack' },
			{ level: 6, move: 'thunderwave' },
			{ level: 11, move: 'thunder' },
			{ level: 16, move: 'doubleteam' },
			{ level: 21, move: 'slam' },
			{ level: 26, move: 'thunderwave' },
			{ level: 31, move: 'agility' },
			{ level: 36, move: 'thunderbolt' },
		],
		egg: ['bulletseed', 'copycat', 'curse', 'detect', 'disarmingvoice', 'doubleteam', 'electroball'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	raichu: {
		levelup: [
			{ level: 1, move: 'thunderbolt' },
			{ level: 1, move: 'quickattack' },
			{ level: 6, move: 'thunderwave' },
			{ level: 11, move: 'thunder' },
			{ level: 16, move: 'doubleteam' },
			{ level: 21, move: 'slam' },
			{ level: 26, move: 'thunderwave' },
			{ level: 31, move: 'agility' },
			{ level: 36, move: 'thunderbolt' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	ditto: {
		levelup: [{ level: 1, move: 'transform' }],
		egg: [],
		tm: [],
	},
	diglett: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'astonish' },
			{ level: 10, move: 'magnitude' },
			{ level: 15, move: 'bulldoze' },
			{ level: 20, move: 'sandtomb' },
			{ level: 25, move: 'earthquake' },
		],
		egg: ['curse', 'memento', 'reversal'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	dugtrio: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'astonish' },
			{ level: 10, move: 'magnitude' },
			{ level: 15, move: 'bulldoze' },
			{ level: 20, move: 'sandtomb' },
			{ level: 25, move: 'earthquake' },
			{ level: 31, move: 'stoneedge' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	meowth: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'bite' },
			{ level: 10, move: 'fakeout' },
			{ level: 15, move: 'furyswipes' },
			{ level: 20, move: 'screech' },
			{ level: 25, move: 'slash' },
			{ level: 30, move: 'payday' },
		],
		egg: ['assist', 'bite', 'captivate', 'fakeout', 'lastresort', 'snatch', 'tailwhip'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	persian: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'bite' },
			{ level: 10, move: 'fakeout' },
			{ level: 15, move: 'furyswipes' },
			{ level: 20, move: 'screech' },
			{ level: 25, move: 'slash' },
			{ level: 30, move: 'payday' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	psyduck: {
		levelup: [
			{ level: 1, move: 'watersport' },
			{ level: 1, move: 'scratch' },
			{ level: 7, move: 'tailwhip' },
			{ level: 13, move: 'disable' },
			{ level: 19, move: 'aquatail' },
			{ level: 25, move: 'psychic' },
			{ level: 31, move: 'hydropump' },
		],
		egg: ['brine', 'crosschop', 'foresight', 'futuresight', 'icywind', 'yawn'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'scald'],
	},
	golduck: {
		levelup: [
			{ level: 1, move: 'watersport' },
			{ level: 1, move: 'scratch' },
			{ level: 7, move: 'tailwhip' },
			{ level: 13, move: 'disable' },
			{ level: 19, move: 'aquatail' },
			{ level: 25, move: 'psychic' },
			{ level: 31, move: 'hydropump' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'scald'],
	},
	mankey: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'lowkick' },
			{ level: 5, move: 'leer' },
			{ level: 9, move: 'focusenergy' },
			{ level: 13, move: 'furyswipes' },
			{ level: 17, move: 'karatechop' },
			{ level: 21, move: 'seismictoss' },
			{ level: 25, move: 'submission' },
		],
		egg: ['closecombat', 'counter', 'foresight', 'helpinghand', 'knockoff'],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	primeape: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'lowkick' },
			{ level: 5, move: 'leer' },
			{ level: 9, move: 'focusenergy' },
			{ level: 13, move: 'furyswipes' },
			{ level: 17, move: 'karatechop' },
			{ level: 21, move: 'seismictoss' },
			{ level: 25, move: 'submission' },
			{ level: 33, move: 'closecombat' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	growlithe: {
		levelup: [
			{ level: 1, move: 'bite' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'ember' },
			{ level: 10, move: 'leer' },
			{ level: 15, move: 'takedown' },
			{ level: 20, move: 'flameburst' },
			{ level: 25, move: 'wildcharge' },
			{ level: 30, move: 'flareblitz' },
		],
		egg: ['closecombat', 'covet', 'doubleedge', 'ironhead', 'morningsun', 'revenge'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower', 'thunderbolt'],
	},
	arcanine: {
		levelup: [
			{ level: 1, move: 'bite' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'ember' },
			{ level: 10, move: 'leer' },
			{ level: 15, move: 'takedown' },
			{ level: 20, move: 'flameburst' },
			{ level: 25, move: 'wildcharge' },
			{ level: 30, move: 'flareblitz' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower', 'thunderbolt'],
	},
	poliwag: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'hypnosis' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'bodyslam' },
			{ level: 25, move: 'raindance' },
			{ level: 31, move: 'hydropump' },
		],
		egg: ['bubblebeam', 'endeavor', 'haze', 'refresh', 'wakeupslap'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	poliwhirl: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'hypnosis' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'bodyslam' },
			{ level: 25, move: 'raindance' },
			{ level: 31, move: 'hydropump' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	poliwrath: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'hypnosis' },
			{ level: 1, move: 'dynamicpunch' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'bodyslam' },
			{ level: 25, move: 'raindance' },
			{ level: 31, move: 'hydropump' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	abra: {
		levelup: [{ level: 1, move: 'teleport' }],
		egg: ['allyswitch', 'barrier', 'encore', 'firepunch', 'guardsplit'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	kadabra: {
		levelup: [
			{ level: 1, move: 'teleport' },
			{ level: 1, move: 'kinesis' },
			{ level: 16, move: 'confusion' },
			{ level: 36, move: 'psychic' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	alakazam: {
		levelup: [
			{ level: 1, move: 'teleport' },
			{ level: 1, move: 'kinesis' },
			{ level: 1, move: 'guardsplit' },
			{ level: 16, move: 'confusion' },
			{ level: 36, move: 'psychic' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	machop: {
		levelup: [
			{ level: 1, move: 'lowkick' },
			{ level: 1, move: 'leer' },
			{ level: 5, move: 'focusenergy' },
			{ level: 9, move: 'karatechop' },
			{ level: 13, move: 'seismictoss' },
			{ level: 17, move: 'submission' },
			{ level: 21, move: 'bulkup' },
			{ level: 25, move: 'crosschop' },
		],
		egg: ['bulletpunch', 'closecombat', 'foresight', 'helpinghand', 'knockoff'],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	machoke: {
		levelup: [
			{ level: 1, move: 'lowkick' },
			{ level: 1, move: 'leer' },
			{ level: 5, move: 'focusenergy' },
			{ level: 9, move: 'karatechop' },
			{ level: 13, move: 'seismictoss' },
			{ level: 17, move: 'submission' },
			{ level: 21, move: 'bulkup' },
			{ level: 25, move: 'crosschop' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	machamp: {
		levelup: [
			{ level: 1, move: 'lowkick' },
			{ level: 1, move: 'leer' },
			{ level: 1, move: 'bulletpunch' },
			{ level: 5, move: 'focusenergy' },
			{ level: 9, move: 'karatechop' },
			{ level: 13, move: 'seismictoss' },
			{ level: 17, move: 'submission' },
			{ level: 21, move: 'bulkup' },
			{ level: 25, move: 'crosschop' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	bellsprout: {
		levelup: [
			{ level: 1, move: 'vinewhip' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'wrap' },
			{ level: 13, move: 'poisonpowder' },
			{ level: 19, move: 'sleeppowder' },
			{ level: 25, move: 'stunspore' },
			{ level: 31, move: 'acid' },
		],
		egg: ['curse', 'gigadrain', 'leafstorm', 'magicalleaf', 'powerwhip', 'synthesis'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	weepinbell: {
		levelup: [
			{ level: 1, move: 'vinewhip' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'wrap' },
			{ level: 13, move: 'poisonpowder' },
			{ level: 19, move: 'sleeppowder' },
			{ level: 25, move: 'stunspore' },
			{ level: 31, move: 'acid' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	victreebel: {
		levelup: [
			{ level: 1, move: 'vinewhip' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'wrap' },
			{ level: 13, move: 'poisonpowder' },
			{ level: 19, move: 'sleeppowder' },
			{ level: 25, move: 'stunspore' },
			{ level: 31, move: 'acid' },
			{ level: 36, move: 'leafblade' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	tentacool: {
		levelup: [
			{ level: 1, move: 'tentacle' },
			{ level: 1, move: 'poisonspray' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'acid' },
			{ level: 25, move: 'toxicspikes' },
			{ level: 31, move: 'mirrorcoat' },
		],
		egg: ['constrict', 'knockoff', 'mudsport', 'rapidspin', 'reflecttype', 'screech'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'sludgebomb'],
	},
	tentacruel: {
		levelup: [
			{ level: 1, move: 'tentacle' },
			{ level: 1, move: 'poisonspray' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'acid' },
			{ level: 25, move: 'toxicspikes' },
			{ level: 31, move: 'mirrorcoat' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'sludgebomb'],
	},
	slowbro: {
		levelup: [
			{ level: 1, move: 'curse' },
			{ level: 1, move: 'yawn' },
			{ level: 1, move: 'disable' },
			{ level: 1, move: 'watersport' },
			{ level: 7, move: 'tailwhip' },
			{ level: 13, move: 'disable' },
			{ level: 19, move: 'aquatail' },
			{ level: 25, move: 'psychic' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'scald'],
	},
	slowpoke: {
		levelup: [
			{ level: 1, move: 'curse' },
			{ level: 1, move: 'yawn' },
			{ level: 7, move: 'tailwhip' },
			{ level: 13, move: 'disable' },
			{ level: 19, move: 'aquatail' },
			{ level: 25, move: 'psychic' },
		],
		egg: ['bellydrum', 'futuresight', 'mudbomb', 'signalbeam', 'snore'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'scald'],
	},
	seel: {
		levelup: [
			{ level: 1, move: 'headbutt' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'aquatail' },
			{ level: 13, move: 'icywind' },
			{ level: 19, move: 'rest' },
			{ level: 25, move: 'aurorabeam' },
			{ level: 31, move: 'aquaring' },
		],
		egg: ['brine', 'fakeout', 'peck', 'signalbeam', 'sleeptalk', 'spitup'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'icebeam'],
	},
	dewgong: {
		levelup: [
			{ level: 1, move: 'headbutt' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'aquatail' },
			{ level: 13, move: 'icywind' },
			{ level: 19, move: 'rest' },
			{ level: 25, move: 'aurorabeam' },
			{ level: 31, move: 'aquaring' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'icebeam'],
	},
	shellder: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bite' },
			{ level: 19, move: 'protect' },
			{ level: 25, move: 'clamp' },
			{ level: 31, move: 'irondefense' },
		],
		egg: ['aurorabeam', 'bubblebeam', 'curse', 'knockoff', 'mudshot', 'wideguard'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	cloyster: {
		levelup: [
			{ level: 1, move: 'withdrawl' },
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'spikecannon' },
			{ level: 7, move: 'watersport' },
			{ level: 13, move: 'bite' },
			{ level: 19, move: 'protect' },
			{ level: 25, move: 'clamp' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	gastly: {
		levelup: [
			{ level: 1, move: 'hypnosis' },
			{ level: 1, move: 'leer' },
			{ level: 5, move: 'astonish' },
			{ level: 10, move: 'sludgebomb' },
			{ level: 15, move: 'meanlook' },
			{ level: 20, move: 'curse' },
			{ level: 25, move: 'shadowball' },
			{ level: 30, move: 'shadowpunch' },
		],
		egg: ['disable', 'haze', 'perishsong', 'shadowsneak', 'suckerpunch'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	haunter: {
		levelup: [
			{ level: 1, move: 'hypnosis' },
			{ level: 1, move: 'leer' },
			{ level: 5, move: 'astonish' },
			{ level: 10, move: 'sludgebomb' },
			{ level: 15, move: 'meanlook' },
			{ level: 20, move: 'curse' },
			{ level: 25, move: 'shadowball' },
			{ level: 30, move: 'shadowpunch' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	gengar: {
		levelup: [
			{ level: 1, move: 'hypnosis' },
			{ level: 1, move: 'leer' },
			{ level: 1, move: 'shadowtag' },
			{ level: 5, move: 'astonish' },
			{ level: 10, move: 'sludgebomb' },
			{ level: 15, move: 'meanlook' },
			{ level: 20, move: 'curse' },
			{ level: 25, move: 'shadowball' },
			{ level: 30, move: 'shadowpunch' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	onix: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'bind' },
			{ level: 13, move: 'rockthrow' },
			{ level: 19, move: 'harden' },
			{ level: 25, move: 'rockslide' },
			{ level: 31, move: 'screech' },
		],
		egg: ['assault', 'block', 'curse', 'stealthrock', 'rockpolish'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	drowzee: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'hypnosis' },
			{ level: 7, move: 'disable' },
			{ level: 13, move: 'confusion' },
			{ level: 19, move: 'headbutt' },
			{ level: 25, move: 'dreameater' },
			{ level: 31, move: 'psychic' },
		],
		egg: ['assist', 'barrier', 'cosmicpower', 'nastyplot', 'trick'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	hypno: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'hypnosis' },
			{ level: 7, move: 'disable' },
			{ level: 13, move: 'confusion' },
			{ level: 19, move: 'headbutt' },
			{ level: 25, move: 'dreameater' },
			{ level: 31, move: 'psychic' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	krabby: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'bubblebeam' },
			{ level: 13, move: 'harden' },
			{ level: 19, move: 'vicegrip' },
			{ level: 25, move: 'stomp' },
			{ level: 31, move: 'crabhammer' },
		],
		egg: ['amnesia', 'ancientpower', 'detoxify', 'knockoff', 'mudshot', 'wideguard'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	kingler: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'bubblebeam' },
			{ level: 13, move: 'harden' },
			{ level: 19, move: 'vicegrip' },
			{ level: 25, move: 'stomp' },
			{ level: 31, move: 'crabhammer' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	voltorb: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'thunderwave' },
			{ level: 7, move: 'sonicboom' },
			{ level: 13, move: 'chargebeam' },
			{ level: 19, move: 'spark' },
			{ level: 25, move: 'thunderbolt' },
			{ level: 31, move: 'explosion' },
		],
		egg: ['charge', 'curse', 'metalsound', 'mirrorcoat', 'painsplit'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	electrode: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'thunderwave' },
			{ level: 7, move: 'sonicboom' },
			{ level: 13, move: 'chargebeam' },
			{ level: 19, move: 'spark' },
			{ level: 25, move: 'thunderbolt' },
			{ level: 31, move: 'explosion' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	exeggcute: {
		levelup: [
			{ level: 1, move: 'barrage' },
			{ level: 1, move: 'leechseed' },
			{ level: 7, move: 'absorb' },
			{ level: 13, move: 'growth' },
			{ level: 19, move: 'bulletseed' },
			{ level: 25, move: 'synthesis' },
			{ level: 31, move: 'solarbeam' },
		],
		egg: ['curse', 'ingrain', 'leafstorm', 'naturepower', 'spitup', 'woodhammer'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'solarbeam'],
	},
	exeggutor: {
		levelup: [
			{ level: 1, move: 'barrage' },
			{ level: 1, move: 'leechseed' },
			{ level: 7, move: 'absorb' },
			{ level: 13, move: 'growth' },
			{ level: 19, move: 'bulletseed' },
			{ level: 25, move: 'synthesis' },
			{ level: 31, move: 'solarbeam' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'solarbeam'],
	},
	cubone: {
		levelup: [
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'tailwhip' },
			{ level: 5, move: 'boneclub' },
			{ level: 9, move: 'headbutt' },
			{ level: 13, move: 'leer' },
			{ level: 17, move: 'focusenergy' },
			{ level: 21, move: 'bonemerang' },
			{ level: 25, move: 'doubleedge' },
		],
		egg: ['ancientpower', 'counter', 'curse', 'detect', 'ironhead'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	marowak: {
		levelup: [
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'tailwhip' },
			{ level: 5, move: 'boneclub' },
			{ level: 9, move: 'headbutt' },
			{ level: 13, move: 'leer' },
			{ level: 17, move: 'focusenergy' },
			{ level: 21, move: 'bonemerang' },
			{ level: 25, move: 'doubleedge' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	hitmonlee: {
		levelup: [
			{ level: 1, move: 'doublekick' },
			{ level: 1, move: 'meditate' },
			{ level: 7, move: 'pursuit' },
			{ level: 13, move: 'seismictoss' },
			{ level: 19, move: 'highkick' },
			{ level: 25, move: 'brickbreak' },
		],
		egg: ['bulletpunch', 'closecombat', 'counter', 'curse', 'fakeout'],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	hitmonchan: {
		levelup: [
			{ level: 1, move: 'cometpunch' },
			{ level: 1, move: 'agility' },
			{ level: 7, move: 'pursuit' },
			{ level: 13, move: 'seismictoss' },
			{ level: 19, move: 'machpunch' },
			{ level: 25, move: 'brickbreak' },
		],
		egg: ['bulletpunch', 'closecombat', 'counter', 'curse', 'feint'],
		tm: ['toxic', 'rest', 'round', 'earthquake'],
	},
	lickitung: {
		levelup: [
			{ level: 1, move: 'lick' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'wrap' },
			{ level: 13, move: 'disable' },
			{ level: 19, move: 'slam' },
			{ level: 25, move: 'acidspray' },
			{ level: 31, move: 'powerwhip' },
		],
		egg: ['bodyslam', 'curse', 'hammerarm', 'muddywater', 'perishsong', 'icywind'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	rhyhorn: {
		levelup: [
			{ level: 1, move: 'stomp' },
			{ level: 1, move: 'tailwhip' },
			{ level: 7, move: 'furyattack' },
			{ level: 13, move: 'hornattack' },
			{ level: 19, move: 'stoneedge' },
			{ level: 25, move: 'earthquake' },
			{ level: 31, move: 'megahorn' },
		],
		egg: ['curse', 'crunch', 'metalburst', 'mudshot', 'reversal', 'sludgebomb'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	rhydon: {
		levelup: [
			{ level: 1, move: 'stomp' },
			{ level: 1, move: 'tailwhip' },
			{ level: 7, move: 'furyattack' },
			{ level: 13, move: 'hornattack' },
			{ level: 19, move: 'stoneedge' },
			{ level: 25, move: 'earthquake' },
			{ level: 31, move: 'megahorn' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	chansey: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'tailwhip' },
			{ level: 9, move: 'refresh' },
			{ level: 13, move: 'doubleslap' },
			{ level: 17, move: 'sing' },
			{ level: 21, move: 'eggbomb' },
			{ level: 25, move: 'takedown' },
		],
		egg: ['aromatherapy', 'curse', 'gravity', 'healbell', 'metronome', 'present'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	kangaskhan: {
		levelup: [
			{ level: 1, move: 'cometpunch' },
			{ level: 1, move: 'leer' },
			{ level: 7, move: 'bite' },
			{ level: 13, move: 'doublehit' },
			{ level: 19, move: 'fakeout' },
			{ level: 25, move: 'dizzypunch' },
			{ level: 31, move: 'crunch' },
		],
		egg: ['curse', 'counter', 'doubleedge', 'focuspunch', 'hammerarm'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	horsea: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'smokescreen' },
			{ level: 7, move: 'focusenergy' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'agility' },
			{ level: 25, move: 'hydropump' },
		],
		egg: ['aurorabeam', 'curse', 'endure', 'octazooka', 'snore'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	seadra: {
		levelup: [
			{ level: 1, move: 'bubble' },
			{ level: 1, move: 'smokescreen' },
			{ level: 7, move: 'focusenergy' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'agility' },
			{ level: 25, move: 'hydropump' },
			{ level: 32, move: 'dragondance' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	goldeen: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'tailwhip' },
			{ level: 7, move: 'focusenergy' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'furyattack' },
			{ level: 25, move: 'waterfall' },
			{ level: 31, move: 'horndrill' },
		],
		egg: ['aquajet', 'bodyslam', 'counter', 'disable', 'doubleedge', 'hydropump'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	seaking: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'tailwhip' },
			{ level: 7, move: 'focusenergy' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'furyattack' },
			{ level: 25, move: 'waterfall' },
			{ level: 31, move: 'horndrill' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	staryu: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 7, move: 'watergun' },
			{ level: 13, move: 'rapidspin' },
			{ level: 19, move: 'recover' },
			{ level: 25, move: 'minimize' },
			{ level: 31, move: 'bubblebeam' },
			{ level: 37, move: 'hydropump' },
		],
		egg: ['astralbarrage', 'curse', 'endure', 'mudshot', 'reflecttype'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	starmie: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'watergun' },
			{ level: 7, move: 'rapidspin' },
			{ level: 13, move: 'recover' },
			{ level: 19, move: 'minimize' },
			{ level: 25, move: 'bubblebeam' },
			{ level: 31, move: 'hydropump' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'psychic'],
	},
	'mr-mime': {
		levelup: [
			{ level: 1, move: 'barrier' },
			{ level: 1, move: 'confusion' },
			{ level: 7, move: 'doubleslap' },
			{ level: 13, move: 'minimize' },
			{ level: 19, move: 'meditate' },
			{ level: 25, move: 'psychic' },
			{ level: 31, move: 'doubleteam' },
		],
		egg: ['allyswitch', 'icywind', 'knockoff', 'powersplit', 'quash', 'teeterdance'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	scyther: {
		levelup: [
			{ level: 1, move: 'quickattack' },
			{ level: 1, move: 'leer' },
			{ level: 7, move: 'focusenergy' },
			{ level: 13, move: 'pursuit' },
			{ level: 19, move: 'falseswipe' },
			{ level: 25, move: 'slash' },
			{ level: 31, move: 'swordsdance' },
			{ level: 37, move: 'xscissor' },
		],
		egg: ['bulletpunch', 'curse', 'defog', 'endure', 'nightslash'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	jynx: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'leer' },
			{ level: 7, move: 'lovelykiss' },
			{ level: 13, move: 'doubleslap' },
			{ level: 19, move: 'icepunch' },
			{ level: 25, move: 'bodyslam' },
			{ level: 31, move: 'icebeam' },
		],
		egg: ['curse', 'fakeout', 'gravity', 'nastyplot', 'wish'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'icebeam'],
	},
	electabuzz: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'thunderwave' },
			{ level: 7, move: 'lowkick' },
			{ level: 13, move: 'swift' },
			{ level: 19, move: 'shockwave' },
			{ level: 25, move: 'thunderpunch' },
			{ level: 31, move: 'thunderbolt' },
		],
		egg: ['crosschop', 'firepunch', 'icepunch', 'rollingkick', 'signalbeam'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	magby: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'ember' },
			{ level: 7, move: 'leer' },
			{ level: 13, move: 'machpunch' },
			{ level: 19, move: 'firespin' },
			{ level: 25, move: 'flamecharge' },
			{ level: 31, move: 'firepunch' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower'],
	},
	magnemite: {
		levelup: [
			{ level: 1, move: 'magnetrise' },
			{ level: 1, move: 'thundershock' },
			{ level: 7, move: 'metalsound' },
			{ level: 13, move: 'thunderwave' },
			{ level: 19, move: 'sonicboom' },
			{ level: 25, move: 'chargebeam' },
			{ level: 31, move: 'spark' },
			{ level: 37, move: 'mirrorshot' },
		],
		egg: ['astonish', 'curse', 'mirrorcoat', 'painsplit', 'wringout'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	magneton: {
		levelup: [
			{ level: 1, move: 'magnetrise' },
			{ level: 1, move: 'thundershock' },
			{ level: 7, move: 'metalsound' },
			{ level: 13, move: 'thunderwave' },
			{ level: 19, move: 'sonicboom' },
			{ level: 25, move: 'chargebeam' },
			{ level: 31, move: 'spark' },
			{ level: 37, move: 'mirrorshot' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	farfetchd: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'sandattack' },
			{ level: 7, move: 'leer' },
			{ level: 13, move: 'furyattack' },
			{ level: 19, move: 'pursuit' },
			{ level: 25, move: 'slash' },
		],
		egg: ['curse', 'defog', 'foresight', 'knockoff', 'steelwing'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	doduo: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'rage' },
			{ level: 9, move: 'furyattack' },
			{ level: 13, move: 'pursuit' },
			{ level: 17, move: 'doubleattack' },
			{ level: 21, move: 'agility' },
		],
		egg: ['counter', 'curse', 'gigadrain', 'knockoff'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	dodrio: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'rage' },
			{ level: 9, move: 'furyattack' },
			{ level: 13, move: 'pursuit' },
			{ level: 17, move: 'doubleattack' },
			{ level: 21, move: 'agility' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	grimer: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'poisongas' },
			{ level: 7, move: 'harden' },
			{ level: 13, move: 'acidspray' },
			{ level: 19, move: 'toxicspikes' },
			{ level: 25, move: 'sludgebomb' },
			{ level: 31, move: 'acidarmor' },
		],
		egg: ['curse', 'endure', 'haze', 'meditate'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	muk: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 1, move: 'poisongas' },
			{ level: 7, move: 'harden' },
			{ level: 13, move: 'acidspray' },
			{ level: 19, move: 'toxicspikes' },
			{ level: 25, move: 'sludgebomb' },
			{ level: 31, move: 'acidarmor' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'sludgebomb'],
	},
	venonat: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'disable' },
			{ level: 7, move: 'poisonpowder' },
			{ level: 13, move: 'leechlife' },
			{ level: 19, move: 'spore' },
			{ level: 25, move: 'psychic' },
		],
		egg: ['batonpass', 'curse', 'gigadrain', 'signalbeam'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'sludgebomb'],
	},
	venomoth: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'disable' },
			{ level: 1, move: 'confusion' },
			{ level: 7, move: 'poisonpowder' },
			{ level: 13, move: 'leechlife' },
			{ level: 19, move: 'spore' },
			{ level: 25, move: 'psychic' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'sludgebomb'],
	},
	paras: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'stunspore' },
			{ level: 7, move: 'absorb' },
			{ level: 13, move: 'furycutter' },
			{ level: 19, move: 'spore' },
			{ level: 25, move: 'growth' },
			{ level: 31, move: 'gigadrain' },
		],
		egg: ['curse', 'leechseed', 'screech'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	parasect: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'stunspore' },
			{ level: 7, move: 'absorb' },
			{ level: 13, move: 'furycutter' },
			{ level: 19, move: 'spore' },
			{ level: 25, move: 'growth' },
			{ level: 31, move: 'gigadrain' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	tauros: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 5, move: 'rage' },
			{ level: 9, move: 'hornattack' },
			{ level: 13, move: 'scaryface' },
			{ level: 17, move: 'pursuit' },
			{ level: 21, move: 'furyattack' },
		],
		egg: ['curse', 'doubleedge', 'feint', 'ironhead', 'zenheadbutt'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	lapras: {
		levelup: [
			{ level: 1, move: 'watergun' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'mist' },
			{ level: 13, move: 'bubblebeam' },
			{ level: 19, move: 'leer' },
			{ level: 25, move: 'icebeam' },
			{ level: 31, move: 'hydropump' },
		],
		egg: ['ancientpower', 'curse', 'dragondance', 'freezedry', 'refresh'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald', 'icebeam'],
	},
	eevee: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 8, move: 'sandattack' },
			{ level: 16, move: 'quickattack' },
			{ level: 24, move: 'bite' },
			{ level: 32, move: 'batonpass' },
			{ level: 40, move: 'takedown' },
		],
		egg: ['captivate', 'charm', 'covet', 'curse', 'detect', 'endure'],
		tm: ['toxic', 'rest', 'round', 'shadowball'],
	},
	vaporeon: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'waterabsorb' },
			{ level: 8, move: 'sandattack' },
			{ level: 16, move: 'quickattack' },
			{ level: 24, move: 'bite' },
			{ level: 32, move: 'batonpass' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	jolteon: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'static' },
			{ level: 8, move: 'sandattack' },
			{ level: 16, move: 'quickattack' },
			{ level: 24, move: 'bite' },
			{ level: 32, move: 'batonpass' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	flareon: {
		levelup: [
			{ level: 1, move: 'tackle' },
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'flashfire' },
			{ level: 8, move: 'sandattack' },
			{ level: 16, move: 'quickattack' },
			{ level: 24, move: 'bite' },
			{ level: 32, move: 'batonpass' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower'],
	},
	porygon: {
		levelup: [
			{ level: 1, move: 'sharpen' },
			{ level: 1, move: 'conversion' },
			{ level: 7, move: 'conversion2' },
			{ level: 13, move: 'recover' },
			{ level: 19, move: 'chargebeam' },
			{ level: 25, move: 'psychic' },
			{ level: 31, move: 'lockon' },
		],
		egg: ['curse', 'nastyplot', 'recover', 'trace'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'thunderbolt'],
	},
	kabuto: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 7, move: 'sandattack' },
			{ level: 13, move: 'protect' },
			{ level: 19, move: 'ancientpower' },
			{ level: 25, move: 'takedown' },
			{ level: 31, move: 'stoneedge' },
		],
		egg: ['aurorabeam', 'curse', 'knockoff', 'rapidspin', 'stealthrock'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	kabutops: {
		levelup: [
			{ level: 1, move: 'scratch' },
			{ level: 1, move: 'growl' },
			{ level: 1, move: 'slash' },
			{ level: 7, move: 'sandattack' },
			{ level: 13, move: 'protect' },
			{ level: 19, move: 'ancientpower' },
			{ level: 25, move: 'takedown' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	omanyte: {
		levelup: [
			{ level: 1, move: 'constrict' },
			{ level: 1, move: 'withdraw' },
			{ level: 7, move: 'bite' },
			{ level: 13, move: 'watergun' },
			{ level: 19, move: 'mudshot' },
			{ level: 25, move: 'leer' },
			{ level: 31, move: 'hydropump' },
		],
		egg: ['curse', 'knockoff', 'mudshot', 'refresh', 'supersonic'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	omastar: {
		levelup: [
			{ level: 1, move: 'constrict' },
			{ level: 1, move: 'withdraw' },
			{ level: 1, move: 'spikecannon' },
			{ level: 7, move: 'bite' },
			{ level: 13, move: 'watergun' },
			{ level: 19, move: 'mudshot' },
			{ level: 25, move: 'leer' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'scald'],
	},
	snorlax: {
		levelup: [
			{ level: 1, move: 'curse' },
			{ level: 1, move: 'yawn' },
			{ level: 7, move: 'pound' },
			{ level: 13, move: 'rest' },
			{ level: 19, move: 'bodyslam' },
			{ level: 25, move: 'snore' },
			{ level: 31, move: 'crunch' },
			{ level: 37, move: 'gigaimpact' },
		],
		egg: ['bellydrum', 'counter', 'curse', 'doubleedge', 'focuspunch'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'earthquake'],
	},
	articuno: {
		levelup: [
			{ level: 1, move: 'gust' },
			{ level: 1, move: 'powdersnow' },
			{ level: 1, move: 'mist' },
			{ level: 31, move: 'icebeam' },
			{ level: 41, move: 'agility' },
			{ level: 51, move: 'roost' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'icebeam'],
	},
	zapdos: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'thunderwave' },
			{ level: 1, move: 'furyattack' },
			{ level: 31, move: 'thunderbolt' },
			{ level: 41, move: 'agility' },
			{ level: 51, move: 'roost' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	moltres: {
		levelup: [
			{ level: 1, move: 'peck' },
			{ level: 1, move: 'ember' },
			{ level: 1, move: 'furyattack' },
			{ level: 31, move: 'flamethrower' },
			{ level: 41, move: 'agility' },
			{ level: 51, move: 'roost' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'flamethrower'],
	},
	dratini: {
		levelup: [
			{ level: 1, move: 'wrap' },
			{ level: 7, move: 'leer' },
			{ level: 13, move: 'thunderwave' },
			{ level: 19, move: 'dragonrage' },
			{ level: 25, move: 'slam' },
			{ level: 31, move: 'agility' },
		],
		egg: ['aquajet', 'curse', 'dragondance', 'dragondarts', 'extremespeed'],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	dragonair: {
		levelup: [
			{ level: 1, move: 'wrap' },
			{ level: 7, move: 'leer' },
			{ level: 13, move: 'thunderwave' },
			{ level: 19, move: 'dragonrage' },
			{ level: 25, move: 'slam' },
			{ level: 31, move: 'agility' },
			{ level: 41, move: 'dragondance' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt'],
	},
	dragonite: {
		levelup: [
			{ level: 1, move: 'wrap' },
			{ level: 1, move: 'leer' },
			{ level: 1, move: 'outrage' },
			{ level: 7, move: 'thunderwave' },
			{ level: 13, move: 'dragonrage' },
			{ level: 19, move: 'slam' },
			{ level: 25, move: 'agility' },
			{ level: 31, move: 'dragondance' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'thunderbolt', 'earthquake'],
	},
	mewtwo: {
		levelup: [
			{ level: 1, move: 'confusion' },
			{ level: 1, move: 'barrier' },
			{ level: 1, move: 'swift' },
			{ level: 1, move: 'psybeam' },
			{ level: 31, move: 'psychic' },
			{ level: 41, move: 'guardsplit' },
			{ level: 51, move: 'calmmind' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic'],
	},
	mew: {
		levelup: [
			{ level: 1, move: 'pound' },
			{ level: 10, move: 'transform' },
			{ level: 20, move: 'megapunch' },
			{ level: 30, move: 'firepunch' },
			{ level: 40, move: 'icepunch' },
			{ level: 50, move: 'thunderpunch' },
			{ level: 60, move: 'psychic' },
			{ level: 70, move: 'barrier' },
		],
		egg: [],
		tm: ['toxic', 'rest', 'round', 'shadowball', 'psychic', 'flamethrower', 'thunderbolt', 'icebeam'],
	},
};

export default MANUAL_LEARNSETS;
