/*
* Pokemon Showdown
* RPG Evolution Data
* Note: Trade Evolution are changed to be level based.
*/
export const MANUAL_EVOLUTIONS: { [key: string]: { evoTo: string, evoLevel: number, evoItem?: string }[] } = {
	// Starters - Gen 1
	'bulbasaur': [{ evoTo: 'ivysaur', evoLevel: 16 }],
	'ivysaur': [{ evoTo: 'venusaur', evoLevel: 32 }],
	'charmander': [{ evoTo: 'charmeleon', evoLevel: 16 }],
	'charmeleon': [{ evoTo: 'charizard', evoLevel: 36 }],
	'squirtle': [{ evoTo: 'wartortle', evoLevel: 16 }],
	'wartortle': [{ evoTo: 'blastoise', evoLevel: 36 }],

	// Starters - Gen 2
	'chikorita': [{ evoTo: 'bayleef', evoLevel: 16 }],
	'bayleef': [{ evoTo: 'meganium', evoLevel: 32 }],
	'cyndaquil': [{ evoTo: 'quilava', evoLevel: 14 }],
	'quilava': [{ evoTo: 'typhlosion', evoLevel: 36 }],
	'totodile': [{ evoTo: 'croconaw', evoLevel: 18 }],
	'croconaw': [{ evoTo: 'feraligatr', evoLevel: 30 }],

	// Starters - Gen 3
	'treecko': [{ evoTo: 'grovyle', evoLevel: 16 }],
	'grovyle': [{ evoTo: 'sceptile', evoLevel: 36 }],
	'torchic': [{ evoTo: 'combusken', evoLevel: 16 }],
	'combusken': [{ evoTo: 'blaziken', evoLevel: 36 }],
	'mudkip': [{ evoTo: 'marshtomp', evoLevel: 16 }],
	'marshtomp': [{ evoTo: 'swampert', evoLevel: 36 }],

	// Starters - Gen 4
	'turtwig': [{ evoTo: 'grotle', evoLevel: 18 }],
	'grotle': [{ evoTo: 'torterra', evoLevel: 32 }],
	'chimchar': [{ evoTo: 'monferno', evoLevel: 14 }],
	'monferno': [{ evoTo: 'infernape', evoLevel: 36 }],
	'piplup': [{ evoTo: 'prinplup', evoLevel: 16 }],
	'prinplup': [{ evoTo: 'empoleon', evoLevel: 36 }],

	// Starters - Gen 5
	'snivy': [{ evoTo: 'servine', evoLevel: 17 }],
	'servine': [{ evoTo: 'serperior', evoLevel: 36 }],
	'tepig': [{ evoTo: 'pignite', evoLevel: 17 }],
	'pignite': [{ evoTo: 'emboar', evoLevel: 36 }],
	'oshawott': [{ evoTo: 'dewott', evoLevel: 17 }],
	'dewott': [{ evoTo: 'samurott', evoLevel: 36 }],

	// Starters - Gen 6
	'chespin': [{ evoTo: 'quilladin', evoLevel: 16 }],
	'quilladin': [{ evoTo: 'chesnaught', evoLevel: 36 }],
	'fennekin': [{ evoTo: 'braixen', evoLevel: 16 }],
	'braixen': [{ evoTo: 'delphox', evoLevel: 36 }],
	'froakie': [{ evoTo: 'frogadier', evoLevel: 16 }],
	'frogadier': [{ evoTo: 'greninja', evoLevel: 36 }],

	// Starters - Gen 7
	'rowlet': [{ evoTo: 'dartrix', evoLevel: 17 }],
	'dartrix': [{ evoTo: 'decidueye', evoLevel: 34 }],
	'litten': [{ evoTo: 'torracat', evoLevel: 17 }],
	'torracat': [{ evoTo: 'incineroar', evoLevel: 34 }],
	'popplio': [{ evoTo: 'brionne', evoLevel: 17 }],
	'brionne': [{ evoTo: 'primarina', evoLevel: 34 }],

	// Starters - Gen 8
	'grookey': [{ evoTo: 'thwackey', evoLevel: 16 }],
	'thwackey': [{ evoTo: 'rillaboom', evoLevel: 35 }],
	'scorbunny': [{ evoTo: 'cinderace', evoLevel: 16 }],
	'cinderace': [{ evoTo: 'raboot', evoLevel: 35 }],
	'sobble': [{ evoTo: 'drizzile', evoLevel: 16 }],
	'drizzile': [{ evoTo: 'inteleon', evoLevel: 35 }],

	// Starters - Gen 9
	'sprigatito': [{ evoTo: 'floragato', evoLevel: 16 }],
	'floragato': [{ evoTo: 'meowscarada', evoLevel: 36 }],
	'fuecoco': [{ evoTo: 'crocalor', evoLevel: 16 }],
	'crocalor': [{ evoTo: 'skeledirge', evoLevel: 36 }],
	'quaxly': [{ evoTo: 'quaxwell', evoLevel: 16 }],
	'quaxwell': [{ evoTo: 'quaquaval', evoLevel: 36 }],

	// Bug Types
	'caterpie': [{ evoTo: 'metapod', evoLevel: 7 }],
	'metapod': [{ evoTo: 'butterfree', evoLevel: 10 }],
	'weedle': [{ evoTo: 'kakuna', evoLevel: 7 }],
	'kakuna': [{ evoTo: 'beedrill', evoLevel: 10 }],
	'paras': [{ evoTo: 'parasect', evoLevel: 24 }],
	'venonat': [{ evoTo: 'venomoth', evoLevel: 31 }],
	'ledyba': [{ evoTo: 'ledian', evoLevel: 18 }],
	'spinarak': [{ evoTo: 'ariados', evoLevel: 18 }],
	'wurmple': [
		{ evoTo: 'silcoon', evoLevel: 7 },
		{ evoTo: 'cascoon', evoLevel: 7 },
	],
	'silcoon': [{ evoTo: 'beautifly', evoLevel: 10 }],
	'cascoon': [{ evoTo: 'dustox', evoLevel: 10 }],
	'nincada': [
		{ evoTo: 'ninjask', evoLevel: 20 },
		{ evoTo: 'shedinja', evoLevel: 20, evoItem: 'pokeball' },
	],
	'surskit': [{ evoTo: 'masquerain', evoLevel: 22 }],
	'volbeat': [{ evoTo: 'illumise', evoLevel: 99 }],
	'trapinch': [{ evoTo: 'vibrava', evoLevel: 35 }],
	'vibrava': [{ evoTo: 'flygon', evoLevel: 45 }],
	'anorith': [{ evoTo: 'armaldo', evoLevel: 40 }],
	'kricketot': [{ evoTo: 'kricketune', evoLevel: 10 }],
	'burmy': [
		{ evoTo: 'wormadam', evoLevel: 20 },
		{ evoTo: 'mothim', evoLevel: 20 },
	],
	'combee': [{ evoTo: 'vespiquen', evoLevel: 21 }],
	'skorupi': [{ evoTo: 'drapion', evoLevel: 40 }],
	'sewaddle': [{ evoTo: 'swadloon', evoLevel: 20 }],
	'swadloon': [{ evoTo: 'leavanny', evoLevel: 30 }],
	'venipede': [{ evoTo: 'whirlipede', evoLevel: 22 }],
	'whirlipede': [{ evoTo: 'scolipede', evoLevel: 30 }],
	'dwebble': [{ evoTo: 'crustle', evoLevel: 34 }],
	'joltik': [{ evoTo: 'galvantula', evoLevel: 36 }],
	'karrablast': [{ evoTo: 'escavalier', evoLevel: 36, evoItem: 'tradehelmet' }],
	'shelmet': [{ evoTo: 'accelgor', evoLevel: 36, evoItem: 'tradekarrablast' }],
	'larvesta': [{ evoTo: 'volcarona', evoLevel: 59 }],
	'scatterbug': [{ evoTo: 'spewpa', evoLevel: 9 }],
	'spewpa': [{ evoTo: 'vivillon', evoLevel: 12 }],
	'dewpider': [{ evoTo: 'araquanid', evoLevel: 22 }],
	'wimpod': [{ evoTo: 'golisopod', evoLevel: 30 }],
	'blipbug': [{ evoTo: 'dottler', evoLevel: 10 }],
	'dottler': [{ evoTo: 'orbeetle', evoLevel: 30 }],
	'sizzlipede': [{ evoTo: 'centiskorch', evoLevel: 28 }],
	'tarountula': [{ evoTo: 'spidops', evoLevel: 17 }],
	'nymble': [{ evoTo: 'lokix', evoLevel: 24 }],
	'rellor': [{ evoTo: 'rabsca', evoLevel: 36 }],
	'applin': [
		{ evoTo: 'flapple', evoLevel: 99, evoItem: 'tartapple' },
		{ evoTo: 'appletun', evoLevel: 99, evoItem: 'sweetapple' },
		{ evoTo: 'dipplin', evoLevel: 36, evoItem: 'syruppyapple' },
	],
	'dipplin': [{ evoTo: 'hydrapple', evoLevel: 42, evoItem: 'dragonchesto' }],

	// Normal Types
	'pidgey': [{ evoTo: 'pidgeotto', evoLevel: 18 }],
	'pidgeotto': [{ evoTo: 'pidgeot', evoLevel: 36 }],
	'rattata': [{ evoTo: 'raticate', evoLevel: 20 }],
	'spearow': [{ evoTo: 'fearow', evoLevel: 20 }],
	'meowth': [{ evoTo: 'persian', evoLevel: 28 }],
	'doduo': [{ evoTo: 'dodrio', evoLevel: 31 }],
	'lickitung': [{ evoTo: 'lickilicky', evoLevel: 36 }],
	'sentret': [{ evoTo: 'furret', evoLevel: 15 }],
	'hoothoot': [{ evoTo: 'noctowl', evoLevel: 20 }],
	'aipom': [{ evoTo: 'ambipom', evoLevel: 36 }],
	'dunsparce': [{ evoTo: 'dudunsparce', evoLevel: 36 }],
	'zigzagoon': [{ evoTo: 'linoone', evoLevel: 20 }],
	'taillow': [{ evoTo: 'swellow', evoLevel: 22 }],
	'skitty': [{ evoTo: 'delcatty', evoLevel: 99, evoItem: 'moonstone' }],
	'whismur': [{ evoTo: 'loudred', evoLevel: 20 }],
	'loudred': [{ evoTo: 'exploud', evoLevel: 40 }],
	'bidoof': [{ evoTo: 'bibarel', evoLevel: 15 }],
	'starly': [{ evoTo: 'staravia', evoLevel: 14 }],
	'staravia': [{ evoTo: 'staraptor', evoLevel: 34 }],
	'buneary': [{ evoTo: 'lopunny', evoLevel: 30 }],
	'glameow': [{ evoTo: 'purugly', evoLevel: 38 }],
	'happiny': [{ evoTo: 'chansey', evoLevel: 30, evoItem: 'ovalstone' }],
	'lillipup': [{ evoTo: 'herdier', evoLevel: 16 }],
	'herdier': [{ evoTo: 'stoutland', evoLevel: 32 }],
	'minccino': [{ evoTo: 'cinccino', evoLevel: 99, evoItem: 'shinystone' }],
	'rufflet': [{ evoTo: 'braviary', evoLevel: 54 }],
	'vullaby': [{ evoTo: 'mandibuzz', evoLevel: 54 }],
	'fletchling': [{ evoTo: 'fletchinder', evoLevel: 17 }],
	'fletchinder': [{ evoTo: 'talonflame', evoLevel: 35 }],
	'goomy': [{ evoTo: 'sliggoo', evoLevel: 40 }],
	'sliggoo': [{ evoTo: 'goodra', evoLevel: 50 }],
	'yungoos': [{ evoTo: 'gumshoos', evoLevel: 20 }],
	'pikipek': [{ evoTo: 'trumbeak', evoLevel: 14 }],
	'trumbeak': [{ evoTo: 'toucannon', evoLevel: 28 }],
	'stufful': [{ evoTo: 'bewear', evoLevel: 27 }],
	'wooloo': [{ evoTo: 'dubwool', evoLevel: 24 }],
	'nickit': [{ evoTo: 'thievul', evoLevel: 18 }],
	'lechonk': [{ evoTo: 'oinkologne', evoLevel: 18 }],
	'tandemaus': [{ evoTo: 'maushold', evoLevel: 25 }],

	// Poison Types
	'ekans': [{ evoTo: 'arbok', evoLevel: 22 }],
	'nidoranf': [{ evoTo: 'nidorina', evoLevel: 16 }],
	'nidorina': [{ evoTo: 'nidoqueen', evoLevel: 99, evoItem: 'moonstone' }],
	'nidoranm': [{ evoTo: 'nidorino', evoLevel: 16 }],
	'nidorino': [{ evoTo: 'nidoking', evoLevel: 99, evoItem: 'moonstone' }],
	'zubat': [{ evoTo: 'golbat', evoLevel: 22 }],
	'oddish': [{ evoTo: 'gloom', evoLevel: 21 }],
	'gloom': [
		{ evoTo: 'vileplume', evoLevel: 99, evoItem: 'leafstone' },
		{ evoTo: 'bellossom', evoLevel: 99, evoItem: 'sunstone' },
	],
	'bellsprout': [{ evoTo: 'weepinbell', evoLevel: 21 }],
	'weepinbell': [{ evoTo: 'victreebel', evoLevel: 99, evoItem: 'leafstone' }],
	'grimer': [{ evoTo: 'muk', evoLevel: 38 }],
	'koffing': [{ evoTo: 'weezing', evoLevel: 35 }],
	'gastly': [{ evoTo: 'haunter', evoLevel: 25 }],
	'haunter': [{ evoTo: 'gengar', evoLevel: 36 }],
	'golbat': [{ evoTo: 'crobat', evoLevel: 30 }],
	'salandit': [{ evoTo: 'salazzle', evoLevel: 33 }],
	'toxel': [
		{ evoTo: 'toxtricity', evoLevel: 30 },
		{ evoTo: 'toxtricitylowkey', evoLevel: 30 },
	],

	// Ground/Rock Types
	'sandshrew': [{ evoTo: 'sandslash', evoLevel: 22 }],
	'diglett': [{ evoTo: 'dugtrio', evoLevel: 26 }],
	'geodude': [{ evoTo: 'graveler', evoLevel: 25 }],
	'graveler': [{ evoTo: 'golem', evoLevel: 36 }],
	'cubone': [{ evoTo: 'marowak', evoLevel: 28 }],
	'rhyhorn': [{ evoTo: 'rhydon', evoLevel: 42 }],
	'rhydon': [{ evoTo: 'rhyperior', evoLevel: 36, evoItem: 'protector' }],
	'onix': [{ evoTo: 'steelix', evoLevel: 36, evoItem: 'metalcoat' }],
	'makuhita': [{ evoTo: 'hariyama', evoLevel: 24 }],
	'numel': [{ evoTo: 'camerupt', evoLevel: 33 }],
	'aron': [{ evoTo: 'lairon', evoLevel: 32 }],
	'lairon': [{ evoTo: 'aggron', evoLevel: 42 }],
	'lileep': [{ evoTo: 'cradily', evoLevel: 40 }],
	'cranidos': [{ evoTo: 'rampardos', evoLevel: 30 }],
	'shieldon': [{ evoTo: 'bastiodon', evoLevel: 30 }],
	'gible': [{ evoTo: 'gabite', evoLevel: 24 }],
	'gabite': [{ evoTo: 'garchomp', evoLevel: 48 }],
	'nosepass': [{ evoTo: 'probopass', evoLevel: 36, evoItem: 'magnet' }],
	'roggenrola': [{ evoTo: 'boldore', evoLevel: 25 }],
	'boldore': [{ evoTo: 'gigalith', evoLevel: 36 }],
	'drillbur': [{ evoTo: 'excadrill', evoLevel: 31 }],
	'tirtouga': [{ evoTo: 'carracosta', evoLevel: 37 }],
	'archen': [{ evoTo: 'archeops', evoLevel: 37 }],
	'golett': [{ evoTo: 'golurk', evoLevel: 43 }],
	'tyrunt': [{ evoTo: 'tyrantrum', evoLevel: 39 }],
	'amaura': [{ evoTo: 'aurorus', evoLevel: 39 }],
	'rockruff': [
		{ evoTo: 'lycanroc-midday', evoLevel: 25 },
		{ evoTo: 'lycanroc-midnight', evoLevel: 25 },
		{ evoTo: 'lycanroc-dusk', evoLevel: 25 },
	],
	'ferroseed': [{ evoTo: 'ferrothorn', evoLevel: 40 }],
	'rolycoly': [{ evoTo: 'carkol', evoLevel: 18 }],
	'carkol': [{ evoTo: 'coalossal', evoLevel: 34 }],
	'silicobra': [{ evoTo: 'sandaconda', evoLevel: 36 }],
	'wiglett': [{ evoTo: 'wugtrio', evoLevel: 26 }],
	'nacli': [{ evoTo: 'naclstack', evoLevel: 24 }],
	'naclstack': [{ evoTo: 'garganacl', evoLevel: 38 }],
	'duraludon': [{ evoTo: 'archaludon', evoLevel: 36, evoItem: 'metalalloy' }],

	// Fire Types
	'vulpix': [{ evoTo: 'ninetales', evoLevel: 99, evoItem: 'firestone' }],
	'growlithe': [{ evoTo: 'arcanine', evoLevel: 99, evoItem: 'firestone' }],
	'ponyta': [{ evoTo: 'rapidash', evoLevel: 40 }],
	'magmar': [{ evoTo: 'magmortar', evoLevel: 36, evoItem: 'magmarizer' }],

	// Water Types
	'psyduck': [{ evoTo: 'golduck', evoLevel: 33 }],
	'poliwag': [{ evoTo: 'poliwhirl', evoLevel: 25 }],
	'poliwhirl': [
		{ evoTo: 'poliwrath', evoLevel: 99, evoItem: 'waterstone' },
		{ evoTo: 'politoed', evoLevel: 36, evoItem: 'kingsrock' },
	],
	'tentacool': [{ evoTo: 'tentacruel', evoLevel: 30 }],
	'slowpoke': [
		{ evoTo: 'slowbro', evoLevel: 37 },
		{ evoTo: 'slowking', evoLevel: 36, evoItem: 'kingsrock' },
	],
	'seel': [{ evoTo: 'dewgong', evoLevel: 34 }],
	'shellder': [{ evoTo: 'cloyster', evoLevel: 99, evoItem: 'waterstone' }],
	'krabby': [{ evoTo: 'kingler', evoLevel: 28 }],
	'horsea': [{ evoTo: 'seadra', evoLevel: 32 }],
	'goldeen': [{ evoTo: 'seaking', evoLevel: 33 }],
	'staryu': [{ evoTo: 'starmie', evoLevel: 99, evoItem: 'waterstone' }],
	'magikarp': [{ evoTo: 'gyarados', evoLevel: 20 }],
	'seadra': [{ evoTo: 'kingdra', evoLevel: 36, evoItem: 'dragonscale' }],
	'lotad': [{ evoTo: 'lombre', evoLevel: 14 }],
	'lombre': [{ evoTo: 'ludicolo', evoLevel: 99, evoItem: 'waterstone' }],
	'barboach': [{ evoTo: 'whiscash', evoLevel: 30 }],
	'corphish': [{ evoTo: 'crawdaunt', evoLevel: 30 }],
	'buizel': [{ evoTo: 'floatzel', evoLevel: 26 }],
	'finneon': [{ evoTo: 'lumineon', evoLevel: 31 }],
	'tympole': [{ evoTo: 'palpitoad', evoLevel: 25 }],
	'palpitoad': [{ evoTo: 'seismitoad', evoLevel: 36 }],
	'frillish': [{ evoTo: 'jellicent', evoLevel: 40 }],
	'clauncher': [{ evoTo: 'clawitzer', evoLevel: 37 }],
	'binacle': [{ evoTo: 'barbaracle', evoLevel: 39 }],
	'arrokuda': [{ evoTo: 'barraskewda', evoLevel: 26 }],
	'finizen': [{ evoTo: 'palafin', evoLevel: 38 }],

	// Psychic Types
	'abra': [{ evoTo: 'kadabra', evoLevel: 16 }],
	'kadabra': [{ evoTo: 'alakazam', evoLevel: 36 }],
	'drowzee': [{ evoTo: 'hypno', evoLevel: 26 }],
	'exeggcute': [{ evoTo: 'exeggutor', evoLevel: 99, evoItem: 'leafstone' }],
	'ralts': [
		{ evoTo: 'kirlia', evoLevel: 20 },
	],
	'kirlia': [
		{ evoTo: 'gardevoir', evoLevel: 30 },
		{ evoTo: 'gallade', evoLevel: 30, evoItem: 'dawnstone' },
	],
	'wynaut': [{ evoTo: 'wobbuffet', evoLevel: 15 }],
	'munna': [{ evoTo: 'musharna', evoLevel: 99, evoItem: 'moonstone' }],
	'gothita': [{ evoTo: 'gothorita', evoLevel: 32 }],
	'gothorita': [{ evoTo: 'gothitelle', evoLevel: 41 }],
	'solosis': [{ evoTo: 'duosion', evoLevel: 32 }],
	'duosion': [{ evoTo: 'reuniclus', evoLevel: 41 }],
	'espurr': [{ evoTo: 'meowstic', evoLevel: 25 }],
	'inkay': [{ evoTo: 'malamar', evoLevel: 30 }],
	'hatenna': [{ evoTo: 'hattrem', evoLevel: 32 }],
	'hattrem': [{ evoTo: 'hatterene', evoLevel: 42 }],
	'flittle': [{ evoTo: 'espathra', evoLevel: 35 }],

	// Fighting Types
	'mankey': [{ evoTo: 'primeape', evoLevel: 28 }],
	'machop': [{ evoTo: 'machoke', evoLevel: 28 }],
	'machoke': [{ evoTo: 'machamp', evoLevel: 36 }],
	'tyrogue': [
		{ evoTo: 'hitmonlee', evoLevel: 30 },
		{ evoTo: 'hitmonchan', evoLevel: 30 },
		{ evoTo: 'hitmontop', evoLevel: 30 },
	],
	'meditite': [{ evoTo: 'medicham', evoLevel: 37 }],
	'riolu': [{ evoTo: 'lucario', evoLevel: 30 }],
	'timburr': [{ evoTo: 'gurdurr', evoLevel: 25 }],
	'gurdurr': [{ evoTo: 'conkeldurr', evoLevel: 36 }],
	'crabrawler': [{ evoTo: 'crabominable', evoLevel: 36, evoItem: 'icestone' }],
	'cufant': [{ evoTo: 'copperajah', evoLevel: 34 }],
	'clobbopus': [{ evoTo: 'grapploct', evoLevel: 36 }],
	'kubfu': [
		{ evoTo: 'urshifu', evoLevel: 70, evoItem: 'towerscrolls' },
		{ evoTo: 'urshifu-rapidstrike', evoLevel: 70, evoItem: 'waterscroll' },
	],
	'primeape': [{ evoTo: 'annihilape', evoLevel: 36 }],
	'pawmi': [{ evoTo: 'pawmo', evoLevel: 18 }],
	'pawmo': [{ evoTo: 'pawmot', evoLevel: 36 }],

	// Electric Types
	'pikachu': [{ evoTo: 'raichu', evoLevel: 99, evoItem: 'thunderstone' }],
	'magnemite': [{ evoTo: 'magneton', evoLevel: 30 }],
	'voltorb': [{ evoTo: 'electrode', evoLevel: 30 }],
	'electabuzz': [{ evoTo: 'electivire', evoLevel: 36, evoItem: 'electirizer' }],
	'pichu': [{ evoTo: 'pikachu', evoLevel: 30 }],
	'electrike': [{ evoTo: 'manectric', evoLevel: 26 }],
	'magneton': [{ evoTo: 'magnezone', evoLevel: 36, evoItem: 'magnet' }],
	'blitzle': [{ evoTo: 'zebstrika', evoLevel: 27 }],
	'helioptile': [{ evoTo: 'heliolisk', evoLevel: 99, evoItem: 'sunstone' }],
	'grubbin': [{ evoTo: 'charjabug', evoLevel: 20 }],
	'charjabug': [{ evoTo: 'vikavolt', evoLevel: 36, evoItem: 'magnet' }],
	'tadbulb': [{ evoTo: 'bellibolt', evoLevel: 25 }],
	'wattrel': [{ evoTo: 'kilowattrel', evoLevel: 25 }],

	// Fairy Types
	'clefairy': [{ evoTo: 'clefable', evoLevel: 99, evoItem: 'moonstone' }],
	'jigglypuff': [{ evoTo: 'wigglytuff', evoLevel: 99, evoItem: 'moonstone' }],
	'cleffa': [{ evoTo: 'clefairy', evoLevel: 30 }],
	'igglybuff': [{ evoTo: 'jigglypuff', evoLevel: 30 }],
	'togepi': [{ evoTo: 'togetic', evoLevel: 30 }],
	'togetic': [{ evoTo: 'togekiss', evoLevel: 36, evoItem: 'shinystone' }],
	'spritzee': [{ evoTo: 'aromatisse', evoLevel: 36, evoItem: 'sachet' }],
	'swirlix': [{ evoTo: 'slurpuff', evoLevel: 36, evoItem: 'whippeddream' }],
	'eevee': [
		{ evoTo: 'vaporeon', evoLevel: 99, evoItem: 'waterstone' },
		// { evoTo: 'jolteon', evoLevel: 99, evoItem: 'thunderstone' },
		// { evoTo: 'flareon', evoLevel: 99, evoItem: 'firestone' },
		{ evoTo: 'espeon', evoLevel: 30 },
		{ evoTo: 'umbreon', evoLevel: 30 },
		{ evoTo: 'leafeon', evoLevel: 36 },
		{ evoTo: 'glaceon', evoLevel: 36 },
		{ evoTo: 'sylveon', evoLevel: 30 },
	],
	'milcery': [{ evoTo: 'alcremie', evoLevel: 30 }],
	'tinkatink': [{ evoTo: 'tinkatuff', evoLevel: 24 }],
	'tinkatuff': [{ evoTo: 'tinkaton', evoLevel: 38 }],
	'fidough': [{ evoTo: 'dachsbun', evoLevel: 26 }],

	// Ghost Types
	'duskull': [{ evoTo: 'dusclops', evoLevel: 37 }],
	'dusclops': [{ evoTo: 'dusknoir', evoLevel: 36, evoItem: 'reapercloth' }],
	'drifloon': [{ evoTo: 'drifblim', evoLevel: 27 }],
	'litwick': [{ evoTo: 'lampent', evoLevel: 41 }],
	'lampent': [{ evoTo: 'chandelure', evoLevel: 99, evoItem: 'duskstone' }],
	'yamask': [{ evoTo: 'cofagrigus', evoLevel: 34 }],
	'phantump': [{ evoTo: 'trevenant', evoLevel: 36 }],
	'pumpkaboo': [{ evoTo: 'gourgeist', evoLevel: 36 }],
	'dreepy': [{ evoTo: 'drakloak', evoLevel: 50 }],
	'drakloak': [{ evoTo: 'dragapult', evoLevel: 60 }],
	'sinistea': [
		{ evoTo: 'polteageist', evoLevel: 36, evoItem: 'chipseal' },
		{ evoTo: 'polteageist-antique', evoLevel: 36, evoItem: 'masterpiece' },
	],
	'impidimp': [{ evoTo: 'morgrem', evoLevel: 32 }],
	'morgrem': [{ evoTo: 'grimmsnarl', evoLevel: 42 }],
	'gimmighoul': [{ evoTo: 'gholdengo', evoLevel: 36 }],
	'poltchageist': [{ evoTo: 'sinistcha', evoLevel: 36, evoItem: 'masterpiece' }],

	// Miscellaneous Evolutions
	'sunkern': [{ evoTo: 'sunflora', evoLevel: 99, evoItem: 'sunstone' }],
	'murkrow': [{ evoTo: 'honchkrow', evoLevel: 36, evoItem: 'duskstone' }],
	'misdreavus': [{ evoTo: 'mismagius', evoLevel: 36, evoItem: 'duskstone' }],
	'sneasel': [{ evoTo: 'weavile', evoLevel: 36, evoItem: 'razorclaw' }],
	'scyther': [
		{ evoTo: 'scizor', evoLevel: 36, evoItem: 'metalcoat' },
		{ evoTo: 'kleavor', evoLevel: 36, evoItem: 'blackaugurite' },
	],
	'porygon': [{ evoTo: 'porygon2', evoLevel: 36, evoItem: 'upgrade' }],
	'porygon2': [{ evoTo: 'porygonz', evoLevel: 36, evoItem: 'dubiousdisc' }],
	'larvitar': [{ evoTo: 'pupitar', evoLevel: 30 }],
	'pupitar': [{ evoTo: 'tyranitar', evoLevel: 55 }],
	'tangela': [{ evoTo: 'tangrowth', evoLevel: 36 }],
	'yanma': [{ evoTo: 'yanmega', evoLevel: 36 }],
	'swinub': [{ evoTo: 'piloswine', evoLevel: 33 }],
	'piloswine': [{ evoTo: 'mamoswine', evoLevel: 36 }],
	'roselia': [{ evoTo: 'roserade', evoLevel: 36, evoItem: 'shinystone' }],
	'budew': [{ evoTo: 'roselia', evoLevel: 30 }],
	'elekid': [{ evoTo: 'electabuzz', evoLevel: 30 }],
	'magby': [{ evoTo: 'magmar', evoLevel: 30 }],
	'bonsly': [{ evoTo: 'sudowoodo', evoLevel: 36 }],
	'mimejr': [{ evoTo: 'mrmime', evoLevel: 36 }],
	'munchlax': [{ evoTo: 'snorlax', evoLevel: 30 }],
	'chingling': [{ evoTo: 'chimecho', evoLevel: 30 }],
	'capsakid': [{ evoTo: 'scovillain', evoLevel: 99, evoItem: 'firestone' }],
	'cetoddle': [{ evoTo: 'cetitan', evoLevel: 30, evoItem: 'icestone' }],

	// Fossil Types
	'omanyte': [{ evoTo: 'omastar', evoLevel: 40 }],
	'kabuto': [{ evoTo: 'kabutops', evoLevel: 40 }],

	// Dragon Types
	'dratini': [{ evoTo: 'dragonair', evoLevel: 30 }],
	'dragonair': [{ evoTo: 'dragonite', evoLevel: 55 }],
	'bagon': [{ evoTo: 'shelgon', evoLevel: 30 }],
	'shelgon': [{ evoTo: 'salamence', evoLevel: 50 }],
	'deino': [{ evoTo: 'zweilous', evoLevel: 50 }],
	'zweilous': [{ evoTo: 'hydreigon', evoLevel: 64 }],
};
