exports.BattlePokedex = {
bulbasaur: {abilities:{"0":"Overgrow","DW":"Chlorophyll"},inherit:true},
ivysaur: {abilities:{"0":"Overgrow","DW":"Chlorophyll"},inherit:true},
venusaur: {abilities:{"0":"Overgrow","DW":"Chlorophyll"},otherFormes:null,inherit:true},
charmander: {abilities:{"0":"Blaze","DW":"Solar Power"},inherit:true},
charmeleon: {abilities:{"0":"Blaze","DW":"Solar Power"},inherit:true},
charizard: {abilities:{"0":"Blaze","DW":"Solar Power"},otherFormes:null,inherit:true},
squirtle: {abilities:{"0":"Torrent","DW":"Rain Dish"},inherit:true},
wartortle: {abilities:{"0":"Torrent","DW":"Rain Dish"},inherit:true},
blastoise: {abilities:{"0":"Torrent","DW":"Rain Dish"},otherFormes:null,inherit:true},
caterpie: {abilities:{"0":"Shield Dust","DW":"Run Away"},inherit:true},
butterfree: {baseStats:{hp:60,atk:45,def:50,spa:80,spd:80,spe:70},abilities:{"0":"Compoundeyes","DW":"Tinted Lens"},inherit:true},
weedle: {abilities:{"0":"Shield Dust","DW":"Run Away"},inherit:true},
beedrill: {baseStats:{hp:65,atk:80,def:40,spa:45,spd:80,spe:75},abilities:{"0":"Swarm","DW":"Sniper"},inherit:true},
pidgey: {abilities:{"0":"Keen Eye","1":"Tangled Feet","DW":"Big Pecks"},inherit:true},
pidgeotto: {abilities:{"0":"Keen Eye","1":"Tangled Feet","DW":"Big Pecks"},inherit:true},
pidgeot: {baseStats:{hp:83,atk:80,def:75,spa:70,spd:70,spe:91},abilities:{"0":"Keen Eye","1":"Tangled Feet","DW":"Big Pecks"},inherit:true},
rattata: {abilities:{"0":"Run Away","1":"Guts","DW":"Hustle"},inherit:true},
raticate: {abilities:{"0":"Run Away","1":"Guts","DW":"Hustle"},inherit:true},
spearow: {abilities:{"0":"Keen Eye","DW":"Sniper"},inherit:true},
fearow: {abilities:{"0":"Keen Eye","DW":"Sniper"},inherit:true},
ekans: {abilities:{"0":"Intimidate","1":"Shed Skin","DW":"Unnerve"},inherit:true},
arbok: {abilities:{"0":"Intimidate","1":"Shed Skin","DW":"Unnerve"},inherit:true},
pikachu: {baseStats:{hp:35,atk:55,def:30,spa:50,spd:40,spe:90},abilities:{"0":"Static","DW":"Lightningrod"},inherit:true},
raichu: {baseStats:{hp:60,atk:90,def:55,spa:90,spd:80,spe:100},abilities:{"0":"Static","DW":"Lightningrod"},inherit:true},
sandshrew: {abilities:{"0":"Sand Veil","DW":"Sand Rush"},inherit:true},
sandslash: {abilities:{"0":"Sand Veil","DW":"Sand Rush"},inherit:true},
nidoranf: {"species":"NidoranF",abilities:{"0":"Poison Point","1":"Rivalry","DW":"Hustle"},inherit:true},
nidorina: {abilities:{"0":"Poison Point","1":"Rivalry","DW":"Hustle"},inherit:true},
nidoqueen: {baseStats:{hp:90,atk:82,def:87,spa:75,spd:85,spe:76},abilities:{"0":"Poison Point","1":"Rivalry","DW":"Sheer Force"},inherit:true},
nidoranm: {"species":"NidoranM",abilities:{"0":"Poison Point","1":"Rivalry","DW":"Hustle"},inherit:true},
nidorino: {abilities:{"0":"Poison Point","1":"Rivalry","DW":"Hustle"},inherit:true},
nidoking: {baseStats:{hp:81,atk:92,def:77,spa:85,spd:75,spe:85},abilities:{"0":"Poison Point","1":"Rivalry","DW":"Sheer Force"},inherit:true},
clefairy: {"types":["Normal"],abilities:{"0":"Cute Charm","1":"Magic Guard","DW":"Friend Guard"},inherit:true},
clefable: {"types":["Normal"],baseStats:{hp:95,atk:70,def:73,spa:85,spd:90,spe:60},abilities:{"0":"Cute Charm","1":"Magic Guard","DW":"Unaware"},inherit:true},
vulpix: {abilities:{"0":"Flash Fire","DW":"Drought"},inherit:true},
ninetales: {abilities:{"0":"Flash Fire","DW":"Drought"},inherit:true},
jigglypuff: {"types":["Normal"],abilities:{"0":"Cute Charm","DW":"Friend Guard"},inherit:true},
wigglytuff: {"types":["Normal"],baseStats:{hp:140,atk:70,def:45,spa:75,spd:50,spe:45},abilities:{"0":"Cute Charm","DW":"Frisk"},inherit:true},
zubat: {abilities:{"0":"Inner Focus","DW":"Infiltrator"},inherit:true},
golbat: {abilities:{"0":"Inner Focus","DW":"Infiltrator"},inherit:true},
oddish: {abilities:{"0":"Chlorophyll","DW":"Run Away"},inherit:true},
gloom: {abilities:{"0":"Chlorophyll","DW":"Stench"},inherit:true},
vileplume: {baseStats:{hp:75,atk:80,def:85,spa:100,spd:90,spe:50},abilities:{"0":"Chlorophyll","DW":"Effect Spore"},inherit:true},
paras: {abilities:{"0":"Effect Spore","1":"Dry Skin","DW":"Damp"},inherit:true},
parasect: {abilities:{"0":"Effect Spore","1":"Dry Skin","DW":"Damp"},inherit:true},
venonat: {abilities:{"0":"Compoundeyes","1":"Tinted Lens","DW":"Run Away"},inherit:true},
venomoth: {abilities:{"0":"Shield Dust","1":"Tinted Lens","DW":"Wonder Skin"},inherit:true},
diglett: {abilities:{"0":"Sand Veil","1":"Arena Trap","DW":"Sand Force"},inherit:true},
dugtrio: {abilities:{"0":"Sand Veil","1":"Arena Trap","DW":"Sand Force"},inherit:true},
meowth: {abilities:{"0":"Pickup","1":"Technician","DW":"Unnerve"},inherit:true},
persian: {abilities:{"0":"Limber","1":"Technician","DW":"Unnerve"},inherit:true},
psyduck: {abilities:{"0":"Damp","1":"Cloud Nine","DW":"Swift Swim"},inherit:true},
golduck: {abilities:{"0":"Damp","1":"Cloud Nine","DW":"Swift Swim"},inherit:true},
mankey: {abilities:{"0":"Vital Spirit","1":"Anger Point","DW":"Defiant"},inherit:true},
primeape: {abilities:{"0":"Vital Spirit","1":"Anger Point","DW":"Defiant"},inherit:true},
growlithe: {abilities:{"0":"Intimidate","1":"Flash Fire","DW":"Justified"},inherit:true},
arcanine: {abilities:{"0":"Intimidate","1":"Flash Fire","DW":"Justified"},inherit:true},
poliwag: {abilities:{"0":"Water Absorb","1":"Damp","DW":"Swift Swim"},inherit:true},
poliwhirl: {abilities:{"0":"Water Absorb","1":"Damp","DW":"Swift Swim"},inherit:true},
poliwrath: {baseStats:{hp:90,atk:85,def:95,spa:70,spd:90,spe:70},abilities:{"0":"Water Absorb","1":"Damp","DW":"Swift Swim"},inherit:true},
abra: {abilities:{"0":"Synchronize","1":"Inner Focus","DW":"Magic Guard"},inherit:true},
kadabra: {abilities:{"0":"Synchronize","1":"Inner Focus","DW":"Magic Guard"},inherit:true},
alakazam: {baseStats:{hp:55,atk:50,def:45,spa:135,spd:85,spe:120},abilities:{"0":"Synchronize","1":"Inner Focus","DW":"Magic Guard"},otherFormes:null,inherit:true},
machop: {abilities:{"0":"Guts","1":"No Guard","DW":"Steadfast"},inherit:true},
machoke: {abilities:{"0":"Guts","1":"No Guard","DW":"Steadfast"},inherit:true},
machamp: {abilities:{"0":"Guts","1":"No Guard","DW":"Steadfast"},inherit:true},
bellsprout: {abilities:{"0":"Chlorophyll","DW":"Gluttony"},inherit:true},
weepinbell: {abilities:{"0":"Chlorophyll","DW":"Gluttony"},inherit:true},
victreebel: {baseStats:{hp:80,atk:105,def:65,spa:100,spd:60,spe:70},abilities:{"0":"Chlorophyll","DW":"Gluttony"},inherit:true},
tentacool: {abilities:{"0":"Clear Body","1":"Liquid Ooze","DW":"Rain Dish"},inherit:true},
tentacruel: {abilities:{"0":"Clear Body","1":"Liquid Ooze","DW":"Rain Dish"},inherit:true},
geodude: {abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sand Veil"},inherit:true},
graveler: {abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sand Veil"},inherit:true},
golem: {baseStats:{hp:80,atk:110,def:130,spa:55,spd:65,spe:45},abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sand Veil"},inherit:true},
ponyta: {abilities:{"0":"Run Away","1":"Flash Fire","DW":"Flame Body"},inherit:true},
rapidash: {abilities:{"0":"Run Away","1":"Flash Fire","DW":"Flame Body"},inherit:true},
slowpoke: {abilities:{"0":"Oblivious","1":"Own Tempo","DW":"Regenerator"},inherit:true},
slowbro: {abilities:{"0":"Oblivious","1":"Own Tempo","DW":"Regenerator"},inherit:true},
magnemite: {abilities:{"0":"Magnet Pull","1":"Sturdy","DW":"Analytic"},inherit:true},
magneton: {abilities:{"0":"Magnet Pull","1":"Sturdy","DW":"Analytic"},inherit:true},
farfetchd: {abilities:{"0":"Keen Eye","1":"Inner Focus","DW":"Defiant"},inherit:true},
doduo: {abilities:{"0":"Run Away","1":"Early Bird","DW":"Tangled Feet"},inherit:true},
dodrio: {abilities:{"0":"Run Away","1":"Early Bird","DW":"Tangled Feet"},inherit:true},
seel: {abilities:{"0":"Thick Fat","1":"Hydration","DW":"Ice Body"},inherit:true},
dewgong: {abilities:{"0":"Thick Fat","1":"Hydration","DW":"Ice Body"},inherit:true},
grimer: {abilities:{"0":"Stench","1":"Sticky Hold","DW":"Poison Touch"},inherit:true},
muk: {abilities:{"0":"Stench","1":"Sticky Hold","DW":"Poison Touch"},inherit:true},
shellder: {abilities:{"0":"Shell Armor","1":"Skill Link","DW":"Overcoat"},inherit:true},
cloyster: {abilities:{"0":"Shell Armor","1":"Skill Link","DW":"Overcoat"},inherit:true},
gengar: {otherFormes:null,inherit:true},
onix: {abilities:{"0":"Rock Head","1":"Sturdy","DW":"Weak Armor"},inherit:true},
drowzee: {abilities:{"0":"Insomnia","1":"Forewarn","DW":"Inner Focus"},inherit:true},
hypno: {abilities:{"0":"Insomnia","1":"Forewarn","DW":"Inner Focus"},inherit:true},
krabby: {abilities:{"0":"Hyper Cutter","1":"Shell Armor","DW":"Sheer Force"},inherit:true},
kingler: {abilities:{"0":"Hyper Cutter","1":"Shell Armor","DW":"Sheer Force"},inherit:true},
voltorb: {abilities:{"0":"Soundproof","1":"Static","DW":"Aftermath"},inherit:true},
electrode: {abilities:{"0":"Soundproof","1":"Static","DW":"Aftermath"},inherit:true},
exeggcute: {abilities:{"0":"Chlorophyll","DW":"Harvest"},inherit:true},
exeggutor: {abilities:{"0":"Chlorophyll","DW":"Harvest"},inherit:true},
cubone: {abilities:{"0":"Rock Head","1":"Lightningrod","DW":"Battle Armor"},inherit:true},
marowak: {abilities:{"0":"Rock Head","1":"Lightningrod","DW":"Battle Armor"},inherit:true},
hitmonlee: {abilities:{"0":"Limber","1":"Reckless","DW":"Unburden"},inherit:true},
hitmonchan: {abilities:{"0":"Keen Eye","1":"Iron Fist","DW":"Inner Focus"},inherit:true},
lickitung: {abilities:{"0":"Own Tempo","1":"Oblivious","DW":"Cloud Nine"},inherit:true},
rhyhorn: {abilities:{"0":"Lightningrod","1":"Rock Head","DW":"Reckless"},inherit:true},
rhydon: {abilities:{"0":"Lightningrod","1":"Rock Head","DW":"Reckless"},inherit:true},
chansey: {abilities:{"0":"Natural Cure","1":"Serene Grace","DW":"Healer"},inherit:true},
tangela: {abilities:{"0":"Chlorophyll","1":"Leaf Guard","DW":"Regenerator"},inherit:true},
kangaskhan: {abilities:{"0":"Early Bird","1":"Scrappy","DW":"Inner Focus"},otherFormes:null,inherit:true},
horsea: {abilities:{"0":"Swift Swim","1":"Sniper","DW":"Damp"},inherit:true},
seadra: {abilities:{"0":"Poison Point","1":"Sniper","DW":"Damp"},inherit:true},
goldeen: {abilities:{"0":"Swift Swim","1":"Water Veil","DW":"Lightningrod"},inherit:true},
seaking: {abilities:{"0":"Swift Swim","1":"Water Veil","DW":"Lightningrod"},inherit:true},
staryu: {abilities:{"0":"Illuminate","1":"Natural Cure","DW":"Analytic"},inherit:true},
starmie: {abilities:{"0":"Illuminate","1":"Natural Cure","DW":"Analytic"},inherit:true},
mrmime: {"types":["Psychic"],abilities:{"0":"Soundproof","1":"Filter","DW":"Technician"},inherit:true},
scyther: {abilities:{"0":"Swarm","1":"Technician","DW":"Steadfast"},inherit:true},
jynx: {abilities:{"0":"Oblivious","1":"Forewarn","DW":"Dry Skin"},inherit:true},
electabuzz: {abilities:{"0":"Static","DW":"Vital Spirit"},inherit:true},
magmar: {abilities:{"0":"Flame Body","DW":"Vital Spirit"},inherit:true},
pinsir: {abilities:{"0":"Hyper Cutter","1":"Mold Breaker","DW":"Moxie"},otherFormes:null,inherit:true},
tauros: {abilities:{"0":"Intimidate","1":"Anger Point","DW":"Sheer Force"},inherit:true},
magikarp: {abilities:{"0":"Swift Swim","DW":"Rattled"},inherit:true},
gyarados: {abilities:{"0":"Intimidate","DW":"Moxie"},otherFormes:null,inherit:true},
lapras: {abilities:{"0":"Water Absorb","1":"Shell Armor","DW":"Hydration"},inherit:true},
ditto: {abilities:{"0":"Limber","DW":"Imposter"},inherit:true},
eevee: {abilities:{"0":"Run Away","1":"Adaptability","DW":"Anticipation"},"evos":["vaporeon","jolteon","flareon","espeon","umbreon","leafeon","glaceon"],inherit:true},
vaporeon: {abilities:{"0":"Water Absorb","DW":"Hydration"},inherit:true},
jolteon: {abilities:{"0":"Volt Absorb","DW":"Quick Feet"},inherit:true},
flareon: {abilities:{"0":"Flash Fire","DW":"Guts"},inherit:true},
porygon: {abilities:{"0":"Trace","1":"Download","DW":"Analytic"},inherit:true},
omanyte: {abilities:{"0":"Swift Swim","1":"Shell Armor","DW":"Weak Armor"},inherit:true},
omastar: {abilities:{"0":"Swift Swim","1":"Shell Armor","DW":"Weak Armor"},inherit:true},
kabuto: {abilities:{"0":"Swift Swim","1":"Battle Armor","DW":"Weak Armor"},inherit:true},
kabutops: {abilities:{"0":"Swift Swim","1":"Battle Armor","DW":"Weak Armor"},inherit:true},
aerodactyl: {abilities:{"0":"Rock Head","1":"Pressure","DW":"Unnerve"},otherFormes:null,inherit:true},
snorlax: {abilities:{"0":"Immunity","1":"Thick Fat","DW":"Gluttony"},inherit:true},
articuno: {abilities:{"0":"Pressure","DW":"Snow Cloak"},inherit:true},
zapdos: {abilities:{"0":"Pressure","DW":"Lightningrod"},inherit:true},
moltres: {abilities:{"0":"Pressure","DW":"Flame Body"},inherit:true},
dratini: {abilities:{"0":"Shed Skin","DW":"Marvel Scale"},inherit:true},
dragonair: {abilities:{"0":"Shed Skin","DW":"Marvel Scale"},inherit:true},
dragonite: {abilities:{"0":"Inner Focus","DW":"Multiscale"},inherit:true},
mewtwo: {abilities:{"0":"Pressure","DW":"Unnerve"},otherFormes:null,inherit:true},
chikorita: {abilities:{"0":"Overgrow","DW":"Leaf Guard"},inherit:true},
bayleef: {abilities:{"0":"Overgrow","DW":"Leaf Guard"},inherit:true},
meganium: {abilities:{"0":"Overgrow","DW":"Leaf Guard"},inherit:true},
cyndaquil: {abilities:{"0":"Blaze","DW":"Flash Fire"},inherit:true},
quilava: {abilities:{"0":"Blaze","DW":"Flash Fire"},inherit:true},
typhlosion: {abilities:{"0":"Blaze","DW":"Flash Fire"},inherit:true},
totodile: {abilities:{"0":"Torrent","DW":"Sheer Force"},inherit:true},
croconaw: {abilities:{"0":"Torrent","DW":"Sheer Force"},inherit:true},
feraligatr: {abilities:{"0":"Torrent","DW":"Sheer Force"},inherit:true},
sentret: {abilities:{"0":"Run Away","1":"Keen Eye","DW":"Frisk"},inherit:true},
furret: {abilities:{"0":"Run Away","1":"Keen Eye","DW":"Frisk"},inherit:true},
hoothoot: {abilities:{"0":"Insomnia","1":"Keen Eye","DW":"Tinted Lens"},inherit:true},
noctowl: {abilities:{"0":"Insomnia","1":"Keen Eye","DW":"Tinted Lens"},inherit:true},
ledyba: {abilities:{"0":"Swarm","1":"Early Bird","DW":"Rattled"},inherit:true},
ledian: {abilities:{"0":"Swarm","1":"Early Bird","DW":"Iron Fist"},inherit:true},
spinarak: {abilities:{"0":"Swarm","1":"Insomnia","DW":"Sniper"},inherit:true},
ariados: {abilities:{"0":"Swarm","1":"Insomnia","DW":"Sniper"},inherit:true},
crobat: {abilities:{"0":"Inner Focus","DW":"Infiltrator"},inherit:true},
chinchou: {abilities:{"0":"Volt Absorb","1":"Illuminate","DW":"Water Absorb"},inherit:true},
lanturn: {abilities:{"0":"Volt Absorb","1":"Illuminate","DW":"Water Absorb"},inherit:true},
pichu: {abilities:{"0":"Static","DW":"Lightningrod"},inherit:true},
cleffa: {"types":["Normal"],abilities:{"0":"Cute Charm","1":"Magic Guard","DW":"Friend Guard"},inherit:true},
igglybuff: {"types":["Normal"],abilities:{"0":"Cute Charm","DW":"Friend Guard"},inherit:true},
togepi: {"types":["Normal"],abilities:{"0":"Hustle","1":"Serene Grace","DW":"Super Luck"},inherit:true},
togetic: {"types":["Normal","Flying"],abilities:{"0":"Hustle","1":"Serene Grace","DW":"Super Luck"},inherit:true},
natu: {abilities:{"0":"Synchronize","1":"Early Bird","DW":"Magic Bounce"},inherit:true},
xatu: {abilities:{"0":"Synchronize","1":"Early Bird","DW":"Magic Bounce"},inherit:true},
mareep: {abilities:{"0":"Static","DW":"Plus"},inherit:true},
flaaffy: {abilities:{"0":"Static","DW":"Plus"},inherit:true},
ampharos: {baseStats:{hp:90,atk:75,def:75,spa:115,spd:90,spe:55},abilities:{"0":"Static","DW":"Plus"},otherFormes:null,inherit:true},
bellossom: {baseStats:{hp:75,atk:80,def:85,spa:90,spd:100,spe:50},abilities:{"0":"Chlorophyll","DW":"Healer"},inherit:true},
marill: {"types":["Water"],abilities:{"0":"Thick Fat","1":"Huge Power","DW":"Sap Sipper"},inherit:true},
azumarill: {"types":["Water"],baseStats:{hp:100,atk:50,def:80,spa:50,spd:80,spe:50},abilities:{"0":"Thick Fat","1":"Huge Power","DW":"Sap Sipper"},inherit:true},
sudowoodo: {abilities:{"0":"Sturdy","1":"Rock Head","DW":"Rattled"},inherit:true},
politoed: {abilities:{"0":"Water Absorb","1":"Damp","DW":"Drizzle"},inherit:true},
hoppip: {abilities:{"0":"Chlorophyll","1":"Leaf Guard","DW":"Infiltrator"},inherit:true},
skiploom: {abilities:{"0":"Chlorophyll","1":"Leaf Guard","DW":"Infiltrator"},inherit:true},
jumpluff: {baseStats:{hp:75,atk:55,def:70,spa:55,spd:85,spe:110},abilities:{"0":"Chlorophyll","1":"Leaf Guard","DW":"Infiltrator"},inherit:true},
aipom: {abilities:{"0":"Run Away","1":"Pickup","DW":"Skill Link"},inherit:true},
sunkern: {abilities:{"0":"Chlorophyll","1":"Solar Power","DW":"Early Bird"},inherit:true},
sunflora: {abilities:{"0":"Chlorophyll","1":"Solar Power","DW":"Early Bird"},inherit:true},
yanma: {abilities:{"0":"Speed Boost","1":"Compoundeyes","DW":"Frisk"},inherit:true},
wooper: {abilities:{"0":"Damp","1":"Water Absorb","DW":"Unaware"},inherit:true},
quagsire: {abilities:{"0":"Damp","1":"Water Absorb","DW":"Unaware"},inherit:true},
espeon: {abilities:{"0":"Synchronize","DW":"Magic Bounce"},inherit:true},
umbreon: {abilities:{"0":"Synchronize","DW":"Inner Focus"},inherit:true},
murkrow: {abilities:{"0":"Insomnia","1":"Super Luck","DW":"Prankster"},inherit:true},
slowking: {abilities:{"0":"Oblivious","1":"Own Tempo","DW":"Regenerator"},inherit:true},
wobbuffet: {abilities:{"0":"Shadow Tag","DW":"Telepathy"},inherit:true},
girafarig: {abilities:{"0":"Inner Focus","1":"Early Bird","DW":"Sap Sipper"},inherit:true},
pineco: {abilities:{"0":"Sturdy","DW":"Overcoat"},inherit:true},
forretress: {abilities:{"0":"Sturdy","DW":"Overcoat"},inherit:true},
dunsparce: {abilities:{"0":"Serene Grace","1":"Run Away","DW":"Rattled"},inherit:true},
gligar: {abilities:{"0":"Hyper Cutter","1":"Sand Veil","DW":"Immunity"},inherit:true},
steelix: {abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sheer Force"},inherit:true},
snubbull: {"types":["Normal"],abilities:{"0":"Intimidate","1":"Run Away","DW":"Rattled"},inherit:true},
granbull: {"types":["Normal"],abilities:{"0":"Intimidate","1":"Quick Feet","DW":"Rattled"},inherit:true},
qwilfish: {abilities:{"0":"Poison Point","1":"Swift Swim","DW":"Intimidate"},inherit:true},
scizor: {abilities:{"0":"Swarm","1":"Technician","DW":"Light Metal"},otherFormes:null,inherit:true},
shuckle: {abilities:{"0":"Sturdy","1":"Gluttony","DW":"Contrary"},inherit:true},
heracross: {abilities:{"0":"Swarm","1":"Guts","DW":"Moxie"},otherFormes:null,inherit:true},
sneasel: {abilities:{"0":"Inner Focus","1":"Keen Eye","DW":"Pickpocket"},inherit:true},
teddiursa: {abilities:{"0":"Pickup","1":"Quick Feet","DW":"Honey Gather"},inherit:true},
ursaring: {abilities:{"0":"Guts","1":"Quick Feet","DW":"Unnerve"},inherit:true},
slugma: {abilities:{"0":"Magma Armor","1":"Flame Body","DW":"Weak Armor"},inherit:true},
magcargo: {abilities:{"0":"Magma Armor","1":"Flame Body","DW":"Weak Armor"},inherit:true},
swinub: {abilities:{"0":"Oblivious","1":"Snow Cloak","DW":"Thick Fat"},inherit:true},
piloswine: {abilities:{"0":"Oblivious","1":"Snow Cloak","DW":"Thick Fat"},inherit:true},
corsola: {abilities:{"0":"Hustle","1":"Natural Cure","DW":"Regenerator"},inherit:true},
remoraid: {abilities:{"0":"Hustle","1":"Sniper","DW":"Moody"},inherit:true},
octillery: {abilities:{"0":"Suction Cups","1":"Sniper","DW":"Moody"},inherit:true},
delibird: {abilities:{"0":"Vital Spirit","1":"Hustle","DW":"Insomnia"},inherit:true},
mantine: {abilities:{"0":"Swift Swim","1":"Water Absorb","DW":"Water Veil"},inherit:true},
skarmory: {abilities:{"0":"Keen Eye","1":"Sturdy","DW":"Weak Armor"},inherit:true},
houndour: {abilities:{"0":"Early Bird","1":"Flash Fire","DW":"Unnerve"},inherit:true},
houndoom: {abilities:{"0":"Early Bird","1":"Flash Fire","DW":"Unnerve"},otherFormes:null,inherit:true},
kingdra: {abilities:{"0":"Swift Swim","1":"Sniper","DW":"Damp"},inherit:true},
phanpy: {abilities:{"0":"Pickup","DW":"Sand Veil"},inherit:true},
donphan: {abilities:{"0":"Sturdy","DW":"Sand Veil"},inherit:true},
porygon2: {abilities:{"0":"Trace","1":"Download","DW":"Analytic"},inherit:true},
stantler: {abilities:{"0":"Intimidate","1":"Frisk","DW":"Sap Sipper"},inherit:true},
smeargle: {abilities:{"0":"Own Tempo","1":"Technician","DW":"Moody"},inherit:true},
tyrogue: {abilities:{"0":"Guts","1":"Steadfast","DW":"Vital Spirit"},inherit:true},
hitmontop: {abilities:{"0":"Intimidate","1":"Technician","DW":"Steadfast"},inherit:true},
smoochum: {abilities:{"0":"Oblivious","1":"Forewarn","DW":"Hydration"},inherit:true},
elekid: {abilities:{"0":"Static","DW":"Vital Spirit"},inherit:true},
magby: {abilities:{"0":"Flame Body","DW":"Vital Spirit"},inherit:true},
miltank: {abilities:{"0":"Thick Fat","1":"Scrappy","DW":"Sap Sipper"},inherit:true},
blissey: {abilities:{"0":"Natural Cure","1":"Serene Grace","DW":"Healer"},inherit:true},
raikou: {abilities:{"0":"Pressure","DW":"Volt Absorb"},inherit:true},
entei: {abilities:{"0":"Pressure","DW":"Flash Fire"},inherit:true},
suicune: {abilities:{"0":"Pressure","DW":"Water Absorb"},inherit:true},
larvitar: {abilities:{"0":"Guts","DW":"Sand Veil"},inherit:true},
tyranitar: {abilities:{"0":"Sand Stream","DW":"Unnerve"},otherFormes:null,inherit:true},
lugia: {abilities:{"0":"Pressure","DW":"Multiscale"},inherit:true},
hooh: {abilities:{"0":"Pressure","DW":"Regenerator"},inherit:true},
missingno: {abilities:{"0":"","DW":""},inherit:true},
tomohawk: {abilities:{"0":"Intimidate","1":"Prankster","DW":"Justified"},inherit:true},
necturna: {abilities:{"0":"Forewarn","DW":"Telepathy"},inherit:true},
mollux: {abilities:{"0":"Dry Skin","DW":"Illuminate"},inherit:true},
aurumoth: {abilities:{"0":"Weak Armor","1":"No Guard","DW":"Illusion"},inherit:true},
syclant: {abilities:{"0":"Compoundeyes","1":"Mountaineer"},inherit:true}
};
