'use strict';
/**
 * Export the Fakemon data in the format the Pokemon Showdown *client* expects.
 *
 * The Teambuilder and the battle UI live in the separate `pokemon-showdown-client`
 * repository, which ships its own copy of the dex. Running this writes drop-in
 * replacements so the client shows only the custom game:
 *
 *   node tools/fakemon/export-client.js [outputDir]
 *
 * Copy the resulting files over `play.pokemonshowdown.com/data/` in the client
 * repo. Because the originals are replaced wholesale, the Teambuilder can only
 * offer Fakemon Pokemon, moves, abilities and items.
 *
 * Battle behaviour is unaffected: the server is always the authority, and the
 * `Fakemon Standard` rule rejects anything else regardless of what a client sends.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const { Dex } = require(path.join(ROOT, 'dist', 'sim'));

const OUT = process.argv[2] || path.join(ROOT, 'dist-client', 'data');

/** The client only renders data, so drop every function and internal field. */
function plain(value) {
	if (Array.isArray(value)) return value.map(plain);
	if (value && typeof value === 'object') {
		const out = {};
		for (const [key, inner] of Object.entries(value)) {
			if (typeof inner === 'function') continue;
			if (key.startsWith('on') || key === 'condition' || key === 'effectType') continue;
			out[key] = plain(inner);
		}
		return out;
	}
	if (typeof value === 'function') return undefined;
	return value;
}

function write(file, exportName, table) {
	fs.mkdirSync(OUT, { recursive: true });
	const body = JSON.stringify(table, null, 1);
	fs.writeFileSync(
		path.join(OUT, file),
		`// Generated by tools/fakemon/export-client.js - do not edit by hand.\n` +
		`exports.${exportName} = ${body};\n`
	);
	return Object.keys(table).length;
}

function main() {
	const dex = Dex.mod('fakemon');
	dex.includeData();

	const pokedex = {};
	for (const [id, entry] of Object.entries(dex.data.Pokedex)) {
		pokedex[id] = plain(entry);
	}

	const movedex = {};
	for (const [id, entry] of Object.entries(dex.data.Moves)) {
		// Original moves kept only for their mechanics, and the internal helper
		// moves, are all tagged Custom and must not appear in the UI.
		if (entry.isNonstandard === 'Custom') continue;
		movedex[id] = plain(entry);
	}

	const abilities = {};
	for (const [id, entry] of Object.entries(dex.data.Abilities)) {
		abilities[id] = plain(entry);
	}

	const items = {};
	for (const [id, entry] of Object.entries(dex.data.Items)) {
		items[id] = plain(entry);
	}

	const counts = {
		pokedex: write('pokedex.js', 'BattlePokedex', pokedex),
		moves: write('moves.js', 'BattleMovedex', movedex),
		abilities: write('abilities.js', 'BattleAbilities', abilities),
		items: write('items.js', 'BattleItems', items),
		learnsets: write('learnsets.js', 'BattleLearnsets', plain(dex.data.Learnsets)),
		typechart: write('typechart.js', 'BattleTypeChart', plain(dex.data.TypeChart)),
		formatsData: write('formats-data.js', 'BattleFormatsData', plain(dex.data.FormatsData)),
	};

	// The client resolves sprites by name; this maps every species to its asset.
	const sprites = {};
	for (const [id, entry] of Object.entries(dex.data.Pokedex)) {
		sprites[id] = {
			front: `assets/pokemon/${id}.png`,
			icon: `assets/pokemon-icons/${id}.png`,
		};
	}
	write('fakemon-sprites.js', 'FakemonSprites', sprites);

	console.log(`Wrote client data to ${OUT}`);
	for (const [name, count] of Object.entries(counts)) {
		console.log(`  ${name}: ${count}`);
	}
	console.log(`  sprites: ${Object.keys(sprites).length}`);
}

main();
