// AUTO-GENERATED by tools/sw97-gen.js: make the cut/new SW97 species legal.
export const FormatsData: import('../../../sim/dex-species').ModdedSpeciesFormatsDataTable = {
	pudie: {
		tier: "OU",
	},
	baririna: {
		tier: "OU",
	},
	tsubomitto: {
		tier: "OU",
	},
	bombseeker: {
		tier: "OU",
	},
	kotora: {
		tier: "OU",
	},
	raitora: {
		tier: "OU",
	},
	madame: {
		tier: "OU",
	},
	norowara: {
		tier: "OU",
	},
	kyonpan: {
		tier: "OU",
	},
	purakkusu: {
		tier: "OU",
	},
	wolfman: {
		tier: "OU",
	},
	warwolf: {
		tier: "OU",
	},
	nameil: {
		tier: "OU",
	},
	honoguma: {
		tier: "OU",
	},
	volbear: {
		tier: "OU",
	},
	dynabear: {
		tier: "OU",
	},
	kurusu: {
		tier: "OU",
	},
	aqua: {
		tier: "OU",
	},
	aquaria: {
		tier: "OU",
	},
	mikon: {
		tier: "OU",
	},
	monja: {
		tier: "OU",
	},
	shibirefugu: {
		tier: "OU",
	},
	gyopin: {
		tier: "OU",
	},
	manbo1: {
		tier: "OU",
	},
	ikari: {
		tier: "OU",
	},
	grotess: {
		tier: "OU",
	},
	para: {
		tier: "OU",
	},
	animon: {
		tier: "OU",
	},
	hinazu: {
		tier: "OU",
	},
	twinz: {
		tier: "OU",
	},
	kounya: {
		tier: "OU",
	},
	rinrin: {
		tier: "OU",
	},
	berurun: {
		tier: "OU",
	},
	puchicorn: {
		tier: "OU",
	},
	turban: {
		tier: "OU",
	},
	betbaby: {
		tier: "OU",
	},
};
