exports.BattlePokedex = {
bulbasaur: {abilities:{"0":"Overgrow"},inherit:true},
ivysaur: {abilities:{"0":"Overgrow"},inherit:true},
venusaur: {abilities:{"0":"Overgrow"},otherFormes:null,inherit:true},
charmander: {abilities:{"0":"Blaze"},inherit:true},
charmeleon: {abilities:{"0":"Blaze"},inherit:true},
charizard: {abilities:{"0":"Blaze"},otherFormes:null,inherit:true},
squirtle: {abilities:{"0":"Torrent"},inherit:true},
wartortle: {abilities:{"0":"Torrent"},inherit:true},
blastoise: {abilities:{"0":"Torrent"},otherFormes:null,inherit:true},
caterpie: {abilities:{"0":"Shield Dust"},inherit:true},
butterfree: {baseStats:{hp:60,atk:45,def:50,spa:80,spd:80,spe:70},abilities:{"0":"Compoundeyes"},inherit:true},
weedle: {abilities:{"0":"Shield Dust"},inherit:true},
beedrill: {baseStats:{hp:65,atk:80,def:40,spa:45,spd:80,spe:75},abilities:{"0":"Swarm"},inherit:true},
pidgey: {abilities:{"0":"Keen Eye","1":"Tangled Feet"},inherit:true},
pidgeotto: {abilities:{"0":"Keen Eye","1":"Tangled Feet"},inherit:true},
pidgeot: {baseStats:{hp:83,atk:80,def:75,spa:70,spd:70,spe:91},abilities:{"0":"Keen Eye","1":"Tangled Feet"},inherit:true},
rattata: {abilities:{"0":"Run Away","1":"Guts"},inherit:true},
raticate: {abilities:{"0":"Run Away","1":"Guts"},inherit:true},
spearow: {abilities:{"0":"Keen Eye"},inherit:true},
fearow: {abilities:{"0":"Keen Eye"},inherit:true},
ekans: {abilities:{"0":"Intimidate","1":"Shed Skin"},inherit:true},
arbok: {abilities:{"0":"Intimidate","1":"Shed Skin"},inherit:true},
pikachu: {baseStats:{hp:35,atk:55,def:30,spa:50,spd:40,spe:90},abilities:{"0":"Static"},inherit:true},
raichu: {baseStats:{hp:60,atk:90,def:55,spa:90,spd:80,spe:100},abilities:{"0":"Static"},inherit:true},
sandshrew: {abilities:{"0":"Sand Veil"},inherit:true},
sandslash: {abilities:{"0":"Sand Veil"},inherit:true},
nidoranf: {"species":"NidoranF",abilities:{"0":"Poison Point","1":"Rivalry"},inherit:true},
nidorina: {abilities:{"0":"Poison Point","1":"Rivalry"},inherit:true},
nidoqueen: {baseStats:{hp:90,atk:82,def:87,spa:75,spd:85,spe:76},abilities:{"0":"Poison Point","1":"Rivalry"},inherit:true},
nidoranm: {"species":"NidoranM",abilities:{"0":"Poison Point","1":"Rivalry"},inherit:true},
nidorino: {abilities:{"0":"Poison Point","1":"Rivalry"},inherit:true},
nidoking: {baseStats:{hp:81,atk:92,def:77,spa:85,spd:75,spe:85},abilities:{"0":"Poison Point","1":"Rivalry"},inherit:true},
clefairy: {"types":["Normal"],abilities:{"0":"Cute Charm","1":"Magic Guard"},inherit:true},
clefable: {"types":["Normal"],baseStats:{hp:95,atk:70,def:73,spa:85,spd:90,spe:60},abilities:{"0":"Cute Charm","1":"Magic Guard"},inherit:true},
vulpix: {abilities:{"0":"Flash Fire"},inherit:true},
ninetales: {abilities:{"0":"Flash Fire"},inherit:true},
jigglypuff: {"types":["Normal"],abilities:{"0":"Cute Charm"},inherit:true},
wigglytuff: {"types":["Normal"],baseStats:{hp:140,atk:70,def:45,spa:75,spd:50,spe:45},abilities:{"0":"Cute Charm"},inherit:true},
zubat: {abilities:{"0":"Inner Focus"},inherit:true},
golbat: {abilities:{"0":"Inner Focus"},inherit:true},
oddish: {abilities:{"0":"Chlorophyll"},inherit:true},
gloom: {abilities:{"0":"Chlorophyll"},inherit:true},
vileplume: {baseStats:{hp:75,atk:80,def:85,spa:100,spd:90,spe:50},abilities:{"0":"Chlorophyll"},inherit:true},
paras: {abilities:{"0":"Effect Spore","1":"Dry Skin"},inherit:true},
parasect: {abilities:{"0":"Effect Spore","1":"Dry Skin"},inherit:true},
venonat: {abilities:{"0":"Compoundeyes","1":"Tinted Lens"},inherit:true},
venomoth: {abilities:{"0":"Shield Dust","1":"Tinted Lens"},inherit:true},
diglett: {abilities:{"0":"Sand Veil","1":"Arena Trap"},inherit:true},
dugtrio: {abilities:{"0":"Sand Veil","1":"Arena Trap"},inherit:true},
meowth: {abilities:{"0":"Pickup","1":"Technician"},inherit:true},
persian: {abilities:{"0":"Limber","1":"Technician"},inherit:true},
psyduck: {abilities:{"0":"Damp","1":"Cloud Nine"},inherit:true},
golduck: {abilities:{"0":"Damp","1":"Cloud Nine"},inherit:true},
mankey: {abilities:{"0":"Vital Spirit","1":"Anger Point"},inherit:true},
primeape: {abilities:{"0":"Vital Spirit","1":"Anger Point"},inherit:true},
growlithe: {abilities:{"0":"Intimidate","1":"Flash Fire"},inherit:true},
arcanine: {abilities:{"0":"Intimidate","1":"Flash Fire"},inherit:true},
poliwag: {abilities:{"0":"Water Absorb","1":"Damp"},inherit:true},
poliwhirl: {abilities:{"0":"Water Absorb","1":"Damp"},inherit:true},
poliwrath: {baseStats:{hp:90,atk:85,def:95,spa:70,spd:90,spe:70},abilities:{"0":"Water Absorb","1":"Damp"},inherit:true},
abra: {abilities:{"0":"Synchronize","1":"Inner Focus"},inherit:true},
kadabra: {abilities:{"0":"Synchronize","1":"Inner Focus"},inherit:true},
alakazam: {baseStats:{hp:55,atk:50,def:45,spa:135,spd:85,spe:120},abilities:{"0":"Synchronize","1":"Inner Focus"},otherFormes:null,inherit:true},
machop: {abilities:{"0":"Guts","1":"No Guard"},inherit:true},
machoke: {abilities:{"0":"Guts","1":"No Guard"},inherit:true},
machamp: {abilities:{"0":"Guts","1":"No Guard"},inherit:true},
bellsprout: {abilities:{"0":"Chlorophyll"},inherit:true},
weepinbell: {abilities:{"0":"Chlorophyll"},inherit:true},
victreebel: {baseStats:{hp:80,atk:105,def:65,spa:100,spd:60,spe:70},abilities:{"0":"Chlorophyll"},inherit:true},
tentacool: {abilities:{"0":"Clear Body","1":"Liquid Ooze"},inherit:true},
tentacruel: {abilities:{"0":"Clear Body","1":"Liquid Ooze"},inherit:true},
geodude: {abilities:{"0":"Rock Head","1":"Sturdy"},inherit:true},
graveler: {abilities:{"0":"Rock Head","1":"Sturdy"},inherit:true},
golem: {baseStats:{hp:80,atk:110,def:130,spa:55,spd:65,spe:45},abilities:{"0":"Rock Head","1":"Sturdy"},inherit:true},
ponyta: {abilities:{"0":"Run Away","1":"Flash Fire"},inherit:true},
rapidash: {abilities:{"0":"Run Away","1":"Flash Fire"},inherit:true},
slowpoke: {abilities:{"0":"Oblivious","1":"Own Tempo"},inherit:true},
slowbro: {abilities:{"0":"Oblivious","1":"Own Tempo"},inherit:true},
magnemite: {abilities:{"0":"Magnet Pull","1":"Sturdy"},inherit:true},
magneton: {abilities:{"0":"Magnet Pull","1":"Sturdy"},inherit:true},
farfetchd: {abilities:{"0":"Keen Eye","1":"Inner Focus"},inherit:true},
doduo: {abilities:{"0":"Run Away","1":"Early Bird"},inherit:true},
dodrio: {abilities:{"0":"Run Away","1":"Early Bird"},inherit:true},
seel: {abilities:{"0":"Thick Fat","1":"Hydration"},inherit:true},
dewgong: {abilities:{"0":"Thick Fat","1":"Hydration"},inherit:true},
grimer: {abilities:{"0":"Stench","1":"Sticky Hold"},inherit:true},
muk: {abilities:{"0":"Stench","1":"Sticky Hold"},inherit:true},
shellder: {abilities:{"0":"Shell Armor","1":"Skill Link"},inherit:true},
cloyster: {abilities:{"0":"Shell Armor","1":"Skill Link"},inherit:true},
gengar: {otherFormes:null,inherit:true},
onix: {abilities:{"0":"Rock Head","1":"Sturdy"},inherit:true},
drowzee: {abilities:{"0":"Insomnia","1":"Forewarn"},inherit:true},
hypno: {abilities:{"0":"Insomnia","1":"Forewarn"},inherit:true},
krabby: {abilities:{"0":"Hyper Cutter","1":"Shell Armor"},inherit:true},
kingler: {abilities:{"0":"Hyper Cutter","1":"Shell Armor"},inherit:true},
voltorb: {abilities:{"0":"Soundproof","1":"Static"},inherit:true},
electrode: {abilities:{"0":"Soundproof","1":"Static"},inherit:true},
exeggcute: {abilities:{"0":"Chlorophyll"},inherit:true},
exeggutor: {abilities:{"0":"Chlorophyll"},inherit:true},
cubone: {abilities:{"0":"Rock Head","1":"Lightningrod"},inherit:true},
marowak: {abilities:{"0":"Rock Head","1":"Lightningrod"},inherit:true},
hitmonlee: {abilities:{"0":"Limber","1":"Reckless"},inherit:true},
hitmonchan: {abilities:{"0":"Keen Eye","1":"Iron Fist"},inherit:true},
lickitung: {abilities:{"0":"Own Tempo","1":"Oblivious"},inherit:true},
rhyhorn: {abilities:{"0":"Lightningrod","1":"Rock Head"},inherit:true},
rhydon: {abilities:{"0":"Lightningrod","1":"Rock Head"},inherit:true},
chansey: {abilities:{"0":"Natural Cure","1":"Serene Grace"},inherit:true},
tangela: {abilities:{"0":"Chlorophyll","1":"Leaf Guard"},inherit:true},
kangaskhan: {abilities:{"0":"Early Bird","1":"Scrappy"},otherFormes:null,inherit:true},
horsea: {abilities:{"0":"Swift Swim","1":"Sniper"},inherit:true},
seadra: {abilities:{"0":"Poison Point","1":"Sniper"},inherit:true},
goldeen: {abilities:{"0":"Swift Swim","1":"Water Veil"},inherit:true},
seaking: {abilities:{"0":"Swift Swim","1":"Water Veil"},inherit:true},
staryu: {abilities:{"0":"Illuminate","1":"Natural Cure"},inherit:true},
starmie: {abilities:{"0":"Illuminate","1":"Natural Cure"},inherit:true},
mrmime: {"types":["Psychic"],abilities:{"0":"Soundproof","1":"Filter"},inherit:true},
scyther: {abilities:{"0":"Swarm","1":"Technician"},inherit:true},
jynx: {abilities:{"0":"Oblivious","1":"Forewarn"},inherit:true},
electabuzz: {abilities:{"0":"Static"},inherit:true},
magmar: {abilities:{"0":"Flame Body"},inherit:true},
pinsir: {abilities:{"0":"Hyper Cutter","1":"Mold Breaker"},otherFormes:null,inherit:true},
tauros: {abilities:{"0":"Intimidate","1":"Anger Point"},inherit:true},
magikarp: {abilities:{"0":"Swift Swim"},inherit:true},
gyarados: {abilities:{"0":"Intimidate"},otherFormes:null,inherit:true},
lapras: {abilities:{"0":"Water Absorb","1":"Shell Armor"},inherit:true},
ditto: {abilities:{"0":"Limber"},inherit:true},
eevee: {abilities:{"0":"Run Away","1":"Adaptability"},"evos":["vaporeon","jolteon","flareon","espeon","umbreon","leafeon","glaceon"],inherit:true},
vaporeon: {abilities:{"0":"Water Absorb"},inherit:true},
jolteon: {abilities:{"0":"Volt Absorb"},inherit:true},
flareon: {abilities:{"0":"Flash Fire"},inherit:true},
porygon: {abilities:{"0":"Trace","1":"Download"},inherit:true},
omanyte: {abilities:{"0":"Swift Swim","1":"Shell Armor"},inherit:true},
omastar: {abilities:{"0":"Swift Swim","1":"Shell Armor"},inherit:true},
kabuto: {abilities:{"0":"Swift Swim","1":"Battle Armor"},inherit:true},
kabutops: {abilities:{"0":"Swift Swim","1":"Battle Armor"},inherit:true},
aerodactyl: {abilities:{"0":"Rock Head","1":"Pressure"},otherFormes:null,inherit:true},
snorlax: {abilities:{"0":"Immunity","1":"Thick Fat"},inherit:true},
articuno: {abilities:{"0":"Pressure"},inherit:true},
zapdos: {abilities:{"0":"Pressure"},inherit:true},
moltres: {abilities:{"0":"Pressure"},inherit:true},
dratini: {abilities:{"0":"Shed Skin"},inherit:true},
dragonair: {abilities:{"0":"Shed Skin"},inherit:true},
dragonite: {abilities:{"0":"Inner Focus"},inherit:true},
mewtwo: {abilities:{"0":"Pressure"},otherFormes:null,inherit:true},
chikorita: {abilities:{"0":"Overgrow"},inherit:true},
bayleef: {abilities:{"0":"Overgrow"},inherit:true},
meganium: {abilities:{"0":"Overgrow"},inherit:true},
cyndaquil: {abilities:{"0":"Blaze"},inherit:true},
quilava: {abilities:{"0":"Blaze"},inherit:true},
typhlosion: {abilities:{"0":"Blaze"},inherit:true},
totodile: {abilities:{"0":"Torrent"},inherit:true},
croconaw: {abilities:{"0":"Torrent"},inherit:true},
feraligatr: {abilities:{"0":"Torrent"},inherit:true},
sentret: {abilities:{"0":"Run Away","1":"Keen Eye"},inherit:true},
furret: {abilities:{"0":"Run Away","1":"Keen Eye"},inherit:true},
hoothoot: {abilities:{"0":"Insomnia","1":"Keen Eye"},inherit:true},
noctowl: {abilities:{"0":"Insomnia","1":"Keen Eye"},inherit:true},
ledyba: {abilities:{"0":"Swarm","1":"Early Bird"},inherit:true},
ledian: {abilities:{"0":"Swarm","1":"Early Bird"},inherit:true},
spinarak: {abilities:{"0":"Swarm","1":"Insomnia"},inherit:true},
ariados: {abilities:{"0":"Swarm","1":"Insomnia"},inherit:true},
crobat: {abilities:{"0":"Inner Focus"},inherit:true},
chinchou: {abilities:{"0":"Volt Absorb","1":"Illuminate"},inherit:true},
lanturn: {abilities:{"0":"Volt Absorb","1":"Illuminate"},inherit:true},
pichu: {abilities:{"0":"Static"},inherit:true},
cleffa: {"types":["Normal"],abilities:{"0":"Cute Charm","1":"Magic Guard"},inherit:true},
igglybuff: {"types":["Normal"],abilities:{"0":"Cute Charm"},inherit:true},
togepi: {"types":["Normal"],abilities:{"0":"Hustle","1":"Serene Grace"},inherit:true},
togetic: {"types":["Normal","Flying"],abilities:{"0":"Hustle","1":"Serene Grace"},inherit:true},
natu: {abilities:{"0":"Synchronize","1":"Early Bird"},inherit:true},
xatu: {abilities:{"0":"Synchronize","1":"Early Bird"},inherit:true},
mareep: {abilities:{"0":"Static"},inherit:true},
flaaffy: {abilities:{"0":"Static"},inherit:true},
ampharos: {baseStats:{hp:90,atk:75,def:75,spa:115,spd:90,spe:55},abilities:{"0":"Static"},otherFormes:null,inherit:true},
bellossom: {baseStats:{hp:75,atk:80,def:85,spa:90,spd:100,spe:50},abilities:{"0":"Chlorophyll"},inherit:true},
marill: {"types":["Water"],abilities:{"0":"Thick Fat","1":"Huge Power"},inherit:true},
azumarill: {"types":["Water"],baseStats:{hp:100,atk:50,def:80,spa:50,spd:80,spe:50},abilities:{"0":"Thick Fat","1":"Huge Power"},inherit:true},
sudowoodo: {abilities:{"0":"Sturdy","1":"Rock Head"},inherit:true},
politoed: {abilities:{"0":"Water Absorb","1":"Damp"},inherit:true},
hoppip: {abilities:{"0":"Chlorophyll","1":"Leaf Guard"},inherit:true},
skiploom: {abilities:{"0":"Chlorophyll","1":"Leaf Guard"},inherit:true},
jumpluff: {baseStats:{hp:75,atk:55,def:70,spa:55,spd:85,spe:110},abilities:{"0":"Chlorophyll","1":"Leaf Guard"},inherit:true},
aipom: {abilities:{"0":"Run Away","1":"Pickup"},inherit:true},
sunkern: {abilities:{"0":"Chlorophyll","1":"Solar Power"},inherit:true},
sunflora: {abilities:{"0":"Chlorophyll","1":"Solar Power"},inherit:true},
yanma: {abilities:{"0":"Speed Boost","1":"Compoundeyes"},inherit:true},
wooper: {abilities:{"0":"Damp","1":"Water Absorb"},inherit:true},
quagsire: {abilities:{"0":"Damp","1":"Water Absorb"},inherit:true},
espeon: {abilities:{"0":"Synchronize"},inherit:true},
umbreon: {abilities:{"0":"Synchronize"},inherit:true},
murkrow: {abilities:{"0":"Insomnia","1":"Super Luck"},inherit:true},
slowking: {abilities:{"0":"Oblivious","1":"Own Tempo"},inherit:true},
wobbuffet: {abilities:{"0":"Shadow Tag"},inherit:true},
girafarig: {abilities:{"0":"Inner Focus","1":"Early Bird"},inherit:true},
pineco: {abilities:{"0":"Sturdy"},inherit:true},
forretress: {abilities:{"0":"Sturdy"},inherit:true},
dunsparce: {abilities:{"0":"Serene Grace","1":"Run Away"},inherit:true},
gligar: {abilities:{"0":"Hyper Cutter","1":"Sand Veil"},inherit:true},
steelix: {abilities:{"0":"Rock Head","1":"Sturdy"},inherit:true},
snubbull: {"types":["Normal"],abilities:{"0":"Intimidate","1":"Run Away"},inherit:true},
granbull: {"types":["Normal"],abilities:{"0":"Intimidate","1":"Quick Feet"},inherit:true},
qwilfish: {abilities:{"0":"Poison Point","1":"Swift Swim"},inherit:true},
scizor: {abilities:{"0":"Swarm","1":"Technician"},otherFormes:null,inherit:true},
shuckle: {abilities:{"0":"Sturdy","1":"Gluttony"},inherit:true},
heracross: {abilities:{"0":"Swarm","1":"Guts"},otherFormes:null,inherit:true},
sneasel: {abilities:{"0":"Inner Focus","1":"Keen Eye"},inherit:true},
teddiursa: {abilities:{"0":"Pickup","1":"Quick Feet"},inherit:true},
ursaring: {abilities:{"0":"Guts","1":"Quick Feet"},inherit:true},
slugma: {abilities:{"0":"Magma Armor","1":"Flame Body"},inherit:true},
magcargo: {abilities:{"0":"Magma Armor","1":"Flame Body"},inherit:true},
swinub: {abilities:{"0":"Oblivious","1":"Snow Cloak"},inherit:true},
piloswine: {abilities:{"0":"Oblivious","1":"Snow Cloak"},inherit:true},
corsola: {abilities:{"0":"Hustle","1":"Natural Cure"},inherit:true},
remoraid: {abilities:{"0":"Hustle","1":"Sniper"},inherit:true},
octillery: {abilities:{"0":"Suction Cups","1":"Sniper"},inherit:true},
delibird: {abilities:{"0":"Vital Spirit","1":"Hustle"},inherit:true},
mantine: {abilities:{"0":"Swift Swim","1":"Water Absorb"},inherit:true},
skarmory: {abilities:{"0":"Keen Eye","1":"Sturdy"},inherit:true},
houndour: {abilities:{"0":"Early Bird","1":"Flash Fire"},inherit:true},
houndoom: {abilities:{"0":"Early Bird","1":"Flash Fire"},otherFormes:null,inherit:true},
kingdra: {abilities:{"0":"Swift Swim","1":"Sniper"},inherit:true},
phanpy: {abilities:{"0":"Pickup"},inherit:true},
donphan: {abilities:{"0":"Sturdy"},inherit:true},
porygon2: {abilities:{"0":"Trace","1":"Download"},inherit:true},
stantler: {abilities:{"0":"Intimidate","1":"Frisk"},inherit:true},
smeargle: {abilities:{"0":"Own Tempo","1":"Technician"},inherit:true},
tyrogue: {abilities:{"0":"Guts","1":"Steadfast"},inherit:true},
hitmontop: {abilities:{"0":"Intimidate","1":"Technician"},inherit:true},
smoochum: {abilities:{"0":"Oblivious","1":"Forewarn"},inherit:true},
elekid: {abilities:{"0":"Static"},inherit:true},
magby: {abilities:{"0":"Flame Body"},inherit:true},
miltank: {abilities:{"0":"Thick Fat","1":"Scrappy"},inherit:true},
blissey: {abilities:{"0":"Natural Cure","1":"Serene Grace"},inherit:true},
raikou: {abilities:{"0":"Pressure"},inherit:true},
entei: {abilities:{"0":"Pressure"},inherit:true},
suicune: {abilities:{"0":"Pressure"},inherit:true},
larvitar: {abilities:{"0":"Guts"},inherit:true},
tyranitar: {abilities:{"0":"Sand Stream"},otherFormes:null,inherit:true},
lugia: {abilities:{"0":"Pressure"},inherit:true},
hooh: {abilities:{"0":"Pressure"},inherit:true},
treecko: {abilities:{"0":"Overgrow"},inherit:true},
grovyle: {abilities:{"0":"Overgrow"},inherit:true},
sceptile: {abilities:{"0":"Overgrow"},inherit:true},
torchic: {abilities:{"0":"Blaze"},inherit:true},
combusken: {abilities:{"0":"Blaze"},inherit:true},
blaziken: {abilities:{"0":"Blaze"},otherFormes:null,inherit:true},
mudkip: {abilities:{"0":"Torrent"},inherit:true},
marshtomp: {abilities:{"0":"Torrent"},inherit:true},
swampert: {abilities:{"0":"Torrent"},inherit:true},
poochyena: {abilities:{"0":"Run Away","1":"Quick Feet"},inherit:true},
mightyena: {abilities:{"0":"Intimidate","1":"Quick Feet"},inherit:true},
zigzagoon: {abilities:{"0":"Pickup","1":"Gluttony"},inherit:true},
linoone: {abilities:{"0":"Pickup","1":"Gluttony"},inherit:true},
wurmple: {abilities:{"0":"Shield Dust"},inherit:true},
beautifly: {abilities:{"0":"Swarm"},inherit:true},
dustox: {abilities:{"0":"Shield Dust"},inherit:true},
lotad: {abilities:{"0":"Swift Swim","1":"Rain Dish"},inherit:true},
lombre: {abilities:{"0":"Swift Swim","1":"Rain Dish"},inherit:true},
ludicolo: {abilities:{"0":"Swift Swim","1":"Rain Dish"},inherit:true},
seedot: {abilities:{"0":"Chlorophyll","1":"Early Bird"},inherit:true},
nuzleaf: {abilities:{"0":"Chlorophyll","1":"Early Bird"},inherit:true},
shiftry: {abilities:{"0":"Chlorophyll","1":"Early Bird"},inherit:true},
taillow: {abilities:{"0":"Guts"},inherit:true},
swellow: {abilities:{"0":"Guts"},inherit:true},
wingull: {abilities:{"0":"Keen Eye"},inherit:true},
pelipper: {abilities:{"0":"Keen Eye"},inherit:true},
ralts: {"types":["Psychic"],abilities:{"0":"Synchronize","1":"Trace"},inherit:true},
kirlia: {"types":["Psychic"],abilities:{"0":"Synchronize","1":"Trace"},inherit:true},
gardevoir: {"types":["Psychic"],abilities:{"0":"Synchronize","1":"Trace"},otherFormes:null,inherit:true},
surskit: {abilities:{"0":"Swift Swim"},inherit:true},
masquerain: {abilities:{"0":"Intimidate"},inherit:true},
shroomish: {abilities:{"0":"Effect Spore","1":"Poison Heal"},inherit:true},
breloom: {abilities:{"0":"Effect Spore","1":"Poison Heal"},inherit:true},
nincada: {abilities:{"0":"Compoundeyes"},inherit:true},
ninjask: {abilities:{"0":"Speed Boost"},inherit:true},
whismur: {abilities:{"0":"Soundproof"},inherit:true},
loudred: {abilities:{"0":"Soundproof"},inherit:true},
exploud: {baseStats:{hp:104,atk:91,def:63,spa:91,spd:63,spe:68},abilities:{"0":"Soundproof"},inherit:true},
makuhita: {abilities:{"0":"Thick Fat","1":"Guts"},inherit:true},
hariyama: {abilities:{"0":"Thick Fat","1":"Guts"},inherit:true},
azurill: {"types":["Normal"],abilities:{"0":"Thick Fat","1":"Huge Power"},inherit:true},
nosepass: {abilities:{"0":"Sturdy","1":"Magnet Pull"},inherit:true},
skitty: {abilities:{"0":"Cute Charm","1":"Normalize"},inherit:true},
delcatty: {abilities:{"0":"Cute Charm","1":"Normalize"},inherit:true},
sableye: {abilities:{"0":"Keen Eye","1":"Stall"},inherit:true},
mawile: {"types":["Steel"],abilities:{"0":"Hyper Cutter","1":"Intimidate"},otherFormes:null,inherit:true},
aron: {abilities:{"0":"Sturdy","1":"Rock Head"},inherit:true},
lairon: {abilities:{"0":"Sturdy","1":"Rock Head"},inherit:true},
aggron: {abilities:{"0":"Sturdy","1":"Rock Head"},otherFormes:null,inherit:true},
meditite: {abilities:{"0":"Pure Power"},inherit:true},
medicham: {abilities:{"0":"Pure Power"},otherFormes:null,inherit:true},
electrike: {abilities:{"0":"Static","1":"Lightningrod"},inherit:true},
manectric: {abilities:{"0":"Static","1":"Lightningrod"},otherFormes:null,inherit:true},
plusle: {abilities:{"0":"Plus"},inherit:true},
minun: {abilities:{"0":"Minus"},inherit:true},
volbeat: {abilities:{"0":"Illuminate","1":"Swarm"},inherit:true},
illumise: {abilities:{"0":"Oblivious","1":"Tinted Lens"},inherit:true},
roselia: {abilities:{"0":"Natural Cure","1":"Poison Point"},inherit:true},
gulpin: {abilities:{"0":"Liquid Ooze","1":"Sticky Hold"},inherit:true},
swalot: {abilities:{"0":"Liquid Ooze","1":"Sticky Hold"},inherit:true},
carvanha: {abilities:{"0":"Rough Skin"},inherit:true},
sharpedo: {abilities:{"0":"Rough Skin"},inherit:true},
wailmer: {abilities:{"0":"Water Veil","1":"Oblivious"},inherit:true},
wailord: {abilities:{"0":"Water Veil","1":"Oblivious"},inherit:true},
numel: {abilities:{"0":"Oblivious","1":"Simple"},inherit:true},
camerupt: {abilities:{"0":"Magma Armor","1":"Solid Rock"},inherit:true},
torkoal: {abilities:{"0":"White Smoke"},inherit:true},
spoink: {abilities:{"0":"Thick Fat","1":"Own Tempo"},inherit:true},
grumpig: {abilities:{"0":"Thick Fat","1":"Own Tempo"},inherit:true},
spinda: {abilities:{"0":"Own Tempo","1":"Tangled Feet"},inherit:true},
trapinch: {abilities:{"0":"Hyper Cutter","1":"Arena Trap"},inherit:true},
cacnea: {abilities:{"0":"Sand Veil"},inherit:true},
cacturne: {abilities:{"0":"Sand Veil"},inherit:true},
swablu: {abilities:{"0":"Natural Cure"},inherit:true},
altaria: {abilities:{"0":"Natural Cure"},inherit:true},
zangoose: {abilities:{"0":"Immunity"},inherit:true},
seviper: {abilities:{"0":"Shed Skin"},inherit:true},
barboach: {abilities:{"0":"Oblivious","1":"Anticipation"},inherit:true},
whiscash: {abilities:{"0":"Oblivious","1":"Anticipation"},inherit:true},
corphish: {abilities:{"0":"Hyper Cutter","1":"Shell Armor"},inherit:true},
crawdaunt: {abilities:{"0":"Hyper Cutter","1":"Shell Armor"},inherit:true},
lileep: {abilities:{"0":"Suction Cups"},inherit:true},
cradily: {abilities:{"0":"Suction Cups"},inherit:true},
anorith: {abilities:{"0":"Battle Armor"},inherit:true},
armaldo: {abilities:{"0":"Battle Armor"},inherit:true},
feebas: {abilities:{"0":"Swift Swim"},inherit:true},
milotic: {abilities:{"0":"Marvel Scale"},inherit:true},
kecleon: {abilities:{"0":"Color Change"},inherit:true},
shuppet: {abilities:{"0":"Insomnia","1":"Frisk"},inherit:true},
banette: {abilities:{"0":"Insomnia","1":"Frisk"},otherFormes:null,inherit:true},
duskull: {abilities:{"0":"Levitate"},inherit:true},
dusclops: {abilities:{"0":"Pressure"},inherit:true},
tropius: {abilities:{"0":"Chlorophyll","1":"Solar Power"},inherit:true},
absol: {abilities:{"0":"Pressure","1":"Super Luck"},otherFormes:null,inherit:true},
wynaut: {abilities:{"0":"Shadow Tag"},inherit:true},
snorunt: {abilities:{"0":"Inner Focus","1":"Ice Body"},inherit:true},
glalie: {abilities:{"0":"Inner Focus","1":"Ice Body"},inherit:true},
spheal: {abilities:{"0":"Thick Fat","1":"Ice Body"},inherit:true},
sealeo: {abilities:{"0":"Thick Fat","1":"Ice Body"},inherit:true},
walrein: {abilities:{"0":"Thick Fat","1":"Ice Body"},inherit:true},
clamperl: {abilities:{"0":"Shell Armor"},inherit:true},
huntail: {abilities:{"0":"Swift Swim"},inherit:true},
gorebyss: {abilities:{"0":"Swift Swim"},inherit:true},
relicanth: {abilities:{"0":"Swift Swim","1":"Rock Head"},inherit:true},
luvdisc: {abilities:{"0":"Swift Swim"},inherit:true},
bagon: {abilities:{"0":"Rock Head"},inherit:true},
shelgon: {abilities:{"0":"Rock Head"},inherit:true},
salamence: {abilities:{"0":"Intimidate"},inherit:true},
beldum: {abilities:{"0":"Clear Body"},inherit:true},
metang: {abilities:{"0":"Clear Body"},inherit:true},
metagross: {abilities:{"0":"Clear Body"},inherit:true},
regirock: {abilities:{"0":"Clear Body"},inherit:true},
regice: {abilities:{"0":"Clear Body"},inherit:true},
registeel: {abilities:{"0":"Clear Body"},inherit:true},
missingno: {abilities:{"0":""},inherit:true},
tomohawk: {abilities:{"0":"Intimidate","1":"Prankster"},inherit:true},
necturna: {abilities:{"0":"Forewarn"},inherit:true},
mollux: {abilities:{"0":"Dry Skin"},inherit:true},
aurumoth: {abilities:{"0":"Weak Armor","1":"No Guard"},inherit:true},
syclant: {abilities:{"0":"Compoundeyes","1":"Mountaineer"},inherit:true}
};
