/**
 * Gen 1 needs a pokedex.js change for the following reasons:
 * Special was a single stat.
 * There was no gender in gen 1.
 * Gotta delete some evolutions and pre-evolutions.
 * Additionally, egg groups, gender ratio, and abilities can be deleted to keep this clean.
 * Obnoxiously, the first ability (0) must be kept to make it easier for users, as otherwise
 * Illegal banlist will check for no ability or "None" ability if users use the teambuilder
 * and do not change the default ability.
 */
exports.BattlePokedex = {
bulbasaur: {gender:"N",abilities:{"0":"Overgrow"},inherit:true},
ivysaur: {gender:"N",abilities:{"0":"Overgrow"},inherit:true},
venusaur: {gender:"N",abilities:{"0":"Overgrow"},otherFormes:null,inherit:true},
charmander: {gender:"N",baseStats:{hp:39,atk:52,def:43,spa:50,spd:50,spe:65},abilities:{"0":"Blaze"},inherit:true},
charmeleon: {gender:"N",baseStats:{hp:58,atk:64,def:58,spa:65,spd:65,spe:80},abilities:{"0":"Blaze"},inherit:true},
charizard: {gender:"N",baseStats:{hp:78,atk:84,def:78,spa:85,spd:85,spe:100},abilities:{"0":"Blaze"},otherFormes:null,inherit:true},
squirtle: {gender:"N",baseStats:{hp:44,atk:48,def:65,spa:50,spd:50,spe:43},abilities:{"0":"Torrent"},inherit:true},
wartortle: {gender:"N",baseStats:{hp:59,atk:63,def:80,spa:65,spd:65,spe:58},abilities:{"0":"Torrent"},inherit:true},
blastoise: {gender:"N",baseStats:{hp:79,atk:83,def:100,spa:85,spd:85,spe:78},abilities:{"0":"Torrent"},otherFormes:null,inherit:true},
caterpie: {gender:"N",abilities:{"0":"Shield Dust"},inherit:true},
metapod: {gender:"N",inherit:true},
butterfree: {gender:"N",baseStats:{hp:60,atk:45,def:50,spa:80,spd:80,spe:70},abilities:{"0":"Compoundeyes"},inherit:true},
weedle: {gender:"N",abilities:{"0":"Shield Dust"},inherit:true},
kakuna: {gender:"N",inherit:true},
beedrill: {gender:"N",baseStats:{hp:65,atk:80,def:40,spa:45,spd:45,spe:75},abilities:{"0":"Swarm"},inherit:true},
pidgey: {gender:"N",abilities:{"0":"Keen Eye"},inherit:true},
pidgeotto: {gender:"N",abilities:{"0":"Keen Eye"},inherit:true},
pidgeot: {gender:"N",baseStats:{hp:83,atk:80,def:75,spa:70,spd:70,spe:91},abilities:{"0":"Keen Eye"},inherit:true},
rattata: {gender:"N",baseStats:{hp:30,atk:56,def:35,spa:25,spd:25,spe:72},abilities:{"0":"Run Away"},inherit:true},
raticate: {gender:"N",baseStats:{hp:55,atk:81,def:60,spa:50,spd:50,spe:97},abilities:{"0":"Run Away"},inherit:true},
spearow: {gender:"N",abilities:{"0":"Keen Eye"},inherit:true},
fearow: {gender:"N",abilities:{"0":"Keen Eye"},inherit:true},
ekans: {gender:"N",baseStats:{hp:35,atk:60,def:44,spa:40,spd:40,spe:55},abilities:{"0":"Intimidate"},inherit:true},
arbok: {gender:"N",baseStats:{hp:60,atk:85,def:69,spa:65,spd:65,spe:80},abilities:{"0":"Intimidate"},inherit:true},
pikachu: {gender:"N",baseStats:{hp:35,atk:55,def:30,spa:50,spd:50,spe:90},abilities:{"0":"Static"},"prevo":null,inherit:true},
raichu: {gender:"N",baseStats:{hp:60,atk:90,def:55,spa:90,spd:90,spe:100},abilities:{"0":"Static"},inherit:true},
sandshrew: {gender:"N",baseStats:{hp:50,atk:75,def:85,spa:30,spd:30,spe:40},abilities:{"0":"Sand Veil","DW":"Sand Rush"},inherit:true},
sandslash: {gender:"N",baseStats:{hp:75,atk:100,def:110,spa:55,spd:55,spe:65},abilities:{"0":"Sand Veil","DW":"Sand Rush"},inherit:true},
nidoranf: {"species":"NidoranF",gender:"N",abilities:{"0":"Poison Point"},inherit:true},
nidorina: {gender:"N",abilities:{"0":"Poison Point"},inherit:true},
nidoqueen: {gender:"N",baseStats:{hp:90,atk:82,def:87,spa:75,spd:75,spe:76},abilities:{"0":"Poison Point"},evoLevel:1,inherit:true},
nidoranm: {"species":"NidoranM",gender:"N",abilities:{"0":"Poison Point","1":"Rivalry","DW":"Hustle"},inherit:true},
nidorino: {gender:"N",abilities:{"0":"Poison Point","1":"Rivalry","DW":"Hustle"},inherit:true},
nidoking: {gender:"N",baseStats:{hp:81,atk:92,def:77,spa:75,spd:75,spe:85},abilities:{"0":"Poison Point","1":"Rivalry","DW":"Sheer Force"},evoLevel:1,inherit:true},
clefairy: {"types":["Normal"],gender:"N",baseStats:{hp:70,atk:45,def:48,spa:60,spd:60,spe:35},abilities:{"0":"Cute Charm","1":"Magic Guard","DW":"Friend Guard"},inherit:true},
clefable: {"types":["Normal"],gender:"N",baseStats:{hp:95,atk:70,def:73,spa:85,spd:85,spe:60},abilities:{"0":"Cute Charm","1":"Magic Guard","DW":"Unaware"},inherit:true},
vulpix: {gender:"N",baseStats:{hp:38,atk:41,def:40,spa:65,spd:65,spe:65},abilities:{"0":"Flash Fire"},inherit:true},
ninetales: {gender:"N",baseStats:{hp:73,atk:76,def:75,spa:100,spd:100,spe:100},abilities:{"0":"Flash Fire"},inherit:true},
jigglypuff: {"types":["Normal"],gender:"N",baseStats:{hp:115,atk:45,def:20,spa:25,spd:25,spe:20},abilities:{"0":"Cute Charm","DW":"Friend Guard"},inherit:true},
wigglytuff: {"types":["Normal"],gender:"N",baseStats:{hp:140,atk:70,def:45,spa:50,spd:50,spe:45},abilities:{"0":"Cute Charm","DW":"Frisk"},inherit:true},
zubat: {gender:"N",baseStats:{hp:40,atk:45,def:35,spa:40,spd:40,spe:55},abilities:{"0":"Inner Focus"},inherit:true},
golbat: {gender:"N",baseStats:{hp:75,atk:80,def:70,spa:75,spd:75,spe:90},abilities:{"0":"Inner Focus"},inherit:true},
oddish: {gender:"N",baseStats:{hp:45,atk:50,def:55,spa:75,spd:75,spe:30},abilities:{"0":"Chlorophyll","DW":"Run Away"},inherit:true},
gloom: {gender:"N",baseStats:{hp:60,atk:65,def:70,spa:85,spd:85,spe:40},abilities:{"0":"Chlorophyll","DW":"Stench"},inherit:true},
vileplume: {gender:"N",baseStats:{hp:75,atk:80,def:85,spa:100,spd:100,spe:50},abilities:{"0":"Chlorophyll","DW":"Effect Spore"},evoLevel:1,inherit:true},
paras: {gender:"N",baseStats:{hp:35,atk:70,def:55,spa:55,spd:55,spe:25},abilities:{"0":"Effect Spore"},inherit:true},
parasect: {gender:"N",baseStats:{hp:60,atk:95,def:80,spa:80,spd:80,spe:30},abilities:{"0":"Effect Spore"},inherit:true},
venonat: {gender:"N",baseStats:{hp:60,atk:55,def:50,spa:40,spd:40,spe:45},abilities:{"0":"Compoundeyes","1":"Tinted Lens"},inherit:true},
venomoth: {gender:"N",baseStats:{hp:70,atk:65,def:60,spa:90,spd:90,spe:90},abilities:{"0":"Shield Dust","1":"Tinted Lens"},inherit:true},
diglett: {gender:"N",baseStats:{hp:10,atk:55,def:25,spa:45,spd:45,spe:95},abilities:{"0":"Sand Veil","1":"Arena Trap"},inherit:true},
dugtrio: {gender:"N",baseStats:{hp:35,atk:80,def:50,spa:70,spd:70,spe:120},abilities:{"0":"Sand Veil","1":"Arena Trap"},inherit:true},
meowth: {gender:"N",abilities:{"0":"Pickup","1":"Technician","DW":"Unnerve"},inherit:true},
persian: {gender:"N",abilities:{"0":"Limber","1":"Technician","DW":"Unnerve"},inherit:true},
psyduck: {gender:"N",baseStats:{hp:50,atk:52,def:48,spa:50,spd:50,spe:55},abilities:{"0":"Damp","1":"Cloud Nine"},inherit:true},
golduck: {gender:"N",baseStats:{hp:80,atk:82,def:78,spa:80,spd:80,spe:85},abilities:{"0":"Damp","1":"Cloud Nine"},inherit:true},
mankey: {gender:"N",baseStats:{hp:40,atk:80,def:35,spa:35,spd:35,spe:70},abilities:{"0":"Vital Spirit","1":"Anger Point","DW":"Defiant"},inherit:true},
primeape: {gender:"N",baseStats:{hp:65,atk:105,def:60,spa:60,spd:60,spe:95},abilities:{"0":"Vital Spirit","1":"Anger Point","DW":"Defiant"},inherit:true},
growlithe: {gender:"N",baseStats:{hp:55,atk:70,def:45,spa:50,spd:50,spe:60},abilities:{"0":"Intimidate"},inherit:true},
arcanine: {gender:"N",baseStats:{hp:90,atk:110,def:80,spa:80,spd:80,spe:95},abilities:{"0":"Intimidate"},inherit:true},
poliwag: {gender:"N",abilities:{"0":"Water Absorb","1":"Damp"},inherit:true},
poliwhirl: {gender:"N",abilities:{"0":"Water Absorb","1":"Damp"},inherit:true},
poliwrath: {gender:"N",baseStats:{hp:90,atk:85,def:95,spa:70,spd:70,spe:70},abilities:{"0":"Water Absorb","1":"Damp"},evoLevel:1,inherit:true},
abra: {gender:"N",baseStats:{hp:25,atk:20,def:15,spa:105,spd:105,spe:90},abilities:{"0":"Synchronize","1":"Inner Focus"},inherit:true},
kadabra: {gender:"N",baseStats:{hp:40,atk:35,def:30,spa:120,spd:120,spe:105},abilities:{"0":"Synchronize","1":"Inner Focus"},inherit:true},
alakazam: {gender:"N",baseStats:{hp:55,atk:50,def:45,spa:135,spd:135,spe:120},abilities:{"0":"Synchronize","1":"Inner Focus"},evoLevel:1,otherFormes:null,inherit:true},
machop: {gender:"N",abilities:{"0":"Guts","1":"No Guard","DW":"Steadfast"},inherit:true},
machoke: {gender:"N",baseStats:{hp:80,atk:100,def:70,spa:50,spd:50,spe:45},abilities:{"0":"Guts","1":"No Guard","DW":"Steadfast"},inherit:true},
machamp: {gender:"N",baseStats:{hp:90,atk:130,def:80,spa:65,spd:65,spe:55},abilities:{"0":"Guts","1":"No Guard","DW":"Steadfast"},evoLevel:1,inherit:true},
bellsprout: {gender:"N",baseStats:{hp:50,atk:75,def:35,spa:70,spd:70,spe:40},abilities:{"0":"Chlorophyll","DW":"Gluttony"},inherit:true},
weepinbell: {gender:"N",baseStats:{hp:65,atk:90,def:50,spa:85,spd:85,spe:55},abilities:{"0":"Chlorophyll","DW":"Gluttony"},inherit:true},
victreebel: {gender:"N",baseStats:{hp:80,atk:105,def:65,spa:100,spd:100,spe:70},abilities:{"0":"Chlorophyll","DW":"Gluttony"},evoLevel:1,inherit:true},
tentacool: {gender:"N",baseStats:{hp:40,atk:40,def:35,spa:100,spd:100,spe:70},abilities:{"0":"Clear Body","1":"Liquid Ooze","DW":"Rain Dish"},inherit:true},
tentacruel: {gender:"N",baseStats:{hp:80,atk:70,def:65,spa:120,spd:120,spe:100},abilities:{"0":"Clear Body","1":"Liquid Ooze","DW":"Rain Dish"},inherit:true},
geodude: {gender:"N",abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sand Veil"},inherit:true},
graveler: {gender:"N",abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sand Veil"},inherit:true},
golem: {gender:"N",baseStats:{hp:80,atk:110,def:130,spa:55,spd:55,spe:45},abilities:{"0":"Rock Head","1":"Sturdy","DW":"Sand Veil"},evoLevel:1,inherit:true},
ponyta: {gender:"N",abilities:{"0":"Run Away","1":"Flash Fire","DW":"Flame Body"},inherit:true},
rapidash: {gender:"N",abilities:{"0":"Run Away","1":"Flash Fire","DW":"Flame Body"},inherit:true},
slowpoke: {gender:"N",abilities:{"0":"Oblivious","1":"Own Tempo","DW":"Regenerator"},inherit:true},
slowbro: {gender:"N",baseStats:{hp:95,atk:75,def:110,spa:80,spd:80,spe:30},abilities:{"0":"Oblivious","1":"Own Tempo","DW":"Regenerator"},inherit:true},
magnemite: {"types":["Electric"],baseStats:{hp:25,atk:35,def:70,spa:95,spd:95,spe:45},abilities:{"0":"Magnet Pull","1":"Sturdy","DW":"Analytic"},inherit:true},
magneton: {"types":["Electric"],baseStats:{hp:50,atk:60,def:95,spa:120,spd:120,spe:70},abilities:{"0":"Magnet Pull","1":"Sturdy","DW":"Analytic"},inherit:true},
farfetchd: {gender:"N",baseStats:{hp:52,atk:65,def:55,spa:58,spd:58,spe:60},abilities:{"0":"Keen Eye","1":"Inner Focus","DW":"Defiant"},inherit:true},
doduo: {gender:"N",abilities:{"0":"Run Away","1":"Early Bird","DW":"Tangled Feet"},inherit:true},
dodrio: {gender:"N",abilities:{"0":"Run Away","1":"Early Bird","DW":"Tangled Feet"},inherit:true},
seel: {gender:"N",baseStats:{hp:65,atk:45,def:55,spa:70,spd:70,spe:45},abilities:{"0":"Thick Fat","1":"Hydration","DW":"Ice Body"},inherit:true},
dewgong: {gender:"N",baseStats:{hp:90,atk:70,def:80,spa:95,spd:95,spe:70},abilities:{"0":"Thick Fat","1":"Hydration","DW":"Ice Body"},inherit:true},
grimer: {gender:"N",baseStats:{hp:80,atk:80,def:50,spa:40,spd:40,spe:25},abilities:{"0":"Stench","1":"Sticky Hold","DW":"Poison Touch"},inherit:true},
muk: {gender:"N",baseStats:{hp:105,atk:105,def:75,spa:65,spd:65,spe:50},abilities:{"0":"Stench","1":"Sticky Hold","DW":"Poison Touch"},inherit:true},
shellder: {gender:"N",baseStats:{hp:30,atk:65,def:100,spa:45,spd:45,spe:40},abilities:{"0":"Shell Armor","1":"Skill Link","DW":"Overcoat"},inherit:true},
cloyster: {gender:"N",baseStats:{hp:50,atk:95,def:180,spa:85,spd:85,spe:70},abilities:{"0":"Shell Armor","1":"Skill Link","DW":"Overcoat"},inherit:true},
gastly: {gender:"N",baseStats:{hp:30,atk:35,def:30,spa:100,spd:100,spe:80},inherit:true},
haunter: {gender:"N",baseStats:{hp:45,atk:50,def:45,spa:115,spd:115,spe:95},inherit:true},
gengar: {gender:"N",baseStats:{hp:60,atk:65,def:60,spa:130,spd:130,spe:110},evoLevel:1,otherFormes:null,inherit:true},
onix: {gender:"N",baseStats:{hp:35,atk:45,def:160,spa:30,spd:30,spe:70},abilities:{"0":"Rock Head","1":"Sturdy","DW":"Weak Armor"},inherit:true},
drowzee: {gender:"N",baseStats:{hp:60,atk:48,def:45,spa:90,spd:90,spe:42},abilities:{"0":"Insomnia","1":"Forewarn","DW":"Inner Focus"},inherit:true},
hypno: {gender:"N",baseStats:{hp:85,atk:73,def:70,spa:115,spd:115,spe:67},abilities:{"0":"Insomnia","1":"Forewarn","DW":"Inner Focus"},inherit:true},
krabby: {gender:"N",abilities:{"0":"Hyper Cutter","1":"Shell Armor","DW":"Sheer Force"},inherit:true},
kingler: {gender:"N",abilities:{"0":"Hyper Cutter","1":"Shell Armor","DW":"Sheer Force"},inherit:true},
voltorb: {abilities:{"0":"Soundproof","1":"Static","DW":"Aftermath"},inherit:true},
electrode: {abilities:{"0":"Soundproof","1":"Static","DW":"Aftermath"},inherit:true},
exeggcute: {gender:"N",baseStats:{hp:60,atk:40,def:80,spa:60,spd:60,spe:40},abilities:{"0":"Chlorophyll","DW":"Harvest"},inherit:true},
exeggutor: {gender:"N",baseStats:{hp:95,atk:95,def:85,spa:125,spd:125,spe:55},abilities:{"0":"Chlorophyll","DW":"Harvest"},inherit:true},
cubone: {gender:"N",baseStats:{hp:50,atk:50,def:95,spa:40,spd:40,spe:35},abilities:{"0":"Rock Head","1":"Lightningrod","DW":"Battle Armor"},inherit:true},
marowak: {gender:"N",baseStats:{hp:60,atk:80,def:110,spa:50,spd:50,spe:45},abilities:{"0":"Rock Head","1":"Lightningrod","DW":"Battle Armor"},inherit:true},
hitmonlee: {gender:"N",baseStats:{hp:50,atk:120,def:53,spa:35,spd:35,spe:87},abilities:{"0":"Limber","1":"Reckless","DW":"Unburden"},inherit:true},
hitmonchan: {gender:"N",baseStats:{hp:50,atk:105,def:79,spa:35,spd:35,spe:76},abilities:{"0":"Keen Eye","1":"Iron Fist","DW":"Inner Focus"},inherit:true},
lickitung: {gender:"N",baseStats:{hp:90,atk:55,def:75,spa:60,spd:60,spe:30},abilities:{"0":"Own Tempo","1":"Oblivious","DW":"Cloud Nine"},inherit:true},
koffing: {gender:"N",baseStats:{hp:40,atk:65,def:95,spa:60,spd:60,spe:35},inherit:true},
weezing: {gender:"N",baseStats:{hp:65,atk:90,def:120,spa:85,spd:85,spe:60},inherit:true},
rhyhorn: {gender:"N",abilities:{"0":"Lightningrod","1":"Rock Head","DW":"Reckless"},inherit:true},
rhydon: {gender:"N",abilities:{"0":"Lightningrod","1":"Rock Head","DW":"Reckless"},inherit:true},
chansey: {gender:"N",baseStats:{hp:250,atk:5,def:5,spa:105,spd:105,spe:50},abilities:{"0":"Natural Cure"},"evos":null,inherit:true},
tangela: {gender:"N",baseStats:{hp:65,atk:55,def:115,spa:100,spd:100,spe:60},abilities:{"0":"Chlorophyll","1":"Leaf Guard","DW":"Regenerator"},inherit:true},
kangaskhan: {gender:"N",baseStats:{hp:105,atk:95,def:80,spa:40,spd:40,spe:90},abilities:{"0":"Early Bird","1":"Scrappy","DW":"Inner Focus"},otherFormes:null,inherit:true},
horsea: {gender:"N",baseStats:{hp:30,atk:40,def:70,spa:70,spd:79,spe:60},abilities:{"0":"Swift Swim","1":"Sniper","DW":"Damp"},inherit:true},
seadra: {gender:"N",baseStats:{hp:55,atk:65,def:95,spa:95,spd:95,spe:85},abilities:{"0":"Poison Point","1":"Sniper","DW":"Damp"},inherit:true},
goldeen: {gender:"N",baseStats:{hp:45,atk:67,def:60,spa:50,spd:50,spe:63},abilities:{"0":"Swift Swim","1":"Water Veil","DW":"Lightningrod"},inherit:true},
seaking: {gender:"N",baseStats:{hp:80,atk:92,def:65,spa:80,spd:80,spe:68},abilities:{"0":"Swift Swim","1":"Water Veil","DW":"Lightningrod"},inherit:true},
staryu: {baseStats:{hp:30,atk:45,def:55,spa:70,spd:70,spe:85},abilities:{"0":"Illuminate","1":"Natural Cure","DW":"Analytic"},inherit:true},
starmie: {baseStats:{hp:60,atk:75,def:85,spa:100,spd:100,spe:115},abilities:{"0":"Illuminate","1":"Natural Cure","DW":"Analytic"},inherit:true},
mrmime: {"types":["Psychic"],gender:"N",baseStats:{hp:40,atk:45,def:65,spa:100,spd:100,spe:90},abilities:{"0":"Soundproof","1":"Filter","DW":"Technician"},inherit:true},
scyther: {gender:"N",baseStats:{hp:70,atk:110,def:80,spa:55,spd:55,spe:105},abilities:{"0":"Swarm","1":"Technician","DW":"Steadfast"},inherit:true},
jynx: {gender:"N",baseStats:{hp:65,atk:50,def:35,spa:95,spd:95,spe:95},abilities:{"0":"Oblivious","1":"Forewarn","DW":"Dry Skin"},inherit:true},
electabuzz: {gender:"N",baseStats:{hp:65,atk:83,def:57,spa:85,spd:85,spe:105},abilities:{"0":"Static","DW":"Vital Spirit"},inherit:true},
magmar: {gender:"N",baseStats:{hp:65,atk:95,def:57,spa:85,spd:85,spe:93},abilities:{"0":"Flame Body","DW":"Vital Spirit"},inherit:true},
pinsir: {gender:"N",baseStats:{hp:65,atk:125,def:100,spa:55,spd:55,spe:85},abilities:{"0":"Hyper Cutter","1":"Mold Breaker","DW":"Moxie"},otherFormes:null,inherit:true},
tauros: {gender:"N",baseStats:{hp:75,atk:100,def:95,spa:70,spd:70,spe:110},abilities:{"0":"Intimidate","1":"Anger Point","DW":"Sheer Force"},inherit:true},
magikarp: {gender:"N",baseStats:{hp:20,atk:10,def:55,spa:20,spd:20,spe:80},abilities:{"0":"Swift Swim","DW":"Rattled"},inherit:true},
gyarados: {gender:"N",baseStats:{hp:95,atk:125,def:79,spa:100,spd:100,spe:81},abilities:{"0":"Intimidate","DW":"Moxie"},otherFormes:null,inherit:true},
lapras: {gender:"N",baseStats:{hp:130,atk:85,def:80,spa:95,spd:95,spe:60},abilities:{"0":"Water Absorb","1":"Shell Armor","DW":"Hydration"},inherit:true},
ditto: {abilities:{"0":"Limber","DW":"Imposter"},inherit:true},
eevee: {gender:"N",baseStats:{hp:55,atk:55,def:50,spa:65,spd:65,spe:55},abilities:{"0":"Run Away","1":"Adaptability","DW":"Anticipation"},"evos":["vaporeon","jolteon","flareon","espeon","umbreon","leafeon","glaceon"],inherit:true},
vaporeon: {gender:"N",baseStats:{hp:130,atk:65,def:60,spa:110,spd:110,spe:65},abilities:{"0":"Water Absorb","DW":"Hydration"},inherit:true},
jolteon: {gender:"N",baseStats:{hp:65,atk:65,def:60,spa:110,spd:110,spe:130},abilities:{"0":"Volt Absorb","DW":"Quick Feet"},inherit:true},
flareon: {gender:"N",baseStats:{hp:65,atk:130,def:60,spa:110,spd:110,spe:65},abilities:{"0":"Flash Fire","DW":"Guts"},inherit:true},
porygon: {baseStats:{hp:65,atk:60,def:70,spa:75,spd:75,spe:40},abilities:{"0":"Trace","1":"Download","DW":"Analytic"},inherit:true},
omanyte: {gender:"N",baseStats:{hp:35,atk:40,def:100,spa:90,spd:90,spe:35},abilities:{"0":"Swift Swim","1":"Shell Armor","DW":"Weak Armor"},inherit:true},
omastar: {gender:"N",baseStats:{hp:70,atk:60,def:125,spa:115,spd:115,spe:55},abilities:{"0":"Swift Swim","1":"Shell Armor","DW":"Weak Armor"},inherit:true},
kabuto: {gender:"N",baseStats:{hp:30,atk:80,def:90,spa:45,spd:45,spe:55},abilities:{"0":"Swift Swim","1":"Battle Armor","DW":"Weak Armor"},inherit:true},
kabutops: {gender:"N",baseStats:{hp:60,atk:115,def:105,spa:70,spd:70,spe:80},abilities:{"0":"Swift Swim","1":"Battle Armor","DW":"Weak Armor"},inherit:true},
aerodactyl: {gender:"N",baseStats:{hp:80,atk:105,def:65,spa:60,spd:60,spe:130},abilities:{"0":"Rock Head","1":"Pressure","DW":"Unnerve"},otherFormes:null,inherit:true},
snorlax: {gender:"N",baseStats:{hp:160,atk:110,def:65,spa:65,spd:65,spe:30},abilities:{"0":"Immunity","1":"Thick Fat","DW":"Gluttony"},inherit:true},
articuno: {baseStats:{hp:90,atk:85,def:100,spa:125,spd:125,spe:85},abilities:{"0":"Pressure","DW":"Snow Cloak"},inherit:true},
zapdos: {baseStats:{hp:90,atk:90,def:85,spa:125,spd:125,spe:100},abilities:{"0":"Pressure","DW":"Lightningrod"},inherit:true},
moltres: {baseStats:{hp:90,atk:100,def:90,spa:125,spd:125,spe:90},abilities:{"0":"Pressure","DW":"Flame Body"},inherit:true},
dratini: {gender:"N",abilities:{"0":"Shed Skin"},inherit:true},
dragonair: {gender:"N",abilities:{"0":"Shed Skin"},inherit:true},
dragonite: {gender:"N",abilities:{"0":"Inner Focus"},inherit:true},
mewtwo: {baseStats:{hp:106,atk:110,def:90,spa:154,spd:154,spe:130},abilities:{"0":"Pressure"},otherFormes:null,inherit:true},
mew: {inherit:true},
missingno: {"types":["Normal","Normal"],gender:"N",abilities:{"0":"Download"},inherit:true}
}
