name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-git@v2

      - name: Sync with upstream repository
        run: |
          git remote add upstream https://github.com/smogon/pokemon-showdown.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master

