name: Publish to npm
on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
permissions:
  contents: read
jobs:
  test:
    uses: ./.github/workflows/test.yml
  get-version:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
      last_version: ${{ steps.last_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 50
      # Check if the package.json version field has changed since the last push
      - name: Get current version from package.json
        id: current_version
        run: |
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - name: Get the version from the last push
        id: last_version
        run: |
          git checkout ${{ github.event.before }}
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
  npm-publish:
    needs:
      - test
      - get-version
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    # We only want to publish if the package.json version field has changed
    if: needs.get-version.outputs.current_version != needs.get-version.outputs.last_version
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: npm ci
      - run: npm run build-npm
      - run: npm publish
